
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//									FOREST RANGER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION forest_ranger_kit BEGIN

COPY_EXISTING ~clabrn01.2da~ ~override/d5rfor.2da~
	LPM remove_blank_lines
	APPEND_FILE ~might_and_guile/ranger/forest_ranger/ranger_goodberry.txt~
	APPEND_FILE ~might_and_guile/ranger/forest_ranger/ranger_enemies.txt~

//change ranger class text___________________________________________________________
//
ACTION_FOR_EACH text_file IN ~clastext~ ~sodcltxt~ ~bgclatxt~ BEGIN
  COPY_EXISTING ~%text_file%.2da~ ~override~
    COUNT_2DA_COLS cols
    COUNT_2DA_ROWS cols rows
    FOR (row = 1; row < rows; ++row) BEGIN
      READ_2DA_ENTRY row 0 cols kit_name
      PATCH_IF (~%kit_name%~ STRING_EQUAL_CASE ~RANGER~) BEGIN
        SET_2DA_ENTRY row 4 cols RESOLVE_STR_REF (@12003)
      END
    END
  IF_EXISTS BUT_ONLY
END

//NO FAVORED ENEMY MENU______________________________________________________________
//
OUTER_SET no_enemy_1 = RESOLVE_STR_REF (@12001)
OUTER_SET no_enemy_2 = RESOLVE_STR_REF (@12002)
COPY ~might_and_guile/ranger/forest_ranger/haterace.2da~ ~override~
	REPLACE_TEXTUALLY ~abc~ ~%no_enemy_1%~
	REPLACE_TEXTUALLY ~xyz~ ~%no_enemy_2%~

//____________________________________________________________________________________
//
LAF check_kit_conflict END

ADD_KIT ~D5_RA_FOREST~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                    T   S           F   Q             S S
//10            L S                     W   C           L   U             W I
//9             A M             B L S   O   I   W       A   A             O N
//8             R A             A O H   H   M   A       I   R C   S       R G
//7             G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6             E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5             S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4             W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3             O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2             R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1             D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_RA_FOREST      0 0 0 0 0 0 0 0~
~D5_RA_FOREST      0 0 0 0 0 0 0 0 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_FOREST          0   0   12  0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_FOREST          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_FOREST          0   0   17  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_FOREST          0   0   15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_RA_FOREST          1  1  0  1  1  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_RA_FOREST          0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE____________________________________________________________
~override/d5rfor.2da~

//RACIAL KIT AVAILABILITY___________________________________________________________
~K_R_H    K_R_D   K_R_G   K_R_E   K_R_HE   K_R_HL   K_R_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @12011
SAY @12012
SAY @12013

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@12014)
		STR_VAR
			kit_name = D5_RA_FOREST
			clswpbon = ~1 0 2~
	END
END

//FOREST RANGER ABILITY FILES________________________________________________________
//
COPY_EXISTING ~sppr207.spl~ ~override/d5rnm01.spl~ // goodberry
	LPM spell_to_innate
COPY ~might_and_guile/ranger/forest_ranger/d5enemf.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~might_and_guile/ranger/forest_ranger/d5enemfa.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfb.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfc.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfd.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfe.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemff.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfg.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfh.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfi.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfj.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfk.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfl.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfm.eff~ ~override~
COPY ~might_and_guile/ranger/forest_ranger/d5enemfn.eff~ ~override~

//REPLACE VANILLA KIT WITH THIS KIT__________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5__rangers.d5~ BEGIN
  ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~K_R_%race%.2da~ BEGIN
	  COPY_EXISTING ~K_R_%race%.2da~ ~override~
		COUNT_2DA_COLS cols
		READ_2DA_ENTRIES_NOW rows cols
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 1 kit
		  PATCH_IF (%kit% = 0) BEGIN
			REMOVE_2DA_ROW row cols
		  END
		END
	  BUT_ONLY
	END
  END
END


//DEFINE SPHERE ACCESS_______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  STR_VAR
    clab_name 		= ~d5rfor~
	sphere_list		= ~ranger_forest_spheres~
	class 			= ~ranger~
 END

LAM ~READ_FNP_KIT_INFO~

ACTION_IF FILE_EXISTS_IN_GAME ~d5__spheres.d5~ BEGIN
  LAF apply_fnp_spheres STR_VAR clab_name = ~d5rfor~ END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5__fnp_usability.d5~ BEGIN
  LAF apply_fnp_usability STR_VAR clab_name = ~d5rfor~ END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spont_option.d5~) BEGIN
  APPEND ~d5rfor.2da~ ~SPNT_SPLS    GA_D5FPSP2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//									MOUNTAIN RANGER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION mountain_ranger_kit BEGIN

LAF check_kit_conflict END

ADD_KIT ~D5_RA_MOUNTAIN~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                    T   S           F   Q             S S
//10            L S                     W   C           L   U             W I
//9             A M             B L S   O   I   W       A   A             O N
//8             R A             A O H   H   M   A       I   R C   S       R G
//7             G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6             E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5             S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4             W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3             O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2             R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1             D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_RA_MOUNTAIN      0 0 0 0 0 0 0 0~
~D5_RA_MOUNTAIN      0 0 0 0 0 0 0 0 2 2 2 2 0 0 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_MOUNTAIN          0   0   12  0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_MOUNTAIN          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_MOUNTAIN          0   0   17  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_MOUNTAIN          0   0   15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_RA_MOUNTAIN          1  1  0  1  1  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_RA_MOUNTAIN          0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/ranger/mountain_ranger/d5rmou.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_R_H    K_R_D   K_R_G   K_R_E   K_R_HE   K_R_HL   K_R_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @12021
SAY @12022
SAY @12023

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@12024)
		STR_VAR
			kit_name = D5_RA_MOUNTAIN
			clswpbon = ~1 0 2~
	END
END

//MOUNTAIN RANGER ABILITY FILES_______________________________________________________
//
COPY ~might_and_guile/ranger/mountain_ranger/d5rmou.2da~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5dpsav3.spl~ ~override~

COPY ~might_and_guile/ranger/mountain_ranger/d5enemm.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~might_and_guile/ranger/mountain_ranger/d5enemma.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmb.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmc.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmd.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemme.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmf.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmg.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmh.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmi.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmj.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmk.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemml.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmm.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmn.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmo.eff~ ~override~
COPY ~might_and_guile/ranger/mountain_ranger/d5enemmp.eff~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  STR_VAR
    clab_name 		= ~d5rmou~
	sphere_list		= ~ranger_mountain_spheres~
	class 			= ~ranger~
 END

LAM ~READ_FNP_KIT_INFO~

ACTION_IF FILE_EXISTS_IN_GAME ~d5__spheres.d5~ BEGIN
  LAF apply_fnp_spheres STR_VAR clab_name = ~d5rmou~ END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5__fnp_usability.d5~ BEGIN
  LAF apply_fnp_usability STR_VAR clab_name = ~d5rmou~ END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spont_option.d5~) BEGIN
  APPEND ~d5rmou.2da~ ~SPNT_SPLS    GA_D5FPSP2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//									JUNGLE RANGER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION jungle_ranger_kit BEGIN

LAF check_kit_conflict END

ADD_KIT ~D5_RA_JUNGLE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                    T   S           F   Q             S S
//10            L S                     W   C           L   U             W I
//9             A M             B L S   O   I   W       A   A             O N
//8             R A             A O H   H   M   A       I   R C   S       R G
//7             G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6             E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5             S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4             W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3             O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2             R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1             D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_RA_JUNGLE      0 0 0 0 0 0 0 0~
~D5_RA_JUNGLE      0 0 0 0 0 0 0 0 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_JUNGLE          0   0   12  0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_JUNGLE          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_JUNGLE          0   0   17  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_JUNGLE          0   0   15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_RA_JUNGLE          1  1  0  1  1  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_RA_JUNGLE          0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/ranger/jungle_ranger/d5rjun.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_R_H    K_R_D   K_R_G   K_R_E   K_R_HE   K_R_HL   K_R_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00010000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @12031
SAY @12032
SAY @12033

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@12034)
		STR_VAR
			kit_name = D5_RA_JUNGLE
			clswpbon = ~1 0 2~
	END
END

//JUNGLE RANGER ABILITY FILES_________________________________________________________
//
COPY ~might_and_guile/ranger/jungle_ranger/d5rjun.2da~ ~override~
COPY ~might_and_guile/ranger/jungle_ranger/d5pres50.spl~ ~override~

COPY ~might_and_guile/ranger/jungle_ranger/d5enemj.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~might_and_guile/ranger/jungle_ranger/d5enemja.eff~ ~override~
COPY ~might_and_guile/ranger/jungle_ranger/d5enemjb.eff~ ~override~
COPY ~might_and_guile/ranger/jungle_ranger/d5enemjc.eff~ ~override~
COPY ~might_and_guile/ranger/jungle_ranger/d5enemjd.eff~ ~override~
COPY ~might_and_guile/ranger/jungle_ranger/d5enemje.eff~ ~override~
COPY ~might_and_guile/ranger/jungle_ranger/d5enemjf.eff~ ~override~
COPY ~might_and_guile/ranger/jungle_ranger/d5enemjg.eff~ ~override~
COPY ~might_and_guile/ranger/jungle_ranger/d5enemjh.eff~ ~override~
COPY ~might_and_guile/ranger/jungle_ranger/d5enemji.eff~ ~override~
COPY ~might_and_guile/ranger/jungle_ranger/d5enemjj.eff~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  STR_VAR
    clab_name 		= ~d5rjun~
	sphere_list		= ~ranger_jungle_spheres~
	class 			= ~ranger~
 END

ACTION_IF FILE_EXISTS_IN_GAME ~d5__spheres.d5~ BEGIN
  LAF apply_fnp_spheres STR_VAR clab_name = ~d5rjun~ END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5__fnp_usability.d5~ BEGIN
  LAF apply_fnp_usability STR_VAR clab_name = ~d5rjun~ END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spont_option.d5~) BEGIN
  APPEND ~d5rjun.2da~ ~SPNT_SPLS    GA_D5FPSP2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//									DESERT RANGER
//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION desert_ranger_kit BEGIN

LAF check_kit_conflict END

ADD_KIT ~D5_RA_DESERT~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                    T   S           F   Q             S S
//10            L S                     W   C           L   U             W I
//9             A M             B L S   O   I   W       A   A             O N
//8             R A             A O H   H   M   A       I   R C   S       R G
//7             G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6             E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5             S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4             W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3             O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2             R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1             D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_RA_DESERT      0 0 0 0 0 0 0 0~
~D5_RA_DESERT      0 0 0 0 0 0 0 0 2 2 2 2 2 0 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_DESERT          0   0   12  0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_DESERT          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_DESERT          0   0   17  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_DESERT          0   0   15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_RA_DESERT          1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_RA_DESERT          0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/ranger/desert_ranger/d5rdes.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_R_H    K_R_D   K_R_G   K_R_E   K_R_HE   K_R_HL   K_R_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00008000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @12041
SAY @12042
SAY @12043

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@12044)
		STR_VAR
			kit_name = D5_RA_DESERT
			clswpbon = ~1 0 2~
	END
END

//DESERT RANGER ABILITY FILES_________________________________________________________
//
COPY ~might_and_guile/ranger/desert_ranger/d5rdes.2da~ ~override~
COPY ~might_and_guile/misc/d5_1hp.spl~ ~override~

COPY ~might_and_guile/ranger/desert_ranger/d5enemd.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~might_and_guile/ranger/desert_ranger/d5enemda.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemdb.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemdc.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemdd.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemde.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemdf.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemdg.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemdh.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemdi.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemdj.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemdk.eff~ ~override~
COPY ~might_and_guile/ranger/desert_ranger/d5enemdl.eff~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  STR_VAR
    clab_name 		= ~d5rdes~
	sphere_list		= ~ranger_desert_spheres~
	class 			= ~ranger~
 END

LAM ~READ_FNP_KIT_INFO~

ACTION_IF FILE_EXISTS_IN_GAME ~d5__spheres.d5~ BEGIN
  LAF apply_fnp_spheres STR_VAR clab_name = ~d5rdes~ END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5__fnp_usability.d5~ BEGIN
  LAF apply_fnp_usability STR_VAR clab_name = ~d5rdes~ END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spont_option.d5~) BEGIN
  APPEND ~d5rdes.2da~ ~SPNT_SPLS    GA_D5FPSP2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
END

END
//__________________________________________________________________________________



//__________________________________________________________________________________
//__________________________________________________________________________________
//
//									ARCTIC RANGER
//__________________________________________________________________________________
//__________________________________________________________________________________

DEFINE_ACTION_FUNCTION arctic_ranger_kit BEGIN

LAF check_kit_conflict END

ADD_KIT ~D5_RA_ARCTIC~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                    T   S           F   Q             S S
//10            L S                     W   C           L   U             W I
//9             A M             B L S   O   I   W       A   A             O N
//8             R A             A O H   H   M   A       I   R C   S       R G
//7             G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6             E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5             S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4             W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3             O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2             R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1             D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_RA_ARCTIC      0 0 0 0 0 0 0 0~
~D5_RA_ARCTIC      0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_ARCTIC          0   0   12  0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_ARCTIC          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_ARCTIC          0   0   17  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_RA_ARCTIC          0   0   15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_RA_ARCTIC          1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_RA_ARCTIC          0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/ranger/arctic_ranger/d5rarc.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_R_H    K_R_D   K_R_G   K_R_E   K_R_HE   K_R_HL   K_R_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00008000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @12051
SAY @12052
SAY @12053

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@12054)
		STR_VAR
			kit_name = D5_RA_ARCTIC
			clswpbon = ~1 0 2~
	END
END

//ARCTIC RANGER ABILITY FILES_________________________________________________________
//
COPY ~might_and_guile/ranger/arctic_ranger/d5rarc.2da~ ~override~
COPY ~might_and_guile/ranger/arctic_ranger/d5cres25.spl~ ~override~

COPY ~might_and_guile/ranger/arctic_ranger/d5enema.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
COPY ~might_and_guile/ranger/arctic_ranger/d5enemaa.eff~ ~override~
COPY ~might_and_guile/ranger/arctic_ranger/d5enemab.eff~ ~override~
COPY ~might_and_guile/ranger/arctic_ranger/d5enemac.eff~ ~override~
COPY ~might_and_guile/ranger/arctic_ranger/d5enemad.eff~ ~override~
COPY ~might_and_guile/ranger/arctic_ranger/d5enemae.eff~ ~override~
COPY ~might_and_guile/ranger/arctic_ranger/d5enemaf.eff~ ~override~
COPY ~might_and_guile/ranger/arctic_ranger/d5enemag.eff~ ~override~
COPY ~might_and_guile/ranger/arctic_ranger/d5enemah.eff~ ~override~
COPY ~might_and_guile/ranger/arctic_ranger/d5enemai.eff~ ~override~
COPY ~might_and_guile/ranger/arctic_ranger/d5enemaj.eff~ ~override~

//DEFINE SPHERE ACCESS______________________________________________________________
//
 LAF ~DEFINE_FNP_KIT_INFO~
  STR_VAR
    clab_name 		= ~d5rarc~
	sphere_list		= ~ranger_arctic_spheres~
	class 			= ~ranger~
 END

ACTION_IF FILE_EXISTS_IN_GAME ~d5__spheres.d5~ BEGIN
  LAF apply_fnp_spheres STR_VAR clab_name = ~d5rarc~ END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5__fnp_usability.d5~ BEGIN
  LAF apply_fnp_usability STR_VAR clab_name = ~d5rarc~ END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spont_option.d5~) BEGIN
  APPEND ~d5rarc.2da~ ~SPNT_SPLS    GA_D5FPSP2  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
END

END
//__________________________________________________________________________________

