
//ADD MAGE HUNTER____________________________________________________________________
//
DEFINE_ACTION_FUNCTION mage_hunter_kit BEGIN

LAF check_kit_conflict END

ADD_KIT ~D5MAGEH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MAGEH       0 0 0 0 0 0 0 0~
~D5MAGEH       0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MAGEH           0   9   9   9   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MAGEH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MAGEH           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MAGEH  	       0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MAGEH           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MAGEH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/ranger/mage_hunter/d5mageh.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_R_H K_R_D K_R_E K_R_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @12503
SAY @12504
SAY @12505
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@12506)
		STR_VAR
			kit_name = D5MAGEH
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//MAGE HUNTER ABILITY FILES__________________________________________________________
//
COPY ~might_and_guile/ranger/mage_hunter/d5mageh.2da~ ~override~

COPY_EXISTING ~spwi318.spl~ ~override/d5_radfl.spl~
	LPM spell_to_innate
COPY_EXISTING ~spwi513.spl~ ~override/d5_rabre.spl~
	LPM spell_to_innate
COPY ~might_and_guile/misc/d5ssvbo.spl~ ~override~
COPY ~might_and_guile/ranger/mage_hunter/d5_mghs1.spl~ ~override~
COPY ~might_and_guile/ranger/mage_hunter/d5_mghsa.eff~ ~override~
COPY ~might_and_guile/ranger/mage_hunter/d5_mghsb.eff~ ~override~
COPY ~might_and_guile/ranger/mage_hunter/d5_mghsc.eff~ ~override~
COPY ~might_and_guile/ranger/mage_hunter/d5_mghs2.spl~ ~override~
	SAY NAME1 @12508
	SAY UNIDENTIFIED_DESC @12509
COPY ~might_and_guile/ranger/mage_hunter/d5_mghs1.eff~ ~override~
COPY ~might_and_guile/ranger/mage_hunter/d5_mghs2.eff~ ~override~
//__________________________________________________________________________________

//WILD TALENT_________________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5mageh.2da~) BEGIN
	APPEND ~d5mageh.2da~ ~WILD_TLNT   AP_D5PSWT_  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
  END
END
//____________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
INCLUDE ~%MOD_FOLDER%/lib/fnp_compatibility.tpa~

LAF ~DEFINE_FNP_KIT_INFO~
  STR_VAR
    clab_name 		= ~d5mageh~
	sphere_list		= ~mage_hunter_spheres~
	class 			= ~scout~
END

LAM ~READ_FNP_KIT_INFO~

ACTION_IF FILE_EXISTS_IN_GAME ~d5__spheres.d5~ BEGIN
  LAF apply_fnp_spheres STR_VAR clab_name = ~d5mageh~ END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5__fnp_usability.d5~ BEGIN
  LAF apply_fnp_usability STR_VAR clab_name = ~d5mageh~ END
END

ACTION_IF (FILE_EXISTS_IN_GAME ~d5__fnp_spont_option.d5~) AND (FILE_EXISTS ~faiths_and_powers/lib/system_fnp_spontaneous.tpa~) BEGIN
  ACTION_IF (FILE_EXISTS ~faiths_and_powers/language/%LANGUAGE%/fnp_spontaneous.tra~) BEGIN
    OUTER_SPRINT spont_lang ~%LANGUAGE%~
  END ELSE BEGIN
    OUTER_SPRINT spont_lang ~english~
  END
  ACTION_IF (FILE_EXISTS ~faiths_and_powers/language/%spont_lang%/fnp_spontaneous.tra~) BEGIN
    WITH_TRA ~faiths_and_powers/language/%spont_lang%/fnp_spontaneous.tra~ BEGIN
      INCLUDE ~faiths_and_powers/lib/system_fnp_spontaneous.tpa~
      LAF fnp_spontaneous STR_VAR kit_clab = ~d5mageh~ learn_res = ~d5magez~ END
    END
  END
END
//__________________________________________________________________________________

//______________________HLAS________________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~TG#TOUG.spl~) BEGIN
	COPY_EXISTING ~LURa0.2da~ ~override/LURa3.2da~	
END
//__________________________________________________________________________________


END	//	end function

