
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						STAT BONUSES
//__________________________________________________________________________________
//__________________________________________________________________________________


//COPY MARKER FILE___________________________________________________________________
//
COPY ~might_and_guile/misc/d5_stats.d5~ ~override~
//___________________________________________________________________________________


//EDIT STAT BONUSES__________________________________________________________________
//
COPY ~might_and_guile/misc/dexmod.2da~ ~override~
COPY ~might_and_guile/misc/strmod.2da~ ~override~
COPY ~might_and_guile/misc/strmodex.2da~ ~override~
COPY ~might_and_guile/misc/mxsplwis.2da~ ~override~
COPY ~might_and_guile/misc/intmod.2da~ ~override~
COPY_EXISTING ~abclasrq.2da~ ~override~
	REPLACE_TEXTUALLY ~ 0~ ~ 7~
	BUT_ONLY
//___________________________________________________________________________________


//EDIT DEMIHUMAN STATS_______________________________________________________________
//
COPY ~might_and_guile/misc/abracead.2da~ ~override~
//___________________________________________________________________________________


//EDIT STAT STRINGS__________________________________________________________________
//
	STRING_SET 9582 @2001 
	STRING_SET 9584 @2002 
	STRING_SET 9585 @2004 
	STRING_SET 9586 @2005 
	STRING_SET 9587 @2006 
//___________________________________________________________________________________


//CHARISMA BONUSES___________________________________________________________________
//
COPY ~might_and_guile/misc/d5_palch.spl~ ~override~
COPY ~might_and_guile/misc/savecndh.2da~ ~override~
COPY ~might_and_guile/misc/savecng.2da~ ~override~
COPY ~might_and_guile/misc/d5_cha15.spl~ ~override~
COPY ~might_and_guile/misc/d5_cha16.spl~ ~override~
COPY ~might_and_guile/misc/d5_cha17.spl~ ~override~
COPY ~might_and_guile/misc/d5_cha18.spl~ ~override~
COPY ~might_and_guile/misc/d5_cha19.spl~ ~override~
COPY ~might_and_guile/misc/d5_chari.spl~ ~override~
COPY ~might_and_guile/misc/d5_chari.cre~ ~override~
COMPILE ~might_and_guile/misc/d5_chari.baf~
//___________________________________________________________________________________


//EXCLUDE PALADINS___________________________________________________________________
//
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_intel_array BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY
ACTION_PHP_EACH d5_intel_array AS boo => zoo BEGIN
	ACTION_IF (%zoo% = 6) AND (FILE_EXISTS_IN_GAME ~%boo%.2da~) THEN BEGIN
		COPY_EXISTING ~%boo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/misc/charisma_paladin.txt~
			BUT_ONLY
	END
END
//___________________________________________________________________________________


//ADD CHARISMA BONUSES_______________________________________________________________
//
COPY_EXISTING ~clabpr01.2da~ ~override~
			~clabdr01.2da~ ~override~
//			~clabpa01.2da~ ~override~
			~clabrn01.2da~ ~override~
			~clabfi01.2da~ ~override~
			~clabth01.2da~ ~override~
			~clabba01.2da~ ~override~
			~clabmo01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 1 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_char_array BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY
ACTION_PHP_EACH d5_char_array AS pu => poo BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%pu%.2da~) THEN BEGIN
		COPY_EXISTING ~%pu%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		BUT_ONLY
	END
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma01.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma02.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma02.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma03.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma03.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma04.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma04.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma05.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma05.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma06.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma06.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma07.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma07.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma08.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma08.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma09.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma09.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
END
//__________________________________________________________________________________


//INTELLIGENCE BONUSES______________________________________________________________
//
COPY ~might_and_guile/misc/d5_intcr.spl~ ~override~
COPY ~might_and_guile/misc/d5_intcr.cre~ ~override~
COPY ~might_and_guile/misc/d5_crit1.spl~ ~override~
COPY ~might_and_guile/misc/d5_crit2.spl~ ~override~
COPY ~might_and_guile/misc/d5_crit3.spl~ ~override~
COPY ~might_and_guile/misc/d5_crit0.spl~ ~override~
COPY ~might_and_guile/misc/d5_wisp1.spl~ ~override~
COPY ~might_and_guile/misc/d5_wisp2.spl~ ~override~
COPY ~might_and_guile/misc/d5_wisp3.spl~ ~override~
COPY ~might_and_guile/misc/d5_wisp4.spl~ ~override~
COPY ~might_and_guile/misc/d5_wisp5.spl~ ~override~
COPY ~might_and_guile/misc/d5_wisp6.spl~ ~override~
COPY ~might_and_guile/misc/d5_wisp7.spl~ ~override~
COPY ~might_and_guile/misc/d5_wisp8.spl~ ~override~
COPY ~might_and_guile/misc/d5_wisp9.spl~ ~override~
COPY ~might_and_guile/misc/d5_int12.spl~ ~override~
COPY ~might_and_guile/misc/d5_int13.spl~ ~override~
COPY ~might_and_guile/misc/d5_int14.spl~ ~override~
COPY ~might_and_guile/misc/d5_int15.spl~ ~override~
COPY ~might_and_guile/misc/d5_int16.spl~ ~override~
COPY ~might_and_guile/misc/d5_int17.spl~ ~override~
COPY ~might_and_guile/misc/d5_int18.spl~ ~override~
COPY ~might_and_guile/misc/d5_int19.spl~ ~override~
COPY ~might_and_guile/misc/d5_int20.spl~ ~override~
COPY ~might_and_guile/misc/d5_int12.cre~ ~override~
COPY ~might_and_guile/misc/d5_int13.cre~ ~override~
COPY ~might_and_guile/misc/d5_int14.cre~ ~override~
COPY ~might_and_guile/misc/d5_int15.cre~ ~override~
COPY ~might_and_guile/misc/d5_int16.cre~ ~override~
COPY ~might_and_guile/misc/d5_int17.cre~ ~override~
COPY ~might_and_guile/misc/d5_int18.cre~ ~override~
COPY ~might_and_guile/misc/d5_int19.cre~ ~override~
COPY ~might_and_guile/misc/d5_int20.cre~ ~override~
COMPILE ~might_and_guile/misc/d5_intcr.baf~
COMPILE ~might_and_guile/misc/d5_int12.baf~
COMPILE ~might_and_guile/misc/d5_int13.baf~
COMPILE ~might_and_guile/misc/d5_int14.baf~
COMPILE ~might_and_guile/misc/d5_int15.baf~
COMPILE ~might_and_guile/misc/d5_int16.baf~
COMPILE ~might_and_guile/misc/d5_int17.baf~
COMPILE ~might_and_guile/misc/d5_int18.baf~
COMPILE ~might_and_guile/misc/d5_int19.baf~
COMPILE ~might_and_guile/misc/d5_int20.baf~
//___________________________________________________________________________________


//ADD CRIT PENALTIES________________________________________________________________
//
COPY_EXISTING ~clabpr01.2da~ ~override~
			~clabdr01.2da~ ~override~
			~clabpa01.2da~ ~override~
			~clabrn01.2da~ ~override~
			~clabfi01.2da~ ~override~
			~clabth01.2da~ ~override~
			~clabba01.2da~ ~override~
			~clabmo01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 1 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_char_array BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY
ACTION_PHP_EACH d5_char_array AS pu => poo BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~%pu%.2da~) THEN BEGIN
		COPY_EXISTING ~%pu%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
		BUT_ONLY
	END
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma01.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma02.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma02.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma03.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma03.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma04.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma04.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma05.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma05.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma06.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma06.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma07.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma07.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma08.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma08.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma09.2da~) THEN BEGIN
	COPY ~might_and_guile/misc/clabma09.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/crit_penalties.txt~
END
//__________________________________________________________________________________


//ADD INTELLIGENCE BONUSES___________________________________________________________
//
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_intel_array BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY
ACTION_PHP_EACH d5_intel_array AS boo => zoo BEGIN
	ACTION_IF (%zoo% = 5) AND (FILE_EXISTS_IN_GAME ~%boo%.2da~) BEGIN
		COPY_EXISTING ~%boo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/misc/intelligence_bards.txt~
	END
	ACTION_IF (%zoo% = 1) AND (FILE_EXISTS_IN_GAME ~%boo%.2da~) BEGIN
		COPY_EXISTING ~%boo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
	END
END
COPY_EXISTING ~clabba01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_bards.txt~
ACTION_IF (FILE_EXISTS_IN_GAME ~clabma01.2da~) BEGIN
	COPY_EXISTING ~clabma01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma01.2da~) BEGIN
	COPY ~might_and_guile/misc/clabma01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma02.2da~) BEGIN
	COPY ~might_and_guile/misc/clabma02.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma03.2da~) BEGIN
	COPY ~might_and_guile/misc/clabma03.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma04.2da~) BEGIN
	COPY ~might_and_guile/misc/clabma04.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma05.2da~) BEGIN
	COPY ~might_and_guile/misc/clabma05.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma06.2da~) BEGIN
	COPY ~might_and_guile/misc/clabma06.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma07.2da~) BEGIN
	COPY ~might_and_guile/misc/clabma07.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma08.2da~) BEGIN
	COPY ~might_and_guile/misc/clabma08.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
END
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~clabma09.2da~) BEGIN
	COPY ~might_and_guile/misc/clabma09.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
END
//__________________________________________________________________________________


CLEAR_ARRAYS
