
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//									ROGUE FEATS
//__________________________________________________________________________________
//__________________________________________________________________________________


//COPY MARKER FILE_________________________________________________________________
//
COPY ~might_and_guile/lib/markers/d5_marker.d5~ ~override/d5__rfeat.d5~
COPY ~might_and_guile/lib/markers/d5_marker.d5~ ~override/d5__wfeat.d5~
//__________________________________________________________________________________


//IMPROVE THAC0 TABLE_______________________________________________________________
//
COPY_EXISTING ~thac0.2da~ ~override~
	COUNT_2DA_COLS cols 
	SET_2DA_ENTRY 2 3 cols ~19~
	SET_2DA_ENTRY 2 6 cols ~17~
	SET_2DA_ENTRY 2 9 cols ~15~
	SET_2DA_ENTRY 2 12 cols ~13~
	SET_2DA_ENTRY 2 15 cols ~11~
	SET_2DA_ENTRY 2 18 cols ~9~
	SET_2DA_ENTRY 2 21 cols ~7~
	SET_2DA_ENTRY 6 3 cols ~19~
	SET_2DA_ENTRY 6 6 cols ~17~
	SET_2DA_ENTRY 6 9 cols ~15~
	SET_2DA_ENTRY 6 12 cols ~13~
	SET_2DA_ENTRY 6 15 cols ~11~
	SET_2DA_ENTRY 6 18 cols ~9~
	SET_2DA_ENTRY 6 21 cols ~7~
	SET_2DA_ENTRY 13 3 cols ~19~
	SET_2DA_ENTRY 13 6 cols ~17~
	SET_2DA_ENTRY 13 9 cols ~15~
	SET_2DA_ENTRY 13 12 cols ~13~
	SET_2DA_ENTRY 13 15 cols ~11~
	SET_2DA_ENTRY 13 18 cols ~9~
	SET_2DA_ENTRY 13 21 cols ~7~
	SET_2DA_ENTRY 14 3 cols ~19~
	SET_2DA_ENTRY 14 6 cols ~17~
	SET_2DA_ENTRY 14 9 cols ~15~
	SET_2DA_ENTRY 14 12 cols ~13~
	SET_2DA_ENTRY 14 15 cols ~11~
	SET_2DA_ENTRY 14 18 cols ~9~
	SET_2DA_ENTRY 14 21 cols ~7~
	SET_2DA_ENTRY 3 4 cols ~18~
	SET_2DA_ENTRY 3 5 cols ~18~
	SET_2DA_ENTRY 3 6 cols ~17~
	SET_2DA_ENTRY 3 7 cols ~16~
	SET_2DA_ENTRY 3 8 cols ~16~
	SET_2DA_ENTRY 3 9 cols ~15~
	SET_2DA_ENTRY 3 10 cols ~14~
	SET_2DA_ENTRY 3 11 cols ~14~
	SET_2DA_ENTRY 3 12 cols ~13~
	SET_2DA_ENTRY 3 13 cols ~12~
	SET_2DA_ENTRY 3 14 cols ~12~
	SET_2DA_ENTRY 3 15 cols ~11~
	SET_2DA_ENTRY 3 16 cols ~10~
	SET_2DA_ENTRY 3 17 cols ~10~
	SET_2DA_ENTRY 3 18 cols ~9~
	SET_2DA_ENTRY 3 19 cols ~8~
	SET_2DA_ENTRY 3 20 cols ~8~
	SET_2DA_ENTRY 3 21 cols ~7~
	SET_2DA_ENTRY 4 4 cols ~18~
	SET_2DA_ENTRY 4 5 cols ~18~
	SET_2DA_ENTRY 4 6 cols ~17~
	SET_2DA_ENTRY 4 7 cols ~16~
	SET_2DA_ENTRY 4 8 cols ~16~
	SET_2DA_ENTRY 4 9 cols ~15~
	SET_2DA_ENTRY 4 10 cols ~14~
	SET_2DA_ENTRY 4 11 cols ~14~
	SET_2DA_ENTRY 4 12 cols ~13~
	SET_2DA_ENTRY 4 13 cols ~12~
	SET_2DA_ENTRY 4 14 cols ~12~
	SET_2DA_ENTRY 4 15 cols ~11~
	SET_2DA_ENTRY 4 16 cols ~10~
	SET_2DA_ENTRY 4 17 cols ~10~
	SET_2DA_ENTRY 4 18 cols ~9~
	SET_2DA_ENTRY 4 19 cols ~8~
	SET_2DA_ENTRY 4 20 cols ~8~
	SET_2DA_ENTRY 4 21 cols ~7~
	SET_2DA_ENTRY 12 4 cols ~18~
	SET_2DA_ENTRY 12 5 cols ~18~
	SET_2DA_ENTRY 12 6 cols ~17~
	SET_2DA_ENTRY 12 7 cols ~16~
	SET_2DA_ENTRY 12 8 cols ~16~
	SET_2DA_ENTRY 12 9 cols ~15~
	SET_2DA_ENTRY 12 10 cols ~14~
	SET_2DA_ENTRY 12 11 cols ~14~
	SET_2DA_ENTRY 12 12 cols ~13~
	SET_2DA_ENTRY 12 13 cols ~12~
	SET_2DA_ENTRY 12 14 cols ~12~
	SET_2DA_ENTRY 12 15 cols ~11~
	SET_2DA_ENTRY 12 16 cols ~10~
	SET_2DA_ENTRY 12 17 cols ~10~
	SET_2DA_ENTRY 12 18 cols ~9~
	SET_2DA_ENTRY 12 19 cols ~8~
	SET_2DA_ENTRY 12 20 cols ~8~
	SET_2DA_ENTRY 12 21 cols ~7~
	FOR (col = 22; col < cols; ++col) BEGIN
		SET_2DA_ENTRY 3 col cols ~6~
		SET_2DA_ENTRY 4 col cols ~6~
		SET_2DA_ENTRY 12 col cols ~6~
	END
BUT_ONLY

ACTION_IF FILE_EXISTS_IN_GAME ~enginest.2da~ BEGIN
  COPY_EXISTING ~thac0.2da~ ~override~
	COUNT_2DA_COLS cols
	SET_2DA_ENTRY 20 3 cols ~19~
	SET_2DA_ENTRY 20 6 cols ~17~
	SET_2DA_ENTRY 20 9 cols ~15~
	SET_2DA_ENTRY 20 12 cols ~13~
	SET_2DA_ENTRY 20 15 cols ~11~
	SET_2DA_ENTRY 20 18 cols ~9~
	SET_2DA_ENTRY 20 21 cols ~7~
  BUT_ONLY
END	
//__________________________________________________________________________________


//REVISED KITS______________________________________________________________________
//
ACTION_IF NOT MOD_IS_INSTALLED ~might_and_guile.tp2~ ~225~ BEGIN
	INCLUDE ~might_and_guile/components/230_revised_stalker.tpa~
END
ACTION_IF NOT MOD_IS_INSTALLED ~might_and_guile.tp2~ ~275~ BEGIN
	INCLUDE ~might_and_guile/components/275_revised_shadowdancer.tpa~
END
//__________________________________________________________________________________

LAF check_kit_conflict END

//ADD ALCHEMIST_____________________________________________________________________

ADD_KIT ~D5ALCHM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5ALCHM       0 0 0 0 0 0 0 0~
~D5ALCHM       0 0 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 0 0 0 0 1 1 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALCHM    	   0   9   0   15   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALCHM           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALCHM           0   0   0   17  0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALCHM  	       0   0   0   15  0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5ALCHM           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5ALCHM           1  1  1  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/feats/d5_alchm.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_T_D K_T_E K_T_G K_T_H K_T_HE K_T_HL K_T_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric = 3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Th0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20081
SAY @20082
SAY @20083
//___________________________________________________________________________________

COPY ~might_and_guile/feats/d5_alchm.2da~ ~override~

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20083)
		STR_VAR
			kit_name = D5ALCHM
			backstab = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
			clswpbon = ~0 0 3~
			thiefskl = ~30 20~
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END
//____________________________________________________________________________________


//WILD TALENT_________________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5_alchm.2da~) BEGIN
	APPEND ~d5_alchm.2da~ ~WILD_TLNT   AP_D5PSWT_  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
  END
END
//____________________________________________________________________________________


//KIT IDENTIFIERS FOR PATCHING LATER__________________________________________________
//
OUTER_SET sd_code = (0x4000 + %D5SHADD%)
OUTER_SET al_code = (0x4000 + %D5ALCHM%)

COPY_EXISTING ~kit.ids~ ~override~
	COUNT_2DA_COLS k_cols
	READ_2DA_ENTRIES_NOW k_rows k_cols 
	FOR (k_row = 1; k_row < k_rows; ++k_row) BEGIN 
	  READ_2DA_ENTRY_FORMER k_rows k_row 1 ~k_kit~ 
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~ASSASIN~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 assassin_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~BOUNTYHUNTER~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 hunter_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~SWASHBUCKLER~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 swashbuckler_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~D5SHADD~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 shadowdancer_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~D5ALCHM~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 alchemist_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~STALKER~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 stalker_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~BEASTMASTER~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 beastmaster_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~D5_RA_FOR~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 forest_ranger_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~D5_RA_MOU~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 mountain_ranger_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~D5_RA_DES~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 desert_ranger_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~D5_RA_JUN~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 jungle_ranger_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~D5_RA_ARC~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 arctic_ranger_ids
	  END
	  PATCH_IF (~%k_kit%~ STRING_EQUAL_CASE ~D5CORSA~) BEGIN
	    SET this_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows this_row 0 corsair_ids
	  END
	END
BUT_ONLY
//____________________________________________________________________________________


//CHANGE CLASS TEXT_________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols 
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ 
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~THIEF~ BEGIN
	    SET thief_row = %row%
		SET_2DA_ENTRY %thief_row% 3 cols RESOLVE_STR_REF (@20000)
		SET_2DA_ENTRY %thief_row% 4 cols RESOLVE_STR_REF (@20002)
		SET_2DA_ENTRY %thief_row% 5 cols RESOLVE_STR_REF (@20001)
		SET_2DA_ENTRY (%thief_row% + 1) 4 cols RESOLVE_STR_REF (@20073)
		SET_2DA_ENTRY (%thief_row% + 2) 4 cols RESOLVE_STR_REF (@20074)
		SET_2DA_ENTRY (%thief_row% + 2) 3 cols RESOLVE_STR_REF (@20075)
		SET_2DA_ENTRY (%thief_row% + 2) 5 cols RESOLVE_STR_REF (@20076)
		SET_2DA_ENTRY (%thief_row% + 3) 4 cols RESOLVE_STR_REF (@20077)
		SET_2DA_ENTRY (%thief_row% + 4) 4 cols RESOLVE_STR_REF (@20078)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~FIGHTER~ BEGIN
	    SET fighter_row = %row%
		SET_2DA_ENTRY %fighter_row% 4 cols RESOLVE_STR_REF (@20015)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~RANGER~ BEGIN
	    SET ranger_row = %row%
		SET_2DA_ENTRY %ranger_row% 4 cols RESOLVE_STR_REF (@20016)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BARBARIAN~ BEGIN
	    SET barb_row = %row%
		SET_2DA_ENTRY %barb_row% 4 cols RESOLVE_STR_REF (@20017)
	  END
	END
  BUT_ONLY
END
ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
  COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols 
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~THIEF~ BEGIN
	    SET thief_row = %row%
		SET_2DA_ENTRY %thief_row% 3 cols RESOLVE_STR_REF (@20000)
		SET_2DA_ENTRY %thief_row% 4 cols RESOLVE_STR_REF (@20002)
		SET_2DA_ENTRY %thief_row% 5 cols RESOLVE_STR_REF (@20001)
		SET_2DA_ENTRY (%thief_row% + 1) 4 cols RESOLVE_STR_REF (@20073)
		SET_2DA_ENTRY (%thief_row% + 2) 4 cols RESOLVE_STR_REF (@20074)
		SET_2DA_ENTRY (%thief_row% + 2) 3 cols RESOLVE_STR_REF (@20075)
		SET_2DA_ENTRY (%thief_row% + 2) 5 cols RESOLVE_STR_REF (@20076)
		SET_2DA_ENTRY (%thief_row% + 3) 4 cols RESOLVE_STR_REF (@20077)
		SET_2DA_ENTRY (%thief_row% + 4) 4 cols RESOLVE_STR_REF (@20078)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~FIGHTER~ BEGIN
	    SET fighter_row = %row%
		SET_2DA_ENTRY %fighter_row% 4 cols RESOLVE_STR_REF (@20015)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~RANGER~ BEGIN
	    SET ranger_row = %row%
		SET_2DA_ENTRY %ranger_row% 4 cols RESOLVE_STR_REF (@20016)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BARBARIAN~ BEGIN
	    SET barb_row = %row%
		SET_2DA_ENTRY %barb_row% 4 cols RESOLVE_STR_REF (@20017)
	  END
	END
  BUT_ONLY
END
ACTION_IF (FILE_EXISTS_IN_GAME ~kitlist.2da~) BEGIN
  COPY_EXISTING ~kitlist.2da~ ~override~
//	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows 9
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~text~
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~ASSASIN~ BEGIN
	    SET assassin_row = %row%
		SET_2DA_ENTRY (%assassin_row%) 4 9 RESOLVE_STR_REF (@20073)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BOUNTY_HUNTER~ BEGIN
	    SET hunter_row = %row%
		SET_2DA_ENTRY (%hunter_row%) 4 9 RESOLVE_STR_REF (@20074)
		SET_2DA_ENTRY (%hunter_row%) 2 9 RESOLVE_STR_REF (@20075)
		SET_2DA_ENTRY (%hunter_row%) 3 9 RESOLVE_STR_REF (@20076)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~SWASHBUCKLER~ BEGIN
	    SET swash_row = %row%
		SET_2DA_ENTRY (%swash_row%) 4 9 RESOLVE_STR_REF (@20077)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~SHADOWDANCER~ BEGIN
	    SET dancer_row = %row%
		SET_2DA_ENTRY (%dancer_row%) 4 9 RESOLVE_STR_REF (@20078)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5SHADD~ BEGIN
	    SET shadd_row = %row%
		SET_2DA_ENTRY (%shadd_row%) 4 9 RESOLVE_STR_REF (@20078)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~FIGHTER~ BEGIN
	    SET fighter_row = %row%
		SET_2DA_ENTRY %fighter_row% 4 cols RESOLVE_STR_REF (@20015)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~RANGER~ BEGIN
	    SET ranger_row = %row%
		SET_2DA_ENTRY %ranger_row% 4 cols RESOLVE_STR_REF (@20016)
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BARBARIAN~ BEGIN
	    SET barb_row = %row%
		SET_2DA_ENTRY %barb_row% 4 cols RESOLVE_STR_REF (@20017)
	  END
	END
  BUT_ONLY
END
//__________________________________________________________________________________


//PREP SPLPROT.2DA__________________________________________________________________
//
APPEND ~splprot.2da~ ~D5_115_FEATS%TAB%115%TAB%-1%TAB%8~ UNLESS ~D5_115_FEATS~
APPEND ~splprot.2da~ ~D5_115_NFEATS%TAB%115%TAB%-1%TAB%9~ UNLESS ~D5_115_NFEATS~
APPEND ~splprot.2da~ ~D5_KIT_IS%TAB%152%TAB%-1%TAB%1~ UNLESS ~D5_KIT_IS~
APPEND ~splprot.2da~ ~D5_KIT_NOT%TAB%152%TAB%-1%TAB%5~ UNLESS ~D5_KIT_NOT~

COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_KIT_IS~ BEGIN
	    SET kit_is_row = %row%
	  END
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_KIT_NOT~ BEGIN
	    SET kit_not_row = %row%
	  END
	END
BUT_ONLY
//__________________________________________________________________________________


//FEAT ABILITY FILES________________________________________________________________
//
// skills/miscellaneous

COPY ~might_and_guile/feats/d5_rfa1b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfa1.spl~ ~override/d5ura1.spl~   // 			stealth bonus
	SAY NAME1 @20101
	SAY UNIDENTIFIED_DESC @20102
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfa1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfa1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfa1a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfa1b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfa1a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ura1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vra1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfa1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfa1a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfa1b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ura1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vra1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfa1b~ END
COPY_EXISTING  ~d5ura1.spl~ ~override/d5vra1.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfa2b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfa2.spl~ ~override/d5ura2.spl~   // 			thieving bonus
	SAY NAME1 @20103
	SAY UNIDENTIFIED_DESC @20104
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfa2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfa2b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfa2a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfa2b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfa2a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ura2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vra2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfa2b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfa2a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfa2b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ura2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vra2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfa2b~ END
COPY_EXISTING  ~d5ura2.spl~ ~override/d5vra2.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfa3b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfa3.spl~ ~override/d5ura3.spl~   // 			detection bonus
	SAY NAME1 @20105
	SAY UNIDENTIFIED_DESC @20106
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfa3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfa3b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfa3a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfa3b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfa3a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ura3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vra3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfa3b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfa3a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfa3b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ura3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vra3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfa3b~ END
COPY_EXISTING  ~d5ura3.spl~ ~override/d5vra3.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfa4b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfa4.spl~ ~override/d5ura4.spl~   // 			lore bonus
	SAY NAME1 @20301
	SAY UNIDENTIFIED_DESC @20302
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfa4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfa4b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfa4a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfa4b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfa4a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ura4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vra4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfa4b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfa4a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfa4b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ura4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vra4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfa4b~ END
COPY_EXISTING  ~d5ura4.spl~ ~override/d5vra4.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfa5b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfa5.spl~ ~override/d5ura5.spl~   // 			luck bonus
	SAY NAME1 @20303
	SAY UNIDENTIFIED_DESC @20304
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfa5b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfa5b~ END
COPY_EXISTING  ~d5ura5.spl~ ~override/d5vra5.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfa9b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfa9.spl~ ~override/d5ura9.spl~   // 			tracking
	SAY NAME1 @20107
	SAY UNIDENTIFIED_DESC @20108
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfa9b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfa9b~ END
COPY_EXISTING  ~d5ura9.spl~ ~override/d5vra9.spl~ 
	WRITE_SHORT 0x1c 1
ACTION_IF !(FILE_EXISTS_IN_GAME ~spcl922.spl~) BEGIN
  COPY ~might_and_guile/feats/spcl922.spl~ ~override~
	SAY NAME1 @20107
	SAY UNIDENTIFIED_DESC @20108
	WRITE_ASCII 0x3a ~d5_rfa9b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfa9b~ END
END
ACTION_IF (FILE_EXISTS_IN_GAME ~spcl922.spl~) BEGIN
  COPY_EXISTING ~spcl922.spl~ ~override~
	WRITE_ASCII 0x3a ~d5_rfa9b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfa9b~ END
END

// mechanical

/*
ADD_PROJECTILE ~might_and_guile/thief/d5trspik.pro~
COPY ~might_and_guile/thief/d5_rfb1.spl~ ~override~   		// 			spike trap
	SAY NAME1 @20111
	SAY UNIDENTIFIED_DESC @20112
COPY ~might_and_guile/thief/d5_rfb1x.spl~ ~override~
COPY ~might_and_guile/thief/d5_rf21.spl~ ~override~
	SAY NAME1 @20111
	SAY UNIDENTIFIED_DESC @20112
COPY ~might_and_guile/thief/d5_rf21b.spl~ ~override~
	LPF ALTER_SPELL_HEADER INT_VAR projectile = %d5trspik% END
*/

COPY ~might_and_guile/feats/d5_rfb1b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfb1.spl~ ~override/d5urb1.spl~   // 			dart trap
	SAY NAME1 @20113
	SAY UNIDENTIFIED_DESC @20114
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfb1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfb1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfb1a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfb1b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfb1a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urb1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrb1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfb1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfb1a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfb1b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urb1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrb1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfb1b~ END
COPY ~might_and_guile/feats/d5_rf21.spl~ ~override~
	SAY NAME1 @20113
	SAY UNIDENTIFIED_DESC @20114
	WRITE_ASCII 0x3a ~d5_rfb1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfb1b~ END
COPY ~might_and_guile/feats/d5_rf21b.spl~ ~override~
COPY_EXISTING  ~d5urb1.spl~ ~override/d5vrb1.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfb3b.bam~ ~override~
ADD_PROJECTILE ~might_and_guile/feats/d5trfire.pro~
COPY ~might_and_guile/feats/d5_rfb3.spl~ ~override/d5urb3.spl~   // 			fire trap
	SAY NAME1 @20115
	SAY UNIDENTIFIED_DESC @20116
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfb3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfb3b~ END
COPY ~might_and_guile/feats/d5_rf23.spl~ ~override~
	SAY NAME1 @20115
	SAY UNIDENTIFIED_DESC @20116
	WRITE_ASCII 0x3a ~d5_rfb3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfb3b~ END
COPY ~might_and_guile/feats/d5_rf23b.spl~ ~override~
	LPF ALTER_SPELL_HEADER INT_VAR projectile = %d5trfire% END
COPY_EXISTING  ~d5urb3.spl~ ~override/d5vrb3.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfb4b.bam~ ~override~
ADD_PROJECTILE ~might_and_guile/feats/d5trweb.pro~
COPY ~might_and_guile/feats/d5_rfb4.spl~ ~override/d5urb4.spl~   // 			web trap
	SAY NAME1 @20117
	SAY UNIDENTIFIED_DESC @20118
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 2
	END
	WRITE_ASCII 0x3a ~d5_rfb4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfb4b~ END
COPY ~might_and_guile/feats/d5_rf24.spl~ ~override~
	SAY NAME1 @20117
	SAY UNIDENTIFIED_DESC @20118
	WRITE_ASCII 0x3a ~d5_rfb4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfb4b~ END
COPY ~might_and_guile/feats/d5_rf24b.spl~ ~override~
	LPF ALTER_SPELL_HEADER INT_VAR projectile = %d5trweb% END
COPY_EXISTING  ~d5urb4.spl~ ~override/d5vrb4.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfb5b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfb5.spl~ ~override/d5urb5.spl~   // 			poison trap
	SAY NAME1 @20119
	SAY UNIDENTIFIED_DESC @20120
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 2
	END
	WRITE_ASCII 0x3a ~d5_rfb1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfb5b~ END
COPY ~might_and_guile/feats/d5_rf25.spl~ ~override~
	SAY NAME1 @20119
	SAY UNIDENTIFIED_DESC @20120
	WRITE_ASCII 0x3a ~d5_rfb1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfb5b~ END
COPY ~might_and_guile/feats/d5_rf25b.spl~ ~override~
COPY_EXISTING  ~d5urb5.spl~ ~override/d5vrb5.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rf2z.spl~ ~override~  		 // 			maze trap
	SAY NAME1 @20129
	SAY UNIDENTIFIED_DESC @20130
COPY ~might_and_guile/feats/d5_rf2z.bam~ ~override~
COPY ~might_and_guile/feats/d5_rf2zb.spl~ ~override~

// alchemical

COPY ~might_and_guile/feats/d5_rfc1b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfc1.spl~ ~override/d5urc1.spl~  		// 			basic alchemy
	SAY NAME1 @20131
	SAY UNIDENTIFIED_DESC @20132
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfc1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc1c~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 318 parameter1 = %alchemist_ids% parameter2 = %kit_is_row% END
COPY ~might_and_guile/feats/d5_rf31.spl~ ~override~
	SAY NAME1 @20131
	SAY UNIDENTIFIED_DESC @20132
	WRITE_ASCII 0x3a ~d5_rfc1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc1b~ END
COPY_EXISTING  ~d5urc1.spl~ ~override/d5vrc1.spl~ 
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/feats/d5_rf31.2da~ ~override~
COPY ~might_and_guile/feats/d5_rf31a.spl~ ~override~
	SAY NAME1 @20133
	SAY UNIDENTIFIED_DESC @20133
COPY ~might_and_guile/feats/d5_rf31b.spl~ ~override~
	SAY NAME1 @20134
	SAY UNIDENTIFIED_DESC @20134
COPY ~might_and_guile/feats/d5_rf31c.spl~ ~override~
	SAY NAME1 @20135
	SAY UNIDENTIFIED_DESC @20135
COPY ~might_and_guile/feats/d5_rf31d.spl~ ~override~
	SAY NAME1 @20136
	SAY UNIDENTIFIED_DESC @20136
COPY ~might_and_guile/feats/d5_rf31e.spl~ ~override~
	SAY NAME1 @20137
	SAY UNIDENTIFIED_DESC @20137
COPY ~might_and_guile/feats/d5_rf31f.spl~ ~override~
	SAY NAME1 @20138
	SAY UNIDENTIFIED_DESC @20138
COPY ~might_and_guile/feats/d5_rf31g.spl~ ~override~
	SAY NAME1 @20139
	SAY UNIDENTIFIED_DESC @20139
ADD_PROJECTILE ~might_and_guile/feats/d5_floil.pro~
COPY ~might_and_guile/feats/d5_floil.itm~ ~override~
	SAY NAME1 @20139
	SAY NAME2 @20139
	SAY UNIDENTIFIED_DESC @20140
	LPF ALTER_ITEM_HEADER INT_VAR projectile = %d5_floil% END
COPY ~might_and_guile/feats/d5_floil.bam~ ~override~

COPY ~might_and_guile/feats/d5_rfc2b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfc2.spl~ ~override/d5urc2.spl~   // 			advanced alchemy
	SAY NAME1 @20181
	SAY UNIDENTIFIED_DESC @20182
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfc2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc2b~ END
COPY ~might_and_guile/feats/d5_rf32.spl~ ~override~
	SAY NAME1 @20181
	SAY UNIDENTIFIED_DESC @20182
	WRITE_ASCII 0x3a ~d5_rfc2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc2b~ END
COPY_EXISTING  ~d5urc2.spl~ ~override/d5vrc2.spl~ 
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/feats/d5_rf32.2da~ ~override~
COPY ~might_and_guile/feats/d5_rf32a.spl~ ~override~
	SAY NAME1 @20183
	SAY UNIDENTIFIED_DESC @20183
COPY ~might_and_guile/feats/d5_rf32b.spl~ ~override~
	SAY NAME1 @20184
	SAY UNIDENTIFIED_DESC @20184
COPY ~might_and_guile/feats/d5_rf32c.spl~ ~override~
	SAY NAME1 @20185
	SAY UNIDENTIFIED_DESC @20185
COPY ~might_and_guile/feats/d5_rf32d.spl~ ~override~
	SAY NAME1 @20186
	SAY UNIDENTIFIED_DESC @20186
COPY ~might_and_guile/feats/d5_rf32e.spl~ ~override~
	SAY NAME1 @20187
	SAY UNIDENTIFIED_DESC @20187
COPY ~might_and_guile/feats/d5_rf32f.spl~ ~override~
	SAY NAME1 @20188
	SAY UNIDENTIFIED_DESC @20188
COPY ~might_and_guile/feats/d5_rf32g.spl~ ~override~
	SAY NAME1 @20189
	SAY UNIDENTIFIED_DESC @20189

COPY ~might_and_guile/feats/d5_rfc3b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfc3.spl~ ~override/d5urc3.spl~   // 			toxic poison
	SAY NAME1 @20161
	SAY UNIDENTIFIED_DESC @20162
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfc3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc3b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %assassin_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfc3a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %assassin_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfc3b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfc3a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urc3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrc3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfc3b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfc3a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfc3b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urc3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrc3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfc3b~ END
COPY_EXISTING ~spcl423.spl~ ~override/d5_rf33.spl~
	SAY NAME1 @20161
	SAY UNIDENTIFIED_DESC @20162
	WRITE_ASCII 0x3a ~d5_rfc3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc3b~ END
COPY_EXISTING  ~d5urc3.spl~ ~override/d5vrc3.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfc4b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfc4.spl~ ~override/d5urc4.spl~   // 			paralytic poison
	SAY NAME1 @20163
	SAY UNIDENTIFIED_DESC @20164
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfc4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc4b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %hunter_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfc4a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %hunter_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfc4b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfc4a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urc4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrc4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfc4b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfc4a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfc4b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urc4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrc4~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfc4b~ END
COPY ~might_and_guile/feats/d5_rf34.spl~ ~override~
	SAY NAME1 @20163
	SAY UNIDENTIFIED_DESC @20164
	WRITE_ASCII 0x3a ~d5_rfc4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc4b~ END
COPY ~might_and_guile/feats/d5_rf34.eff~ ~override~
COPY ~might_and_guile/feats/d5_rf34a.spl~ ~override~
	SAY NAME1 @20163
	SAY UNIDENTIFIED_DESC @20164
COPY_EXISTING  ~d5urc4.spl~ ~override/d5vrc4.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfc6b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfc6.spl~ ~override/d5urc6.spl~   // 			flaming weapon
	SAY NAME1 @20151
	SAY UNIDENTIFIED_DESC @20152
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfc6b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc6b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfc6a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfc6b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfc6a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urc6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrc6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfc6b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfc6a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfc6b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urc6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrc6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfc6b~ END
COPY ~might_and_guile/feats/d5_rf36.spl~ ~override~
	SAY NAME1 @20151
	SAY UNIDENTIFIED_DESC @20152
	WRITE_ASCII 0x3a ~d5_rfc6b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc6b~ END
COPY ~might_and_guile/feats/d5_rf36.eff~ ~override~
COPY_EXISTING  ~d5urc6.spl~ ~override/d5vrc6.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfc7b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfc7.spl~ ~override/d5urc7.spl~   // 		  hulking transformation
	SAY NAME1 @20171
	SAY UNIDENTIFIED_DESC @20172
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfc7b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc7~ END
COPY ~might_and_guile/feats/d5_rf37.spl~ ~override~
	SAY NAME1 @20171
	SAY UNIDENTIFIED_DESC @20172
	WRITE_ASCII 0x3a ~d5_rfc7b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfc7b~ END
COPY ~might_and_guile/feats/d5_alnf.spl~ ~override~
	SAY NAME1 @40
	SAY UNIDENTIFIED_DESC @40
COPY ~might_and_guile/feats/d5_clalc.itm~ ~override~
	SAY NAME1 @20173
	SAY UNIDENTIFIED_DESC @20173
COPY ~might_and_guile/feats/d5_alch.cre~ ~override~
	SAY NAME1 @20174
COPY_EXISTING  ~d5urc7.spl~ ~override/d5vrc7.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rf3z.spl~ ~override~   		 // 			high-level alchemy
	SAY NAME1 @20191
	SAY UNIDENTIFIED_DESC @20192
COPY ~might_and_guile/feats/d5_rf3z.2da~ ~override~
COPY ~might_and_guile/feats/d5_rf3za.spl~ ~override~
	SAY NAME1 @20193
	SAY UNIDENTIFIED_DESC @20193
COPY ~might_and_guile/feats/d5_rf3zb.spl~ ~override~
	SAY NAME1 @20194
	SAY UNIDENTIFIED_DESC @20194
COPY ~might_and_guile/feats/d5_rf3zc.spl~ ~override~
	SAY NAME1 @20195
	SAY UNIDENTIFIED_DESC @20195
COPY ~might_and_guile/feats/d5_rf3zd.spl~ ~override~
	SAY NAME1 @20196
	SAY UNIDENTIFIED_DESC @20196
COPY ~might_and_guile/feats/d5_rf3ze.spl~ ~override~
	SAY NAME1 @20197
	SAY UNIDENTIFIED_DESC @20197
COPY ~might_and_guile/feats/d5_rf3zf.spl~ ~override~
	SAY NAME1 @20198
	SAY UNIDENTIFIED_DESC @20198

// evasive

COPY ~might_and_guile/feats/d5_rfd1b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfd1.spl~ ~override/d5urd1.spl~    // 			AC bonus
	SAY NAME1 @20201
	SAY UNIDENTIFIED_DESC @20202
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 2
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfd1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfd1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %swashbuckler_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfd1a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %swashbuckler_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfd1b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfd1a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urd1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrd1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfd1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfd1a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfd1b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urd1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrd1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfd1b~ END
COPY_EXISTING  ~d5urd1.spl~ ~override/d5vrd1.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfd1.spl~ ~override/d5urd0.spl~    // 			AC bonus
	SAY NAME1 @20201
	SAY UNIDENTIFIED_DESC @20202
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 2
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfd1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfd1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %swashbuckler_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfd0a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %swashbuckler_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfd0b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfd0a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urd0~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrd0~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfd0b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfd0a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfd0b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urd0~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrd0~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfd0b~ END
COPY_EXISTING  ~d5urd0.spl~ ~override/d5vrd0.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfd2b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfd2.spl~ ~override/d5urd2.spl~   // 			escape artist
	SAY NAME1 @20221
	SAY UNIDENTIFIED_DESC @20222
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 2
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfd2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfd2b~ END
/*old
COPY ~might_and_guile/feats/d5_rf42.spl~ ~override~
	SAY NAME1 @20221
	SAY UNIDENTIFIED_DESC @20222
	WRITE_ASCII 0x3a ~d5_rfd2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfd2b~ END
*/
COPY_EXISTING ~sppr308.spl~ ~override/d5rf42.spl~ 
	LPF ALTER_SPELL_HEADER INT_VAR target = 1 projectile = 1 STR_VAR icon = ~d5_rfd2b~ END
COPY_EXISTING  ~d5urd2.spl~ ~override/d5vrd2.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfd3b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfd3.spl~ ~override/d5urd3.spl~   //			iwd spell evasion
	SAY NAME1 @20223
	SAY UNIDENTIFIED_DESC @20224
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 2
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfd3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfd3b~ END
OUTER_SET optional_evade = 1
INCLUDE ~%MOD_FOLDER%/lib/spell_evasion.tpa~
ACTION_PHP_EACH evade_spells AS evadable_spell => val BEGIN
  ACTION_IF (%val% = 1) BEGIN
    LAF add_evade_spell INT_VAR evasion_spellstate = 252 evasion_save = 2 STR_VAR evade_ext = ~spl~ evade_res = EVAL ~%evadable_spell%~ evade_prefix = ~D5EV~ END
  END
END
ACTION_PHP_EACH evade_items AS evadable_item => val BEGIN
  ACTION_IF (%val% = 1) BEGIN
    LAF add_evade_spell INT_VAR evasion_spellstate = 252 evasion_save = 2 STR_VAR evade_ext = ~itm~ evade_res = EVAL ~%evadable_item%~ evade_prefix = ~D5EV~ END
  END
END
COPY_EXISTING  ~d5urd3.spl~ ~override/d5vrd3.spl~ 
	WRITE_SHORT 0x1c 1

ACTION_IF FILE_EXISTS_IN_GAME ~clabth01.2da~ BEGIN
  COPY_EXISTING ~clabth01.2da~ ~override~
	REPLACE_TEXTUALLY ~AP_#EVASION~ ~****       ~
  BUT_ONLY
END
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_evasion_array BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY
ACTION_PHP_EACH d5_evasion_array AS fo => sho BEGIN
  ACTION_IF (%sho% = 4) AND (FILE_EXISTS_IN_GAME ~%fo%.2da~) BEGIN
	COPY_EXISTING ~%fo%.2da~ ~override~
	  REPLACE_TEXTUALLY ~AP_#EVASION~ ~****       ~	
	  REPLACE_TEXTUALLY ~AP_D5EVADE ~ ~****       ~	
	BUT_ONLY
  END
END

//COPY_EXISTING ~sw1h04.itm~ ~override/d5__evasion.d5~

COPY ~might_and_guile/feats/d5_rfd4b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfd4.spl~ ~override/d5urd4.spl~   // 			missile snaring
	SAY NAME1 @20203
	SAY UNIDENTIFIED_DESC @20204
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 2
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfd4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfd4b~ END
CREATE EFF ~d5_rfd4~
	WRITE_LONG 0x10 232
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 0
	WRITE_LONG 0x20 20
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~d5_rf44~ #8
COPY_EXISTING  ~d5urd4.spl~ ~override/d5vrd4.spl~ 
	WRITE_SHORT 0x1c 1

LAF d5_resolve_state STR_VAR new_state_id = ~D5_SNAREARROW~ RET new_state_ind END
OUTER_SET missile_snaring_state = %new_state_ind%
OUTER_SET nada = RESOLVE_STR_REF (~ ~)
ACTION_IF NOT FILE_EXISTS_IN_GAME ~7eyes.2da~ BEGIN
	COPY ~might_and_guile/misc/7eyes.2da~ ~override~
END
APPEND ~7eyes.2da~ ~SNARE_ARROW  %missile_snaring_state%         %nada%         12*0x800000 *           *           *            *            *          *          *          * ~ UNLESS ~SNARE_ARROW~
COPY_EXISTING ~7eyes.2da~ ~override~
  COUNT_2DA_ROWS 1 rows
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY row 0 1 tag
	PATCH_IF (~%tag%~ STRING_EQUAL_CASE ~SNARE_ARROW~) BEGIN
	  SET 7eyes_row = row
	END
  END
BUT_ONLY
COPY ~might_and_guile/feats/d5_rf44.spl~ ~override~
  PATCH_IF (IS_AN_INT %7eyes_row%) BEGIN
	LPF ALTER_EFFECT INT_VAR match_opcode = 335 parameter1 = %missile_snaring_state% parameter2 = %7eyes_row% END
  END

COPY ~might_and_guile/feats/d5_rfd5b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfd5.spl~ ~override/d5urd5.spl~   // 			save bonuses
	SAY NAME1 @20211
	SAY UNIDENTIFIED_DESC @20212
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 2
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfd5b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfd5b~ END
COPY_EXISTING  ~d5urd5.spl~ ~override/d5vrd5.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfd6b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfd6.spl~ ~override/d5urd6.spl~   // 			spell/wand saves
	SAY NAME1 @20213
	SAY UNIDENTIFIED_DESC @20214
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 2
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfd6b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfd6b~ END
COPY_EXISTING  ~d5urd6.spl~ ~override/d5vrd6.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfd7b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfd7.spl~ ~override/d5urd7.spl~   // 			death/polymorph saves
	SAY NAME1 @20215
	SAY UNIDENTIFIED_DESC @20216
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 2
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfd7b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfd7b~ END
COPY_EXISTING  ~d5urd7.spl~ ~override/d5vrd7.spl~ 
	WRITE_SHORT 0x1c 1

// slippery mind: 5 Charm, 128 Confusion, 76 feeblemind, 213 Maze
LAF d5_resolve_state STR_VAR new_state_id = ~D5_CHARMEVADE~ RET new_state_ind END
OUTER_SET charm_evasion_state = %new_state_ind%
COPY ~might_and_guile/feats/d5_rfd8b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfd8.spl~ ~override/d5urd8.spl~   // 			charm evasion
	SAY NAME1 @20217
	SAY UNIDENTIFIED_DESC @20218
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 2
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfd8b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfd8b~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 328 parameter2 = %charm_evasion_state% END
COPY_EXISTING  ~d5urd8.spl~ ~override/d5vrd8.spl~ 
	WRITE_SHORT 0x1c 1
<<<<<<<< d5/d5chrmev.2da
2DA V1.0 
RES
>>>>>>>> 
COPY ~d5/d5chrmev.2da~ ~override/d5chrmev.2da~ 
COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
  PHP_EACH ab_array AS int => ab_off BEGIN
	GET_OFFSET_ARRAY2 fx_array ab_off SPL_V10_HEAD_EFFECTS
	PHP_EACH fx_array AS int => fx_off BEGIN
	  READ_SHORT fx_off fx_type
	  PATCH_IF (fx_type = 5) || (fx_type = 128) || (fx_type = 76) || (fx_type = 213) BEGIN
//		  PATCH_PRINT "%SOURCE_RES%.spl subject to Slippery Mind"
		  INNER_ACTION BEGIN
			APPEND ~d5chrmev.2da~ ~%SOURCE_RES% 	SPL~ UNLESS ~%SOURCE_RES%~
		  END
	  END
	END
  END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  GET_OFFSET_ARRAY ab_array ITM_V10_HEADERS
  PHP_EACH ab_array AS int => ab_off BEGIN
	GET_OFFSET_ARRAY2 fx_array ab_off ITM_V10_HEAD_EFFECTS
	PHP_EACH fx_array AS int => fx_off BEGIN
	  READ_SHORT fx_off fx_type
	  PATCH_IF (fx_type = 5) || (fx_type = 128) || (fx_type = 76) || (fx_type = 213) BEGIN
//		  PATCH_PRINT "%SOURCE_RES%.itm subject to Slippery Mind"
		  INNER_ACTION BEGIN
			APPEND ~d5chrmev.2da~ ~%SOURCE_RES% 	ITM~ UNLESS ~%SOURCE_RES%~
		  END
	  END
	END
  END
BUT_ONLY
COPY_EXISTING ~d5chrmev.2da~ ~override~ 
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY row 0 cols charm_evade_res
	READ_2DA_ENTRY row 1 cols charm_evade_type
	PATCH_IF (~%charm_evade_type%~ STRING_EQUAL_CASE ~spl~) BEGIN 
	 PATCH_IF FILE_EXISTS_IN_GAME ~%charm_evade_res%.spl~ BEGIN
	  INNER_ACTION BEGIN
		LAF add_evade_spell INT_VAR evasion_spellstate = %charm_evasion_state% evasion_save = 1 STR_VAR evade_ext = ~spl~ evade_condition = ~spellstate~ evade_res = EVAL ~%charm_evade_res%~ evade_prefix = ~D5VC~ END
	  END
	 END
	END
	PATCH_IF (~%charm_evade_type%~ STRING_EQUAL_CASE ~spl~) BEGIN 
	 PATCH_IF FILE_EXISTS_IN_GAME ~%charm_evade_res%.itm~ BEGIN
	  INNER_ACTION BEGIN
		LAF add_evade_spell INT_VAR evasion_spellstate = %charm_evasion_state% evasion_save = 1 STR_VAR evade_ext = ~itm~ evade_condition = ~spellstate~ evade_res = EVAL ~%charm_evade_res%~ evade_prefix = ~D5VC~ END
	  END
	 END
	END
  END
BUT_ONLY

// combat 

COPY ~might_and_guile/feats/d5_rfe1b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfe1.spl~ ~override/d5ure1.spl~  	 // 			melee thac0
	SAY NAME1 @20231
	SAY UNIDENTIFIED_DESC @20232
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfe1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfe1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %swashbuckler_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfe1a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %swashbuckler_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfe1b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfe1a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ure1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vre1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfe1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfe1a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfe1b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ure1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vre1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfe1b~ END
COPY_EXISTING  ~d5ure1.spl~ ~override/d5vre1.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfe1.spl~ ~override/d5ure0.spl~   // 			melee thac0
	SAY NAME1 @20231
	SAY UNIDENTIFIED_DESC @20232
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfe1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfe1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %swashbuckler_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfe0a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %swashbuckler_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfe0b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfe0a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ure0~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vre0~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfe0b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfe0a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfe0b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ure0~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vre0~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfe0b~ END
COPY_EXISTING  ~d5ure0.spl~ ~override/d5vre0.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfe3b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfe3.spl~ ~override/d5ure3.spl~   // 			ranged thac0
	SAY NAME1 @20233
	SAY UNIDENTIFIED_DESC @20234
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfe3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfe3b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfe3a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfe3b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfe3a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ure3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vre3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfe3b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfe3a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfe3b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ure3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vre3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfe3b~ END
COPY_EXISTING  ~d5ure3.spl~ ~override/d5vre3.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfe5b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfe5.spl~ ~override/d5ure5.spl~   // 			backstab bonus
	SAY NAME1 @20241
	SAY UNIDENTIFIED_DESC @20242
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfe5b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfe5b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %assassin_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfe5a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %assassin_ids% parameter2 = %kit_is_row% timing = 9 duration = 0 STR_VAR resource = ~d5_rfe5b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfe5a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ure5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vre5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfe5b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfe5a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfe5b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ure5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vre5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfe5b~ END
COPY_EXISTING  ~d5ure5.spl~ ~override/d5vre5.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfe6b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfe6.spl~ ~override/d5ure6.spl~   	//	 			crit bonus
	SAY NAME1 @20243
	SAY UNIDENTIFIED_DESC @20244
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfe6b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfe6b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5ure7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vre7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~D5URFE7~ END
COPY_EXISTING  ~d5ure6.spl~ ~override/d5vre6.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfe7b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfe7.spl~ ~override/d5ure7.spl~  	 // 			crit bonus 2
	SAY NAME1 @20245
	SAY UNIDENTIFIED_DESC @20246
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 2
	END
	WRITE_ASCII 0x3a ~d5_rfe6b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfe7b~ END
COPY_EXISTING  ~d5ure7.spl~ ~override/d5vre7.spl~ 
	WRITE_SHORT 0x1c 1
	LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = ~d5ure6~ resource = ~d5vre6~ END

// combat techniques

COPY ~might_and_guile/feats/d5_rfe8b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfe8.spl~ ~override/d5ure8.spl~	 //				swashbuckling
	SAY NAME1 @3112
	SAY UNIDENTIFIED_DESC @3113
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfe8b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfe8b~ END
COPY ~might_and_guile/misc/d5swash.spl~ ~override~
	SAY NAME1 @3112
	SAY UNIDENTIFIED_DESC @3113
	WRITE_ASCII 0x3a ~d5_rfe8b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfe8b~ END
COPY ~might_and_guile/misc/d5swshb.eff~ ~override~
COPY ~might_and_guile/misc/d5swshc.spl~ ~override~
COPY ~might_and_guile/misc/d5swshx.spl~ ~override~
	SAY NAME1 @3114
	SAY UNIDENTIFIED_DESC @3114
	WRITE_ASCII 0x3a ~d5swshx~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5swshx~ END
COPY ~might_and_guile/misc/d5swshx.bam~ ~override~
COPY_EXISTING  ~d5ure8.spl~ ~override/d5vre8.spl~ 
	WRITE_SHORT 0x1c 1
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
	READ_BYTE 0x31 prof
	PATCH_IF (prof = 103) || (prof = 104) || (prof = 105) || (prof = 106) || (prof = 107) BEGIN
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = ~d5swshc~ END
	END
  END
BUT_ONLY

INCLUDE ~might_and_guile/lib/extra_prof_dialogue.tpa~
COPY ~might_and_guile/feats/d5_rfe9b.bam~ ~override~
COPY ~might_and_guile/feats/d5ftpr0f.spl~ ~override/d5ure9.spl~	 	//		extra prof
	SAY NAME1 @20496
	SAY UNIDENTIFIED_DESC @20497
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 2
	END
	WRITE_ASCII 0x3a ~d5_rfe9b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfe9b~ END
COPY ~might_and_guile/feats/d5ftprx.spl~ ~override~
	SAY NAME1 @20496
	SAY UNIDENTIFIED_DESC @20497
	WRITE_ASCII 0x3a ~d5_rfe9b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfe9b~ END
COPY ~might_and_guile/feats/d5ftprof.eff~ ~override~
COPY ~might_and_guile/feats/d5ftprof.cre~ ~override~
COPY_EXISTING  ~d5ure9.spl~ ~override/d5vre9.spl~ 
	WRITE_SHORT 0x1c 1

/*
COPY ~might_and_guile/feats/d5_rfg1b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfg1.spl~ ~override~   // 			trip
	SAY NAME1 @20251
	SAY UNIDENTIFIED_DESC @20252
	WRITE_ASCII 0x3a ~d5_rfg1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfg1b~ END
COPY ~might_and_guile/feats/d5_rf71.spl~ ~override~
	SAY NAME1 @20251
	SAY UNIDENTIFIED_DESC @20252
	WRITE_ASCII 0x3a ~d5_rfg1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfg1b~ END
COPY ~might_and_guile/fighter/d5_wf07.eff~ ~override~

COPY ~might_and_guile/feats/d5_rfg2b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfg2.spl~ ~override~ 			  // 			disarm
	SAY NAME1 @20253
	SAY UNIDENTIFIED_DESC @20254
	WRITE_ASCII 0x3a ~d5_rfg2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfg2b~ END
COPY ~might_and_guile/feats/d5_rf72.spl~ ~override~
	SAY NAME1 @20253
	SAY UNIDENTIFIED_DESC @20254
	WRITE_ASCII 0x3a ~d5_rfg2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfg2b~ END
COPY ~might_and_guile/feats/d5_rf72a.eff~ ~override~
COPY ~might_and_guile/feats/d5_rf72b.eff~ ~override~
COPY ~might_and_guile/feats/d5_rf72c.eff~ ~override~
*/

COPY ~might_and_guile/feats/d5_rfg3b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfg3.spl~ ~override/d5urg3.spl~   // 			blind
	SAY NAME1 @20255
	SAY UNIDENTIFIED_DESC @20256
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfg3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfg3b~ END
COPY ~might_and_guile/feats/d5_rf73.spl~ ~override~
	SAY NAME1 @20255
	SAY UNIDENTIFIED_DESC @20256
	WRITE_ASCII 0x3a ~d5_rfg3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfg3b~ END
COPY ~might_and_guile/feats/d5_rf73.eff~ ~override~
COPY_EXISTING  ~d5urg3.spl~ ~override/d5vrg3.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfg4b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfg4.spl~ ~override/d5urg4.spl~   // 			disrupt
	SAY NAME1 @20257
	SAY UNIDENTIFIED_DESC @20258
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfg4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfg4b~ END
COPY ~might_and_guile/feats/d5_rf74.spl~ ~override~
	SAY NAME1 @20257
	SAY UNIDENTIFIED_DESC @20258
	WRITE_ASCII 0x3a ~d5_rfg4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfg4b~ END
COPY ~might_and_guile/feats/d5_rf74.eff~ ~override~
COPY_EXISTING  ~d5urg4.spl~ ~override/d5vrg4.spl~ 
	WRITE_SHORT 0x1c 1

// ***** change this to a chance of each effect
COPY ~might_and_guile/feats/d5_rfg5b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfg5.spl~ ~override/d5urg5.spl~   // 			fighting dirty
	SAY NAME1 @20259
	SAY UNIDENTIFIED_DESC @20260
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfg5b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfg5b~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 parameter1 = (4 << 24) END
COPY_EXISTING  ~d5urg5.spl~ ~override/d5vrg5.spl~ 
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols 
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_115_FEATS~ BEGIN
	    SET 115_dirty = %row%
	  END
	END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
	READ_BYTE 0x31 prof
	PATCH_IF (%prof% = 115) || (%prof% = 89) || (%prof% = 90) || (%prof% = 91) || (%prof% = 92) || (%prof% = 93) || (%prof% = 94) || (%prof% = 95) || (%prof% = 96) || (%prof% = 97) || (%prof% = 98) || (%prof% = 99) || (%prof% = 100) || (%prof% = 101) || (%prof% = 102) BEGIN	// any weapon
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 248 target = 1 timing = 2 resist_dispel = 0 STR_VAR resource = ~d5_rf75a~ END
	END
  END
BUT_ONLY
COPY ~might_and_guile/feats/d5_rf75a.eff~ ~override~
COPY ~might_and_guile/feats/d5_rf75a.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 326 parameter1 = (4 << 24) parameter2 = %115_dirty% END
COPY ~might_and_guile/feats/d5_rf75b.spl~ ~override~
COPY ~might_and_guile/feats/d5_rf75d.spl~ ~override~
COPY ~might_and_guile/feats/d5_rf75f.spl~ ~override~

// pseudo-magical

COPY ~might_and_guile/feats/d5_rfh1b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfh2b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfh1.spl~ ~override/d5urh1.spl~   //          grease jar/smoke bomb
	SAY NAME1 @20271
	SAY UNIDENTIFIED_DESC @20272
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_rfh2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfh2b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfh2a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfh2b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfh2a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urh2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrh2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfh2b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfh2a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfh2b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urh2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrh2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfh2b~ END
COPY_EXISTING  ~d5urh1.spl~ ~override/d5vrh1.spl~ 
	WRITE_SHORT 0x1c 1
COPY_EXISTING ~spwi101.spl~ ~override/d5_rf81.spl~  		 //            grease jar
	SAY NAME1 @20273 
	SAY UNIDENTIFIED_DESC @20274
	WRITE_ASCII 0x3a ~d5_rfh1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfh1b~ END
	LPM spell_to_innate
COPY_EXISTING ~spwi213.spl~ ~override/d5_rf82.spl~  		 //            smoke bomb
	SAY NAME1 @20275
	SAY UNIDENTIFIED_DESC @20276
	WRITE_ASCII 0x3a ~d5_rfh2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfh2b~ END
	LPM spell_to_innate

COPY ~might_and_guile/feats/d5_rfh5b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfh5.spl~ ~override/d5urh5.spl~   //           shadow pool
	SAY NAME1 @2755
	SAY UNIDENTIFIED_DESC @2756
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 2
	END
	WRITE_ASCII 0x3a ~d5_rfh5b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfh5b~ END
	LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 171 STR_VAR resource = ~d5_rf85~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfh5a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfh5b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfh5a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urh5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrh5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfh5b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfh5a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfh5b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urh5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrh5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfh5b~ END
COPY_EXISTING ~d5_shad1.spl~ ~override/d5_rf85.spl~
	SAY NAME1 @2755
	SAY UNIDENTIFIED_DESC @2756
	WRITE_ASCII 0x3a ~d5_rfh5b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfh5b~ END
//COPY ~might_and_guile/feats/d5_shad1.2da~ ~override~
COPY_EXISTING  ~d5urh5.spl~ ~override/d5vrh5.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_rfh6b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfh6.spl~ ~override/d5urh6.spl~   // 		  illusion pool
	SAY NAME1 @20283
	SAY UNIDENTIFIED_DESC @20284
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 2
	END
	WRITE_ASCII 0x3a ~d5_rfh6b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfh6b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfh6a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_rfh6b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfh6a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urh6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrh6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_rfh6b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfh6a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_rfh6b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5urh6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vrh6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_rfh6b~ END
COPY ~might_and_guile/feats/d5_illp.spl~ ~override~
	SAY NAME1 @20283
	SAY UNIDENTIFIED_DESC @20284
	WRITE_ASCII 0x3a ~d5_rfh6b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfh6b~ END
COPY ~might_and_guile/feats/d5illpa.2da~ ~override~
COPY ~might_and_guile/feats/d5illpb.2da~ ~override~
COPY ~might_and_guile/feats/d5illpc.2da~ ~override~
COPY ~might_and_guile/feats/d5illp5.spl~ ~override~
	SAY NAME1 @20285
	SAY UNIDENTIFIED_DESC @20286
COPY ~might_and_guile/feats/d5illp5a.spl~ ~override~
	SAY NAME1 @20285
COPY ~might_and_guile/feats/d5illp5b.spl~ ~override~
	SAY NAME1 @20285
COPY ~might_and_guile/feats/d5illp5a.eff~ ~override~
COPY_EXISTING  ~d5urh6.spl~ ~override/d5vrh6.spl~ 
	WRITE_SHORT 0x1c 1

//use scrolls/wands_________________________________________________________________
//
COPY ~might_and_guile/feats/d5_rfh4b.bam~ ~override~
COPY ~might_and_guile/feats/d5_rfh4.spl~ ~override/d5urh4.spl~   //           UMD
	SAY NAME1 @20293
	SAY UNIDENTIFIED_DESC @20294
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 2
	END
	WRITE_ASCII 0x3a ~d5_rfh4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfh4b~ END
//	LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = ~d5_numd~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5_numd~ END
COPY_EXISTING  ~d5urh4.spl~ ~override/d5vrh4.spl~ 
	WRITE_SHORT 0x1c 1
COPY_EXISTING  ~d5urh4.spl~ ~override/d5_umd.spl~ 
	WRITE_SHORT 0x1c 4
	WRITE_LONG 0x34 1

LAF d5_resolve_specific STR_VAR new_specific_id = ~D5_NO_UMD~ RET new_specific_ind END

OUTER_SET no_umd_specific = %new_specific_ind%

COPY ~might_and_guile/feats/d5_nscrl.spl~ ~override/d5_numd.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR resource = ~d5_numd~ END
// add .eff setting local variable
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 STR_VAR resource = ~d5numdlv~ END

COPY ~might_and_guile/feats/d5_rf84n.eff~ ~override/D5_NUMD.eff~
  WRITE_LONG 0x1c %no_umd_specific%
  WRITE_LONG 0x90 1
  WRITE_EVALUATED_ASCII 0x94 ~D5_NUMD~ #8

// make an .eff to set D5NOUMD local variable
CREATE EFF ~d5numdlv~
	WRITE_LONG 0x10 309
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 1
	WRITE_LONG 0x20 0
	WRITE_LONG 0x24 9
	WRITE_LONG 0x28 0
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~D5NOUMD~ #8

OUTER_SET scroll_count = 0
OUTER_SPRINT $use_scrolls(~%scroll_count%~) ~scroll~
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  READ_BYTE     0x2f current ELSE 0
  READ_BYTE     0x2b current2 ELSE 0
  READ_LONG 0x64 headoffset  ELSE 0
  READ_SHORT 0x68 headcount  ELSE 0
  READ_LONG 0x6a effectsoffset  ELSE 0
  haslearn = 0
  hascast = 0
//	  PATCH_IF (headcount = 2) BEGIN
    FOR (headcyc = 0; headcyc < headcount ; headcyc = headcyc + 1) BEGIN
      thishead = 0
      READ_SHORT (headoffset + (headcyc * 0x38) + 0x1e) effcount  ELSE 0
      READ_SHORT (headoffset + (headcyc * 0x38) + 0x20) effectsindex  ELSE 0
      FOR (effcyc = 0; effcyc < effcount; effcyc = effcyc + 1) BEGIN
        READ_SHORT (effectsoffset + (effectsindex + effcyc)* 0x30) opcode ELSE 0
        PATCH_IF (opcode = 0x93) AND (thishead = 0) BEGIN
          READ_ASCII (effectsoffset + 0x14 + (effectsindex + effcyc)* 0x30) resref_learn  ELSE 0
          INNER_PATCH_FILE ~%resref_learn%.spl~ BEGIN
            READ_SHORT 0x1c type
          END
          PATCH_IF (type = 1) BEGIN // spell scroll
            thishead = 1
            haslearn = 1
          END
        END // PATCH_IF... (opcode = learn spell)
        PATCH_IF ((opcode = 0x92) OR (opcode = 0x94)) AND (thishead = 0) BEGIN
          READ_ASCII (effectsoffset + 0x14 + (effectsindex + effcyc)* 0x30) resref_cast  ELSE 0
          INNER_PATCH_FILE ~%resref_cast%.spl~ BEGIN
            READ_SHORT 0x1c type
          END
          PATCH_IF (type = 1) OR (type = 2) BEGIN // spell scroll
            thishead = 1
            hascast = 1
          END
        END // PATCH_IF (opcode = cast spell)
      END // FOR... effect_cycle
    END // FOR... header cycle
//  END // PATCH_IF... have exactly 2 headers
  PATCH_IF (haslearn = 1) AND (hascast = 1) /*AND (~%resref_cast%~ STRING_EQUAL_CASE ~%resref_learn%~) */BEGIN
	SPRINT $use_scrolls(~%scroll_count%~) ~%SOURCE_RES%~
	SET ++scroll_count
  END
BUT_ONLY
ACTION_PHP_EACH use_scrolls AS num => scroll BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%scroll%.itm~ BEGIN
//	PRINT ~%scroll% is a wizard scroll~
	COPY_EXISTING ~%scroll%.itm~ ~override~
	  WRITE_BYTE 0x1f (THIS BAND 0b11111101)
	  WRITE_BYTE 0x20 (THIS BAND 0b10111101)
	  PATCH_IF !(FILE_EXISTS_IN_GAME ~d5__umd.d5~) BEGIN
		LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter2 = 6 parameter1 = %no_umd_specific% timing = 2 END
	  END
	BUT_ONLY
  END
END
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  READ_SHORT	0x1c item_type
  PATCH_IF (item_type = 35) BEGIN
	READ_BYTE 0x20 thief_use
	PATCH_IF (%thief_use% BAND 0b01000000) = 0b01000000 BEGIN
	  WRITE_BYTE 0x1f (THIS BAND 0b11111101)
	  WRITE_BYTE 0x20 (THIS BAND 0b10111101)
	  PATCH_IF !(FILE_EXISTS_IN_GAME ~d5__umd.d5~) BEGIN
		LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter2 = 6 parameter1 = %no_umd_specific% timing = 2 END
	  END
	END
  END
BUT_ONLY

 ACTION_IF GAME_INCLUDES ~sod~ BEGIN
  COPY_EXISTING dplayer2.bcs override
	DECOMPILE_AND_PATCH BEGIN
	  REPLACE_TEXTUALLY ~THEN[%WNL%%LNL%%MNL%%TAB% ]+RESPONSE[%TAB% ]+#100[%WNL%%LNL%%MNL%%TAB% ]+ChangeSpecifics(Myself,\(1\|NORMAL\))~
    ~
  !Specifics(Myself,D5_NO_UMD)
  Switch("D5NOUMD","locals")
THEN
  RESPONSE #0
    ChangeSpecifics(Myself,NORMAL)
    SetGlobal("bd_joined","locals",0)
    SetGlobal("bd_npc_camp","locals",0)
  RESPONSE #1
    ChangeSpecifics(Myself,D5_NO_UMD)~
	END
  BUT_ONLY
 END
 
 COPY ~%MOD_FOLDER%/lib/markers/d5_marker.d5~ ~override/d5__umd.d5~

//	end use scrolls/wands

// ***** if WtP installed, make feat for automatic wild talent


// warrior feats______________________________________________________________________
//
// group tactics

COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf11n.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~D5_WF11~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~D5_WF11N~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf12n.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~D5_WF12~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~D5_WF12N~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf13n.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~D5_WF13~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~D5_WF13N~ END

COPY ~might_and_guile/feats/d5_wfa1b.bam~ ~override~
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5uwa1.spl~	//			offensive tactics
	SAY NAME1 @20321
	SAY UNIDENTIFIED_DESC @20322
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfa1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfa1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF11N~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5_wf11~ END
COPY_EXISTING  ~d5uwa1.spl~ ~override/d5vwa1.spl~ 
	WRITE_SHORT 0x1c 1
CREATE EFF ~D5_WF11~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_LONG 0x28 0
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~D5_WF11~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5_WF11~ #8
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf11.spl~
	SAY NAME1 @20321
	SAY UNIDENTIFIED_DESC @20322
	WRITE_ASCII 0x3a ~d5_wfa1b~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~d5_wfa1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF11~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF12~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF13~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf11~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf12~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf13~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF11A~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF12~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF13~ END
COPY ~might_and_guile/feats/d5_wf11a.eff~ ~override~
COPY ~might_and_guile/feats/d5_wf11a.spl~ ~override~

COPY ~might_and_guile/feats/d5_wfa2b.bam~ ~override~
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5uwa2.spl~	//			defensive tactics
	SAY NAME1 @20323
	SAY UNIDENTIFIED_DESC @20324
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfa2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfa2b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF12N~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5_wf12~ END
COPY_EXISTING  ~d5uwa2.spl~ ~override/d5vwa2.spl~ 
	WRITE_SHORT 0x1c 1
CREATE EFF ~D5_WF12~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_LONG 0x28 0
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~D5_WF12~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5_WF12~ #8
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf12.spl~
	SAY NAME1 @20323
	SAY UNIDENTIFIED_DESC @20324
	WRITE_ASCII 0x3a ~d5_wfa2b~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~d5_wfa2b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF11~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF12~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF13~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf11~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf12~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf13~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF11~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF12A~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF13~ END
COPY ~might_and_guile/feats/d5_wf12a.eff~ ~override~
COPY ~might_and_guile/feats/d5_wf12a.spl~ ~override~

COPY ~might_and_guile/feats/d5_wfa3b.bam~ ~override~
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5uwa3.spl~	//			efficient tactics
	SAY NAME1 @20325
	SAY UNIDENTIFIED_DESC @20326
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfa3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfa3b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF13N~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5_wf13~ END
COPY_EXISTING  ~d5uwa3.spl~ ~override/d5vwa3.spl~ 
	WRITE_SHORT 0x1c 1
CREATE EFF ~D5_WF13~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_LONG 0x28 0
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~D5_WF13~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5_WF13~ #8
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf13.spl~
	SAY NAME1 @20325
	SAY UNIDENTIFIED_DESC @20326
	WRITE_ASCII 0x3a ~d5_wfa3b~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~d5_wfa3b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF11~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF12~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF13~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf11~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf12~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf13~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF11~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF12~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF13A~ END
COPY ~might_and_guile/feats/d5_wf13a.eff~ ~override~
COPY ~might_and_guile/feats/d5_wf13a.spl~ ~override~

// melee postures

COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf21n.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~D5_WF21~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5_wf21n~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf22n.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~D5_WF22~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5_wf22n~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf23n.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~D5_WF23~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5_wf23n~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf24n.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~D5_WF24~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5_wf24n~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf25n.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~D5_WF25~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5_wf25n~ END

COPY ~might_and_guile/feats/d5_wfb1b.bam~ ~override~
COPY ~might_and_guile/feats/d5_wfb1.spl~ ~override/d5uwb1.spl~	//			aggressive posture
	SAY NAME1 @20341
	SAY UNIDENTIFIED_DESC @20342
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfb1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfb1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF21N~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5_wf21~ END
COPY_EXISTING  ~d5uwb1.spl~ ~override/d5vwb1.spl~ 
	WRITE_SHORT 0x1c 1
CREATE EFF ~D5_WF21~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_LONG 0x28 0
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~D5_WF21~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5_WF21~ #8
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf21.spl~
	SAY NAME1 @20341
	SAY UNIDENTIFIED_DESC @20342
	WRITE_ASCII 0x3a ~d5_wfb1~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~d5_wfb1b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF22~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF23~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF24~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF25~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf22~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf23~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf24~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf25~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 248 target = 1 timing = 0 duration = 126244000 STR_VAR resource = ~D5_WF21b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 142 target = 1 parameter2 = 21 timing = 0 duration = 126244000 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF22~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF23~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF24~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF25~ END
COPY ~might_and_guile/feats/d5_wf21b.eff~ ~override~
COPY ~might_and_guile/feats/d5_wf21b.spl~ ~override~

COPY ~might_and_guile/feats/d5_wfb2b.bam~ ~override~
COPY ~might_and_guile/feats/d5_wfb2.spl~ ~override/d5uwb2.spl~	//			disarming posture
	SAY NAME1 @20343
	SAY UNIDENTIFIED_DESC @20344
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfb2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfb2b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF22N~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5_wf22~ END
COPY_EXISTING  ~d5uwb2.spl~ ~override/d5vwb2.spl~ 
	WRITE_SHORT 0x1c 1
CREATE EFF ~D5_WF22~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_LONG 0x28 0
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~D5_WF22~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5_WF22~ #8
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wf22.spl~
	SAY NAME1 @20343
	SAY UNIDENTIFIED_DESC @20344
	WRITE_ASCII 0x3a ~d5_wfb2b~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~d5_wfb2b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF22~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF23~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF24~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF25~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf22~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf23~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf24~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf25~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 248 target = 1 timing = 0 duration = 126244000 STR_VAR resource = ~D5_WF22b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 142 target = 1 parameter2 = 82 timing = 0 duration = 126244000 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF23~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF24~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF25~ END
COPY ~might_and_guile/feats/d5_wf22b.eff~ ~override~
COPY ~might_and_guile/feats/d5_wf22b.spl~ ~override~

COPY ~might_and_guile/feats/d5_wfb3b.bam~ ~override~
COPY ~might_and_guile/feats/d5_wfb3.spl~ ~override/d5uwb3.spl~	//			parry slashing
	SAY NAME1 @20345
	SAY UNIDENTIFIED_DESC @20346
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfb3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfb3b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF23N~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5_wf23~ END
COPY_EXISTING  ~d5uwb3.spl~ ~override/d5vwb3.spl~ 
	WRITE_SHORT 0x1c 1
CREATE EFF ~D5_WF23~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_LONG 0x28 0
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~D5_WF23~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5_WF23~ #8
COPY ~might_and_guile/feats/d5_wf23.spl~ ~override~
	SAY NAME1 @20345
	SAY UNIDENTIFIED_DESC @20346
	WRITE_ASCII 0x3a ~d5_wfb3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfb3b~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf25~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf24~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf23~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf22~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf21~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF25~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF24~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF23~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF22~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 142 target = 1 parameter2 = 15 timing = 0 duration = 126244000 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF22~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF24~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF25~ END

COPY ~might_and_guile/feats/d5_wfb4b.bam~ ~override~
COPY ~might_and_guile/feats/d5_wfb4.spl~ ~override/d5uwb4.spl~	//			parry piercing
	SAY NAME1 @20347
	SAY UNIDENTIFIED_DESC @20348
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfb4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfb4b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF24N~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5_wf24~ END
COPY_EXISTING  ~d5uwb4.spl~ ~override/d5vwb4.spl~ 
	WRITE_SHORT 0x1c 1
CREATE EFF ~D5_WF24~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_LONG 0x28 0
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~D5_WF24~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5_WF24~ #8
COPY ~might_and_guile/feats/d5_wf24.spl~ ~override~
	SAY NAME1 @20347
	SAY UNIDENTIFIED_DESC @20348
	WRITE_ASCII 0x3a ~d5_wfb4b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfb4b~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf25~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf24~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf23~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf22~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf21~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF25~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF24~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF23~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF22~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 142 target = 1 parameter2 = 15 timing = 0 duration = 126244000 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF22~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF23~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF25~ END

COPY ~might_and_guile/feats/d5_wfb5b.bam~ ~override~
COPY ~might_and_guile/feats/d5_wfb5.spl~ ~override/d5uwb5.spl~	//			parry crushing
	SAY NAME1 @20349
	SAY UNIDENTIFIED_DESC @20350
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfb5b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfb5b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_WF25N~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~d5_wf25~ END
COPY_EXISTING  ~d5uwb5.spl~ ~override/d5vwb5.spl~ 
	WRITE_SHORT 0x1c 1
CREATE EFF ~D5_WF25~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_LONG 0x28 0
	WRITE_SHORT 0x2c 100
	WRITE_EVALUATED_ASCII 0x30 ~D5_WF25~ #8
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5_WF25~ #8
COPY ~might_and_guile/feats/d5_wf25.spl~ ~override~
	SAY NAME1 @20349
	SAY UNIDENTIFIED_DESC @20350
	WRITE_ASCII 0x3a ~d5_wfb5b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfb5b~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf25~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf24~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf23~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf22~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = ~d5_wf21~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF25~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF24~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF23~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF22~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 142 target = 1 parameter2 = 15 timing = 0 duration = 126244000 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF21~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF22~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF23~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~D5_WF24~ END

// misc warrior

LAM d5_quickstride_speed
ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_STRIDE~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_STRIDE~) BEGIN
		SET quickstride_state = %state_ind%
	  END
	END
  BUT_ONLY
END
ACTION_IF !(VARIABLE_IS_SET %quickstride_state%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_STRIDE~ RET new_state_ind END
  OUTER_SET quickstride_state = %new_state_ind%
END
COPY ~might_and_guile/feats/d5_wfc1b.bam~ ~override~
COPY ~might_and_guile/feats/d5_wfc1.spl~ ~override/d5uwc1.spl~   // 			quickstride
	SAY NAME1 @2450
	SAY UNIDENTIFIED_DESC @20110
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfc1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfc1b~ END
COPY ~might_and_guile/misc/d5strid.spl~ ~override/d5_wf31.spl~
	SAY NAME1 @2450
	SAY UNIDENTIFIED_DESC @20110
	WRITE_ASCII 0x3a ~d5_wfc1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfc1b~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 176 parameter1 = %d5_quickstride_bonus% END
	LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = ~d5_rwlk~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = ~d5_wf31~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 parameter2 = %quickstride_state% timing = 9 special = 1 END
COPY ~might_and_guile/misc/d5_rwlkb.bam~ ~override~
COPY ~might_and_guile/misc/d5swalk.spl~ ~override/d5_rwlk.spl~
	SAY NAME1 @2451
	SAY UNIDENTIFIED_DESC @2451
	WRITE_ASCII 0x3a ~d5_rwlkb~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rwlkb~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = ~d5_wf31~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = ~d5_wf31~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = ~d5_rwlk~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~spcl813~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~qdmnk02~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~qdmnk03~ END
COPY_EXISTING  ~d5uwc1.spl~ ~override/d5vwc1.spl~ 
	WRITE_SHORT 0x1c 1
OUTER_SET speed_item_ind = 0
OUTER_SPRINT $speed_boost_items(~%speed_item_ind%~) ~speed_boost_item~
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
	READ_BYTE 0x18 flags
	PATCH_IF (flags BOR 0b11111011 = 0b11111111) BEGIN 	//	droppable flag
  	  SET speed_boost = 0
	  READ_LONG 0x6a effectsoffset ELSE 0
	  READ_SHORT 0x70 effectscount ELSE 0
	  FOR (effcyc = 0; effcyc < effectscount; effcyc = effcyc + 1) BEGIN
		READ_SHORT (effectsoffset + (effcyc * 0x30)) opcode ELSE 0
		READ_SHORT (effectsoffset + (effcyc * 0x30)) + 0x04 param1 ELSE 0
		PATCH_IF (opcode = 126) && (param1 > 0) BEGIN
		  SET speed_boost = 1
		END
	  END
	  PATCH_IF (speed_boost = 1) BEGIN
		SPRINT $speed_boost_items(~%speed_item_ind%~) ~%SOURCE_RES%~
		SET ++speed_item_ind
	  END
	END
  END
BUT_ONLY
ACTION_PHP_EACH speed_boost_items AS ind => speed_item BEGIN
  COPY_EXISTING ~%speed_item%.itm~ ~override~
//	LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5_rwlk~ END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 326 target = 1 parameter1 = %quickstride_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5_rwlk~ END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = ~d5_wf31~ END
  IF_EXISTS BUT_ONLY
END

COPY ~might_and_guile/feats/d5_wfc2b.bam~ ~override~
COPY ~might_and_guile/feats/d5_wfc2.spl~ ~override/d5uwc2.spl~   // 			+5 hp
	SAY NAME1 @20305
	SAY UNIDENTIFIED_DESC @20306
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfc2b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfc2b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_wfc2a~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 duration = 0 STR_VAR resource = ~d5_wfc2b~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wfc2a.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5uwc2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vwc2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5_wfc2b~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_wfc2a~ END
COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5_wfc2b.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5uwc2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 duration = 0 STR_VAR resource = ~d5vwc2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 duration = 0 STR_VAR resource = ~d5_wfc2b~ END
COPY_EXISTING  ~d5uwc2.spl~ ~override/d5vwc2.spl~ 
	WRITE_SHORT 0x1c 1

COPY ~might_and_guile/feats/d5_wfc3b.bam~ ~override~
COPY ~might_and_guile/feats/d5_wfc3.spl~ ~override/d5uwc3.spl~   // 			10% DR
	SAY NAME1 @20307
	SAY UNIDENTIFIED_DESC @20308
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfc3b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfc3b~ END
COPY_EXISTING  ~d5uwc3.spl~ ~override/d5vwc3.spl~ 
	WRITE_SHORT 0x1c 1

LAF d5_resolve_state STR_VAR new_state_id = ~D5_POISONEVADE~ RET new_state_ind END
OUTER_SET poison_evasion_state = %new_state_ind%
COPY ~might_and_guile/feats/d5_wfc5b.bam~ ~override~
COPY ~might_and_guile/feats/d5_wfc5.spl~ ~override/d5uwc5.spl~   // 			poison/disease evasion
	SAY NAME1 @20309
	SAY UNIDENTIFIED_DESC @20310
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfc5b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfc5b~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 328 parameter2 = %poison_evasion_state% END
COPY_EXISTING  ~d5uwc5.spl~ ~override/d5vwc5.spl~ 
	WRITE_SHORT 0x1c 1
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5poisev.2da~) BEGIN
<<<<<<<< d5/d5poisev.2da
2DA V1.0 
RES
>>>>>>>> 
 COPY ~d5/d5poisev.2da~ ~override/d5poisev.2da~ 
 COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
  PHP_EACH ab_array AS int => ab_off BEGIN
	GET_OFFSET_ARRAY2 fx_array ab_off SPL_V10_HEAD_EFFECTS
	PHP_EACH fx_array AS int => fx_off BEGIN
	  READ_SHORT fx_off fx_type
	  PATCH_IF fx_type = 25 BEGIN 							// poison
		PATCH_IF !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPPR722~) && !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI714~) BEGIN
//		  PATCH_PRINT "%SOURCE_RES% is a poison spell"
		  INNER_ACTION BEGIN
			APPEND ~d5poisev.2da~ ~%SOURCE_RES% 	SPL~ UNLESS ~%SOURCE_RES%~
		  END
		END
	  END
	  PATCH_IF fx_type = 12 BEGIN 							// damage (poison)
    	READ_SHORT fx_off + 0xa damage_type
		PATCH_IF damage_type = 32 BEGIN
		  PATCH_IF !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPPR722~) && !(~%SOURCE_RES%~ STRING_EQUAL_CASE ~SPWI714~) BEGIN
//			PATCH_PRINT "%SOURCE_RES% is a poison spell"
			INNER_ACTION BEGIN
			  APPEND ~d5poisev.2da~ ~%SOURCE_RES% 	SPL~ UNLESS ~%SOURCE_RES%~
			END
		  END
		END
	  END
	  PATCH_IF fx_type = 78 BEGIN 							// disease
//		  PATCH_PRINT "%SOURCE_RES% is a disease spell"
		  INNER_ACTION BEGIN
			APPEND ~d5poisev.2da~ ~%SOURCE_RES% 	SPL~ UNLESS ~%SOURCE_RES%~
		  END
	  END
	END
  END
 BUT_ONLY
 COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  GET_OFFSET_ARRAY ab_array ITM_V10_HEADERS
  PHP_EACH ab_array AS int => ab_off BEGIN
	GET_OFFSET_ARRAY2 fx_array ab_off ITM_V10_HEAD_EFFECTS
	PHP_EACH fx_array AS int => fx_off BEGIN
	  READ_SHORT fx_off fx_type
	  PATCH_IF fx_type = 25 BEGIN 							// poison
//		  PATCH_PRINT "%SOURCE_RES% is a poison item"
		  INNER_ACTION BEGIN
			APPEND ~d5poisev.2da~ ~%SOURCE_RES% 	ITM~ UNLESS ~%SOURCE_RES%~
		  END
	  END
	  PATCH_IF fx_type = 12 BEGIN 							// damage (poison)
    	READ_SHORT fx_off + 0xa damage_type
		PATCH_IF damage_type = 32 BEGIN
//			PATCH_PRINT "%SOURCE_RES% is a poison item"
			INNER_ACTION BEGIN
			  APPEND ~d5poisev.2da~ ~%SOURCE_RES% 	ITM~ UNLESS ~%SOURCE_RES%~
			END
		END
	  END
	  PATCH_IF fx_type = 78 BEGIN 							// disease
//		  PATCH_PRINT "%SOURCE_RES% is a disease item"
		  INNER_ACTION BEGIN
			APPEND ~d5poisev.2da~ ~%SOURCE_RES% 	ITM~ UNLESS ~%SOURCE_RES%~
		  END
	  END
	END
  END
 BUT_ONLY
 COPY_EXISTING ~d5poisev.2da~ ~override~ 
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY row 0 cols poison_evade_res
	READ_2DA_ENTRY row 1 cols poison_evade_type
	PATCH_IF (~%poison_evade_type%~ STRING_EQUAL_CASE ~spl~) BEGIN 
	 PATCH_IF FILE_EXISTS_IN_GAME ~%poison_evade_res%.spl~ BEGIN
	  INNER_ACTION BEGIN
		LAF add_evade_spell INT_VAR evasion_spellstate = %poison_evasion_state% evasion_save = 1 STR_VAR evade_ext = ~spl~ evade_condition = ~spellstate~ evade_res = EVAL ~%poison_evade_res%~ evade_prefix = ~D5VP~ END
	  END
	 END
	END
	PATCH_IF (~%poison_evade_type%~ STRING_EQUAL_CASE ~itm~) BEGIN 
	 PATCH_IF FILE_EXISTS_IN_GAME ~%poison_evade_res%.itm~ BEGIN
	  INNER_ACTION BEGIN
		LAF add_evade_spell INT_VAR evasion_spellstate = %poison_evasion_state% evasion_save = 1 STR_VAR evade_ext = ~itm~ evade_condition = ~spellstate~ evade_res = EVAL ~%poison_evade_res%~ evade_prefix = ~D5VP~ END
	  END
	 END
	END
  END
 BUT_ONLY
END	// end if not already present

// determination: 39 Sleep, 217 PW Sleep, 109 Hold, 175 Hold2, 24 Horror, 45 Stun, 210 PW Stun
LAF d5_resolve_state STR_VAR new_state_id = ~D5_STUNEVADE~ RET new_state_ind END
OUTER_SET stun_evasion_state = %new_state_ind%
COPY ~might_and_guile/feats/d5_wfc6b.bam~ ~override~
COPY ~might_and_guile/feats/d5_wfc6.spl~ ~override/d5uwc6.spl~   // 			hold/stun evasion
	SAY NAME1 @20219
	SAY UNIDENTIFIED_DESC @20220
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_wfc6b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfc6b~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 328 parameter2 = %stun_evasion_state% END
COPY_EXISTING  ~d5uwc6.spl~ ~override/d5vwc6.spl~ 
	WRITE_SHORT 0x1c 1
<<<<<<<< d5/d5stunev.2da
2DA V1.0 
RES
>>>>>>>> 
COPY ~d5/d5stunev.2da~ ~override/d5stunev.2da~ 
COPY_EXISTING_REGEXP GLOB ~^.+\.spl$~ ~override~
  GET_OFFSET_ARRAY ab_array SPL_V10_HEADERS
  PHP_EACH ab_array AS int => ab_off BEGIN
	GET_OFFSET_ARRAY2 fx_array ab_off SPL_V10_HEAD_EFFECTS
	PHP_EACH fx_array AS int => fx_off BEGIN
	  READ_SHORT fx_off fx_type
	  PATCH_IF (fx_type = 217) || (fx_type = 24) || (fx_type = 175) || (fx_type = 39) || (fx_type = 109) || (fx_type = 210) || (fx_type = 45) BEGIN
//		  PATCH_PRINT "%SOURCE_RES%.spl is subject to Determination"
		  INNER_ACTION BEGIN
			APPEND ~d5stunev.2da~ ~%SOURCE_RES% 	SPL~ UNLESS ~%SOURCE_RES%~
		  END
	  END
	END
  END
BUT_ONLY
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  GET_OFFSET_ARRAY ab_array ITM_V10_HEADERS
  PHP_EACH ab_array AS int => ab_off BEGIN
	GET_OFFSET_ARRAY2 fx_array ab_off ITM_V10_HEAD_EFFECTS
	PHP_EACH fx_array AS int => fx_off BEGIN
	  READ_SHORT fx_off fx_type
	  PATCH_IF (fx_type = 217) || (fx_type = 24) || (fx_type = 175) || (fx_type = 39) || (fx_type = 109) || (fx_type = 210) || (fx_type = 45) BEGIN
//		  PATCH_PRINT "%SOURCE_RES%.itm is subject to Determination"
		  INNER_ACTION BEGIN
			APPEND ~d5stunev.2da~ ~%SOURCE_RES% 	ITM~ UNLESS ~%SOURCE_RES%~
		  END
	  END
	END
  END
BUT_ONLY
COPY_EXISTING ~d5stunev.2da~ ~override~ 
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY row 0 cols stun_evade_res
	READ_2DA_ENTRY row 1 cols poison_evade_type
	PATCH_IF (~%stun_evade_type%~ STRING_EQUAL_CASE ~spl~) BEGIN 
	 PATCH_IF FILE_EXISTS_IN_GAME ~%stun_evade_res%.spl~ BEGIN
	  INNER_ACTION BEGIN
		LAF add_evade_spell INT_VAR evasion_spellstate = %stun_evasion_state% evasion_save = 16 STR_VAR evade_ext = ~spl~ evade_condition = ~spellstate~ evade_res = EVAL ~%stun_evade_res%~ evade_prefix = ~D5VS~ END
	  END
	 END
	END
	PATCH_IF (~%stun_evade_type%~ STRING_EQUAL_CASE ~itm~) BEGIN 
	 PATCH_IF FILE_EXISTS_IN_GAME ~%stun_evade_res%.itm~ BEGIN
	  INNER_ACTION BEGIN
		LAF add_evade_spell INT_VAR evasion_spellstate = %stun_evasion_state% evasion_save = 16 STR_VAR evade_ext = ~itm~ evade_condition = ~spellstate~ evade_res = EVAL ~%stun_evade_res%~ evade_prefix = ~D5VS~ END
	  END
	 END
	END
  END
BUT_ONLY

ACTION_IF (FILE_EXISTS_IN_GAME ~d5pswt0.spl~) BEGIN
  COPY_EXISTING ~d5pswt0.spl~ ~override/d5upsw.spl~	//			wild talent
	SAY NAME1 @20298
	SAY UNIDENTIFIED_DESC @20299
	WRITE_SHORT 0x1c 2
	WRITE_BYTE 0x21 (THIS | 0b11000000)
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 1
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5pswt0~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5pswt0~ END
	PATCH_IF !(MOD_IS_INSTALLED ~will_to_power.tp2~ ~900~) BEGIN
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 probability1 = 93 probability2 = 0 STR_VAR match_resource = ~d5pswt1~ END
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 probability1 = 96 probability2 = 89 STR_VAR match_resource = ~d5pswt2~ END
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 146 probability1 = 100 probability2 = 94 STR_VAR match_resource = ~d5pswt3~ END
	END
  COPY_EXISTING  ~d5upsw.spl~ ~override/d5vpsw.spl~ 
	WRITE_SHORT 0x1c 1
END


//end feat ability files____________________________________________________________


ACTION_DEFINE_ASSOCIATIVE_ARRAY feat_nums_lets BEGIN
	1	=> a
	2	=> b
	3	=> c
	4	=> d
	5	=> e
	6	=> f
	7	=> g
	8	=> h
	9	=> i
	10	=> j
	11	=> k
	12	=> l
	13	=> m
	14	=> n
	15	=> o
	16	=> p
	17	=> q
	18	=> r
	19	=> s
	20	=> t
END


//UI FEAT MENU______________________________________________________________________
//
COPY ~might_and_guile/feats/d5flstf.2da~ ~override~ 
  PATCH_IF (FILE_EXISTS_IN_GAME ~d5pswt0.spl~) BEGIN
	COUNT_2DA_COLS cols
	COUNT_2DA_ROWS cols rows
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY row 0 cols feat
	  PATCH_IF (~%feat%~ STRING_EQUAL_CASE ~d5upsw~) BEGIN
		PATCH_FOR_EACH patch_col IN ~1~ ~2~ ~3~ ~4~ ~5~ ~6~ ~7~ ~8~ ~9~ ~14~ ~15~ ~24~ BEGIN
		  PATCH_IF (cols > patch_col) BEGIN
			SET_2DA_ENTRY row patch_col cols 1
		  END
		END
	  END
	  PATCH_IF (~%feat%~ STRING_EQUAL_CASE ~d5vpsw~) BEGIN
		PATCH_FOR_EACH patch_col IN ~10~ ~11~ ~12~ ~13~ ~16~ ~17~ ~18~ ~19~ ~20~ ~21~ ~22~ ~23~ ~25~ BEGIN
		  PATCH_IF (cols > patch_col) BEGIN
			SET_2DA_ENTRY row patch_col cols 1
		  END
		END
	  END
	END
  END

ACTION_IF !(GAME_IS ~iwdee~) BEGIN
  COPY ~might_and_guile/feats/d5ftskn.2da~ ~override~
END
ACTION_IF (GAME_IS ~iwdee~) BEGIN
  COPY ~might_and_guile/feats/d5ftskn_iwd.2da~ ~override/d5ftskn.2da~
END

INCLUDE ~might_and_guile/lib/sequencer_menu_d5.tpa~

OUTER_SPRINT feat_select_string @20011 // ~Feat Selection~ 
OUTER_SET feat_select_strref = RESOLVE_STR_REF (@20011) // (%feat_select_string%)
OUTER_SPRINT feat_title_string @20012 
OUTER_SPRINT feat_label_string @20013 

/*
ACTION_FOR_EACH high_level_feat IN 
	~d5urb3~ 
	~d5vrb3~ 
	~d5urb4~ 
	~d5vrb4~ 
	~d5urb5~ 
	~d5vrb5~ 
	~d5urd4~ 
	~d5vrd4~ 
	~d5urd8~ 
	~d5vrd8~ 
	~d5ure8~ 
	~d5vre8~ 
	~d5ure9~ 
	~d5vre9~ 
	~d5urh4~ 
	~d5vrh4~ 
	~d5urh5~ 
	~d5vrh5~ 
	~d5urh6~ 
	~d5vrh6~ 
	~d5uwc6~ 
	~d5vwc6~ BEGIN
  COPY_EXISTING ~%high_level_feat%.spl~ ~override~
	WRITE_LONG 0x34 4
  IF_EXISTS BUT_ONLY
END
*/

COPY_EXISTING ~d5flstf.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (col = 1; col < cols; ++col) BEGIN
	READ_2DA_ENTRY 0 (col - 1) (cols - 1) feat_kit_2da
	INNER_ACTION BEGIN
	  COPY_EXISTING ~kitlist.2da~ ~override~
		READ_2DA_ENTRIES_NOW rows 10
		FOR (row = 1; row < rows; ++row) BEGIN
		  READ_2DA_ENTRY_FORMER rows row 0 kitlist_index
		  READ_2DA_ENTRY_FORMER rows row 3 kitlist_name
		  READ_2DA_ENTRY_FORMER rows row 5 kitlist_2da
		  READ_2DA_ENTRY_FORMER rows row 8 kitlist_class
		  READ_2DA_ENTRY_FORMER rows row 9 kitids_num
		  PATCH_IF (~%kitlist_2da%~ STRING_EQUAL_CASE ~%feat_kit_2da%~) /*&& (IS_AN_INT %kitids_num%)*/ BEGIN
			PATCH_IF (%kitlist_class% = 3) OR (%kitlist_class% = 6) OR (%kitlist_class% = 8) OR (%kitlist_class% = 11) OR (%kitlist_class% = 12) OR (%kitlist_class% = 15) OR (%kitlist_class% = 16) OR (%kitlist_class% = 18) BEGIN
			  SET feat_spell_class = 1
			END ELSE BEGIN
			  SET feat_spell_class = 2
			END
	        SPRINT $feat_kit_list(~%kitlist_index%~)~%kitids_num%~
			GET_STRREF %kitlist_name% kit_name_strref
//			SPRINT feat_select_string /* @___ */ ~Feat Selection~
//			SET feat_select_strref = RESOLVE_STR_REF (~Feat Selection~) 
			SPRINT feat_select_name ~%kit_name_strref% %feat_select_string%~
			SET kit_seq_name = RESOLVE_STR_REF (~%feat_select_name%~) 
			SET kit_seq_tip = RESOLVE_STR_REF (~%feat_select_name%~) 
			SET kit_seq_index = %kitlist_index% 
			INNER_ACTION BEGIN
			  LAF CREATE_SEQUENCER_MENU 
			   INT_VAR 
				name = %kit_seq_name%
				tip = %kit_seq_tip%
				desc = RESOLVE_STR_REF (~blah~) 
				column = %col% 
				class = %feat_spell_class%
			   STR_VAR 
				resref = EVAL ~d5ft%kit_seq_index%~
				icon = ~spcl919b~
				spelltable = ~d5ftskn~ 
				spelllist = ~d5flstf~
				title = EVAL ~%feat_title_string%~
				label = EVAL ~%feat_label_string%~
			  END
			END
		  END
		END
	  BUT_ONLY
	END
  END
BUT_ONLY

//OUTER_SPRINT feat_select_thief ~Thief %feat_select_string%~
//OUTER_SET thief_seq_name = RESOLVE_STR_REF (~%feat_select_thief%~) 
//OUTER_SET thief_seq_tip = RESOLVE_STR_REF (~%feat_select_thief%~) 
LAF CREATE_SEQUENCER_MENU 
  INT_VAR 
	name = %feat_select_strref%
	tip = %feat_select_strref%
	desc = RESOLVE_STR_REF (~blah~) 
	column = 1
	class = 2
  STR_VAR 
	resref = ~d5ftt4~
	icon = ~spcl919b~
	spelltable = ~d5ftskn~ 
	spelllist = ~d5flstf~
	title = EVAL ~%feat_title_string%~
	label = EVAL ~%feat_label_string%~
END
LAF CREATE_SEQUENCER_MENU 
  INT_VAR 
	name = %feat_select_strref%
	tip = %feat_select_strref%
	desc = RESOLVE_STR_REF (~blah~) 
	column = 8
	class = 2
  STR_VAR 
	resref = ~d5ftt2~
	icon = ~spcl919b~
	spelltable = ~d5ftskn~ 
	spelllist = ~d5flstf~
	title = EVAL ~%feat_title_string%~
	label = EVAL ~%feat_label_string%~
END
LAF CREATE_SEQUENCER_MENU 
  INT_VAR 
	name = %feat_select_strref%
	tip = %feat_select_strref%
	desc = RESOLVE_STR_REF (~blah~) 
	column = 10
	class = 1
  STR_VAR 
	resref = ~d5ftt12~
	icon = ~spcl919b~
	spelltable = ~d5ftskn~ 
	spelllist = ~d5flstf~
	title = EVAL ~%feat_title_string%~
	label = EVAL ~%feat_label_string%~
END
LAF CREATE_SEQUENCER_MENU 
  INT_VAR 
	name = %feat_select_strref%
	tip = %feat_select_strref%
	desc = RESOLVE_STR_REF (~blah~) 
	column = 14
	class = 2
  STR_VAR 
	resref = ~d5ftt9~
	icon = ~spcl919b~
	spelltable = ~d5ftskn~ 
	spelllist = ~d5flstf~
	title = EVAL ~%feat_title_string%~
	label = EVAL ~%feat_label_string%~
END
LAF CREATE_SEQUENCER_MENU 
  INT_VAR 
	name = %feat_select_strref%
	tip = %feat_select_strref%
	desc = RESOLVE_STR_REF (~blah~) 
	column = 15
	class = 2
  STR_VAR 
	resref = ~d5ftt13~
	icon = ~spcl919b~
	spelltable = ~d5ftskn~ 
	spelllist = ~d5flstf~
	title = EVAL ~%feat_title_string%~
	label = EVAL ~%feat_label_string%~
END
LAF CREATE_SEQUENCER_MENU 
  INT_VAR 
	name = %feat_select_strref%
	tip = %feat_select_strref%
	desc = RESOLVE_STR_REF (~blah~) 
	column = 16
	class = 1
  STR_VAR 
	resref = ~d5ftt15~
	icon = ~spcl919b~
	spelltable = ~d5ftskn~ 
	spelllist = ~d5flstf~
	title = EVAL ~%feat_title_string%~
	label = EVAL ~%feat_label_string%~
END

COPY_EXISTING ~d5flstf.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 0; row < rows; ++row) BEGIN
  	READ_2DA_ENTRY row 0 cols ~book_feat~
	INNER_ACTION BEGIN
	  COPY_EXISTING ~%book_feat%.spl~ ~override/%book_feat%L.spl~
		WRITE_SHORT 0x1c 4
		WRITE_LONG 0x34 1
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%book_feat%~ END
	  IF_EXISTS BUT_ONLY
	END
  END
BUT_ONLY

/* already did with d5featx! just didn't apply it to any kit tables
//remove feats for duals____________________________________________________________

COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5featrm.spl~

COPY_EXISTING ~d5flstf.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 0; row < rows; ++row) BEGIN
  	READ_2DA_ENTRY row 0 cols ~book_feat~
	INNER_ACTION BEGIN
	  COPY_EXISTING ~d5featrm.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%book_feat%~ END
	  IF_EXISTS BUT_ONLY
	END
  END
BUT_ONLY

//__________________________________________________________________________________
*/

//__________________________________________________________________________________

COPY ~might_and_guile/misc/d5_thac1.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/misc/d5_acbo1.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/misc/d5_savbo.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/misc/d5_1hpbo.spl~ ~override~
	SAY NAME1 @7
//__________________________________________________________________________________


//EDIT SKILL POINTS_________________________________________________________________
//
COPY_EXISTING ~thiefskl.2da~ ~override~
  SET_2DA_ENTRY_LATER ~#skills~ 3 1 30 // trueclass start
  SET_2DA_ENTRY_LATER ~#skills~ 3 2 20 // per level
  SET_2DA_ENTRY_LATER ~#skills~ 4 1 30 // shadowdancer start
  SET_2DA_ENTRY_LATER ~#skills~ 4 2 20 // per level
  SET_2DA_ENTRY_LATER ~#skills~ 5 1 30 // assassin start
  SET_2DA_ENTRY_LATER ~#skills~ 5 2 20 // per level
  SET_2DA_ENTRY_LATER ~#skills~ 6 1 30 // hunter start
  SET_2DA_ENTRY_LATER ~#skills~ 6 2 20 // per level
  SET_2DA_ENTRY_LATER ~#skills~ 7 1 30 // swashbuckler start
  SET_2DA_ENTRY_LATER ~#skills~ 7 2 20 // per level
  SET_2DA_ENTRIES_NOW ~#skills~ 1
  PRETTY_PRINT_2DA
BUT_ONLY
//__________________________________________________________________________________


//EDIT BACKSTABS____________________________________________________________________
//
COPY_EXISTING ~backstab.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 3; row < rows; ++row) BEGIN 
	FOR (col = 2; col < 10; ++col) BEGIN 
	  SET_2DA_ENTRY_LATER ~#backstab~ row col 2 
	END
	FOR (col = 10; col < 19; ++col) BEGIN 
	  SET_2DA_ENTRY_LATER ~#backstab~ row col 3 
	END
	FOR (col = 19; col < cols; ++col) BEGIN 
	  SET_2DA_ENTRY_LATER ~#backstab~ row col 4 
	END
  END
  SET_2DA_ENTRIES_NOW ~#backstab~ 1
  FOR (col = 2; col < 10; ++col) BEGIN 
	  SET_2DA_ENTRY_LATER ~#altbackstab~ 4 col 1 // shadowdancer
	  SET_2DA_ENTRY_LATER ~#altbackstab~ 7 col 1 // stalker
  END
  FOR (col = 10; col < 19; ++col) BEGIN 
	  SET_2DA_ENTRY_LATER ~#altbackstab~ 4 col 2 // shadowdancer
	  SET_2DA_ENTRY_LATER ~#altbackstab~ 7 col 2 // stalker
  END
  FOR (col = 19; col < cols; ++col) BEGIN 
	  SET_2DA_ENTRY_LATER ~#altbackstab~ 4 col 3 // shadowdancer
	  SET_2DA_ENTRY_LATER ~#altbackstab~ 7 col 3 // stalker
  END
  SET_2DA_ENTRIES_NOW ~#altbackstab~ 1
  PRETTY_PRINT_2DA
COPY_EXISTING ~backstab.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  READ_2DA_ENTRIES_NOW rows cols 
  FOR (row = 1; row < rows; ++row) BEGIN 
	READ_2DA_ENTRY_FORMER rows row 0 ~text~ 
	PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5_LOREMASTER~ BEGIN
	  SET lorem_row = %row%
	END
	PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5RANMAGE~ BEGIN
	  SET ranma_row = %row%
	END
  END
  FOR (col = 2; col < 10; ++col) BEGIN
	PATCH_IF VARIABLE_IS_SET ~lorem_row~ BEGIN
	  SET_2DA_ENTRY_LATER ~#modbackstab~ (lorem_row + 3) col 1 
	END
	PATCH_IF VARIABLE_IS_SET ~ranma_row~ BEGIN
	  SET_2DA_ENTRY_LATER ~#modbackstab~ (ranma_row + 3) col 1 
	END
  END
  FOR (col = 10; col < 19; ++col) BEGIN
	PATCH_IF VARIABLE_IS_SET ~lorem_row~ BEGIN
	  SET_2DA_ENTRY_LATER ~#modbackstab~ (lorem_row + 3) col 1 
	END
	PATCH_IF VARIABLE_IS_SET ~ranma_row~ BEGIN
	  SET_2DA_ENTRY_LATER ~#modbackstab~ (ranma_row + 3) col 1 
	END
  END
  FOR (col = 19; col < cols; ++col) BEGIN
	PATCH_IF VARIABLE_IS_SET ~lorem_row~ BEGIN
	  SET_2DA_ENTRY_LATER ~#modbackstab~ (lorem_row + 3) col 1 
	END
	PATCH_IF VARIABLE_IS_SET ~ranma_row~ BEGIN
	  SET_2DA_ENTRY_LATER ~#modbackstab~ (ranma_row + 3) col 1 
	END
  END
  SET_2DA_ENTRIES_NOW ~#modbackstab~ 1
  PRETTY_PRINT_2DA
//__________________________________________________________________________________


//NU FEAT FILES_____________________________________________________________________
//
COPY ~might_and_guile/feats/d5_feat.bam~ ~override~

ACTION_PHP_EACH feat_nums_lets AS num => let BEGIN
  COPY ~might_and_guile/feats/d5feat1.spl~ ~override/d5feat%num%.spl~ 
	LPF DELETE_EFFECT INT_VAR match_opcode = 206 END
	LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = ~d5feat1~ resource = EVAL ~d5feat%num%~ END
  COPY ~might_and_guile/feats/d5feat1.eff~ ~override/d5feat%num%.eff~ 
	WRITE_EVALUATED_ASCII 0x30 ~d5feat%let%~ #8

//  COPY ~might_and_guile/feats/d5feata.spl~ ~override/d5feat%let%.spl~
  COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5feat%let%.spl~
	SAY NAME1 @20099
	SAY UNIDENTIFIED_DESC @20100
	WRITE_ASCII 0x3a ~d5_feat~ #8
	LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5_feat~ END
//	LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR match_resource = ~d5feata~ resource = EVAL ~d5feat%let%~ END
	LPF ADD_SPELL_CFEFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~d5feat%let%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5feat%num%~ END
	PHP_EACH feat_kit_list AS ind => ids BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~d5ft%ind%~ END
	END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0x4000 parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~d5feattc~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 2 parameter2 = 5 timing = 9 STR_VAR resource = ~d5urfe7~ END
//	LPF DELETE_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = ~d5_feat~ END
END

COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5feattc.spl~
  PATCH_FOR_EACH class IN ~2~ ~4~ ~12~ ~9~ ~13~ ~15~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %class% parameter2 = 105 timing = 1 STR_VAR resource = EVAL ~d5ftt%class%~ END
  END

ACTION_PHP_EACH feat_kit_list AS ind => ids BEGIN
  COPY_EXISTING ~d5ft%ind%.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~d5ft%ind%~ END
  IF_EXISTS BUT_ONLY
END
ACTION_FOR_EACH trueclass_feat_spell IN ~d5ftt2~ ~d5ftt4~ ~d5ftt12~ ~d5ftt9~ ~d5ftt13~ ~d5ftt15~ BEGIN
  COPY_EXISTING ~%trueclass_feat_spell%.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~%trueclass_feat_spell%~ END
  IF_EXISTS BUT_ONLY
END

COPY ~might_and_guile/feats/d5feat0.spl~ ~override~
	SAY NAME1 @20099
	SAY UNIDENTIFIED_DESC @20100
	WRITE_ASCII 0x3a ~d5_feat~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_feat~ END

ACTION_IF GAME_IS ~iwdee~ BEGIN
  APPEND ~splprot.2da~ ~D5_MIN_INT%TAB%38%TAB%-1%TAB%4~
  COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_MIN_INT~ BEGIN
	    SET min_int_row = %row%
	  END
	END
  BUT_ONLY
END

COPY ~might_and_guile/feats/d5ifeat.spl~ ~override~ 
  PATCH_FOR_EACH letter IN ~D~ ~E~ ~F~ ~G~ ~H~ ~I~ ~J~ ~K~ ~L~ ~M~ ~N~ ~O~ ~P~ ~Q~ ~R~ ~S~ ~T~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~d5_feat%letter%~ END
  END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5_wf11n~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5_wf12n~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5_wf13n~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5_wf21n~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5_wf22n~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5_wf23n~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5_wf24n~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5_wf25n~ END
COPY ~might_and_guile/feats/d5ifeat1.eff~ ~override~ 
  PATCH_IF GAME_IS ~iwdee~ BEGIN
	WRITE_LONG 0x20 %min_int_row%
  END
COPY ~might_and_guile/feats/d5ifeat2.eff~ ~override~ 
  PATCH_IF GAME_IS ~iwdee~ BEGIN
	WRITE_LONG 0x20 %min_int_row%
  END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5featx.spl~) BEGIN
  COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5featx.spl~
END
COPY ~might_and_guile/feats/d5flstf.2da~ ~might_and_guile/temp/d5flstf.2da~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 1; row < rows; ++row) BEGIN
  	READ_2DA_ENTRY row 0 cols spellbook_feat
	INNER_ACTION BEGIN
	  COPY_EXISTING ~d5featx.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%spellbook_feat%~ END
	  BUT_ONLY
	END
  END
BUT_ONLY
/* do each of these in their own components
COPY ~might_and_guile/feats/d5flsta.2da~ ~might_and_guile/temp/d5flsta.2da~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 1; row < rows; ++row) BEGIN
  	READ_2DA_ENTRY row 0 cols spellbook_feat
	INNER_ACTION BEGIN
	  COPY_EXISTING ~d5featx.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%spellbook_feat%~ END
	  BUT_ONLY
	END
  END
BUT_ONLY
COPY ~might_and_guile/feats/d5flstb.2da~ ~might_and_guile/temp/d5flstb.2da~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 1; row < rows; ++row) BEGIN
  	READ_2DA_ENTRY row 0 cols spellbook_feat
	INNER_ACTION BEGIN
	  COPY_EXISTING ~d5featx.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%spellbook_feat%~ END
	  BUT_ONLY
	END
  END
BUT_ONLY
*/

COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5nfeats.spl~
  PATCH_FOR_EACH letter IN ~A~ ~B~ ~C~ ~D~ ~E~ ~F~ ~G~ ~H~ ~I~ ~J~ ~K~ ~L~ ~M~ ~N~ ~O~ ~P~ ~Q~ ~R~ ~S~ ~T~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~d5_feat%letter%~ END
  END

COPY ~might_and_guile/feats/d5mcft1.spl~ ~override~
  LPF ALTER_EFFECT INT_VAR match_opcode = 318 parameter2 = %kit_not_row% END
COPY ~might_and_guile/feats/d5mcft1.eff~ ~override~

ACTION_PHP_EACH feat_nums_lets AS num => let BEGIN
  ACTION_IF (num > 1) && (num < 10) BEGIN
	COPY_EXISTING ~d5mcft1.eff~ ~override/d5mcft%num%.eff~
	  WRITE_EVALUATED_ASCII 0x30 ~d5feat%let%~ #8
	BUT_ONLY
	COPY_EXISTING ~d5mcft1.spl~ ~override/d5mcft%num%.spl~
	  LPF ALTER_EFFECT INT_VAR match_opcode = 318 STR_VAR resource = EVAL ~d5mcft%num%~ END
	  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR resource = EVAL ~d5mcft%num%~ END
	  LPF ALTER_EFFECT INT_VAR match_opcode = 206 STR_VAR resource = EVAL ~d5mcft%num%~ END
	BUT_ONLY
  END
END
//__________________________________________________________________________________


//APPLY FEATS IN CLABS______________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~clabth01.2da~ BEGIN
	APPEND ~clabth01.2da~ ~NO_UMD      AP_D5_NUMD  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
	COPY_EXISTING ~clabth01.2da~ ~override~
		REPLACE_TEXTUALLY ~GA_SPCL412~ ~****      ~	
		REPLACE_TEXTUALLY ~AP_D5CL412~ ~****      ~	
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_trueclass.txt~
		APPEND_FILE ~might_and_guile/feats/feats_multithief.txt~
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabth02.2da~ BEGIN
	COPY_EXISTING ~clabth02.2da~ ~override~
		REPLACE_TEXTUALLY ~GA_SPCL412~ ~****      ~	
		REPLACE_TEXTUALLY ~AP_SPCL421~ ~****      ~	
		REPLACE_TEXTUALLY ~GA_SPCL423~ ~****      ~	
		REPLACE_TEXTUALLY ~AP_SPCL332~ ~****      ~	
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_assassin.txt~
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabth03.2da~ BEGIN
	COPY_EXISTING ~clabth03.2da~ ~override~
		REPLACE_TEXTUALLY ~GA_SPCL412~ ~****      ~	
		REPLACE_TEXTUALLY ~GA_SPCL414~ ~****      ~	
		REPLACE_TEXTUALLY ~GA_SPCL417~ ~****      ~	
		REPLACE_TEXTUALLY ~GA_SPCL801~ ~****      ~	
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_hunter.txt~
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabth04.2da~ BEGIN
	COPY_EXISTING ~clabth04.2da~ ~override~
		REPLACE_TEXTUALLY ~GA_SPCL412~ ~****      ~	
		REPLACE_TEXTUALLY ~AP_SPCL141~ ~****      ~	
		REPLACE_TEXTUALLY ~AP_SPCL441~ ~****      ~	
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_swashbuckler.txt~
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabth05.2da~ BEGIN
	COPY_EXISTING ~clabth05.2da~ ~override~
		REPLACE_TEXTUALLY ~GA_SPCL412~ ~****      ~	
		REPLACE_TEXTUALLY ~AP_SPSD01 ~ ~****      ~	
		REPLACE_TEXTUALLY ~GA_SPSD02 ~ ~****      ~	
		REPLACE_TEXTUALLY ~GA_D5_SHAD1~ ~****       ~	
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_shadowdancer.txt~
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_shadd.2da~ BEGIN
	COPY_EXISTING ~d5_shadd.2da~ ~override~
		REPLACE_TEXTUALLY ~GA_SPCL412~ ~****      ~	
		REPLACE_TEXTUALLY ~AP_SPSD01 ~ ~****      ~	
		REPLACE_TEXTUALLY ~GA_SPSD02 ~ ~****      ~	
		REPLACE_TEXTUALLY ~GA_D5_SHAD1~ ~****       ~	
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_shadowdancer.txt~
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~a!burg.2da~ BEGIN
	COPY_EXISTING ~a!burg.2da~ ~override~
		REPLACE_TEXTUALLY ~GA_SPCL412~ ~****      ~	
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_burglar.txt~
	BUT_ONLY
END

ACTION_FOR_EACH mageclab IN ~clabma01~ ~clabma02~ ~clabma03~ ~clabma04~ ~clabma05~ ~clabma06~ ~clabma07~ ~clabma08~ ~clabma09~ BEGIN
  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%mageclab%.2da~ BEGIN
    COPY ~might_and_guile/misc/%mageclab%.2da~ ~override~
  END 
END

APPEND ~clabma01.2da~ ~UMD         AP_D5_UMD   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
  UNLESS ~AP_D5_UMD~
APPEND ~clabma01.2da~ ~NO_FEATS    AP_D5NFEATS ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

APPEND ~clabpr01.2da~ ~NO_FEATS    AP_D5NFEATS ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

ACTION_IF FILE_EXISTS_IN_GAME ~clabfi01.2da~ BEGIN
	COPY_EXISTING ~clabfi01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_fighter.txt~
	BUT_ONLY
END

ACTION_IF FILE_EXISTS_IN_GAME ~clabfi05.2da~ BEGIN
	COPY_EXISTING ~clabfi05.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_SPCL154~ ~****      ~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_barbarian.txt~
	BUT_ONLY
	ACTION_IF GAME_IS ~bgee~ BEGIN
		COPY ~might_and_guile/feats/spcl152_bg1.spl~ ~override/spcl152.spl~
			SAY UNIDENTIFIED_DESC @20018
	END
	ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
		COPY ~might_and_guile/feats/spcl152_bg2.spl~ ~override/spcl152.spl~
			SAY UNIDENTIFIED_DESC @20018
	END
	ACTION_IF GAME_IS ~iwdee~ BEGIN
		COPY ~might_and_guile/feats/spcl152_iwd.spl~ ~override/spcl152.spl~
			SAY UNIDENTIFIED_DESC @20018
	END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5rbarb.2da~ BEGIN
	COPY_EXISTING ~d5rbarb.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_SPCL154~ ~****      ~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_barbarian.txt~
	BUT_ONLY
	ACTION_IF GAME_IS ~bgee~ BEGIN
		COPY ~might_and_guile/feats/spcl152_bg1.spl~ ~override/spcl152.spl~
			SAY UNIDENTIFIED_DESC @20018
	END
	ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
		COPY ~might_and_guile/feats/spcl152_bg2.spl~ ~override/spcl152.spl~
			SAY UNIDENTIFIED_DESC @20018
	END
	ACTION_IF GAME_IS ~iwdee~ BEGIN
		COPY ~might_and_guile/feats/spcl152_iwd.spl~ ~override/spcl152.spl~
			SAY UNIDENTIFIED_DESC @20018
	END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5shmbb.2da~ BEGIN
	COPY_EXISTING ~d5shmbb.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_SPCL154~ ~****      ~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_barbarian.txt~
	BUT_ONLY
	ACTION_IF GAME_IS ~bgee~ BEGIN
		COPY ~might_and_guile/feats/spcl152_bg1.spl~ ~override/spcl152.spl~
			SAY UNIDENTIFIED_DESC @20018
	END
	ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
		COPY ~might_and_guile/feats/spcl152_bg2.spl~ ~override/spcl152.spl~
			SAY UNIDENTIFIED_DESC @20018
	END
	ACTION_IF GAME_IS ~iwdee~ BEGIN
		COPY ~might_and_guile/feats/spcl152_iwd.spl~ ~override/spcl152.spl~
			SAY UNIDENTIFIED_DESC @20018
	END
END

ACTION_FOR_EACH ranger IN ~clabrn01~ ~clabrn04~ ~d5rfor~ ~d5rmou~ ~d5rdes~ ~d5rjun~ ~d5rarc~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%ranger%.2da~ BEGIN
	COPY_EXISTING ~%ranger%.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/feats_ranger.txt~
	BUT_ONLY
  END
END

COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_feat_array BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY
ACTION_PHP_EACH d5_feat_array AS bo => zo BEGIN
	ACTION_IF (%zo% = 4) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		APPEND ~%bo%.2da~ ~NO_UMD      AP_D5_NUMD  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
		COPY_EXISTING ~%bo%.2da~ ~override~
			REPLACE_TEXTUALLY ~GA_SPCL412~ ~****      ~	
	END
	ACTION_IF (%zo% = 1) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		APPEND ~%bo%.2da~ ~UMD         AP_D5_UMD   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
		  UNLESS ~AP_D5_UMD~
		APPEND ~%bo%.2da~ ~NO_FEATS    AP_D5NFEATS ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
	END
	ACTION_IF (%zo% = 3) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		APPEND ~%bo%.2da~ ~NO_FEATS    AP_D5NFEATS ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
	END
END

APPEND ~clabpr01.2da~ ~NO_FEATS    AP_D5FEATX  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ UNLESS ~AP_D5FEATX~

APPEND ~clabdr01.2da~ ~NO_FEATS    AP_D5FEATX  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ UNLESS ~AP_D5FEATX~

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_kitlist~ 9
  FOR (row = 2; row < r2en_kitlist; row += 1) BEGIN
    READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 5 class_ab
    READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 8 class_num
    PATCH_IF /*(class_num = 1) OR*/ (class_num = 3) OR (class_num = 11) BEGIN // just cleric and druid...?
      INNER_ACTION BEGIN
        APPEND ~%class_ab%.2da~ ~NO_FEATS    AP_D5FEATX  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~ UNLESS ~AP_D5FEATX~
      END
    END
  END
BUT_ONLY

//__________________________________________________________________________________


//add feat abilities to joinable NPCs_______________________________________________
//
// need to give some feats directly to thief/mages
//
LAM JOINABLE_NPC_ARRAYS

ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
//  PRINT ~%cre% => %dv%~ 
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
	  READ_LONG 0x244 npc_kit
	  PATCH_IF (npc_kit = 0) BEGIN
		WRITE_SHORT 0x244 0
		WRITE_SHORT 0x246 0x4000
	  END
	END
  BUT_ONLY
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
		READ_BYTE 0x273 npc_class
		READ_LONG 0x244 npc_kit
		PATCH_IF (npc_class = 4) BEGIN
			REMOVE_KNOWN_SPELL ~spcl412~ ~spcl414~
			LPF ADD_CRE_EFFECT INT_VAR opcode=172 target=1 timing=9 power=1 STR_VAR resource=~spcl412~ END
			LPF ADD_CRE_EFFECT INT_VAR opcode=172 target=1 timing=9 power=1 STR_VAR resource=~spcl414~ END
			PATCH_IF (npc_kit = 16384) BEGIN
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat1~ END
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat2~ END
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat3~ END
			END
			READ_BYTE 0x234 npc_level
			PATCH_IF (npc_level > 2) BEGIN
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat4~ END
			END
			PATCH_IF (npc_level > 4) BEGIN 
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat5~ END
			END
			PATCH_IF (npc_level > 6) BEGIN 
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat6~ END
			END
			PATCH_IF (npc_level > 8) BEGIN 
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat7~ END
			END
			PATCH_IF (npc_level > 10) BEGIN 
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat8~ END
			END
			PATCH_IF (npc_level > 12) BEGIN 
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat9~ END
			END
			PATCH_IF (npc_level > 14) BEGIN 
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat10~ END
			END
			PATCH_IF (npc_level > 16) BEGIN 
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat11~ END
			END
			PATCH_IF (npc_level > 18) BEGIN 
				LPF ADD_CRE_EFFECT INT_VAR opcode=146 target=1 timing=9 power=1 STR_VAR resource=~d5feat12~ END
			END
		END
		PATCH_IF (npc_class = 9 || npc_class = 15) BEGIN
			REMOVE_KNOWN_SPELL ~spcl412~ ~spcl414~
			LPF ADD_CRE_EFFECT INT_VAR opcode=172 target=1 timing=9 power=1 STR_VAR resource=~spcl412~ END
			LPF ADD_CRE_EFFECT INT_VAR opcode=172 target=1 timing=9 power=1 STR_VAR resource=~spcl414~ END
			READ_BYTE 0x10 ~oc_thief~ // reads the byte containing the original class
			PATCH_IF ((~%oc_thief%~ BAND ~0b01000000~) = ~0b01000000~) BEGIN // if original class = thief
				PATCH_IF (npc_kit = 16384) BEGIN
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5feata~ END
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5featb~ END
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5featc~ END
				END
				READ_BYTE 0x235 npc_level
				PATCH_IF (npc_level > 2) BEGIN
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5featd~ END
				END
				PATCH_IF (npc_level > 4) BEGIN 
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5feate~ END
				END
				PATCH_IF (npc_level > 6) BEGIN 
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5featf~ END
				END
				PATCH_IF (npc_level > 8) BEGIN 
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5featg~ END
				END
				PATCH_IF (npc_level > 10) BEGIN 
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5feath~ END
				END
				PATCH_IF (npc_level > 12) BEGIN 
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5feati~ END
				END
				PATCH_IF (npc_level > 14) BEGIN 
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5featj~ END
				END
				PATCH_IF (npc_level > 16) BEGIN 
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5featk~ END
				END
				PATCH_IF (npc_level > 18) BEGIN 
					LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5featl~ END
				END
			END
		END
		PATCH_IF (npc_class = 13) BEGIN
			REMOVE_KNOWN_SPELL ~spcl412~ ~spcl414~
			REMOVE_MEMORIZED_SPELL ~spcl412~ ~spcl414~
			LPF ADD_CRE_EFFECT INT_VAR opcode=172 target=1 timing=9 power=1 STR_VAR resource=~spcl412~ END
			LPF ADD_CRE_EFFECT INT_VAR opcode=172 target=1 timing=9 power=1 STR_VAR resource=~spcl414~ END
		END
	END
  BUT_ONLY
END
//__________________________________________________________________________________


//apply feats to AI thieves & fighters______________________________________________
//
ACTION_PHP_EACH NON_JOINABLE_NPC_ARRAY AS cre => dv BEGIN
//  PRINT ~%cre% => %dv%~ 
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
	  READ_BYTE 0x273 npc_class
	  PATCH_IF (npc_class = 4) BEGIN
		LPF ADD_CRE_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (4 << 24) parameter2 = 115 timing = 9 END
		LPF ADD_CRE_EFFECT INT_VAR opcode = 328 target = 1 parameter2 = 252 timing = 9 special = 1 END
		LPF ADD_CRE_EFFECT INT_VAR opcode=206 target=1 timing=9 parameter1=(0 - 1) STR_VAR resource=~d5_numd~ END
		SET random_num1 = RANDOM (1 3)
		PATCH_IF (%random_num1% = 1) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 0 target = 1 parameter1 = 1 parameter2 = 0 timing = 0 duration = 126144000  END
		END
		PATCH_IF (%random_num1% = 2) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 278 target = 1 parameter1 = 1 parameter2 = 0 timing = 1 END
		END
		PATCH_IF (%random_num1% = 3) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 325 target = 1 parameter1 = 1 parameter2 = 0 timing = 1 END
		END
		SET random_num2 = RANDOM (1 3)
		PATCH_IF (%random_num2% = 1) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 22 target = 1 parameter1 = 1 parameter2 = 0 timing = 1 END
		END
		PATCH_IF (%random_num2% = 2) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 328 target = 1 parameter2 = %charm_evasion_state% timing = 1 special = 1 END
		END
		PATCH_IF (%random_num2% = 3) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 9 STR_VAR resource = ~d5_rfd4~ END
		END
	  END
	  PATCH_IF (npc_class = 2) BEGIN
		SET random_num3 = RANDOM (1 5)
		PATCH_IF (%random_num3% = 1) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 248 target = 1 timing = 0 duration = 126144000 STR_VAR resource = ~d5_wf21~ END
		END
		PATCH_IF (%random_num3% = 2) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 248 target = 1 timing = 0 duration = 126144000 STR_VAR resource = ~d5_wf22~ END
		END
		PATCH_IF (%random_num3% = 3) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 0 target = 1 parameter1 = 3 parameter2 = 8 timing = 0 duration = 126144000 END
		END
		PATCH_IF (%random_num3% = 4) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 0 target = 1 parameter1 = 3 parameter2 = 4 timing = 0 duration = 126144000 END
		END
		PATCH_IF (%random_num3% = 5) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 0 target = 1 parameter1 = 3 parameter2 = 1 timing = 0 duration = 126144000 END
		END
		LPF ADD_CRE_EFFECT INT_VAR opcode=206 target=1 timing=9 parameter1=(0 - 1) STR_VAR resource=~d5_numd~ END
		SET random_num4 = RANDOM (1 4)
		PATCH_IF (%random_num4% = 1) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 301 target = 1 parameter1 = 1 timing = 1 special = 1 END
		END
		PATCH_IF (%random_num4% = 2) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 86 target = 1 parameter1 = 10 parameter2 = 0  timing = 1 END
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 87 target = 1 parameter1 = 10 parameter2 = 0  timing = 1 END
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 88 target = 1 parameter1 = 10 parameter2 = 0  timing = 1 END
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 89 target = 1 parameter1 = 10 parameter2 = 0  timing = 1 END
		END
		PATCH_IF (%random_num4% = 3) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 328 target = 1 parameter2 = %poison_evasion_state% timing = 1 special = 1 END
		END
		PATCH_IF (%random_num4% = 4) BEGIN
		  LPF ADD_CRE_EFFECT INT_VAR opcode = 328 target = 1 parameter2 = %stun_evasion_state% timing = 1 special = 1 END
		END
	  END
	END
  BUT_ONLY
END
//__________________________________________________________________________________


//CHANGE ROGUE HLAS_________________________________________________________________
//
LAF action_remove_hla STR_VAR kit_name = ~SWASHBUCKLER~ remove_ability = ~GA_SPCL910~ END	
LAF action_remove_hla STR_VAR kit_name = ~SWASHBUCKLER~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~SWASHBUCKLER~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~SWASHBUCKLER~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~SWASHBUCKLER~ remove_ability = ~GA_RR#THL04~ END
LAF action_remove_hla STR_VAR kit_name = ~SWASHBUCKLER~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~SWASHBUCKLER~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~SWASHBUCKLER~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~SWASHBUCKLER~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~SWASHBUCKLER~ ability = ~AP_D5_RFD1~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~SWASHBUCKLER~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~SWASHBUCKLER~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~SWASHBUCKLER~ ability = ~GA_D5_RF85~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~SWASHBUCKLER~ ability = ~GA_D5_ILLP~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~SWASHBUCKLER~ ability = ~AP_D5_RFH4~ num_allowed = ~1~ END

LAF action_remove_hla STR_VAR kit_name = ~ASSASIN~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~ASSASIN~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~ASSASIN~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~ASSASIN~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~ASSASIN~ remove_ability = ~GA_RR#THL04~ END
LAF action_remove_hla STR_VAR kit_name = ~ASSASIN~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~ASSASIN~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~ASSASIN~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~ASSASIN~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~ASSASIN~ ability = ~GA_D5_RF2Z~ num_allowed = ~16~ END
LAF action_add_hla STR_VAR kit_name = ~ASSASIN~ ability = ~AP_D5_RFD1~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~ASSASIN~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~ASSASIN~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~ASSASIN~ ability = ~GA_D5_RF85~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~ASSASIN~ ability = ~GA_D5_ILLP~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~ASSASIN~ ability = ~AP_D5_RFH4~ num_allowed = ~1~ END

//LAF action_remove_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ ability = ~GA_D5_RF2Z~ num_allowed = ~16~ END
LAF action_add_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ ability = ~AP_D5_RFD1~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ ability = ~GA_D5_RF85~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ ability = ~GA_D5_ILLP~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BOUNTY_HUNTER~ ability = ~AP_D5_RFH4~ num_allowed = ~1~ END

LAF action_remove_hla STR_VAR kit_name = ~SHADOWDANCER~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~SHADOWDANCER~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~SHADOWDANCER~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~SHADOWDANCER~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~SHADOWDANCER~ remove_ability = ~GA_RR#THL04~ END
LAF action_remove_hla STR_VAR kit_name = ~SHADOWDANCER~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~SHADOWDANCER~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~SHADOWDANCER~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~SHADOWDANCER~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~SHADOWDANCER~ ability = ~GA_D5_RF2Z~ num_allowed = ~16~ END
LAF action_add_hla STR_VAR kit_name = ~SHADOWDANCER~ ability = ~AP_D5_RFD1~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~SHADOWDANCER~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~SHADOWDANCER~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~SHADOWDANCER~ ability = ~GA_D5_RF85~ num_allowed = ~6~ END
LAF action_add_hla STR_VAR kit_name = ~SHADOWDANCER~ ability = ~AP_D5_RFH4~ num_allowed = ~1~ END

LAF action_remove_hla STR_VAR kit_name = ~D5SHADD~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~D5SHADD~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~D5SHADD~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~D5SHADD~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~D5SHADD~ remove_ability = ~GA_RR#THL04~ END
LAF action_remove_hla STR_VAR kit_name = ~D5SHADD~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~D5SHADD~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~D5SHADD~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~D5SHADD~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~D5SHADD~ ability = ~GA_D5_RF2Z~ num_allowed = ~16~ END
LAF action_add_hla STR_VAR kit_name = ~D5SHADD~ ability = ~AP_D5_RFD1~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~D5SHADD~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~D5SHADD~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~D5SHADD~ ability = ~GA_D5_RF85~ num_allowed = ~6~ END
LAF action_add_hla STR_VAR kit_name = ~D5SHADD~ ability = ~AP_D5_RFH4~ num_allowed = ~1~ END

LAF action_remove_hla STR_VAR kit_name = ~D5ALCHM~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~D5ALCHM~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~D5ALCHM~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~D5ALCHM~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~D5ALCHM~ remove_ability = ~GA_RR#THL04~ END
LAF action_remove_hla STR_VAR kit_name = ~D5ALCHM~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~D5ALCHM~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~D5ALCHM~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~D5ALCHM~ ability = ~GA_d5_rf3z~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~D5ALCHM~ ability = ~GA_D5_RF2Z~ num_allowed = ~16~ END
LAF action_add_hla STR_VAR kit_name = ~D5ALCHM~ ability = ~AP_D5_RFD1~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~D5ALCHM~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~D5ALCHM~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~D5ALCHM~ ability = ~GA_D5_RF85~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~D5ALCHM~ ability = ~GA_D5_ILLP~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~D5ALCHM~ ability = ~AP_D5_RFH4~ num_allowed = ~1~ END

LAF action_remove_hla STR_VAR kit_name = ~THIEF~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~THIEF~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~THIEF~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~THIEF~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~THIEF~ remove_ability = ~GA_RR#THL04~ END
LAF action_remove_hla STR_VAR kit_name = ~THIEF~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~THIEF~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~THIEF~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~THIEF~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~THIEF~ ability = ~GA_D5_RF2Z~ num_allowed = ~16~ END
LAF action_add_hla STR_VAR kit_name = ~THIEF~ ability = ~AP_D5_RFD1~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~THIEF~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~THIEF~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~THIEF~ ability = ~GA_D5_RF85~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~THIEF~ ability = ~GA_D5_ILLP~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~THIEF~ ability = ~AP_D5_RFH4~ num_allowed = ~1~ END

LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_THIEF~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_THIEF~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_THIEF~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_THIEF~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_THIEF~ remove_ability = ~GA_RR#THL04~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_THIEF~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_THIEF~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_THIEF~ ability = ~GA_D5_RF2Z~ num_allowed = ~16~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_THIEF~ ability = ~AP_D5_RFD1~ num_allowed = ~2~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_THIEF~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_THIEF~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_THIEF~ ability = ~GA_D5_RF85~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_THIEF~ ability = ~GA_D5_ILLP~ num_allowed = ~3~ END

LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ remove_ability = ~GA_RR#THL04~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ ability = ~GA_D5_RF2Z~ num_allowed = ~16~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ ability = ~AP_D5_RFD1~ num_allowed = ~2~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ ability = ~GA_D5_RF85~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~FIGHTER_MAGE_THIEF~ ability = ~GA_D5_ILLP~ num_allowed = ~3~ END

LAF action_remove_hla STR_VAR kit_name = ~MAGE_THIEF~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~MAGE_THIEF~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~MAGE_THIEF~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~MAGE_THIEF~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~MAGE_THIEF~ remove_ability = ~GA_RR#THL04~ END
LAF action_remove_hla STR_VAR kit_name = ~MAGE_THIEF~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~MAGE_THIEF~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~MAGE_THIEF~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~MAGE_THIEF~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~MAGE_THIEF~ ability = ~GA_D5_RF2Z~ num_allowed = ~16~ END
LAF action_add_hla STR_VAR kit_name = ~MAGE_THIEF~ ability = ~AP_D5_RFD1~ num_allowed = ~2~ END
LAF action_add_hla STR_VAR kit_name = ~MAGE_THIEF~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~MAGE_THIEF~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~MAGE_THIEF~ ability = ~GA_D5_RF85~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~MAGE_THIEF~ ability = ~GA_D5_ILLP~ num_allowed = ~3~ END

LAF action_remove_hla STR_VAR kit_name = ~CLERIC_THIEF~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~CLERIC_THIEF~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~CLERIC_THIEF~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~CLERIC_THIEF~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~CLERIC_THIEF~ remove_ability = ~GA_RR#THL04~ END
LAF action_remove_hla STR_VAR kit_name = ~CLERIC_THIEF~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~CLERIC_THIEF~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~CLERIC_THIEF~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~CLERIC_THIEF~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~CLERIC_THIEF~ ability = ~GA_D5_RF2Z~ num_allowed = ~16~ END
LAF action_add_hla STR_VAR kit_name = ~CLERIC_THIEF~ ability = ~AP_D5_RFD1~ num_allowed = ~2~ END
LAF action_add_hla STR_VAR kit_name = ~CLERIC_THIEF~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~CLERIC_THIEF~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~CLERIC_THIEF~ ability = ~GA_D5_RF85~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~CLERIC_THIEF~ ability = ~GA_D5_ILLP~ num_allowed = ~3~ END

LAF action_remove_hla STR_VAR kit_name = ~BLADE~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~BLADE~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~BLADE~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~BLADE~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~BLADE~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~BLADE~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~BLADE~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BLADE~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BLADE~ ability = ~AP_SPCL928~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BLADE~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~BLADE~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~BLADE~ ability = ~GA_SPCL900~ num_allowed = ~5~ END
LAF action_add_hla STR_VAR kit_name = ~BLADE~ ability = ~GA_SPCL904~ num_allowed = ~5~ END

LAF action_remove_hla STR_VAR kit_name = ~JESTER~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~JESTER~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~JESTER~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~JESTER~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~JESTER~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~JESTER~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~JESTER~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~JESTER~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~JESTER~ ability = ~AP_SPCL928~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~JESTER~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~JESTER~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~JESTER~ ability = ~GA_D5_RF85~ num_allowed = ~5~ END
LAF action_add_hla STR_VAR kit_name = ~JESTER~ ability = ~GA_SPCL904~ num_allowed = ~5~ END

LAF action_remove_hla STR_VAR kit_name = ~SKALD~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~SKALD~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~SKALD~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~SKALD~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~SKALD~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~SKALD~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~SKALD~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~SKALD~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~SKALD~ ability = ~GA_SPCL904~ num_allowed = ~5~ END
LAF action_add_hla STR_VAR kit_name = ~SKALD~ ability = ~GA_SPCL906~ num_allowed = ~5~ END
LAF action_add_hla STR_VAR kit_name = ~SKALD~ ability = ~GA_SPCL907~ num_allowed = ~5~ END
LAF action_add_hla STR_VAR kit_name = ~SKALD~ ability = ~GA_SPCL908~ num_allowed = ~5~ END

LAF action_remove_hla STR_VAR kit_name = ~BARD~ remove_ability = ~GA_SPCL910~ END
LAF action_remove_hla STR_VAR kit_name = ~BARD~ remove_ability = ~GA_SPCL911~ END
LAF action_remove_hla STR_VAR kit_name = ~BARD~ remove_ability = ~GA_SPCL912~ END
LAF action_remove_hla STR_VAR kit_name = ~BARD~ remove_ability = ~GA_SPCL918~ END
LAF action_remove_hla STR_VAR kit_name = ~BARD~ remove_ability = ~GA_RR#ALCHT~ END
LAF action_remove_hla STR_VAR kit_name = ~BARD~ remove_ability = ~GA_TG#BRPO~ END
LAF action_add_hla STR_VAR kit_name = ~BARD~ ability = ~GA_D5_RF31~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BARD~ ability = ~GA_D5_RF32~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BARD~ ability = ~AP_SPCL928~ num_allowed = ~3~ END
LAF action_add_hla STR_VAR kit_name = ~BARD~ ability = ~AP_D5_URD2~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~BARD~ ability = ~AP_D5_RF43~ num_allowed = ~1~ END
LAF action_add_hla STR_VAR kit_name = ~BARD~ ability = ~GA_SPCL904~ num_allowed = ~5~ END
LAF action_add_hla STR_VAR kit_name = ~BARD~ ability = ~GA_SPCL906~ num_allowed = ~5~ END
//__________________________________________________________________________________

CLEAR_ARRAYS

