
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						HIT DICE CHANGES
//__________________________________________________________________________________
//__________________________________________________________________________________


COPY ~might_and_guile/misc/hpconbon.2da~ ~override~
COPY ~might_and_guile/misc/hpbarb.2da~ ~override~
COPY ~might_and_guile/misc/hpcm.2da~ ~override~
COPY ~might_and_guile/misc/hpct.2da~ ~override~
COPY ~might_and_guile/misc/hpfc.2da~ ~override~
COPY ~might_and_guile/misc/hpfm.2da~ ~override~
COPY ~might_and_guile/misc/hpfmt.2da~ ~override~
COPY ~might_and_guile/misc/hpft.2da~ ~override~
COPY ~might_and_guile/misc/hpmt.2da~ ~override~
COPY ~might_and_guile/misc/hpmonk.2da~ ~override~
COPY ~might_and_guile/misc/hpprs.2da~ ~override~
COPY ~might_and_guile/misc/hprog.2da~ ~override~
COPY ~might_and_guile/misc/hpwar.2da~ ~override~
COPY ~might_and_guile/misc/hpwiz.2da~ ~override~
//___________________________________________________________________________________

