
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								PSIONICS
//__________________________________________________________________________________
//__________________________________________________________________________________


//COPY MARKER FILE_________________________________________________________________
//
COPY ~might_and_guile/lib/markers/d5_psion.d5~ ~override~
//__________________________________________________________________________________


//ADD PSYPHER_________________________________________________________________________
//
ADD_KIT ~D5_PSYPHER~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_PSYPHER    1 1 1 0 0 0 0 1~
~D5_PSYPHER    1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_PSYPHER         9   9   12  15  9  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_PSYPHER         0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_PSYPHER         0   0   0   17  0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_PSYPHER         0   0   0   15  0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_PSYPHER         1  1  1  1  1  1  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_PSYPHER         1  1  1  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/psi/d5psirog.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_T_D K_T_E K_T_G K_T_H K_T_HE K_T_HL K_T_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Th0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20501
SAY @20502
SAY @20503
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20503)
		STR_VAR
			kit_name = D5_PSYPHER
			backstab = ~1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
			clswpbon = ~0 0 3~
			thiefskl = ~30 12~
			thiefscl = ~0 100 100 100 100 100 0 0~
			clsrcreq = ~1 1 1 1 1 1 1~
	END
END
//____________________________________________________________________________________


//ADD SOULBLADE_______________________________________________________________________
//
ADD_KIT ~D5_SOULBLADE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                    T   S           F   Q             S S
//10            L S                     W   C           L   U             W I
//9             A M             B L S   O   I   W       A   A             O N
//8             R A             A O H   H   M   A       I   R C   S       R G
//7             G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6             E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5             S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4             W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3             O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2             R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1             D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_SOULBLADE   0 3 1 3 3 0 0 1~
~D5_SOULBLADE   0 3 1 3 3 0 0 1 0 3 3 0 0 3 3 3 0 3 3 0 0 0 3 1 1 1 1 1 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_SOULBLADE      9   9   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_SOULBLADE      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_SOULBLADE      17  0   0   0   17  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_SOULBLADE      15  0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_SOULBLADE      1  1  1  1  1  1  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_SOULBLADE      0  1  1  1  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/psi/d5psiwar.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_F_H K_F_G K_F_E K_F_HE K_F_HL K_F_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00010000 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG20 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @20511
SAY @20512
SAY @20513
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@20513)
		STR_VAR
			kit_name = D5_SOULBLADE
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________


//KIT IDENTIFIERS FOR PATCHING LATER__________________________________________________
//
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_COLS k_cols // amount of columns
	READ_2DA_ENTRIES_NOW k_rows k_cols // read all file into memory  
	FOR (k_row = 1; k_row < k_rows; ++k_row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER k_rows k_row 1 ~k_kit~ // read column value
	  PATCH_IF ~%k_kit%~ STRING_EQUAL_CASE ~D5_PSYPHER~ BEGIN
	    SET al_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows al_row 9 ps_code
	  END
	  PATCH_IF ~%k_kit%~ STRING_EQUAL_CASE ~D5_SOULBLADE~ BEGIN
	    SET al_row = %k_row%
	    READ_2DA_ENTRY_FORMER k_rows al_row 9 sb_code
	  END
	END
BUT_ONLY
//____________________________________________________________________________________


//CHANGE CLASS TEXT_________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~THIEF~ BEGIN
	    SET patch_row = %row%
	  END
	END
	SET_2DA_ENTRY %patch_row% 4 cols RESOLVE_STR_REF (@20500)
  BUT_ONLY
END
ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
  COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~THIEF~ BEGIN
	    SET patch_row = %row%
	  END
	END
	SET_2DA_ENTRY %patch_row% 4 cols RESOLVE_STR_REF (@20500)
  BUT_ONLY
END
//__________________________________________________________________________________


//PSIONIC ABILITY FILES_____________________________________________________________
//
COPY ~might_and_guile/misc/d5_1hpbo.spl~ ~override~
	SAY NAME1 @7
//
COPY ~might_and_guile/psi/d5psa01.spl~ ~override~   // 				telepathy
	SAY NAME1 @20601
	SAY UNIDENTIFIED_DESC @20602
COPY ~might_and_guile/psi/d5ps101.spl~ ~override~   //  			mind thrust
	SAY NAME1 @20603
	SAY UNIDENTIFIED_DESC @20604
COPY ~might_and_guile/psi/d5_ps101.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps101.eff~ ~override~

COPY ~might_and_guile/psi/d5psa02.spl~ ~override~   //  			id insinuation
	SAY NAME1 @20605
	SAY UNIDENTIFIED_DESC @20606
COPY ~might_and_guile/psi/d5ps102.spl~ ~override~
	SAY NAME1 @20605
	SAY UNIDENTIFIED_DESC @20606
COPY ~might_and_guile/psi/d5_ps102.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps102.eff~ ~override~

COPY ~might_and_guile/psi/d5psa03.spl~ ~override~   // 				domination
	SAY NAME1 @20607
	SAY UNIDENTIFIED_DESC @20608
COPY ~might_and_guile/psi/d5ps103.spl~ ~override~
	SAY NAME1 @20607
	SAY UNIDENTIFIED_DESC @20608
COPY ~might_and_guile/psi/d5_ps103.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps103.eff~ ~override~

COPY ~might_and_guile/psi/d5psa04.spl~ ~override~   // 				psychic crush
	SAY NAME1 @20609
	SAY UNIDENTIFIED_DESC @20610
COPY ~might_and_guile/psi/d5ps104.spl~ ~override~
	SAY NAME1 @20609
	SAY UNIDENTIFIED_DESC @20610
COPY ~might_and_guile/psi/d5_ps104.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps104.eff~ ~override~

COPY ~might_and_guile/psi/d5psa05.spl~ ~override~   // 			intellect fortress
	SAY NAME1 @20611
	SAY UNIDENTIFIED_DESC @20612
COPY ~might_and_guile/psi/d5ps105.spl~ ~override~
	SAY NAME1 @20611
	SAY UNIDENTIFIED_DESC @20612
COPY ~might_and_guile/psi/d5_ps105.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps105.eff~ ~override~
COPY ~might_and_guile/psi/d5ps10e.spl~ ~override~
	SAY NAME1 @20613
	SAY UNIDENTIFIED_DESC @20613
COPY ~might_and_guile/psi/d5_ps10e.bam~ ~override~

COPY ~might_and_guile/psi/d5_ps200.bam~ ~override~  // 				telekinesis
COPY ~might_and_guile/psi/d5psb01.spl~ ~override~
	SAY NAME1 @20621
	SAY UNIDENTIFIED_DESC @20622
COPY ~might_and_guile/psi/d5ps201.spl~ ~override~   // 				root
	SAY NAME1 @20623
	SAY UNIDENTIFIED_DESC @20624
COPY ~might_and_guile/psi/d5_ps201.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps201.eff~ ~override~

COPY ~might_and_guile/psi/d5psb02.spl~ ~override~   // 				kinetic ram
	SAY NAME1 @20625
	SAY UNIDENTIFIED_DESC @20626
COPY ~might_and_guile/psi/d5ps202.spl~ ~override~
	SAY NAME1 @20625
	SAY UNIDENTIFIED_DESC @20626
COPY ~might_and_guile/psi/d5_ps202.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps202.eff~ ~override~

COPY ~might_and_guile/psi/d5psb03.spl~ ~override~   // 				inertial barrier
	SAY NAME1 @20627
	SAY UNIDENTIFIED_DESC @20628
COPY ~might_and_guile/psi/d5ps203.spl~ ~override~
	SAY NAME1 @20627
	SAY UNIDENTIFIED_DESC @20628
COPY ~might_and_guile/psi/d5_ps203.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps203.eff~ ~override~

COPY ~might_and_guile/psi/d5psb04.spl~ ~override~   // 				psychic knife
	SAY NAME1 @20629
	SAY UNIDENTIFIED_DESC @20630
COPY ~might_and_guile/psi/d5ps204.spl~ ~override~
	SAY NAME1 @20629
	SAY UNIDENTIFIED_DESC @20630
COPY ~might_and_guile/psi/d5_ps204.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps204.eff~ ~override~
COPY ~might_and_guile/psi/d5psibla.itm~ ~override~
	SAY NAME1 @20629
	SAY UNIDENTIFIED_DESC @20629
COPY ~might_and_guile/psi/d5psibla.bam~ ~override~

COPY ~might_and_guile/psi/d5psb05.spl~ ~override~   // 				free action
	SAY NAME1 @20631
	SAY UNIDENTIFIED_DESC @20632
COPY ~might_and_guile/psi/d5ps205.spl~ ~override~
	SAY NAME1 @20631
	SAY UNIDENTIFIED_DESC @20632
COPY ~might_and_guile/psi/d5_ps205.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps205.eff~ ~override~
COPY ~might_and_guile/psi/d5ps20e.spl~ ~override~
	SAY NAME1 @20633
	SAY UNIDENTIFIED_DESC @20633
COPY ~might_and_guile/psi/d5_ps20e.bam~ ~override~

COPY ~might_and_guile/psi/d5_ps300.bam~ ~override~
COPY ~might_and_guile/psi/d5psc01.spl~ ~override~   // 				pyrokinesis
	SAY NAME1 @20641
	SAY UNIDENTIFIED_DESC @20642
COPY ~might_and_guile/psi/d5ps301.spl~ ~override~   //  			static transfer
	SAY NAME1 @20643
	SAY UNIDENTIFIED_DESC @20644
COPY ~might_and_guile/psi/d5ps301.itm~ ~override~
	SAY NAME1 @20643
	SAY UNIDENTIFIED_DESC @20644
COPY ~might_and_guile/psi/d5ps301d.spl~ ~override~
	SAY NAME1 @20643
	SAY UNIDENTIFIED_DESC @20644
COPY ~might_and_guile/psi/d5_ps301.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps301.eff~ ~override~

COPY ~might_and_guile/psi/d5psc02.spl~ ~override~   //  			energy draw
	SAY NAME1 @20645
	SAY UNIDENTIFIED_DESC @20646
COPY ~might_and_guile/psi/d5ps302.spl~ ~override~
	SAY NAME1 @20645
	SAY UNIDENTIFIED_DESC @20646
COPY ~might_and_guile/psi/d5_ps302.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps302.eff~ ~override~

COPY ~might_and_guile/psi/d5psc03.spl~ ~override~   // 				generate lightning
	SAY NAME1 @20647
	SAY UNIDENTIFIED_DESC @20648
COPY ~might_and_guile/psi/d5ps303.spl~ ~override~
	SAY NAME1 @20647
	SAY UNIDENTIFIED_DESC @20648
COPY ~might_and_guile/psi/d5_ps303.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps303.eff~ ~override~

COPY ~might_and_guile/psi/d5psc04.spl~ ~override~   // 				psychic combustion
	SAY NAME1 @20649
	SAY UNIDENTIFIED_DESC @20650
//Projectile
ADD_PROJECTILE ~might_and_guile/psi/b_pfire.pro~   //	projectile
COPY ~might_and_guile/psi/PFIREA.bam~ ~override~
COPY ~might_and_guile/psi/PFIREX.bam~ ~override~
COPY ~might_and_guile/psi/#PRFIRE.vvc~ ~override~
COPY ~might_and_guile/psi/#EFF_P45.WAV~ ~override~
COPY ~might_and_guile/psi/#ARE_P03.WAV~ ~override~
COPY ~might_and_guile/psi/d5ps304.spl~ ~override~
	SAY NAME1 @20649
	SAY UNIDENTIFIED_DESC @20650
	WRITE_SHORT 0x098 ~%b_pfire%~  //Projectile
COPY ~might_and_guile/psi/d5_ps304.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps304.eff~ ~override~

COPY ~might_and_guile/psi/d5psc05.spl~ ~override~   // 				energy barrier
	SAY NAME1 @20651
	SAY UNIDENTIFIED_DESC @20652
COPY ~might_and_guile/psi/d5ps305.spl~ ~override~
	SAY NAME1 @20651
	SAY UNIDENTIFIED_DESC @20652
COPY ~might_and_guile/psi/d5_ps305.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps305.eff~ ~override~
COPY ~might_and_guile/psi/d5ps30e.spl~ ~override~
	SAY NAME1 @20653
	SAY UNIDENTIFIED_DESC @20653
COPY ~might_and_guile/psi/d5_ps30e.bam~ ~override~

COPY ~might_and_guile/psi/d5_ps400.bam~ ~override~
COPY ~might_and_guile/psi/d5psd01.spl~ ~override~   // 				biokinesis
	SAY NAME1 @20661
	SAY UNIDENTIFIED_DESC @20662
COPY ~might_and_guile/psi/d5ps401.spl~ ~override~   //  			adrenaline rush
	SAY NAME1 @20663
	SAY UNIDENTIFIED_DESC @20664
COPY ~might_and_guile/psi/d5_ps401.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps401.eff~ ~override~

COPY ~might_and_guile/psi/d5psd02.spl~ ~override~   //  			metabolic boost
	SAY NAME1 @20665
	SAY UNIDENTIFIED_DESC @20666
COPY ~might_and_guile/psi/d5ps402.spl~ ~override~
	SAY NAME1 @20665
	SAY UNIDENTIFIED_DESC @20666
COPY ~might_and_guile/psi/d5_ps402.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps402.eff~ ~override~

COPY ~might_and_guile/psi/d5psd03.spl~ ~override~   // 				camouflage
	SAY NAME1 @20667
	SAY UNIDENTIFIED_DESC @20668
COPY ~might_and_guile/psi/d5ps403.spl~ ~override~
	SAY NAME1 @20667
	SAY UNIDENTIFIED_DESC @20668
COPY ~might_and_guile/psi/d5_ps403.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps403.eff~ ~override~

COPY ~might_and_guile/psi/d5psd04.spl~ ~override~   // 				carapace
	SAY NAME1 @20669
	SAY UNIDENTIFIED_DESC @20670
COPY ~might_and_guile/psi/d5ps404.spl~ ~override~
	SAY NAME1 @20669
	SAY UNIDENTIFIED_DESC @20670
COPY ~might_and_guile/psi/d5_ps404.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps404.eff~ ~override~

COPY ~might_and_guile/psi/d5psd05.spl~ ~override~   // 				bioregeneration
	SAY NAME1 @20671
	SAY UNIDENTIFIED_DESC @20672
COPY ~might_and_guile/psi/d5ps405.spl~ ~override~
	SAY NAME1 @20671
	SAY UNIDENTIFIED_DESC @20672
COPY ~might_and_guile/psi/d5_ps405.bam~ ~override~
COPY ~might_and_guile/psi/d5_ps405.eff~ ~override~
COPY ~might_and_guile/psi/d5ps40e.spl~ ~override~
	SAY NAME1 @20673
	SAY UNIDENTIFIED_DESC @20673
COPY ~might_and_guile/psi/d5_ps40e.bam~ ~override~

//end feat ability files____________________________________________________________


//FEAT CLAB FILES___________________________________________________________________
//
ACTION_FOR_EACH featspell IN ~d5rof01~ ~d5rof02~ ~d5rof03~ ~d5rof04~ ~d5rof05~ ~d5rof06~ ~d5rof07~ ~d5rof08~ ~d5rof09~ ~d5rof10~ ~d5rof11~ ~d5rof12~ BEGIN
  COPY_EXISTING ~%featspell%.spl~ ~override~
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 177 parameter1 = %ps_code% STR_VAR match_resource = ~D5_RFXD~ resource = ~D5_RFXPS~ END
	LPF CLONE_EFFECT INT_VAR multi_match = 1 match_opcode = 177 parameter1 = %sb_code% STR_VAR match_resource = ~D5_RFXD~ resource = ~D5_RFXSB~ END
END

COPY ~might_and_guile/thief/d5_rfxps.eff~ ~override~ 	//	psypher
COPY ~might_and_guile/thief/d5_rfxps.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/thief/d5_rfxsb.eff~ ~override~ 	//	soulblade
COPY ~might_and_guile/thief/d5_rfxsb.spl~ ~override~
	SAY NAME1 @7

// need to mess with these v

COPY_EXISTING ~d5psa00.spl~ ~override~
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 resist_dispel = 0 STR_VAR resource = ~D5PSD01~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 resist_dispel = 0 STR_VAR resource = ~D5PSC01~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 resist_dispel = 0 STR_VAR resource = ~D5PSB01~ END
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 resist_dispel = 0 STR_VAR resource = ~D5PSA01~ END

// REMEMBER: if add more feats, add them to d5_rfz.spl!!!!!!!!!!!

//__________________________________________________________________________________

