
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								REVISED BARDS
//__________________________________________________________________________________
//__________________________________________________________________________________

/* 
plan: make 'em all thieves

still to do: 
/- make spellcasting system
/- make bard songs from item
/- finish item use
/- TEST basic bard
/- restrict thief abilities
/- restrict skill points
/- disable thief skill buttons
/- remove real bards from menus
/- change class name to rogue
/- install kits
/- TEST
/- fix HLAs and HLA tables
/- set strongholds
/- change joinable NPCs
/- test spell slot bonuses
- fix +spell slot items - make .EFFs
- fix feat dialogues (it's triggering the spell dialogue atm)
- make music a quickslot ability, not item ability..??

FOR EACH KIT:
- get kitids code
- omit from AP_D5TNUSE append
- add 326 applying 1st bard song to d5bsong.itm
- append column to d5brdspl
- add d5brdthf table to clab

thiefscl:
PP	OL	FT	MS	HiS	DI	ST	Stealth

*/

//COPY MARKER FILE_________________________________________________________________
//
COPY ~might_and_guile/lib/markers/d5_bards.d5~ ~override~
//__________________________________________________________________________________


LAM JOINABLE_NPC_ARRAYS


//CHANGE CLASS TEXT_________________________________________________________________
//
//ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
 ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~THIEF~ BEGIN
	    SET T_row = %row%
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~FIGHTER_THIEF~ BEGIN
	    SET FT_row = %row%
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~CLERIC_THIEF~ BEGIN
	    SET CT_row = %row%
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BARD~ BEGIN
	    SET OB_row = %row%
	  END
	END
	SET_2DA_ENTRY %T_row% 3 cols RESOLVE_STR_REF (@20000)
	SET_2DA_ENTRY %T_row% 5 cols RESOLVE_STR_REF (@20001)
	SET_2DA_ENTRY %FT_row% 3 cols RESOLVE_STR_REF (@20003)
	SET_2DA_ENTRY %FT_row% 5 cols RESOLVE_STR_REF (@20004)
	SET_2DA_ENTRY %CT_row% 3 cols RESOLVE_STR_REF (@20005)
	SET_2DA_ENTRY %CT_row% 5 cols RESOLVE_STR_REF (@20006)
	SET_2DA_ENTRY %OB_row% 3 cols RESOLVE_STR_REF (@20007)
	SET_2DA_ENTRY %OB_row% 5 cols RESOLVE_STR_REF (@20008)
  BUT_ONLY
 END
 ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
  COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~THIEF~ BEGIN
	    SET T_row = %row%
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~FIGHTER_THIEF~ BEGIN
	    SET FT_row = %row%
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~CLERIC_THIEF~ BEGIN
	    SET CT_row = %row%
	  END
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~BARD~ BEGIN
	    SET OB_row = %row%
	  END
	END
	SET_2DA_ENTRY %T_row% 3 cols RESOLVE_STR_REF (@20000)
	SET_2DA_ENTRY %T_row% 5 cols RESOLVE_STR_REF (@20001)
	SET_2DA_ENTRY %FT_row% 3 cols RESOLVE_STR_REF (@20003)
	SET_2DA_ENTRY %FT_row% 5 cols RESOLVE_STR_REF (@20004)
	SET_2DA_ENTRY %CT_row% 3 cols RESOLVE_STR_REF (@20005)
	SET_2DA_ENTRY %CT_row% 5 cols RESOLVE_STR_REF (@20006)
	SET_2DA_ENTRY %OB_row% 3 cols RESOLVE_STR_REF (@20007)
	SET_2DA_ENTRY %OB_row% 5 cols RESOLVE_STR_REF (@20008)
  BUT_ONLY
 END
//END
//____________________________________________________________________________________


//BARD ABILITY FILES_________________________________________________________________
//
COPY ~might_and_guile/misc/d5lor05.spl~ ~override~				//	5-point lore bonus
	SAY NAME1 ~ ~
	SAY UNIDENTIFIED_DESC ~ ~
COPY ~might_and_guile/misc/d5lor20.spl~ ~override~				//	20-point lore bonus
	SAY NAME1 ~ ~
	SAY UNIDENTIFIED_DESC ~ ~
COPY ~might_and_guile/fighter/d5swash.spl~ ~override~			//	swashbuckling ability
	SAY NAME1 @3106
	SAY UNIDENTIFIED_DESC @3107
COPY ~might_and_guile/misc/d5_notu.spl~ ~override~				//	disable turn undead
	SAY NAME1 ~ ~
	SAY UNIDENTIFIED_DESC ~ ~
	
//disable skill buttons_______________________________________________________________
//
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5noppb.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 1 timing = 9 END
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5nomsb.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 0 timing = 9 END
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5noftb.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 14 timing = 9 END

//base HLA table______________________________________________________________________
//
COPY ~might_and_guile/nubards/lud5brd.2da~ ~override~
//____________________________________________________________________________________


//NEW "TRUECLASS" BARD________________________________________________________________
//
ADD_KIT ~D5_BARD~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_BARD       0 0 0 0 0 0 0 0~
~D5_BARD       0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS__________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_BARD    	   0   12  0   9   0   15~

//KIT STAT MODIFIERS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_BARD           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT___________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_BARD           0   17  0   17  0   17~

//REQUIREMENTS TO DUAL FROM THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_BARD  	       0   15  0   15  0   15~

//ALIGNMENT RESTRICTIONS_____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_BARD           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS_________________________________________________________________
//                 FT CL MA TH DR RA
~D5_BARD           1  1  0  0  0  0~

//KIT ABILITIES 2DA FILE_____________________________________________________________
~might_and_guile/nubards/d5_bard.2da~

//RACIAL KIT AVAILABILITY____________________________________________________________
~K_T_H K_T_E K_T_HE K_T_G~

//UNUSABLE FLAGS AND KIT BASE CLASS__________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
//~0x00800000 4~
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION__________________________________________________
~D5BRD~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION_________________________________________________
SAY @21801
SAY @21802
SAY @21803
//___________________________________________________________________________________

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21803)
		STR_VAR
			kit_name = D5_BARD
			clswpbon = ~0 0 3~
			backstab = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
			thiefskl = ~15 7~
			thiefscl = ~100 100 0 0 0 100 0 0~
			clsrcreq = ~1 1 1 0 0 1 0~
	END
END
//___________________________________________________________________________________

//BARD ABILITY FILES_________________________________________________________________
//
COPY_EXISTING ~might_and_guile/nubards/d5_bard.2da~ ~override~
//___________________________________________________________________________________


//ADD BLADE AS THIEF KIT______________________________________________________________
//
ADD_KIT ~D5_BLADE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_BLADE      0 0 0 0 0 0 0 0~
~D5_BLADE      0 0 0 0 0 0 0 0 0 2 2 0 0 0 2 2 0 1 0 0 0 0 1 1 0 1 1 1 0 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS__________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_BLADE          12   12  0   0   0   9~

//KIT STAT MODIFIERS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_BLADE          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT___________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_BLADE          0   17  0   17  0   17~

//REQUIREMENTS TO DUAL FROM THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_BLADE          0   15  0   15  0   15~

//ALIGNMENT RESTRICTIONS_____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_BLADE          1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS_________________________________________________________________
//                 FT CL MA TH DR RA
~D5_BLADE          1  1  0  0  0  0~

//KIT ABILITIES 2DA FILE_____________________________________________________________
~might_and_guile/nubards/d5_blade.2da~

//RACIAL KIT AVAILABILITY____________________________________________________________
~K_T_E K_T_H K_T_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS__________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION__________________________________________________
~D5BRD~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION_________________________________________________
SAY @21806
SAY @21807
SAY @21808
//___________________________________________________________________________________

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21808)
		STR_VAR
			kit_name = D5_BLADE
			backstab = ~1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2~
			clswpbon = ~0 0 3~
			thiefskl = ~20 12~
			thiefscl = ~100 0 0 100 100 0 100 0~
			clsrcreq = ~1 1 1 0 0 0 0~
	END
END
//____________________________________________________________________________________

//BLADE ABILITY FILES_________________________________________________________________
//
COPY ~might_and_guile/nubards/d5_blade.2da~ ~override~

// remove extra spell slots line
// hmm, do that below

//____________________________________________________________________________________


//ADD JESTER AS THIEF KIT______________________________________________________________
//
ADD_KIT ~D5_JESTER~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_JESTER     0 1 0 0 1 1 1 0~
~D5_JESTER     0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS__________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_JESTER          0   12  0   0   0   12~

//KIT STAT MODIFIERS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_JESTER          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT___________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_JESTER          0   17  0   17  0   17~

//REQUIREMENTS TO DUAL FROM THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_JESTER          0   15  0   15  0   15~

//ALIGNMENT RESTRICTIONS_____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_JESTER          0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS_________________________________________________________________
//                 FT CL MA TH DR RA
~D5_JESTER          1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE_____________________________________________________________
~might_and_guile/nubards/d5_jstr.2da~

//RACIAL KIT AVAILABILITY____________________________________________________________
~K_T_E K_T_H K_T_HE K_T_G~

//UNUSABLE FLAGS AND KIT BASE CLASS__________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION__________________________________________________
~D5BRD~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION_________________________________________________
SAY @21811
SAY @21812
SAY @21813
//___________________________________________________________________________________

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21813)
		STR_VAR
			kit_name = D5_JESTER
			clswpbon = ~0 0 3~
			backstab = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
			thiefskl = ~15 7~
			thiefscl = ~100 100 0 0 0 100 0 0~
			clsrcreq = ~1 1 1 0 0 1 0~
	END
END
//____________________________________________________________________________________

//JESTER ABILITY FILES________________________________________________________________
//
COPY ~might_and_guile/nubards/d5_jstr.2da~ ~override~
//____________________________________________________________________________________


//ADD SKALD AS FIGHTER/THIEF__________________________________________________________
//
ADD_KIT ~D5_SKALD~

//WEAPON PROFICIENCIES________________________________________________________________
//11           	                        T   S           F   Q             S S
//10           	L S                     W   C           L   U             W I
//9            	A M             B L S   O   I   W       A   A             O N
//8            	R A             A O H   H   M   A       I   R C   S       R G
//7            	G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            	E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            	S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            	W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            	O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            	R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            	D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_SKALD       2 2 2 2 2 2 2 2~
~D5_SKALD       0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_SKALD          12  0   0   12  0   15~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_SKALD          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT__________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_SKALD          17  0   0   0   0   17~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_SKALD  	       15  0   0   0   0   15~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_SKALD          1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_SKALD          0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE____________________________________________________________
~might_and_guile/nubards/d5_skld.2da~

//RACIAL KIT AVAILABILITY___________________________________________________________
~K_FT_D K_FT_H K_FT_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20, FM = 7, FC = 8, FT = 9, MT = 13, CM = 14, CT = 15, CR = 18
~0x00004000 9~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~D5BRD~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION_________________________________________________
SAY @21816
SAY @21817
SAY @21818
//___________________________________________________________________________________

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21818)
		STR_VAR
			kit_name = D5_SKALD
			clswpbon = ~1 0 3~
			hpclass = ~HPFT~
			backstab = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
			thiefskl = ~15 7~
			thiefscl = ~0 0 0 0 0 100 0 0~
			clsrcreq = ~1 1 1 0 0 0 0~
	END
END
//___________________________________________________________________________________

//SKALD ABILITY FILES________________________________________________________________
//
COPY ~might_and_guile/nubards/d5_skld.2da~ ~override~
//___________________________________________________________________________________

//QD_MULTICLASS______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_skld.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_SKALD~ 
		kit_clab = ~d5_skld~
		base_class = ~T~
		mc_dir = ~might_and_guile/lib/qd_mc~
  END
END 
//___________________________________________________________________________________


//ADD GALLANT AS FIGHTER/THIEF_______________________________________________________
//
ADD_KIT ~D5_GALLANT~

//WEAPON PROFICIENCIES_______________________________________________________________
//11           	                        T   S           F   Q             S S
//10           	L S                     W   C           L   U             W I
//9            	A M             B L S   O   I   W       A   A             O N
//8            	R A             A O H   H   M   A       I   R C   S       R G
//7            	G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            	E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            	S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            	W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            	O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            	R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            	D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_GALLANT     2 2 2 2 2 2 2 2~
~D5_GALLANT     0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_GALLANT        0   0   12  0   0   15~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_GALLANT        0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT__________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_GALLANT        0   0   17  0   0   17~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_GALLANT    	   0   0   15  0   0   15~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_GALLANT        1  1  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_GALLANT        0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE____________________________________________________________
~might_and_guile/nubards/d5_glnt.2da~

//RACIAL KIT AVAILABILITY___________________________________________________________
~K_FT_E K_FT_H K_FT_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 9~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~D5BRD~

//TOB STARTING EQUIPMENT____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @21821
SAY @21822
SAY @21823
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21823)
		STR_VAR
			kit_name = D5_GALLANT  
			clswpbon = ~1 0 3~
			hpclass = ~HPFT~
			backstab = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
			thiefskl = ~0 0~
			thiefscl = ~0 0 0 0 0 0 0 0~
			clsrcreq = ~1 1 1 0 0 0 0~
	END
END
//___________________________________________________________________________________

//GALLANT ABILITY FILES______________________________________________________________
//
COPY ~might_and_guile/nubards/d5_glnt.2da~ ~override~
COPY ~might_and_guile/misc/d5dsvbo.spl~ ~override~
COPY_EXISTING ~sppr409.spl~ ~override/d5galdw.spl~
	LPM spell_to_innate
//___________________________________________________________________________________


//QD_MULTICLASS______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_glnt.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_GALLANT~ 
		kit_clab = ~d5_glnt~
		base_class = ~T~
		mc_dir = ~might_and_guile/lib/qd_mc~
  END
END 
//___________________________________________________________________________________


//ADD HERALD AS FIGHTER/THIEF________________________________________________________
//
ADD_KIT ~D5_HERALD~

//WEAPON PROFICIENCIES_______________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_HERALD     2 2 2 2 2 2 2 2~
~D5_HERALD     0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS__________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_HERALD         0   12  0   12  0   12~

//KIT STAT MODIFIERS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_HERALD         0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT___________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_HERALD         0   17  0   17  0   17~

//REQUIREMENTS TO DUAL FROM THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_HERALD         0   15  0   15  0   15~

//ALIGNMENT RESTRICTIONS_____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_HERALD         1  1  1  1  1  1  0  0  0~

//DUAL CLASS OPTIONS_________________________________________________________________
//                 FT CL MA TH DR RA
~D5_HERALD         0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE_____________________________________________________________
~might_and_guile/nubards/d5_hrld.2da~

//RACIAL KIT AVAILABILITY____________________________________________________________
~K_FT_E K_FT_H K_FT_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS__________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20, FT = 9, FC = 8, CT = 15, CR = 18, FM = 7, CM = 14, MT = 13
~0x00004000 9~

//HIGH LEVEL ABILITIES ABBREVIATION__________________________________________________
~D5BRD~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION_________________________________________________
SAY @21826
SAY @21827
SAY @21828
//___________________________________________________________________________________

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee sod bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21828)
		STR_VAR
			kit_name = D5_HERALD
			clswpbon = ~1 0 3~
			hpclass = ~HPFT~
			backstab = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
			thiefskl = ~15 7~
			thiefscl = ~0 100 100 0 0 100 0 0~
			clsrcreq = ~1 1 1 0 0 0 0~
	END
END
//___________________________________________________________________________________

//QD_MULTICLASS______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_hrld.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_HERALD~ 
		kit_clab = ~d5_hrld~
		base_class = ~T~
		mc_dir = ~might_and_guile/lib/qd_mc~
  END
END 
//___________________________________________________________________________________

//HERALD ABILITY FILES_______________________________________________________________
//
COPY ~might_and_guile/nubards/d5_hrld.2da~ ~override~
//___________________________________________________________________________________


//ADD MEISTERSINGER AS THIEF KIT_____________________________________________________
//
ADD_KIT ~D5_MEISTER~

//WEAPON PROFICIENCIES_______________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_MEISTER    0 0 0 0 0 0 0 0~
~D5_MEISTER    0 0 0 0 0 0 0 0 0 2 2 2 0 0 3 3 0 1 0 0 0 0 1 1 0 1 2 1 0 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS__________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_MEISTER         0   12  0   0   9   12~

//KIT STAT MODIFIERS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_MEISTER         0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT___________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_MEISTER         0   17  0   0   17  17~

//REQUIREMENTS TO DUAL FROM THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_MEISTER         0   15  0   0   17  15~

//ALIGNMENT RESTRICTIONS_____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_MEISTER         0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS_________________________________________________________________
//                 FT CL MA TH DR RA
~D5_MEISTER         1  1  0  0  0  0~

//KIT ABILITIES 2DA FILE_____________________________________________________________
~might_and_guile/nubards/d5_mstr.2da~

//RACIAL KIT AVAILABILITY____________________________________________________________
~K_T_E K_T_H K_T_HE K_T_HL K_T_G~

//UNUSABLE FLAGS AND KIT BASE CLASS__________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION__________________________________________________
~D5BRD~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION_________________________________________________
SAY @21831
SAY @21832
SAY @21833
//___________________________________________________________________________________

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21833)
		STR_VAR
			kit_name = D5_MEISTER
			clswpbon = ~0 0 3~
			backstab = ~1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1~
			thiefskl = ~15 7~
			thiefscl = ~0 0 100 100 100 0 0 0~
			clsrcreq = ~1 1 1 0 1 1 0~
	END
END
//___________________________________________________________________________________

//MEISTERSINGER ABILITY FILES________________________________________________________
//
COPY ~might_and_guile/nubards/d5_mstr.2da~ ~override~
//___________________________________________________________________________________


//ADD JINXER AS THIEF_________________________________________________________________
//
ADD_KIT ~D5_JINXER~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_JINXER     0 0 0 0 0 0 0 0~
~D5_JINXER     0 0 0 0 0 0 0 0 0 1 1 1 0 1 1 1 0 1 0 0 0 0 1 1 0 1 1 1 0 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS__________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_JINXER          0   12  0   12  0   12~

//KIT STAT MODIFIERS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_JINXER          0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT___________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_JINXER          0   17  0   17  0   17~

//REQUIREMENTS TO DUAL FROM THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_JINXER          0   15  0   15  0   15~

//ALIGNMENT RESTRICTIONS_____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_JINXER          0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS_________________________________________________________________
//                 FT CL MA TH DR RA
~D5_JINXER          1  0  0  0  0  0~

//KIT ABILITIES 2DA FILE_____________________________________________________________
~might_and_guile/nubards/d5_jinx.2da~

//RACIAL KIT AVAILABILITY____________________________________________________________
~K_T_E K_T_H K_T_HE K_T_G~

//UNUSABLE FLAGS AND KIT BASE CLASS__________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION__________________________________________________
~D5BRD~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION_________________________________________________
SAY @21836
SAY @21837
SAY @21838
//___________________________________________________________________________________

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21838)
		STR_VAR
			kit_name = D5_JINXER
			backstab = ~1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2~
			clswpbon = ~0 0 3~
			thiefskl = ~20 12~
			thiefscl = ~100 100 100 0 0 100 0 0~
			clsrcreq = ~1 1 1 0 1 0 0~
	END
END
//____________________________________________________________________________________

//JINXER ABILITY FILES________________________________________________________________
//
COPY ~might_and_guile/nubards/d5_jinx.2da~ ~override~

//____________________________________________________________________________________


//ADD LORESINGER AS CLERIC/THIEF_____________________________________________________
//
ADD_KIT ~D5_LORESINGER~

// need to make this a cleric/thief kit

//WEAPON PROFICIENCIES_______________________________________________________________
//11           		                        T   S           F   Q             S S
//10           		L S                     W   C           L   U             W I
//9            		A M             B L S   O   I   W       A   A             O N
//8            		R A             A O H   H   M   A       I   R C   S       R G
//7            		G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            		E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            		S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            		W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            		O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            		R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            		D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_LORESINGER      0 0 0 0 0 0 0 0~
~D5_LORESINGER      0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_LORESINGER      12  0   0   12  0   15~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_LORESINGER      0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT__________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_LORESINGER      17  0   0   0   0   17~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_LORESINGER      15  0   0   0   0   15~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_LORESINGER      1  1  0  1  1  0  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_LORESINGER     0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE____________________________________________________________
~might_and_guile/nubards/d5_lors.2da~

//RACIAL KIT AVAILABILITY___________________________________________________________
~K_CT_E K_CT_H K_CT_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~D5BRD~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION_________________________________________________
SAY @21841
SAY @21842
SAY @21843
//___________________________________________________________________________________

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21843)
		STR_VAR
			kit_name = D5_LORESINGER
			clswpbon = ~0 0 3~
			hpclass = ~HPCT~
	END
END
//___________________________________________________________________________________

//LORESINGER ABILITY FILES___________________________________________________________
//
COPY ~might_and_guile/nubards/d5_lors.2da~ ~override~
//___________________________________________________________________________________

// will this work?  let's find out!
//DEFINE SPHERE ACCESS______________________________________________________________
//
LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	u_leather_armor 	= 1
	u_chain_armor 		= 0
	u_plate_armor 		= 0
	u_club_staff	 	= 1
	u_hammers	 		= 1
	u_maces 	 		= 1
	u_flails 			= 1
	u_axes 				= 1
	u_daggers 			= 1
	u_short_swords		= 1
	u_long_swords		= 1
	u_scimitars 		= 1
	u_katanas 			= 1
	u_bastard_swords 	= 1
	u_2hand_swords 		= 1
	u_halberds 			= 1
	u_spears 			= 1
	u_darts 			= 1
	u_slings 			= 1
	u_bows 				= 1
	u_crossbows 		= 1  
  STR_VAR
    clab_name 		= ~d5_lors~
	class 			= ~cleric_thief~
	s_Life 			= ~major~
	s_Death 		= ~x~
	s_Benediction 	= ~major~
	s_Destruction 	= ~minor~
	s_Protection 	= ~major~
	s_War 			= ~minor~
	s_Exploration   = ~major~
	s_Knowledge 	= ~major~
	s_Deception 	= ~x~
	s_Thought 		= ~major~
	s_Dread 		= ~x~
	s_Vigor 		= ~minor~
	s_Affliction 	= ~x~
	s_Animal 		= ~minor~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~minor~
	s_Fire 			= ~x~
	s_Light 		= ~major~
	s_Shadow 		= ~x~
	s_Magic 		= ~minor~
	s_Perdition     = ~x~
END

LAM ~READ_FNP_KIT_INFO~

ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
  LAM apply_fnp_spheres
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_fnp_usability.d5~ BEGIN
  LAM apply_fnp_usability
END
//__________________________________________________________________________________

//QD_MULTICLASS_______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_lors.2da~ BEGIN
  LAF qd_multiclass
	STR_VAR
		kit_name = ~D5_LORESINGER~ 
		kit_clab = ~d5_lors~
		base_class = ~T~
		mc_dir = ~might_and_guile/lib/qd_mc~
  END
END 
//__________________________________________________________________________________


/*
//ADD HEXBLADE AS DEMIBARD___________________________________________________________
//
ADD_KIT ~D5_HEXBLADE~

//WEAPON PROFICIENCIES________________________________________________________________
//11           	                        T   S           F   Q             S S
//10           	L S                     W   C           L   U             W I
//9            	A M             B L S   O   I   W       A   A             O N
//8            	R A             A O H   H   M   A       I   R C   S       R G
//7            	G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            	E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            	S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            	W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            	O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            	R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            	D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5_HEXBLADE    0 0 0 0 0 0 0 0~
~D5_HEXBLADE    0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_HEXBLADE       12  0   0   12  0   15~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_HEXBLADE       0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT__________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_HEXBLADE       15  0   0   0   0   15~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5_HEXBLADE  	   15  0   0   0   0   15~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5_HEXBLADE       0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5_HEXBLADE       0  0  0  1  0  0~

//KIT ABILITIES 2DA FILE____________________________________________________________
~might_and_guile/nubards/d5_hexbl.2da~

//RACIAL KIT AVAILABILITY___________________________________________________________
~K_F_E K_F_H K_F_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ba0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION_________________________________________________
SAY @21831
SAY @21832
SAY @21833
//___________________________________________________________________________________

//EE KIT EXTRAS______________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@21833)
		STR_VAR
			kit_name = D5_HEXBLADE
			clswpbon = ~1 0 3~
			hpclass = ~HPPRS~
	END
END
//___________________________________________________________________________________

//HEXBLADE ABILITY FILES_____________________________________________________________
//
COPY ~might_and_guile/nubards/d5_hexbl.2da~ ~override~
COPY ~might_and_guile/misc/d5ssvbo.spl~ ~override~
//___________________________________________________________________________________

//DON'T USE SCROLLS/WANDS___________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rf84n.spl~ BEGIN
	APPEND ~d5_hexbl.2da~ ~ABILITY    AP_D5_RF84N ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
//	APPEND ~d5_hexbl.2da~ ~ABILITY    AP_D5_RF83N ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
//__________________________________________________________________________________
*/


//GET KIT IDENTIFIERS________________________________________________________________
//
// ***** update this for all kits

COPY_EXISTING ~kit.ids~ ~override~
  COUNT_2DA_COLS cols 
  READ_2DA_ENTRIES_NOW rows cols 
  FOR (row = 1; row < rows; ++row) BEGIN 
    READ_2DA_ENTRY_FORMER rows row 1 ~kit~ 
    PATCH_IF ~%kit%~ STRING_EQUAL_CASE ~D5_BARD~ BEGIN
      SET bard_row = %row%
      READ_2DA_ENTRY_FORMER rows bard_row 0 nu_bard_code
    END
    PATCH_IF ~%kit%~ STRING_EQUAL_CASE ~D5_BLADE~ BEGIN
      SET bard_row = %row%
      READ_2DA_ENTRY_FORMER rows bard_row 0 nu_blade_code
    END
    PATCH_IF ~%kit%~ STRING_EQUAL_CASE ~D5_JESTER~ BEGIN
      SET bard_row = %row%
      READ_2DA_ENTRY_FORMER rows bard_row 0 nu_jester_code
    END
    PATCH_IF ~%kit%~ STRING_EQUAL_CASE ~D5_SKALD~ BEGIN
      SET bard_row = %row%
      READ_2DA_ENTRY_FORMER rows bard_row 0 nu_skald_code
    END
    PATCH_IF ~%kit%~ STRING_EQUAL_CASE ~D5_GALLANT~ BEGIN
      SET bard_row = %row%
      READ_2DA_ENTRY_FORMER rows bard_row 0 nu_gallant_code
    END
    PATCH_IF ~%kit%~ STRING_EQUAL_CASE ~D5_HERALD~ BEGIN
      SET bard_row = %row%
      READ_2DA_ENTRY_FORMER rows bard_row 0 nu_herald_code
    END
    PATCH_IF ~%kit%~ STRING_EQUAL_CASE ~D5_MEISTER~ BEGIN
      SET bard_row = %row%
      READ_2DA_ENTRY_FORMER rows bard_row 0 nu_meister_code
    END
    PATCH_IF ~%kit%~ STRING_EQUAL_CASE ~D5_JINXER~ BEGIN
      SET bard_row = %row%
      READ_2DA_ENTRY_FORMER rows bard_row 0 nu_jinxer_code
    END
    PATCH_IF ~%kit%~ STRING_EQUAL_CASE ~D5_LORESINGER~ BEGIN
      SET bard_row = %row%
      READ_2DA_ENTRY_FORMER rows bard_row 0 nu_loresinger_code
    END
  END
BUT_ONLY
//___________________________________________________________________________________


//use scrolls/wands__________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_umd.spl~ BEGIN

 COPY ~might_and_guile/feats/d5_rfh4.bam~ ~override~
 COPY ~might_and_guile/feats/d5_rfh4.spl~ ~override/d5_umd.spl~   //           UMD
	SAY NAME1 @20293
	SAY UNIDENTIFIED_DESC @20294
	WRITE_ASCII 0x3a ~d5_rfh4~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rfh4~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = ~d5_numd~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5_numd~ END

 LAF d5_resolve_specific STR_VAR new_specific_id = ~D5_NO_UMD~ RET new_specific_ind END

 OUTER_SET no_umd_specific = %new_specific_ind%

/*
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5_numd.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
*/
 COPY ~might_and_guile/feats/d5_nscrl.spl~ ~override/d5_numd.spl~
  LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR resource = ~d5_numd~ END
COPY ~might_and_guile/feats/d5_rf84n.eff~ ~override/D5_NUMD.eff~
  WRITE_LONG 0x1c %no_umd_specific%
  WRITE_LONG 0x90 1
  WRITE_EVALUATED_ASCII 0x94 ~D5_NUMD~ #8

 OUTER_SET scroll_count = 0
 OUTER_SPRINT $use_scrolls(~%scroll_count%~) ~scroll~
 COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  READ_BYTE     0x2f current ELSE 0
  READ_BYTE     0x2b current2 ELSE 0
  READ_LONG 0x64 headoffset  ELSE 0
  READ_SHORT 0x68 headcount  ELSE 0
  READ_LONG 0x6a effectsoffset  ELSE 0
  haslearn = 0
  hascast = 0
//	  PATCH_IF (headcount = 2) BEGIN
    FOR (headcyc = 0; headcyc < headcount ; headcyc = headcyc + 1) BEGIN
      thishead = 0
      READ_SHORT (headoffset + (headcyc * 0x38) + 0x1e) effcount  ELSE 0
      READ_SHORT (headoffset + (headcyc * 0x38) + 0x20) effectsindex  ELSE 0
      FOR (effcyc = 0; effcyc < effcount; effcyc = effcyc + 1) BEGIN
        READ_SHORT (effectsoffset + (effectsindex + effcyc)* 0x30) opcode ELSE 0
        PATCH_IF (opcode = 0x93) AND (thishead = 0) BEGIN
          READ_ASCII (effectsoffset + 0x14 + (effectsindex + effcyc)* 0x30) resref_learn  ELSE 0
          INNER_PATCH_FILE ~%resref_learn%.spl~ BEGIN
            READ_SHORT 0x1c type
          END
          PATCH_IF (type = 1) BEGIN // spell scroll
            thishead = 1
            haslearn = 1
          END
        END // PATCH_IF... (opcode = learn spell)
        PATCH_IF ((opcode = 0x92) OR (opcode = 0x94)) AND (thishead = 0) BEGIN
          READ_ASCII (effectsoffset + 0x14 + (effectsindex + effcyc)* 0x30) resref_cast  ELSE 0
          INNER_PATCH_FILE ~%resref_cast%.spl~ BEGIN
            READ_SHORT 0x1c type
          END
          PATCH_IF (type = 1) OR (type = 2) BEGIN // spell scroll
            thishead = 1
            hascast = 1
          END
        END // PATCH_IF (opcode = cast spell)
      END // FOR... effect_cycle
    END // FOR... header cycle
//  END // PATCH_IF... have exactly 2 headers
  PATCH_IF (haslearn = 1) AND (hascast = 1) /*AND (~%resref_cast%~ STRING_EQUAL_CASE ~%resref_learn%~) */BEGIN
	SPRINT $use_scrolls(~%scroll_count%~) ~%SOURCE_RES%~
	SET ++scroll_count
  END
 BUT_ONLY
 ACTION_PHP_EACH use_scrolls AS num => scroll BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%scroll%.itm~ BEGIN
	PRINT ~%scroll% is a wizard scroll~
	COPY_EXISTING ~%scroll%.itm~ ~override~
	  WRITE_BYTE 0x1f (THIS BAND 0b11110111)
	  WRITE_BYTE 0x20 (THIS BAND 0b10111111)
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter2 = 6 parameter1 = %no_umd_specific% timing = 2 END
	BUT_ONLY
  END
 END
 COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  READ_SHORT	0x1c item_type
  PATCH_IF (item_type = 35) BEGIN
	READ_BYTE 0x20 thief_use
	PATCH_IF (%thief_use% BAND 0b01000000) = 0b01000000 BEGIN
	  WRITE_BYTE 0x1f (THIS BAND 0b11110111)
	  WRITE_BYTE 0x20 (THIS BAND 0b10111111)
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter2 = 6 parameter1 = %no_umd_specific% timing = 2 END
	END
  END
 BUT_ONLY

 COPY_EXISTING ~clabth01.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~might_and_guile/feats/no_umd.txt~
 BUT_ONLY
 COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
	  READ_2DA_ENTRY %index% 5 9 modclab
	  READ_2DA_ENTRY %index% 8 9 modclass
	  DEFINE_ASSOCIATIVE_ARRAY d5_319_array BEGIN "%modclab%" => "%modclass%" END
	END
 BUT_ONLY
 ACTION_PHP_EACH d5_319_array AS bo => zo BEGIN
// ***** omit bard kits that can use wands/scrolls
	ACTION_IF (%zo% = 4) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_bard~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_jstr~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_hrld~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_jinx~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_lors~) BEGIN
	  COPY_EXISTING ~%bo%.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/feats/no_umd.txt~
	END
 END

END
//	end use scrolls/wands
//____________________________________________________________________________________


//catch other items___________________________________________________________________
//
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5tnuse.spl~

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  READ_SHORT 0x1c item_type
  READ_BYTE 0x1e bard_use
  READ_BYTE 0x20 thief_use
  PATCH_IF NOT (item_type = 11) && NOT (item_type = 35) BEGIN
	PATCH_IF ((%bard_use% BOR 0b10111111) = 0b10111111) && ((%thief_use% BAND 0b01000000) = 0b01000000) BEGIN
	  WRITE_BYTE 0x1f (THIS BAND 0b11111101)
	  WRITE_BYTE 0x20 (THIS BAND 0b10111101)
//	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = 0 parameter2 = 9 timing = 2 END
//	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 target = 1 parameter1 = 16384 parameter2 = 9 timing = 2 END
	  SPRINT item_res ~%SOURCE_RES%~
	  INNER_ACTION BEGIN
		COPY_EXISTING ~d5tnuse.spl~ ~override~
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 180 target = 1 parameter1 = (0 - 1) parameter2 = 0 timing = 9 STR_VAR resource = EVAL ~%item_res%~ END
		BUT_ONLY
	  END
	END
  END
BUT_ONLY

// apply d5tnuse to all T kits, except all bards
// (including trueclass thief, which will cover all FT/CT kits)

APPEND ~clabth01.2da~ ~BARD_USE    AP_D5TNUSE  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
COPY_EXISTING ~kitlist.2da~ ~override~
  COUNT_2DA_ROWS ~9~ "rows"
  FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
	READ_2DA_ENTRY %index% 5 9 modclab
	READ_2DA_ENTRY %index% 8 9 modclass
	DEFINE_ASSOCIATIVE_ARRAY d5_180_array BEGIN "%modclab%" => "%modclass%" END
  END
BUT_ONLY
ACTION_PHP_EACH d5_180_array AS bo => zo BEGIN
// ***** omit bard kits
  ACTION_IF (%zo% = 4) && FILE_EXISTS_IN_GAME ~%bo%.2da~ && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_bard~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_blade~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_jstr~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_skld~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_glnt~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_hrld~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_mstr~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_jinx~) && NOT (~%bo%~ STRING_EQUAL_CASE ~d5_bard~) BEGIN
	APPEND ~%bo%.2da~ ~BARD_USE    AP_D5TNUSE  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
  END
END

//____________________________________________________________________________________


//fix UAI_____________________________________________________________________________
//
// if UAI is in the game, have it 321 d5tnuse
// and, for good measure, have it 321 d5_numd
ACTION_IF FILE_EXISTS_IN_GAME ~spcl915.spl~ BEGIN
  COPY_EXISTING ~spcl915.spl~ ~override~
  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5tnuse~ END
  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~D5_NUMD~ END
END
//____________________________________________________________________________________


//INSTALL NEW BARD AURAS_____________________________________________________________
//
// set these up as item abilities. 

// here: 1) a single item, with a 214 ability
// 2) the 214 target ability initiates the relevant bard song
//    ... and adds the cancel item
// 3) the cancel ability stops all bard songs
//    ... and add the song choice item

// 'start song' .ITM uses 214 to choose song 
// ... and 112 to remove self 
// ... and 143 to add stop song .ITM
// have all scripts and scrolls 171 the A spells instead of W spells
// turn the A spells into wizard spells
// A spell triggers the B .EFF, with 232
// B spell has the song effects
// make a 'stop song' .ITM, with 321 vs. all A spells
// ... and 112 to remove self
// ... and 143 to add start song .ITM

APPEND ~splprot.2da~ ~D5_KIT_IS%TAB%152%TAB%-1%TAB%1~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_KIT_IS~ BEGIN
	    SET kit_is_row = %row%
	  END
	END
BUT_ONLY

COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bsong.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5bsong~ END

COPY ~might_and_guile/nubards/d5bdmusa.bam~ ~override~			//		song icon
COPY ~might_and_guile/nubards/d5bsong.itm~ ~override~			//		bard song .itm
  LPF ALTER_ITEM_HEADER INT_VAR target = 7 speed = 0 STR_VAR icon = ~d5bdmusa~ END
// ***** add 326 effect for each bard kit's 1st song
  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 2 parameter1 = %nu_bard_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5bd01~ END
  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 2 parameter1 = %nu_blade_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5bd21~ END
  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 2 parameter1 = %nu_jester_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5bd22~ END
  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 2 parameter1 = %nu_skald_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5bd03~ END
  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 2 parameter1 = %nu_gallant_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5bd02~ END
  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 2 parameter1 = %nu_herald_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5bd42~ END
  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 2 parameter1 = %nu_meister_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5bd01~ END
  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 2 parameter1 = %nu_jinxer_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5bd22~ END
  LPF ADD_ITEM_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 2 parameter1 = %nu_loresinger_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = ~d5bd06~ END

COPY ~might_and_guile/nubards/d5bdmusx.bam~ ~override~			//		no song icon
COPY ~might_and_guile/nubards/d5xsong.itm~ ~override~			//		stop song .itm
  LPF ALTER_ITEM_HEADER INT_VAR target = 7 STR_VAR icon = ~d5bdmusx~ END
  PATCH_FOR_EACH all_songs IN ~01a~ ~02a~ ~03a~ ~05a~ ~06a~ ~07a~ ~08a~ ~20a~ ~21a~ ~22a~ ~23a~ ~24a~ ~25a~ ~41a~ ~42a~ ~43a~ ~46a~ ~47a~ ~48a~ ~61a~ BEGIN
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 21 opcode = 321 target = 1 STR_VAR resource = EVAL ~d5bd%all_songs%~ END
  END
  LPF ADD_ITEM_EFFECT INT_VAR opcode = 279 target = 1 parameter2 = 13 timing = 1 END

COPY ~might_and_guile/nubards/d5_bd01.bam~ ~override~			//		song icon
COPY ~might_and_guile/nubards/d5bd01a.spl~ ~override~			//		luck inspiration
  SAY NAME1 @21011
  LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd01~ END
  WRITE_SHORT 0x1c 1
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd01b.eff~ ~override~			//		232 eff triggered by song
COPY ~might_and_guile/nubards/d5bd01b.spl~ ~override~			//		aura triggered by 232 eff
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd01.spl~	//		give song
  SAY NAME1 @21011
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd01a~ END

COPY ~might_and_guile/nubards/d5_bd02.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd02a.spl~ ~override~			//		morale inspiration
	SAY NAME1 @21021
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd02~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd02b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd02b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd02.spl~
  SAY NAME1 @21021
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd02a~ END

COPY ~might_and_guile/nubards/d5_bd03.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd03a.spl~ ~override~			//		power inspiration
	SAY NAME1 @21031
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd03~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd03b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd03b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd03.spl~
  SAY NAME1 @21031
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd03a~ END

COPY ~might_and_guile/nubards/d5_bd05.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd05a.spl~ ~override~			//		RI inspiration
	SAY NAME1 @21051
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd05~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd05b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd05b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd05.spl~
  SAY NAME1 @21051
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd05a~ END

COPY ~might_and_guile/nubards/d5_bd06.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd06a.spl~ ~override~			//		bless inspiration
	SAY NAME1 @21061
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd06~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd06b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd06b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd06.spl~
  SAY NAME1 @21061
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd06a~ END

COPY ~might_and_guile/nubards/d5_bd07.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd07a.spl~ ~override~			//		NPP inspiration
	SAY NAME1 @21071
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd07~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd07b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd07b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd07.spl~
  SAY NAME1 @21071
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd07a~ END

COPY ~might_and_guile/nubards/d5_bd08.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd08a.spl~ ~override~			//		mind shield inspiration
	SAY NAME1 @21081
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd08~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd08b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd08b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd08.spl~
  SAY NAME1 @21081
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd08a~ END

COPY ~might_and_guile/nubards/d5_bd09.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd09a.spl~ ~override~			//		death ward inspiration
	SAY NAME1 @21071
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd07~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd09b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd09b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd09.spl~
  SAY NAME1 @21091
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd09a~ END

COPY ~might_and_guile/nubards/d5_bd20.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd20a.spl~ ~override~			//		casting interference emanation
	SAY NAME1 @21201
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd20~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd20b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd20b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd20.spl~
  SAY NAME1 @21201
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd20a~ END

COPY ~might_and_guile/nubards/d5_bd21.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd21a.spl~ ~override~			//		combat penalties emanation
	SAY NAME1 @21211
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd21~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd21b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd21b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd21.spl~
  SAY NAME1 @21211
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd21a~ END

COPY ~might_and_guile/nubards/d5_bd22.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd22a.spl~ ~override~			//		save penalties emanation
	SAY NAME1 @21221
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd22~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd22b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd22b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd22.spl~
  SAY NAME1 @21221
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd22a~ END

COPY ~might_and_guile/nubards/d5_bd23.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd23a.spl~ ~override~			//		confusion emanation
	SAY NAME1 @21231
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd23~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd23b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd23b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd23.spl~
  SAY NAME1 @21231
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd23a~ END

COPY ~might_and_guile/nubards/d5_bd24.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd24a.spl~ ~override~			//		hold undead emanation
	SAY NAME1 @21241
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd24~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd24b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd24b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd24.spl~
  SAY NAME1 @21241
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd24a~ END

COPY ~might_and_guile/nubards/d5_bd25.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd25a.spl~ ~override~			//		entangle emanation
	SAY NAME1 @21251
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd25~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd25b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd25b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd25.spl~
  SAY NAME1 @21251
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd25a~ END

COPY ~might_and_guile/nubards/d5_bd41.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd41a.spl~ ~override~			//		blur aura
	SAY NAME1 @21411
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd41~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
//COPY ~might_and_guile/nubards/d5bd41a.eff~ ~override~
COPY ~might_and_guile/nubards/d5bd41b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd41b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd41.spl~
  SAY NAME1 @21411
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd41a~ END

COPY ~might_and_guile/nubards/d5_bd42.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd42a.spl~ ~override~			//		mind blank aura
	SAY NAME1 @21421
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd42~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd42b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd42b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd42.spl~
  SAY NAME1 @21421
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd42a~ END

COPY ~might_and_guile/nubards/d5_bd43.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd43a.spl~ ~override~			//		MGOI aura
	SAY NAME1 @21431
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd43~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd43b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd43b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd43.spl~
  SAY NAME1 @21431
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd43a~ END

COPY ~might_and_guile/nubards/d5_bd46.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd46a.spl~ ~override~			//		fear aura
	SAY NAME1 @21461
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd46~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd46b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd46b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd46.spl~
  SAY NAME1 @21461
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd46a~ END

COPY ~might_and_guile/nubards/d5_bd47.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd47a.spl~ ~override~			//		slow aura
	SAY NAME1 @21471
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd47~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd47b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd47b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd47.spl~
  SAY NAME1 @21471
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd47a~ END

COPY ~might_and_guile/nubards/d5_bd48.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd48a.spl~ ~override~			//		dispel illusions aura
	SAY NAME1 @21481
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd48~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd48b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd48b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd48.spl~
  SAY NAME1 @21481
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd48a~ END

COPY ~might_and_guile/nubards/d5_bd61.bam~ ~override~
COPY ~might_and_guile/nubards/d5bd61a.spl~ ~override~			//		maze aura
	SAY NAME1 @21611
	LPF ALTER_SPELL_HEADER INT_VAR location = 2 STR_VAR icon = ~d5_bd61~ END
	WRITE_SHORT 0x1c 1
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 13 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 112 target = 1 timing = 9 STR_VAR resource = ~d5bsong~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 143 target = 1 parameter1 = 14 timing = 9 STR_VAR resource = ~d5xsong~ END
COPY ~might_and_guile/nubards/d5bd61b.spl~ ~override~
COPY ~might_and_guile/nubards/d5bd61b.eff~ ~override~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bd61.spl~
  SAY NAME1 @21611
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5bd61a~ END
//___________________________________________________________________________________


//ADD NEW AURAS TO WORLD_____________________________________________________________
//
// just alter/clone the 177 effects to cover the new kits
// ... wait, also need to make the .EFFs

COPY ~might_and_guile/nubards/d5bd05.itm~ ~override~			//		mirror images
	SAY NAME2 @21051
	SAY IDENTIFIED_DESC @21052
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 177 parameter1 = %nu_bard_code% parameter2 = 9 STR_VAR resource = ~d5bd05a~ END
/*
	  PATCH_FOR_EACH nubard_kit IN ~%nu_blade_code%~ ~%nu_jester_code%~ ~%nu_skald_code%~ ~%nu_gallant_code%~ ~%nu_herald_code%~ ~%nu_meister_code%~ ~%nu_jinxer_code%~ BEGIN
		LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 177 parameter1 = %nubard_kit% parameter2 = 9 END
	  END
*/
CREATE EFF ~d5bd05a~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5bd05a~ #8
/*
ACTION_IF FILE_EXISTS_IN_GAME ~pwarden.cre~ BEGIN
  COPY_EXISTING ~pwarden.cre~ ~override~
	ADD_CRE_ITEM ~d5bd05~ #1 #0 #0 ~IDENTIFIED~ ~INV~
END
*/
ACTION_IF FILE_EXISTS_IN_GAME ~raelis.dlg~ BEGIN
  COMPILE ~might_and_guile/nubards/raelisadd.d~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~edion.sto~)THEN BEGIN
  COPY_EXISTING ~edion.sto~ ~override~
	ADD_STORE_ITEM ~d5bd05~ #1 #0 #0 ~identified~ #1
END

COPY ~might_and_guile/nubards/d5bd08.itm~ ~override~			//		mind shield
	SAY NAME2 @21081
	SAY IDENTIFIED_DESC @21082
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 177 parameter1 = %nu_bard_code% parameter2 = 9 STR_VAR resource = ~d5bd08a~ END
/*
	  PATCH_FOR_EACH nubard_kit IN ~%nu_blade_code%~ ~%jinxer_code%~ ~%herald_code%~ ~%nu_gallant_code%~ ~%hexblade_code%~ ~%nu_skald_code%~ BEGIN
		LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 177 parameter1 = %nubard_kit% parameter2 = 9 END
	  END
*/
CREATE EFF ~d5bd08a~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5bd08a~ #8
ACTION_IF FILE_EXISTS_IN_GAME ~pirmur01.cre~ BEGIN
  COPY_EXISTING ~pirmur01.cre~ ~override~
	ADD_CRE_ITEM ~d5bd08~ #1 #0 #0 ~IDENTIFIED~ ~INV~
END

COPY ~might_and_guile/nubards/d5bd24.itm~ ~override~			//		hold undead
	SAY NAME2 @21241
	SAY IDENTIFIED_DESC @21242
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 177 parameter1 = %nu_bard_code% parameter2 = 9 STR_VAR resource = ~d5bd24a~ END
/*
	  PATCH_FOR_EACH nubard_kit IN ~%nu_blade_code%~ ~%jinxer_code%~ ~%herald_code%~ ~%nu_gallant_code%~ ~%hexblade_code%~ ~%nu_skald_code%~ BEGIN
		LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 177 parameter1 = %nubard_kit% parameter2 = 9 END
	  END
*/
CREATE EFF ~d5bd24a~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5bd24a~ #8
ACTION_IF FILE_EXISTS_IN_GAME ~theshal.cre~ BEGIN
  COPY_EXISTING ~theshal.cre~ ~override~
	ADD_CRE_ITEM ~d5bd24~ #0 #0 #0 ~IDENTIFIED~ ~INV~
END
ACTION_IF (FILE_EXISTS_IN_GAME ~shlehlan.sto~)THEN BEGIN
  COPY_EXISTING ~shlehlan.sto~ ~override~
	ADD_STORE_ITEM ~d5bd24~ #1 #0 #0 ~identified~ #1
END

COPY ~might_and_guile/nubards/d5bd25.itm~ ~override~			//		entangle
	SAY NAME2 @21241
	SAY IDENTIFIED_DESC @21242
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 177 parameter1 = %nu_bard_code% parameter2 = 9 STR_VAR resource = ~d5bd25a~ END
/*
	  PATCH_FOR_EACH nubard_kit IN ~%nu_blade_code%~ ~%jinxer_code%~ ~%herald_code%~ ~%nu_gallant_code%~ ~%hexblade_code%~ ~%nu_skald_code%~ BEGIN
		LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 177 parameter1 = %nubard_kit% parameter2 = 9 END
	  END
*/
CREATE EFF ~d5bd25a~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5bd25a~ #8
ACTION_IF FILE_EXISTS_IN_GAME ~jugmim01.cre~ BEGIN
  COPY_EXISTING ~jugmim01.cre~ ~override~
	ADD_CRE_ITEM ~d5bd25~ #1 #0 #0 ~IDENTIFIED~ ~INV~
END

COPY ~might_and_guile/nubards/d5bd48.itm~ ~override~			//		dispel illusions
	SAY NAME2 @21481
	SAY IDENTIFIED_DESC @21482
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 177 parameter1 = %nu_bard_code% parameter2 = 9 STR_VAR resource = ~d5bd48a~ END
/*
	  PATCH_FOR_EACH nubard_kit IN ~%nu_blade_code%~ ~%jinxer_code%~ ~%herald_code%~ ~%nu_gallant_code%~ ~%hexblade_code%~ ~%nu_skald_code%~ BEGIN
		LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 177 parameter1 = %nubard_kit% parameter2 = 9 END
	  END
*/
CREATE EFF ~d5bd48a~
	WRITE_LONG 0x10 171
	WRITE_LONG 0x14 1
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5bd48a~ #8
ACTION_IF (FILE_EXISTS_IN_GAME ~stoblack.sto~)THEN BEGIN
  COPY_EXISTING ~stoblack.sto~ ~override~
	ADD_STORE_ITEM ~d5bd48~ #0 #0 #0 ~identified~ #1
END
//___________________________________________________________________________________


//ADD SUPPORT FOR FEAT SYSTEM________________________________________________________
//

ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  EXTEND_TOP ~d5_feat.bcs~ ~might_and_guile/nubards/d5_fbrd.baf~
  COMPILE ~might_and_guile/feats/dialog/d5fbard.d~ 
  COMPILE ~might_and_guile/feats/dialog/d5fblade.d~ 
  COMPILE ~might_and_guile/feats/dialog/d5fjstr.d~ 
  COMPILE ~might_and_guile/feats/dialog/d5fskld.d~ 
  COMPILE ~might_and_guile/feats/dialog/d5fglnt.d~ 
  COMPILE ~might_and_guile/feats/dialog/d5fhrld.d~ 
  COMPILE ~might_and_guile/feats/dialog/d5fmstr.d~ 
  COMPILE ~might_and_guile/feats/dialog/d5flors.d~ 
  COMPILE ~might_and_guile/feats/dialog/d5fjinx.d~ 

  APPEND ~d5_bard.2da~ ~D5FEATS     AP_D5FEAT1  ****        AP_D5FEAT2  ****        ****        AP_D5FEAT3  ****        ****        AP_D5FEAT4  ****        ****        AP_D5FEAT5  ****        ****        AP_D5FEAT6  ****        ****        AP_D5FEAT7  ****        ****        AP_D5FEAT8  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
//ABILITY     AP_D5IFEAT  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****         ****        ****        ****        ****        ****        ****  
  APPEND ~d5_blade.2da~ ~D5FEATS     ****        ****        AP_D5FEAT2  ****        ****        AP_D5FEAT3  ****        ****        AP_D5FEAT4  ****        ****        AP_D5FEAT5  ****        ****        AP_D5FEAT6  ****        ****        AP_D5FEAT7  ****        ****        AP_D5FEAT8  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
  APPEND ~d5_jstr.2da~ ~D5FEATS     ****        ****        AP_D5FEAT2  ****        ****        AP_D5FEAT3  ****        ****        AP_D5FEAT4  ****        ****        AP_D5FEAT5  ****        ****        AP_D5FEAT6  ****        ****        AP_D5FEAT7  ****        ****        AP_D5FEAT8  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
  APPEND ~d5_skld.2da~ ~D5FEATS     ****        ****        AP_D5FEAT2  ****        ****        AP_D5FEAT3  ****        ****        AP_D5FEAT4  ****        ****        AP_D5FEAT5  ****        ****        AP_D5FEAT6  ****        ****        AP_D5FEAT7  ****        ****        AP_D5FEAT8  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
  APPEND ~d5_glnt.2da~ ~D5FEATS     ****        ****        AP_D5FEAT2  ****        ****        AP_D5FEAT3  ****        ****        AP_D5FEAT4  ****        ****        AP_D5FEAT5  ****        ****        AP_D5FEAT6  ****        ****        AP_D5FEAT7  ****        ****        AP_D5FEAT8  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
  APPEND ~d5_hrld.2da~ ~D5FEATS     ****        ****        AP_D5FEAT2  ****        ****        AP_D5FEAT3  ****        ****        AP_D5FEAT4  ****        ****        AP_D5FEAT5  ****        ****        AP_D5FEAT6  ****        ****        AP_D5FEAT7  ****        ****        AP_D5FEAT8  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
  APPEND ~d5_mstr.2da~ ~D5FEATS     ****        ****        AP_D5FEAT2  ****        ****        AP_D5FEAT3  ****        ****        AP_D5FEAT4  ****        ****        AP_D5FEAT5  ****        ****        AP_D5FEAT6  ****        ****        AP_D5FEAT7  ****        ****        AP_D5FEAT8  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
  APPEND ~d5_jinx.2da~ ~D5FEATS     ****        ****        AP_D5FEAT2  ****        ****        AP_D5FEAT3  ****        ****        AP_D5FEAT4  ****        ****        AP_D5FEAT5  ****        ****        AP_D5FEAT6  ****        ****        AP_D5FEAT7  ****        ****        AP_D5FEAT8  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
  APPEND ~d5_lors.2da~ ~D5FEATS     ****        ****        AP_D5FEAT2  ****        ****        AP_D5FEAT3  ****        ****        AP_D5FEAT4  ****        ****        AP_D5FEAT5  ****        ****        AP_D5FEAT6  ****        ****        AP_D5FEAT7  ****        ****        AP_D5FEAT8  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  ACTION_FOR_EACH feat IN ~d5feata~ ~d5featb~ ~d5featc~ ~d5featd~ ~d5feate~ ~d5featf~ ~d5featg~ ~d5feath~ ~d5feati~ ~d5featj~ ~d5featk~ ~d5featl~ ~d5featm~ ~d5featn~ ~d5feato~ ~d5featp~ ~d5featq~ ~d5featr~ ~d5feats~ ~d5featt~ BEGIN
	COPY ~might_and_guile/feats/%feat%.spl~ ~override~
		SAY NAME1 @20099
		SAY UNIDENTIFIED_DESC @20100
		WRITE_ASCII 0x3a ~d5_feat~ #8
		LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_feat~ END
  END
  COPY ~might_and_guile/feats/d5_feat.bam~ ~override~
  COPY ~might_and_guile/feats/d5_feat.eff~ ~override~ 
  COPY ~might_and_guile/feats/d5_feat.cre~ ~override~ 
  COMPILE ~might_and_guile/nubards/d5_feat.baf~ 
  COMPILE ~might_and_guile/nubards/d5vbard.d~ 
  APPEND ~d5_bard.2da~ ~D5SONGS     ****        ****        GA_D5FEATD  ****        ****        GA_D5FEATE  ****        ****        GA_D5FEATF  ****        ****        GA_D5FEATG  ****        ****        GA_D5FEATH  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****       ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
//___________________________________________________________________________________


/*
//ARMORED CASTING FOR BARDS__________________________________________________________
//
// maybe do nothing. since they are thieves, they can't even wear heavy armor!

INCLUDE ~%MOD_FOLDER%/lib/d5_armored_casting/d5_armored_casting.tpa~

LAM D5_ARMORED_CASTING

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
	  READ_SHORT 0x1c type
	  READ_LONG 0x22 appearance
	  PATCH_IF (type = 2) BEGIN // armor
		PATCH_IF (appearance = 16690) BEGIN // leather appearance
		  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 177 parameter1 = 5 parameter2 = 5 timing = 2 STR_VAR resource = ~d5arca1~ END
		END
/*
		PATCH_IF (appearance = 16691) BEGIN // chain appearance
		  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 177 parameter1 = 5 parameter2 = 5 timing = 2 STR_VAR resource = ~d5arca2~ END
		END
		PATCH_IF (appearance = 16692) BEGIN // plate appearance
		  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 177 parameter1 = 5 parameter2 = 5 timing = 2 STR_VAR resource = ~d5arca3~ END
		END
*/
	  END
	END
BUT_ONLY
//___________________________________________________________________________________
*/


/*
//SPECIALIZATION FOR BARDS___________________________________________________________
// 
// probably omit this

ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ BEGIN

  COPY_EXISTING ~clswpbon.2da~ ~override~
	SET_2DA_ENTRY 7 1 1 1
	SET_2DA_ENTRY 42 1 1 1
	SET_2DA_ENTRY 43 1 1 1
	SET_2DA_ENTRY 44 1 1 1

  OUTER_SET bard_int_prof_1 = 13 		// min INT score for first level-1 weapon specialization
  OUTER_SET bard_int_prof_2 = 15 		// min INT score for second level-1 weapon specialization

  COPY ~might_and_guile/profs/d5_lswo.spl~ ~override~
  COPY ~might_and_guile/profs/d5_sswo.spl~ ~override~
  COPY ~might_and_guile/profs/d5_dagg.spl~ ~override~
  COPY ~might_and_guile/profs/d5_scim.spl~ ~override~
  COPY ~might_and_guile/profs/d5_2swo.spl~ ~override~
  COPY ~might_and_guile/profs/d5_spea.spl~ ~override~
  COPY ~might_and_guile/profs/d5_staf.spl~ ~override~
  COPY ~might_and_guile/profs/d5_club.spl~ ~override~
  COPY ~might_and_guile/profs/d5_flai.spl~ ~override~
  COPY ~might_and_guile/profs/d5_hamm.spl~ ~override~
  COPY ~might_and_guile/profs/d5_baxe.spl~ ~override~
  COPY ~might_and_guile/profs/d5_mace.spl~ ~override~
  COPY ~might_and_guile/profs/d5_bows.spl~ ~override~
  COPY ~might_and_guile/profs/d5_slin.spl~ ~override~
  COPY ~might_and_guile/profs/d5_xbow.spl~ ~override~

  COPY ~might_and_guile/profs/d5wepf1.spl~ ~override~
  COPY ~might_and_guile/profs/d5wepf1.eff~ ~override~
  COPY ~might_and_guile/profs/d5wepfa.spl~ ~override~
	SAY NAME1 @12300
	SAY UNIDENTIFIED_DESC @12300
	WRITE_ASCII 0x3a ~d5_wepfo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wepfo~ END
  COPY ~might_and_guile/profs/d5wepf2.spl~ ~override~
  COPY ~might_and_guile/profs/d5wepf2.eff~ ~override~
  COPY ~might_and_guile/profs/d5wepfb.spl~ ~override~
	SAY NAME1 @12300
	SAY UNIDENTIFIED_DESC @12300
	WRITE_ASCII 0x3a ~d5_wepfo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wepfo~ END
  COPY ~might_and_guile/profs/d5wepf3.spl~ ~override~
  COPY ~might_and_guile/profs/d5wepf3.eff~ ~override~
  COPY ~might_and_guile/profs/d5wepfc.spl~ ~override~
	SAY NAME1 @12300
	SAY UNIDENTIFIED_DESC @12300
	WRITE_ASCII 0x3a ~d5_wepfo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wepfo~ END
  COPY ~might_and_guile/profs/d5wepf4.spl~ ~override~
  COPY ~might_and_guile/profs/d5wepf4.eff~ ~override~
  COPY ~might_and_guile/profs/d5wepfd.spl~ ~override~
	SAY NAME1 @12300
	SAY UNIDENTIFIED_DESC @12300
	WRITE_ASCII 0x3a ~d5_wepfo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wepfo~ END
  COPY ~might_and_guile/profs/d5wepf5.spl~ ~override~
  COPY ~might_and_guile/profs/d5wepf5.eff~ ~override~
  COPY ~might_and_guile/profs/d5wepfe.spl~ ~override~
	SAY NAME1 @12300
	SAY UNIDENTIFIED_DESC @12300
	WRITE_ASCII 0x3a ~d5_wepfo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wepfo~ END
  COPY ~might_and_guile/profs/d5_wepfo.bam~ ~override~
  COPY ~might_and_guile/profs/d5_wepfo.eff~ ~override~
  COPY ~might_and_guile/profs/d5_wepfo.cre~ ~override~
  COMPILE ~might_and_guile/profs/d5_wepfo.baf~
  COMPILE ~might_and_guile/profs/d5_wepfo.d~

  ACTION_IF GAME_IS ~iwdee~ BEGIN
	COPY_EXISTING ~d5_wepfo.dlg~ ~override~
	  DECOMPILE_AND_PATCH BEGIN
		REPLACE_TEXTUALLY ~PROFICIENCYCLUB~ ~EXTRAPROFICIENCY1~
	  END
  END

  APPEND ~splprot.2da~ ~D5_INT_GTEQ%TAB%38%TAB%-1%TAB%4~

  COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	COUNT_2DA_ROWS cols rows // amount of rows
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
      READ_2DA_ENTRY_FORMER rows row 0 ~stat~ // read column value
      PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_INT_GTEQ~ BEGIN
    	SET int_gteq_row = %row%
      END
	END
  BUT_ONLY

  COPY ~might_and_guile/profs/d5iprf4.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 326 parameter1 = %bard_int_prof_1% parameter2 = %int_gteq_row% END
  COPY ~might_and_guile/profs/d5iprf5.spl~ ~override~
    LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 326 parameter1 = %bard_int_prof_2% parameter2 = %int_gteq_row% END

  ACTION_IF FILE_EXISTS_IN_GAME ~clabba01.2da~ BEGIN
	COPY_EXISTING ~clabba01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/nubards/bard_intprof.txt~
	BUT_ONLY
  END
  ACTION_IF FILE_EXISTS_IN_GAME ~clabba04.2da~ BEGIN
	COPY_EXISTING ~clabba04.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/nubards/skald_focus.txt~
	BUT_ONLY
  END

  COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 2 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_bard_profs BEGIN "%modclab%" => "%modclass%" END
	END
  BUT_ONLY
  ACTION_PHP_EACH d5_bard_profs AS hu => lu BEGIN
	ACTION_IF (%lu% = 5) AND (FILE_EXISTS_IN_GAME ~%hu%.2da~) BEGIN
		COPY_EXISTING ~%hu%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/nubards/bard_intprof.txt~
		BUT_ONLY
	END
  END
END
//___________________________________________________________________________________
*/


//ADD MORE BARD SPELLS_______________________________________________________________
//

// IWD Curse:
COPY_EXISTING - ~spell.ids~ ~might_and_guile/backup~
  COUNT_REGEXP_INSTANCES ~CLERIC_CURSE~ curse_exists
ACTION_IF NOT (curse_exists) BEGIN
  COPY ~might_and_guile/nubards/d5curse.spl~ ~override~
	SAY NAME1 @21903
	SAY UNIDENTIFIED_DESC @21904
	WRITE_ASCII 0x3a ~SPPR112C~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~SPPR112B~ END
  COPY ~might_and_guile/nubards/sppr112c.bam~ ~override~
  COPY ~might_and_guile/nubards/sppr112b.bam~ ~override~
  ADD_SPELL ~override/d5curse.spl~ 4 3 CLERIC_CURSE
END

ADD_PROJECTILE ~might_and_guile/nubards/d5shout.pro~

// IWD Shout:
COPY_EXISTING - ~spell.ids~ ~might_and_guile/backup~
  COUNT_REGEXP_INSTANCES ~WIZARD_SHOUT~ shout_exists
ACTION_IF NOT (shout_exists) BEGIN
  COPY ~might_and_guile/nubards/d5shout.spl~ ~override~
	SAY NAME1 @21905
	SAY UNIDENTIFIED_DESC @21906
	WRITE_ASCII 0x3a ~SPWI431C~ #8
	LPF ALTER_SPELL_HEADER INT_VAR projectile = %d5shout% STR_VAR icon = ~SPWI431B~ END
  COPY ~might_and_guile/nubards/#tra_08.wav~ ~override~
  COPY ~might_and_guile/nubards/spwi431c.bam~ ~override~
  COPY ~might_and_guile/nubards/spwi431b.bam~ ~override~

  ADD_SPELL ~override/d5shout.spl~ 4 3 WIZARD_SHOUT
END

// IWD Great Shout:
COPY_EXISTING - ~spell.ids~ ~might_and_guile/backup~
  COUNT_REGEXP_INSTANCES ~WIZARD_GREAT_SHOUT~ great_shout_exists
ACTION_IF NOT (great_shout_exists) BEGIN
  COPY ~might_and_guile/nubards/d5gshou.spl~ ~override~
	SAY NAME1 @21905
	SAY UNIDENTIFIED_DESC @21906
	WRITE_ASCII 0x3a ~SPWI806C~ #8
	LPF ALTER_SPELL_HEADER INT_VAR projectile = %d5shout% STR_VAR icon = ~SPWI806B~ END
  COPY ~might_and_guile/nubards/#tra_08.wav~ ~override~
  COPY ~might_and_guile/nubards/spwi806c.bam~ ~override~
  COPY ~might_and_guile/nubards/spwi806b.bam~ ~override~
  ADD_SPELL ~override/d5gshou.spl~ 4 7 WIZARD_GREAT_SHOUT
END

/* add_spell this and give it to true bards in place of Vocalize
// Declamation (targetable Vocalize):
COPY ~might_and_guile/nubards/d5bdvoc.spl~ ~override~
	SAY NAME1 @21901
	SAY UNIDENTIFIED_DESC @21902
*/

//___________________________________________________________________________________


//SR ANIMAL SUMMONING________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN 	// Spell Revisions
  ACTION_DEFINE_ASSOCIATIVE_ARRAY sr_ids BEGIN
	1120 => CLERIC_ANIMAL_SUMMONING_SR_LEVEL_1
	1220 => CLERIC_ANIMAL_SUMMONING_SR_LEVEL_2
	1320 => CLERIC_ANIMAL_SUMMONING_SR_LEVEL_3
  END
  ACTION_PHP_EACH sr_ids AS key=>value BEGIN
	APPEND "spell.ids" "%key% %value%" UNLESS "%key% +%value%"  
  END
END
//___________________________________________________________________________________


// SPONTANEOUS CASTING________________________________________________________________
//
// need to ...change the filenames where appropriate (but also, leave the same where appropriate)

//INCLUDE ~might_and_guile/nubards/nubard_kit_arrays.tpa~

//COPY_EXISTING ~might_and_guile/nubards/d5_bard.2da~ ~override/d5brdspl.2da~
<<<<<<<< d5/d5brdthf.2da

BARDSPLS    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 

>>>>>>>> 
COPY ~d5/d5brdthf.2da~ ~override/d5brdthf.2da~

//add spell slot stat checks to SPLPROT_______________________________________________
//
APPEND ~splprot.2da~ ~D5_SLOTS_1_4%TAB%106%TAB%-1%TAB%7~
  UNLESS ~D5_SLOTS_1_4~
APPEND ~splprot.2da~ ~D5_SLOTS_5_9%TAB%107%TAB%-1%TAB%7~
  UNLESS ~D5_SLOTS_5_9~
APPEND ~splprot.2da~ ~D5_FATIGUE_IS%TAB%30%TAB%-1%TAB%1~
  UNLESS ~D5_FATIGUE_IS~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS_1_4~ BEGIN
	  SET fake_sorc_slots_1_4 = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS_5_9~ BEGIN
	  SET fake_sorc_slots_5_9 = %row%
	END
	PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_IS~ BEGIN
	  SET fatigue_value = %row%
	END
  END
BUT_ONLY


//create advance copies of some spells________________________________________________
//
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5b206.spl~

COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot1a.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot1b.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot1c.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot1d.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot2a.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot2b.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot2c.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot2d.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot3a.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot3b.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot3c.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot3d.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot4a.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot4b.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot4c.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot4d.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot5a.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot5b.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot5c.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot5d.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot6a.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot6b.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot6c.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot6d.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot7a.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot7b.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot7c.spl~
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blot7d.spl~

COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5bsplz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot1a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot1b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot1c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot1d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot2a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot2b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot2c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot2d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot3a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot3b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot3c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot3d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 28) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot4a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 28) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot4b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 28) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot4c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 28) parameter2 = %fake_sorc_slots_1_4% timing = 1 STR_VAR resource = ~d5blot4d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 8) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot5a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 8) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot5b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 8) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot5c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 8) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot5d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 12) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot6a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 12) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot6b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 12) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot6c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 12) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot6d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot7a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot7b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot7c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_sorc_slots_5_9% timing = 1 STR_VAR resource = ~d5blot7d~ END


//assign stats for spell slots to each spell level____________________________________
//
// level 1 = (106 << 16)
// level 2 = (106 << 20)
// level 3 = (106 << 24)
// level 4 = (106 << 28)
// level 5 = (107 << 8)
// level 6 = (107 << 12)
// level 7 = (107 << 16)
// [ level 8 = (107 << 20) ]
// [ level 9 = (107 << 24) ]
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src1.spl~ BEGIN
  COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src1.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (106 + (0x10000 * 1)) timing = 9 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src2.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src2.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (106 + (0x10000 * 1)) timing = 9 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src3.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src3.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (106 + (0x10000 * 1)) timing = 9 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src4.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src4.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (106 + (0x10000 * 1)) timing = 9 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src5.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src5.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (107 + (0x10000 * 1)) timing = 9 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src6.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src6.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (107 + (0x10000 * 1)) timing = 9 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src7.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src7.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (107 + (0x10000 * 1)) timing = 9 END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-1.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src-1.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (106 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-2.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src-2.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (106 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-3.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src-3.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (106 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-4.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src-4.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 28) parameter2 = (106 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-5.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src-5.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (107 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-6.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src-6.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (107 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-7.spl~ BEGIN
 COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5src-7.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (107 + (0x10000 * 1)) timing = 1 END
END

//add spell slots_____________________________________________________________________
//
APPEND ~d5brdthf.2da~ ~SRCSLOTS    ****        AP_D5SRC1   AP_D5SRC1   AP_D5SRC2   AP_D5SRC1   AP_D5SRC2   AP_D5SRC3   AP_D5SRC2   AP_D5SRC3   AP_D5SRC4   AP_D5SRC3   AP_D5SRC4   AP_D5SRC5   AP_D5SRC4   AP_D5SRC5   AP_D5SRC6   AP_D5SRC5   AP_D5SRC6   AP_D5SRC7   AP_D5SRC6   AP_D5SRC7   AP_D5SRC2   AP_D5SRC3   AP_D5SRC6   AP_D5SRC4   AP_D5SRC7   AP_D5SRC5   AP_D5SRC6   AP_D5SRC7   AP_D5SRC7   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
SRCSLOTS    ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        AP_D5SRC1   AP_D5SRC2   AP_D5SRC3   AP_D5SRC4   AP_D5SRC5   AP_D5SRC1   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
SRCSLOTX    ****        AP_D5SRC1   ****        ****        AP_D5SRC2   ****        ****        AP_D5SRC3   ****        ****        AP_D5SRC4   ****        ****        AP_D5SRC5   ****        ****        AP_D5SRC6   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** 
~


//make spell selection dialogue_______________________________________________________
//... adapted from aquadrizzt's spell knowledge dialogue
//
COPY ~might_and_guile/nubards/d5sbrdkn.2da~ ~override~ //save a copy of bard known spell progression 

COPY ~might_and_guile/nubards/d5mbard.cre~ ~override~ 
			WRITE_ASCII 0x248 ~d5mbard~ #8
//			WRITE_ASCII 0x2cc ~d5mbard~ #8

COPY ~might_and_guile/nubards/d5mbard.spl~ ~override~
			SAY NAME1 @21921 // ~Spell Knowledge~
			SAY UNIDENTIFIED_DESC @21921
			LPF ALTER_SPELL_EFFECT INT_VAR match_opcode = 67 STR_VAR resource = ~d5mbard~ END 

COMPILE ~might_and_guile/nubards/d5mbard.baf~
//COPY 	~might_and_guile/nubards/d5mbard.d~ ~override~ //easy to access copy of .d file to update

//level spells known snippet
<<<<<<<< d5/brd_spells_known.baf
	IF
		Level(LastSummonerOf(Myself),%lvl%)
	THEN	
		RESPONSE #100 
			SetGlobal("d5_brd_max_1","GLOBAL",%first%)
			SetGlobal("d5_brd_max_2","GLOBAL",%second%)
			SetGlobal("d5_brd_max_3","GLOBAL",%third%)
			SetGlobal("d5_brd_max_4","GLOBAL",%fourth%)
			SetGlobal("d5_brd_max_5","GLOBAL",%fifth%)
			SetGlobal("d5_brd_max_6","GLOBAL",%sixth%)
			SetGlobal("d5_brd_max_7","GLOBAL",%seventh%)
			Continue() 
	END 
>>>>>>>>
//level spells known ([second to] last defined level) snippet
<<<<<<<< d5/brd_spells_known_max.baf
	IF
		OR(2)
		Level(LastSummonerOf(Myself),%lvl%)
		LevelGT(LastSummonerOf(Myself),%lvl%)
	THEN	
		RESPONSE #100 
			SetGlobal("d5_brd_max_1","GLOBAL",%first%)
			SetGlobal("d5_brd_max_2","GLOBAL",%second%)
			SetGlobal("d5_brd_max_3","GLOBAL",%third%)
			SetGlobal("d5_brd_max_4","GLOBAL",%fourth%)
			SetGlobal("d5_brd_max_5","GLOBAL",%fifth%)
			SetGlobal("d5_brd_max_6","GLOBAL",%sixth%)
			SetGlobal("d5_brd_max_7","GLOBAL",%seventh%)
			Continue() 
	END 
>>>>>>>>

COPY_EXISTING ~d5sbrdkn.2da~ ~override~ 
	COUNT_2DA_COLS num_cols
//	COUNT_2DA_ROWS num_cols num_rows
	READ_2DA_ENTRIES_NOW ~r2en_sor_spl_kwn~ num_cols
	FOR (row = 0; row < r2en_sor_spl_kwn; row += 1) BEGIN
		READ_2DA_ENTRY_FORMER ~r2en_sor_spl_kwn~ row 1 first
		READ_2DA_ENTRY_FORMER ~r2en_sor_spl_kwn~ row 2 second
		READ_2DA_ENTRY_FORMER ~r2en_sor_spl_kwn~ row 3 third
		READ_2DA_ENTRY_FORMER ~r2en_sor_spl_kwn~ row 4 fourth
		READ_2DA_ENTRY_FORMER ~r2en_sor_spl_kwn~ row 5 fifth
		READ_2DA_ENTRY_FORMER ~r2en_sor_spl_kwn~ row 6 sixth
		READ_2DA_ENTRY_FORMER ~r2en_sor_spl_kwn~ row 7 seventh
		INNER_ACTION BEGIN 
			ACTION_IF (row = %r2en_sor_spl_kwn%-1) THEN BEGIN 
				EXTEND_BOTTOM ~d5mbard.bcs~ ~d5/brd_spells_known_max.baf~ 
					lvl = (%row% + 1)
					EVAL 
			END 
			ELSE BEGIN 
				EXTEND_BOTTOM ~d5mbard.bcs~ ~d5/brd_spells_known.baf~ 
					lvl = (%row% + 1)
					EVAL 
			END 
		END 
	END 
BUT_ONLY	

//script spell check snippet
<<<<<<<< d5/script_add_spell_check.baf
	IF
		NextTriggerObject(LastSummonerOf(Myself)) 
		Global("%real_spell%","LOCALS",1)
	THEN	
		RESPONSE #100 
			IncrementGlobal("%cur_lvl%","GLOBAL",1)
			Continue() 
	END 
>>>>>>>>
//script initiate dialog snippet
<<<<<<<< d5/script_spells_end.baf
	IF
		Kit(LastSummonerOf(Myself),"%kitids_name%")
	THEN
		RESPONSE #100
//			ActionOverride(LastSummonerOf(Myself),StartDialogOverride("kit_2da",Myself)) // use this if/when switch to LOCALS
			StartDialog("%kit_2da%",LastSummonerOf(Myself))
	END
>>>>>>>>
//dialog spell details snippet
<<<<<<<< d5/dialog_spell_info.d
	IF ~~ %real_spell% 
		SAY ~%spell_description%~ 
			++ @21923 DO ~ActionOverride(LastSummonerOf(Myself),ApplySpellRES("%learn_spell%",Myself)) ActionOverride(LastSummonerOf(Myself),IncrementGlobal("%real_spell%","LOCALS",1) ActionOverride(LastSummonerOf(Myself),Rest()) IncrementGlobal("%cur_lvl%","GLOBAL",1) SmallWait(1)~ + refresh
			++ @21924 + %lvl_menu%
			++ @21925 + main_menu
			++ @21926 + end
	END 
>>>>>>>>


//clone spells________________________________________________________________________
//

<<<<<<<< d5/d5bclons.2da
2DA V1.0 
SPLRES
		206		LEARN	EFF		INNATE	LOCAL
>>>>>>>> 

COPY ~d5/d5bclons.2da~ ~override/d5bclons.2da~ 


COPY ~might_and_guile/nubards/d5brdspl.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (col = 2; col < cols; ++col) BEGIN
	READ_2DA_ENTRY_FORMER rows 0 col ~kit_2da~
	INNER_ACTION BEGIN
	  COPY ~might_and_guile/nubards/d5mbard.d~ ~override/%kit_2da%.d~
		REPLACE_TEXTUALLY ~BEGIN D5MBARD~ ~BEGIN %kit_2da%~
	END
  END
COPY ~might_and_guile/nubards/d5brdspl.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~spont_spell~
	READ_2DA_ENTRY_FORMER rows row 1 ~spont_spell_level~
	PATCH_IF (IDS_OF_SYMBOL ("spell" "%spont_spell%") > 0) BEGIN
	  LPF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = EVAL ~%spont_spell%~ RET spell_res END
	  PATCH_IF FILE_EXISTS_IN_GAME ~%spell_res%.spl~ BEGIN
		INNER_ACTION BEGIN
		  COPY_EXISTING ~%spell_res%.spl~ ~override~
			READ_STRREF NAME1 spell_name
			READ_STRREF UNIDENTIFIED_DESC spell_description
			SET spell_level = %spont_spell_level%
			SNPRINT (0 - 3) spell_num ~%spell_res%~
			PATCH_IF (~%spell_res%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Ww][Ii][1-9][0-9][0-9]~ = 0) BEGIN
			  INNER_PATCH_SAVE 206_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5b6~
			  END
			  INNER_PATCH_SAVE learn_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5bx~
			  END
			  INNER_PATCH_SAVE spell_eff ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~D5BV~
			  END
			  INNER_PATCH_SAVE innate_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5b4~
			  END
			END
			PATCH_IF (~%spell_res%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Pp][Rr][1-9][0-9][0-9]~ = 0) BEGIN
			  INNER_PATCH_SAVE 206_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Pp][Rr]~ ~d5d6~
			  END
			  INNER_PATCH_SAVE learn_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Pp][Rr]~ ~d5dx~
			  END
			  INNER_PATCH_SAVE spell_eff ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Pp][Rr]~ ~D5DV~
			  END
			  INNER_PATCH_SAVE innate_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Pp][Rr]~ ~d5d4~
			  END
			END
			PATCH_IF (~%spell_res%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Ii][Nn][1-9][0-9][0-9]~ = 0) BEGIN
			  INNER_PATCH_SAVE 206_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Ii][Nn]~ ~d5i6~
			  END
			  INNER_PATCH_SAVE learn_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Ii][Nn]~ ~d5ix~
			  END
			  INNER_PATCH_SAVE spell_eff ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Ii][Nn]~ ~D5IV~
			  END
			  INNER_PATCH_SAVE innate_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Ii][Nn]~ ~d5i4~
			  END
			END
			PATCH_IF (~%spell_res%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Cc][Ll][1-9][0-9][0-9]~ = 0) BEGIN
			  INNER_PATCH_SAVE 206_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~d5c6~
			  END
			  INNER_PATCH_SAVE learn_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~d5cx~
			  END
			  INNER_PATCH_SAVE spell_eff ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~D5CV~
			  END
			  INNER_PATCH_SAVE innate_spell ~%spell_res%~ BEGIN
				REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~d5c4~
			  END
			END
			TEXT_SPRINT real_spell ~%spell_res%~
		  BUT_ONLY
		  ACTION_IF NOT (FILE_CONTAINS_EVALUATED (~d5bclons.2da~ ~%spell_res%~)) BEGIN
			APPEND ~d5bclons.2da~ ~%spell_res%	%206_spell%	%learn_spell%	%spell_eff%	%innate_spell%	%real_spell% ~
		  END
// make innates with cloned spell effects
		  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%innate_spell%.spl~ BEGIN
			COPY_EXISTING ~%SOURCE_RES%.spl~ ~override/%innate_spell%.spl~
			  WRITE_SHORT 0x1c 4
			  LPF ALTER_SPELL_HEADER INT_VAR location = 4 END
// ***** exempt lvl 1 if lv1 1 cantrips
			  PATCH_IF MOD_IS_INSTALLED ~tomeandblood.tp2~ ~142~ BEGIN
			   PATCH_IF NOT (%spell_level%) = 1 BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5src-%spell_level%~ END
			   END
			  END
			  PATCH_IF NOT MOD_IS_INSTALLED ~tomeandblood.tp2~ ~142~ BEGIN
				LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5src-%spell_level%~ END
			  END
			  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  END
// make .EFFs adding the innate spell
		  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%spell_eff%.eff~ BEGIN
			CREATE EFF ~%spell_eff%~
			 WRITE_LONG 0x10 171
			 WRITE_LONG 0x14 1
			 WRITE_LONG 0x24 0
			 WRITE_LONG 0x28 1
			 WRITE_SHORT 0x2c 100
			 WRITE_EVALUATED_ASCII 0x30 ~%innate_spell%~ #8
			 WRITE_LONG 0x90 1
			 WRITE_EVALUATED_ASCII 0x94 ~%spell_eff%~ #8
		  END
// make 206 spells preventing the .EFF
		  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%206_spell%.spl~ BEGIN
			COPY ~might_and_guile/lib/d5_base.spl~ ~override/%206_spell%.spl~
			 WRITE_SHORT 0x1c 4
		  	 LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  END
// add 206 spells to CLAB spell
		  COPY_EXISTING ~d5b206.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
// make learn spells canceling the 206
		  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%learn_spell%.spl~ BEGIN
			COPY ~might_and_guile/lib/d5_base.spl~ ~override/%learn_spell%.spl~
		  	 LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
			 LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
//		  	 LPF ADD_SPELL_EFFECT INT_VAR opcode = 309 target = 1 parameter1 = 1 parameter2 = 0 timing = 9 STR_VAR resource = EVAL ~%real_spell%~ END
		  	 LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  END
// add 172 to d5bsplz
		  COPY_EXISTING ~d5bsplz.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
// generate slot#x spells
		  COPY_EXISTING ~d5blot%spell_level%a.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  COPY_EXISTING ~d5blot%spell_level%b.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  COPY_EXISTING ~d5blot%spell_level%c.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  COPY_EXISTING ~d5blot%spell_level%d.spl~ ~override~
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
// put dialogue together
		  EXTEND_BOTTOM ~d5mbard.bcs~ ~d5/script_add_spell_check.baf~ 
			SPRINT spl ~%real_spell%~ 
			SPRINT cur_lvl ~d5_brd_cur_~^~%spell_level%~
			EVAL 
		END // end inner_action
	  END
	END
  END
COPY ~might_and_guile/nubards/d5brdspl.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (col = 2; col < cols; ++col) BEGIN
	READ_2DA_ENTRY_FORMER rows 0 col ~kit_2da~
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~spont_spell~
	  READ_2DA_ENTRY_FORMER rows row 1 ~spell_level~
	  READ_2DA_ENTRY_FORMER rows row col ~value~
	  PATCH_IF (value = 1) BEGIN
		PATCH_IF (IDS_OF_SYMBOL ("spell" "%spont_spell%") > 0) BEGIN
		  LPF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = EVAL ~%spont_spell%~ RET spell_res END
		  PATCH_IF FILE_EXISTS_IN_GAME ~%spell_res%.spl~ BEGIN
			INNER_ACTION BEGIN
			  COPY_EXISTING ~%spell_res%.spl~ ~override~
				READ_STRREF NAME1 spell_name
				READ_STRREF UNIDENTIFIED_DESC spell_description
				SNPRINT (0 - 3) spell_num ~%spell_res%~
				TEXT_SPRINT real_spell ~%spell_res%~
			  COPY_EXISTING ~override/%kit_2da%.d~ ~override~
				SPRINT name "%spell_name%"
				SPRINT desc "%spell_description%"
				SPRINT cur_lvl ~d5_brd_cur_%spell_level%~
				SPRINT spl "%spell_res%"
				SPRINT lvl "%spell_level%"
				SPRINT lvl_menu ~level_%spell_level%~
				PATCH_IF (~%spell_res%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Ww][Ii][1-9][0-9][0-9]~ = 0) BEGIN
				  INNER_PATCH_SAVE 206_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5b6~
				  END
				  INNER_PATCH_SAVE learn_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5bx~
				  END
				  INNER_PATCH_SAVE spell_eff ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~D5BV~
				  END
				  INNER_PATCH_SAVE innate_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5b4~
				  END
				END
				PATCH_IF (~%spell_res%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Pp][Rr][1-9][0-9][0-9]~ = 0) BEGIN
				  INNER_PATCH_SAVE 206_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Pp][Rr]~ ~d5d6~
				  END
				  INNER_PATCH_SAVE learn_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Pp][Rr]~ ~d5dx~
				  END
				  INNER_PATCH_SAVE spell_eff ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Pp][Rr]~ ~D5DV~
				  END
				  INNER_PATCH_SAVE innate_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Pp][Rr]~ ~d5d4~
				  END
				END
				PATCH_IF (~%spell_res%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Ii][Nn][1-9][0-9][0-9]~ = 0) BEGIN
				  INNER_PATCH_SAVE 206_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Ii][Nn]~ ~d5i6~
				  END
				  INNER_PATCH_SAVE learn_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Ii][Nn]~ ~d5ix~
				  END
				  INNER_PATCH_SAVE spell_eff ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Ii][Nn]~ ~D5IV~
				  END
				  INNER_PATCH_SAVE innate_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Ii][Nn]~ ~d5i4~
				  END
				END
				PATCH_IF (~%spell_res%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Cc][Ll][1-9][0-9][0-9]~ = 0) BEGIN
				  INNER_PATCH_SAVE 206_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~d5c6~
				  END
				  INNER_PATCH_SAVE learn_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~d5cx~
				  END
				  INNER_PATCH_SAVE spell_eff ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~D5CV~
				  END
				  INNER_PATCH_SAVE innate_spell ~%spell_res%~ BEGIN
					REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~d5c4~
				  END
				END
				APPEND_FILE_EVALUATE  ~d5/dialog_spell_info.d~ 
				REPLACE_TEXTUALLY ~//Marker %lvl%~ ~~~~~+ ~NextTriggerObject(LastSummonerOf(Myself)) !Global("%real_spell%","LOCALS",1)~ +~%spell_name%~ + %real_spell% 
										//Marker %lvl%~~~~~
			END // end inner_action
		  END
		END
	  END
	END
  END


//finish spell learning dialogues______________________________________________________
//
COPY ~might_and_guile/nubards/d5brdspl.2da~ ~override~
  COUNT_2DA_COLS cols
  FOR (col = 2; col < cols; ++col) BEGIN
	READ_2DA_ENTRY 0 col cols ~kit_2da~
	INNER_ACTION BEGIN
	  COPY_EXISTING ~kitlist.2da~ ~override~
//		COUNT_2DA_COLS cols 
		READ_2DA_ENTRIES_NOW rows 10 
		FOR (row = 1; row < rows; ++row) BEGIN 
	      READ_2DA_ENTRY_FORMER rows row 5 ~kitlist_2da~ 
	      READ_2DA_ENTRY_FORMER rows row 1 ~kitids_name~ 
	      PATCH_IF (~%kitlist_2da%~ STRING_EQUAL_CASE ~%kit_2da%~) BEGIN
			INNER_ACTION BEGIN
			  EXTEND_BOTTOM ~d5mbard.bcs~ ~d5/script_spells_end.baf~ EVAL 
			END
	      END
	    END
	  BUT_ONLY
//	  EXTEND_BOTTOM ~d5mbard.bcs~ ~d5/script_spells_end.baf~ EVAL 
	END
  END
BUT_ONLY

COPY ~might_and_guile/nubards/d5brdspl.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (col = 2; col < cols; ++col) BEGIN
	READ_2DA_ENTRY_FORMER rows 0 col ~kit_2da~
	INNER_ACTION BEGIN
	  PRINT ~Compiling %kit_2da%.d~
	  COMPILE ~override/%kit_2da%.d~
	END
  END
BUT_ONLY

APPEND ~d5brdthf.2da~ ~LEARNSPLS   GA_D5MBARD  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~


//apply EFF protections_______________________________________________________________
//
APPEND ~d5brdthf.2da~ ~NO_WSPLS    AP_D5B206   ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~


//daily spell slot refresh____________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5slotz.spl~ BEGIN
  COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blotz.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5blots~ END
END
APPEND ~d5brdthf.2da~ ~SPLSLOTS    AP_D5BLOTZ  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5blots.eff~ BEGIN
  CREATE EFF ~d5blots~
	WRITE_LONG 0x10 232
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 0
	WRITE_LONG 0x20 20
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5blots~ #8
	WRITE_LONG 0x48 102
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5blots.spl~ BEGIN
  COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5blots.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_value% timing = 1 STR_VAR resource = ~d5brfrsh~ END
END


// spell to refresh spell slots_______________________________________________________
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5brfrsh.spl~ BEGIN
  COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5brfrsh.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-4~ END
  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
END


//manually create versions of sequencer/contingency___________________________________
//


//metamagic scrolls___________________________________________________________________
// ...make sequencer/contingency scrolls unusable by bards
//
COPY ~might_and_guile/nubards/d5brdspl.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (col = 2; col < cols; ++col) BEGIN
	READ_2DA_ENTRY_FORMER rows 0 col ~kit_2da~
	INNER_ACTION BEGIN
	  ACTION_FOR_EACH meta_scroll IN ~scrl6p~ ~scrl8l~ ~scrl9d~ ~scrl7u~ ~scrl9q~ BEGIN
		ACTION_IF FILE_EXISTS_IN_GAME ~%meta_scroll%.itm~ BEGIN
		  COPY_EXISTING ~kitlist.2da~ ~override~
//			COUNT_2DA_COLS cols 
			READ_2DA_ENTRIES_NOW rows 10
			FOR (row = 1; row < rows; ++row) BEGIN 
		      READ_2DA_ENTRY_FORMER rows row 5 ~kitlist_2da~ 
		      PATCH_IF (~%kitlist_2da%~ STRING_EQUAL_CASE ~%kit_2da%~) BEGIN
		    	READ_2DA_ENTRY_FORMER rows row 9 kitids_code
		      END
		    END
		  BUT_ONLY
		  COPY_EXISTING ~%meta_scroll%.itm~ ~override~
			LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %kitids_code% parameter2 = 9 power = 0 timing = 2 END
		END
	  END
	END
  END
BUT_ONLY

ACTION_FOR_EACH meta_scroll IN ~scrl6p~ ~scrl8l~ ~scrl9d~ ~scrl7u~ ~scrl9q~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%meta_scroll%.itm~ BEGIN
	COPY_EXISTING ~%meta_scroll%.itm~ ~override~
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 319 parameter1 = %nu_bard_code% parameter2 = 9 power = 0 timing = 2 END
// et al.
  END
END


//immunity to backstab bonus__________________________________________________________
//
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5nbstb.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 101 target = 1 parameter2 = 263 END
APPEND ~d5brdthf.2da~ ~NO_BSTAB    AP_D5NBSTB  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~


//append spontaneous to CLAB tables___________________________________________________
//
COPY_EXISTING ~d5_bard.2da~ ~override~
			  ~d5_blade.2da~ ~override~
			  ~d5_jstr.2da~ ~override~
			  ~d5_skld.2da~ ~override~
			  ~d5_glnt.2da~ ~override~
			  ~d5_hrld.2da~ ~override~
			  ~d5_mstr.2da~ ~override~
			  ~d5_jinx.2da~ ~override~
			  ~d5_lors.2da~ ~override~
// ***** et al.
  APPEND_FILE ~override/d5brdthf.2da~


//remove one slot from Blade etc.____________________________________________________
//
// ***** blade, herald, jinxer

COPY_EXISTING ~d5_blade.2da~ ~override~
			  ~d5_hrld.2da~ ~override~
			  ~d5_jinx.2da~ ~override~
	READ_2DA_ENTRIES_NOW rows 2
	SET rows_removed = 0
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 line
	  PATCH_IF (~%line%~ STRING_EQUAL_CASE ~SRCSLOTX~) BEGIN
		REMOVE_2DA_ROW (row - rows_removed) cols
		SET rows_removed += 1
	  END
	END
BUT_ONLY


//base known spells for SOME bards____________________________________________________
//
LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~WIZARD_SHOUT~ RET spell_res END
OUTER_SPRINT shout_res ~%spell_res%~
//OUTER_SPRINT shout_num ~%spell_num%~
//OUTER_SNPRINT 1 shout_type ~%shout_num%~
OUTER_INNER_PATCH_SAVE 206_shout ~%shout_res%~ BEGIN
  REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~d5c6~
  REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5b6~
END
  LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~WIZARD_GREAT_SHOUT~ RET spell_res END
OUTER_SPRINT great_shout_res spell_res
OUTER_INNER_PATCH_SAVE 206_great_shout ~%great_shout_res%~ BEGIN
  REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~d5c6~
  REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5b6~
END
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5brdz1.spl~
// ... get RES of wizard_shout and wizard_great_shout
  PATCH_FOR_EACH 206_spell IN ~d5b6219~ ~d5b6223~ ~%206_shout%~ ~d5b6419~ ~d5d6512~ ~d5b6612~ ~%206_great_shout%~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
  END
APPEND ~d5_bard.2da~ ~BARDSPLS    AP_D5BRDZ1  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

// *****
// ... do this for meistersinger too - animal summoning spells
COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5meiz1.spl~
  PATCH_FOR_EACH 206_spell IN ~d5d6402~ ~d5d6501~ ~d5d6602~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
  END

ACTION_IF FILE_EXISTS_IN_GAME ~dvsrv4here.mrk~ BEGIN
 COPY_EXISTING ~might_and_guile/lib/d5_base.spl~ ~override/d5meiz1.spl~
  PATCH_FOR_EACH 206_spell IN ~d5d6120~ ~d5d6220~ ~d5d6320~ BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
  END  
END
APPEND ~d5_mstr.2da~ ~BARDSPLS    AP_D5MEIZ1  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

// *****
// ... and curse/doom/malison for jinxer
LAF RES_NUM_OF_SPELL_NAME STR_VAR spell_name = ~CLERIC_CURSE~ RET spell_res END
OUTER_SPRINT curse_res spell_res
OUTER_INNER_PATCH_SAVE 206_curse ~%curse_res%~ BEGIN
  REPLACE_TEXTUALLY ~[Ss][Pp][Cc][Ll]~ ~d5c6~
  REPLACE_TEXTUALLY ~[Ss][Pp][Pp][Rr]~ ~d5d6~
END

COPY ~might_and_guile/lib/d5_base.spl~ ~override/d5jnxz1.spl~
  PATCH_FOR_EACH 206_spell IN ~d5d6113~ ~%206_curse%~ ~d5d6307~ ~d5b6412~  BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
  END
  
APPEND ~d5_jinx.2da~ ~BARDSPLS    AP_D5JNXZ1  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
//____________________________________________________________________________________


//HLA TABLES__________________________________________________________________________
//
//***** give extra feats as HLAs (up to ... 5?)
//
// ...make bard HLAs available to these thief kits
//
// add vocalize aura
COPY ~might_and_guile/nubards/d5nosil.spl~ ~override~
  SAY NAME1 @21998
  SAY UNIDENTIFIED_DESC @21999
COPY ~might_and_guile/nubards/d5nosil.eff~ ~override~
COPY ~might_and_guile/nubards/d5nosila.spl~ ~override~

COPY_EXISTING ~d5src1.spl~ ~override/d5brds1.spl~
  SAY NAME1 @21991
  SAY UNIDENTIFIED_DESC @21991
COPY_EXISTING ~d5src2.spl~ ~override/d5brds2.spl~
  SAY NAME1 @21992
  SAY UNIDENTIFIED_DESC @21992
COPY_EXISTING ~d5src3.spl~ ~override/d5brds3.spl~
  SAY NAME1 @21993
  SAY UNIDENTIFIED_DESC @21993
COPY_EXISTING ~d5src4.spl~ ~override/d5brds4.spl~
  SAY NAME1 @21994
  SAY UNIDENTIFIED_DESC @21994
COPY_EXISTING ~d5src5.spl~ ~override/d5brds5.spl~
  SAY NAME1 @21995
  SAY UNIDENTIFIED_DESC @21995
COPY_EXISTING ~d5src6.spl~ ~override/d5brds6.spl~
  SAY NAME1 @21996
  SAY UNIDENTIFIED_DESC @21996
COPY_EXISTING ~d5src7.spl~ ~override/d5brds7.spl~
  SAY NAME1 @21997
  SAY UNIDENTIFIED_DESC @21997

LAF action_add_hla STR_VAR kit_name = ~D5_BLADE~ ability = ~GA_SPCL900~ num_allowed = ~2~ END			//	whirlwind
LAF action_add_hla STR_VAR kit_name = ~D5_BLADE~ ability = ~GA_SPCL423~ num_allowed = ~2~ END			//	poison weapon
LAF action_remove_hla STR_VAR kit_name = ~D5_BLADE~ remove_ability = ~GA_SPCL905~ END					//	no critical strike
LAF action_remove_hla STR_VAR kit_name = ~D5_BLADE~ remove_ability = ~GA_SPCL906~ END					//	no power attack
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  LAF action_add_hla STR_VAR kit_name = ~D5_BLADE~ ability = ~AP_D5_RFA5~ num_allowed = ~1~ END			//	luck bonus
  LAF action_add_hla STR_VAR kit_name = ~D5_BLADE~ ability = ~AP_D5_RFD3~ num_allowed = ~1~ END			//	spell evasion
  LAF action_add_hla STR_VAR kit_name = ~D5_BLADE~ ability = ~AP_D5_UMD~ num_allowed = ~1~ END			//	use scrolls/wands
  LAF action_add_hla STR_VAR kit_name = ~D5_BLADE~ ability = ~GA_D5FEAT0~ num_allowed = ~3~ END			//	extra feats
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  LAF action_add_hla STR_VAR kit_name = ~D5_JESTER~ ability = ~AP_D5_RFA5~ num_allowed = ~2~ END		//	luck bonus
  LAF action_add_hla STR_VAR kit_name = ~D5_JESTER~ ability = ~AP_D5_RFD3~ num_allowed = ~1~ END		//	spell evasion
  LAF action_add_hla STR_VAR kit_name = ~D5_JESTER~ ability = ~AP_D5_RFD5~ num_allowed = ~3~ END		//	saving throw bonus
  LAF action_add_hla STR_VAR kit_name = ~D5_JESTER~ ability = ~GA_D5FEAT0~ num_allowed = ~3~ END		//	extra feats
END

LAF action_add_hla STR_VAR kit_name = ~D5_SKALD~ ability = ~GA_909~ num_allowed = ~3~ prerequisite = ~AP_SPCL905~ END	//	smite
LAF action_add_hla STR_VAR kit_name = ~D5_SKALD~ ability = ~GA_902~ num_allowed = ~3~ END				//	death blow
LAF action_add_hla STR_VAR kit_name = ~D5_SKALD~ ability = ~GA_908~ num_allowed = ~3~ END				//	war cry
LAF action_add_hla STR_VAR kit_name = ~D5_SKALD~ ability = ~GA_321~ num_allowed = ~1~ END				//	zerk rage
LAF action_remove_hla STR_VAR kit_name = ~D5_SKALD~ remove_ability = ~GA_SPCL913~ END					//	no evasion
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  LAF action_add_hla STR_VAR kit_name = ~D5_SKALD~ ability = ~GA_D5FEAT0~ num_allowed = ~3~ END			//	extra feats
END

LAF action_add_hla STR_VAR kit_name = ~D5_GALLANT~ ability = ~GA_909~ num_allowed = ~3~ prerequisite = ~AP_SPCL905~ END	//	smite
LAF action_add_hla STR_VAR kit_name = ~D5_GALLANT~ ability = ~GA_904~ num_allowed = ~1~ END				//	resist magic
LAF action_add_hla STR_VAR kit_name = ~D5_GALLANT~ ability = ~GA_211~ num_allowed = ~1~ END				//	lay on hands
LAF action_add_hla STR_VAR kit_name = ~D5_GALLANT~ ability = ~GA_233~ num_allowed = ~3~ END				//	pro. evil 10' radius
LAF action_remove_hla STR_VAR kit_name = ~D5_GALLANT~ remove_ability = ~GA_SPCL913~ END					//	no evasion
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  LAF action_add_hla STR_VAR kit_name = ~D5_GALLANT~ ability = ~GA_D5FEAT0~ num_allowed = ~3~ END		//	extra feats
END

LAF action_add_hla STR_VAR kit_name = ~D5_HERALD~ ability = ~GA_907~ num_allowed = ~1~ END				//	resist magic
LAF action_add_hla STR_VAR kit_name = ~D5_HERALD~ ability = ~GA_904~ num_allowed = ~1~ END				//	hardiness
LAF action_add_hla STR_VAR kit_name = ~D5_HERALD~ ability = ~GA_908~ num_allowed = ~3~ END				//	war cry
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  LAF action_add_hla STR_VAR kit_name = ~D5_HERALD~ ability = ~AP_D5_RFA5~ num_allowed = ~1~ END		//	luck bonus
  LAF action_add_hla STR_VAR kit_name = ~D5_HERALD~ ability = ~AP_D5_RFD3~ num_allowed = ~1~ END		//	spell evasion
//  LAF action_add_hla STR_VAR kit_name = ~D5_HERALD~ ability = ~AP_D5_WFA2~ num_allowed = ~1~ excluded_by = ~AP_D5_WFA3~ END		//	offensive tactics
//  LAF action_add_hla STR_VAR kit_name = ~D5_HERALD~ ability = ~AP_D5_WFA3~ num_allowed = ~1~ excluded_by = ~AP_D5_WFA2~ END		//	defensive tactics
  LAF action_add_hla STR_VAR kit_name = ~D5_HERALD~ ability = ~GA_D5FEAT0~ num_allowed = ~3~ END		//	extra feats
END

LAF action_add_hla STR_VAR kit_name = ~D5_MEISTER~ ability = ~GA_SPCL922~ num_allowed = ~1~ END			//	tracking
LAF action_add_hla STR_VAR kit_name = ~D5_MEISTER~ ability = ~AP_SPCL924~ num_allowed = ~1~ END			//	poison immunity
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  LAF action_add_hla STR_VAR kit_name = ~D5_MEISTER~ ability = ~AP_D5_RFA5~ num_allowed = ~2~ END		//	luck bonus
  LAF action_add_hla STR_VAR kit_name = ~D5_MEISTER~ ability = ~AP_D5_RFD3~ num_allowed = ~1~ END		//	spell evasion
  LAF action_add_hla STR_VAR kit_name = ~D5_MEISTER~ ability = ~AP_D5_UMD~ num_allowed = ~1~ END		//	use scrolls/wands
  LAF action_add_hla STR_VAR kit_name = ~D5_MEISTER~ ability = ~GA_D5FEAT0~ num_allowed = ~3~ END		//	extra feats
END

LAF action_add_hla STR_VAR kit_name = ~D5_JINXER~ ability = ~GA_SPCL914~ num_allowed = ~3~ prerequisite = ~AP_SPCL913~ END	//	greater evasion
LAF action_add_hla STR_VAR kit_name = ~D5_JINXER~ ability = ~AP_SPSD02~ num_allowed = ~3~ END			//	shadowstep
LAF action_add_hla STR_VAR kit_name = ~D5_JINXER~ ability = ~AP_SPCL937~ num_allowed = ~1~ END			//	shadow maze
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  LAF action_add_hla STR_VAR kit_name = ~D5_JINXER~ ability = ~AP_D5_RFA5~ num_allowed = ~1~ END		//	luck bonus
  LAF action_add_hla STR_VAR kit_name = ~D5_JINXER~ ability = ~AP_D5_RFD3~ num_allowed = ~1~ END		//	spell evasion
  LAF action_add_hla STR_VAR kit_name = ~D5_JINXER~ ability = ~AP_D5_RFG5~ num_allowed = ~1~ END		//	fighting dirty
  LAF action_add_hla STR_VAR kit_name = ~D5_JINXER~ ability = ~GA_D5FEAT0~ num_allowed = ~3~ END			//	extra feats
END

LAF action_add_hla STR_VAR kit_name = ~D5_LORESINGER~ ability = ~GA_907~ num_allowed = ~1~ END			//	resist magic
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  LAF action_add_hla STR_VAR kit_name = ~D5_LORESINGER~ ability = ~AP_D5_RFA5~ num_allowed = ~2~ END	//	luck bonus
  LAF action_add_hla STR_VAR kit_name = ~D5_LORESINGER~ ability = ~AP_D5_RFD3~ num_allowed = ~1~ END	//	spell evasion
  LAF action_add_hla STR_VAR kit_name = ~D5_LORESINGER~ ability = ~GA_D5FEAT0~ num_allowed = ~3~ END	//	extra feats
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  LAF action_add_hla STR_VAR kit_name = ~D5_BARD~ ability = ~AP_D5_RFA5~ num_allowed = ~2~ END			//	luck bonus
  LAF action_add_hla STR_VAR kit_name = ~D5_BARD~ ability = ~AP_D5_RFD3~ num_allowed = ~1~ END			//	spell evasion
  LAF action_add_hla STR_VAR kit_name = ~D5_BARD~ ability = ~AP_D5_RFD5~ num_allowed = ~3~ END			//	saving throw bonus
  LAF action_add_hla STR_VAR kit_name = ~D5_BARD~ ability = ~GA_D5FEAT0~ num_allowed = ~3~ END			//	extra feats
END

ACTION_IF FILE_EXISTS_IN_GAME ~RR#BHL01.SPL~ BEGIN
  ACTION_FOR_EACH bard_kit IN ~D5_BARD~ ~D5_BLADE~ ~D5_JESTER~ ~D5_SKALD~ ~D5_GALLANT~ ~D5_HERALD~ ~D5_MEISTER~ ~D5_JINXER~ ~D5_LORESINGER~ BEGIN
// replace spcl921 with RR magic flute
	LAF action_replace_hla STR_VAR kit_name = ~D5_BARD~ remove_ability = ~GA_SPCL921~ ability = ~GA_RR#BHL07~ END
// add other RR HLAs
	LAF action_add_hla STR_VAR kit_name = ~%bard_kit%~ ability = ~GA_RR#BHL01~ num_allowed = ~3~ END		//	mass charm
	LAF action_add_hla STR_VAR kit_name = ~%bard_kit%~ ability = ~GA_RR#BHL02~ num_allowed = ~3~ END		//	enthralling melody
	LAF action_add_hla STR_VAR kit_name = ~%bard_kit%~ ability = ~GA_RR#BHL05~ num_allowed = ~3~ END		//	resonating weapon
	LAF action_add_hla STR_VAR kit_name = ~%bard_kit%~ ability = ~GA_RR#BHL06~ num_allowed = ~3~ END		//	sound barrier
	LAF action_add_hla STR_VAR kit_name = ~%bard_kit%~ ability = ~GA_RR#BHL03~ num_allowed = ~3~ END		//	sound burst
  END
END

//____________________________________________________________________________________


//CHANGE NPC BARDS____________________________________________________________________
//
// do a basic algorithmic change
// then specifically make garrick = gallant and eldoth = jinxer

COPY_EXISTING ~kitlist.2da~ ~override~
  COUNT_2DA_ROWS 8 rows
  FOR (row = 3; row < rows; ++row) BEGIN 
	READ_2DA_ENTRY row 1 8 ~kit_name~
	PATCH_IF (~%kit_name%~ STRING_EQUAL_CASE ~D5_BARD~ = 1) BEGIN
	  SET new_bard = %row% - 1
	END
  END
BUT_ONLY

ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
  PRINT ~%cre% => %dv%~ 
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
	  READ_BYTE 0x273 npc_class
	  READ_SHORT 0x246 old_kit
	  PATCH_IF (npc_class = 5) BEGIN
		PATCH_IF (old_kit = 16384) OR
		  		(old_kit = 0) BEGIN										//	trueclass bards
		  WRITE_BYTE 0x234 1 											// sets level to 1
		  WRITE_BYTE 0x235 1
		  WRITE_BYTE 0x236 1
		  WRITE_BYTE 0x273 4 											// sets class
		  WRITE_SHORT 0x244 0
		  WRITE_SHORT 0x246 0x4000 + %nu_bard_code% 					// changes kit
		  WRITE_BYTE 0x0045 10
		  WRITE_BYTE 0x0064 5
		  WRITE_BYTE 0x0065 5
		  WRITE_BYTE 0x0066 10
		  WRITE_BYTE 0x0067 5
		  WRITE_BYTE 0x0068 10
		  WRITE_BYTE 0x0069 5
		  WRITE_BYTE 0x006a 5
	 	  READ_BYTE 0x23d npc_con
		  PATCH_IF (npc_con < 15) BEGIN
			WRITE_SHORT 0x24 6
			WRITE_SHORT 0x26 6
		  END
		  PATCH_IF (npc_con = 15) BEGIN
			WRITE_SHORT 0x24 7
			WRITE_SHORT 0x26 7
		  END
		  PATCH_IF (npc_con > 15) BEGIN
			WRITE_SHORT 0x24 8
			WRITE_SHORT 0x26 8
		  END
		END
		PATCH_IF (old_kit = 16397) BEGIN 								//	blades
		  WRITE_BYTE 0x234 1 											// sets level to 1
		  WRITE_BYTE 0x235 1
		  WRITE_BYTE 0x236 1
		  WRITE_BYTE 0x273 4 											// sets class
		  WRITE_SHORT 0x244 0
		  WRITE_SHORT 0x246 %nu_blade_code% 							// changes kit
		  WRITE_BYTE 0x0045 10
		  WRITE_BYTE 0x0064 5
		  WRITE_BYTE 0x0065 5
		  WRITE_BYTE 0x0066 10
		  WRITE_BYTE 0x0067 5
		  WRITE_BYTE 0x0068 10
		  WRITE_BYTE 0x0069 5
		  WRITE_BYTE 0x006a 5
	 	  READ_BYTE 0x23d npc_con
		  PATCH_IF (npc_con < 15) BEGIN
			WRITE_SHORT 0x24 6
			WRITE_SHORT 0x26 6
		  END
		  PATCH_IF (npc_con = 15) BEGIN
			WRITE_SHORT 0x24 7
			WRITE_SHORT 0x26 7
		  END
		  PATCH_IF (npc_con > 15) BEGIN
			WRITE_SHORT 0x24 8
			WRITE_SHORT 0x26 8
		  END
		END
		PATCH_IF (old_kit = 16398) BEGIN 								//	jesters
		  WRITE_BYTE 0x234 1 											// sets level to 1
		  WRITE_BYTE 0x235 1
		  WRITE_BYTE 0x236 1
		  WRITE_BYTE 0x273 4 											// sets class
		  WRITE_SHORT 0x244 0
		  WRITE_SHORT 0x246 %nu_jester_code% 							// changes kit
		  WRITE_BYTE 0x0045 10
		  WRITE_BYTE 0x0064 5
		  WRITE_BYTE 0x0065 5
		  WRITE_BYTE 0x0066 10
		  WRITE_BYTE 0x0067 5
		  WRITE_BYTE 0x0068 10
		  WRITE_BYTE 0x0069 5
		  WRITE_BYTE 0x006a 5
	 	  READ_BYTE 0x23d npc_con
		  PATCH_IF (npc_con < 15) BEGIN
			WRITE_SHORT 0x24 6
			WRITE_SHORT 0x26 6
		  END
		  PATCH_IF (npc_con = 15) BEGIN
			WRITE_SHORT 0x24 7
			WRITE_SHORT 0x26 7
		  END
		  PATCH_IF (npc_con > 15) BEGIN
			WRITE_SHORT 0x24 8
			WRITE_SHORT 0x26 8
		  END
		END
		REMOVE_KNOWN_SPELLS
		REMOVE_MEMORIZED_SPELLS
		PATCH_IF (old_kit = 16399) BEGIN 								//	skalds
// ***** figure out proficiencies... just double for now
		  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 match_parameter1 = 1 parameter1 = 2 END
		  WRITE_BYTE 0x234 1 											// sets level to 1
		  WRITE_BYTE 0x235 1
		  WRITE_BYTE 0x236 1
		  WRITE_BYTE 0x273 9											// sets class
		  WRITE_SHORT 0x244 0
		  WRITE_SHORT 0x246 %nu_skald_code% 							// changes kit
		  WRITE_BYTE 0x0045 10
		  WRITE_BYTE 0x0064 5
		  WRITE_BYTE 0x0065 5
		  WRITE_BYTE 0x0066 10
		  WRITE_BYTE 0x0067 5
		  WRITE_BYTE 0x0068 10
		  WRITE_BYTE 0x0069 5
		  WRITE_BYTE 0x006a 5
		  PATCH_IF (npc_con < 15) BEGIN
			WRITE_SHORT 0x24 8
			WRITE_SHORT 0x26 8
		  END
		  PATCH_IF (npc_con = 15) BEGIN
			WRITE_SHORT 0x24 9
			WRITE_SHORT 0x26 9
		  END
		  PATCH_IF (npc_con = 16) BEGIN
			WRITE_SHORT 0x24 10
			WRITE_SHORT 0x26 10
		  END
		  PATCH_IF (npc_con = 17) BEGIN
			WRITE_SHORT 0x24 11
			WRITE_SHORT 0x26 11
		  END
		  PATCH_IF (npc_con > 17) BEGIN
			WRITE_SHORT 0x24 12
			WRITE_SHORT 0x26 12
		  END
		END
		PATCH_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
			LPF ADD_CRE_EFFECT INT_VAR opcode = 171 target = 1 timing = 9 STR_VAR resource = ~d5feata~ END
		END
	  END
	END
  BUT_ONLY
END

ACTION_FOR_EACH char IN ~eldoth~ ~eldoth5~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%char%.cre~ BEGIN
	COPY_EXISTING ~%char%.cre~ ~override~
	  WRITE_SHORT 0x244 0
	  WRITE_SHORT 0x246 %nu_jinxer_code% 								// changes kit
	BUT_ONLY
  END
END

ACTION_FOR_EACH char IN ~garric~ ~garric2~ ~garric4~ ~garric6~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%char%.cre~ BEGIN
	COPY_EXISTING ~garric2.cre~ ~override/%char%.cre~
	  WRITE_BYTE 0x273 9												// sets class
	  WRITE_SHORT 0x244 0
	  WRITE_SHORT 0x246 %nu_gallant_code% 								// changes kit
	  READ_BYTE 0x23d npc_con
	  PATCH_IF (npc_con < 15) BEGIN
		WRITE_SHORT 0x24 8
		WRITE_SHORT 0x26 8
	  END
	  PATCH_IF (npc_con = 15) BEGIN
		WRITE_SHORT 0x24 9
		WRITE_SHORT 0x26 9
	  END
	  PATCH_IF (npc_con = 16) BEGIN
		WRITE_SHORT 0x24 10
		WRITE_SHORT 0x26 10
	  END
	  PATCH_IF (npc_con = 17) BEGIN
		WRITE_SHORT 0x24 11
		WRITE_SHORT 0x26 11
	  END
	  PATCH_IF (npc_con > 17) BEGIN
		WRITE_SHORT 0x24 12
		WRITE_SHORT 0x26 12
	  END
// ***** figure out proficiencies (just double what's already there??)
	  LPF ALTER_EFFECT INT_VAR silent = 1 match_opcode = 233 match_parameter1 = 1 parameter1 = 2 END
	BUT_ONLY
  END
END
//___________________________________________________________________________________


//CHANGE BARD STRONGHOLDS____________________________________________________________
//
// give theater to bard, blade, jester, gallant, loresinger
ACTION_IF GAME_IS ~BG2EE EET~ BEGIN

<<<<<<<< d5/raelis+.d
EXTEND_BOTTOM RAELIS 71 
  IF ~Global("PlayerHasStronghold","GLOBAL",0)
  	  OR(5)
		Kit(Player1,D5_BARD)
		Kit(Player1,D5_BLADE)
		Kit(Player1,D5_JESTER)
		Kit(Player1,D5_GALLANT)
		Kit(Player1,D5_LORESINGER)
~ THEN DO ~EraseJournalEntry(4685)
EraseJournalEntry(46846)
EraseJournalEntry(46847)
EraseJournalEntry(46848)
EraseJournalEntry(46849)
EraseJournalEntry(46850)
EraseJournalEntry(46851)
AddXPObject(Player1,44000)
AddXPObject(Player2,44000)
AddXPObject(Player3,44000)
AddXPObject(Player4,44000)
AddXPObject(Player5,44000)
AddXPObject(Player6,44000)
~ SOLVED_JOURNAL #47761 GOTO 61
END

EXTEND_BOTTOM RAELIS 72
  IF ~  OR(5)
	Kit(Player1,D5_BARD)
	Kit(Player1,D5_BLADE)
	Kit(Player1,D5_JESTER)
	Kit(Player1,D5_GALLANT)
	Kit(Player1,D5_LORESINGER)
  ~ THEN GOTO 73
END

EXTEND_BOTTOM HAERDA 99
  IF ~  OR(5)
	Kit(Player1,D5_BARD)
	Kit(Player1,D5_BLADE)
	Kit(Player1,D5_JESTER)
	Kit(Player1,D5_GALLANT)
	Kit(Player1,D5_LORESINGER)
  ~ THEN EXTERN ~RAELIS~ 59
END
>>>>>>>> 

COMPILE ~d5/raelis+.d~

// take guild away from bard, jester, skald, gallant, herald, meistersinger, loresinger

<<<<<<<< d5/renal+.d
ADD_TRANS_TRIGGER RENAL 7 ~!Kit(Player1,D5_BARD)
!Kit(Player1,D5_JESTER)
!Kit(Player1,D5_SKALD)
!Kit(Player1,D5_GALLANT)
!Kit(Player1,D5_HERALD)
!Kit(Player1,D5_MEISTER)
!Kit(Player1,D5_LORESINGER)~ DO 1
EXTEND_BOTTOM RENAL 7
  IF ~OR(7)
  Kit(Player1,D5_BARD)
  Kit(Player1,D5_JESTER)
  Kit(Player1,D5_SKALD)
  Kit(Player1,D5_GALLANT)
  Kit(Player1,D5_HERALD)
  Kit(Player1,D5_MEISTER)
  Kit(Player1,D5_LORESINGER)~ THEN REPLY #21233 GOTO 18
END
>>>>>>>> 

COMPILE ~d5/renal+.d~

// give ranger cabin to meistersinger

<<<<<<<< d5/uhmayor+.d
EXTEND_BOTTOM UHMAY01 31
  IF ~  Kit(Player1,D5_MEISTER)
Global("PlayerHasStronghold","GLOBAL",0)
Global("MayorPay","GLOBAL",0)
~ THEN GOTO 34
END 

EXTEND_BOTTOM UHMAY01 33
  IF ~  Global("PlayerHasStronghold","GLOBAL",0)
Kit(Player1,D5_MEISTER)
~ THEN GOTO 34
END
>>>>>>>> 

COMPILE ~d5/uhmayor+.d~

END	//	end game_is
//____________________________________________________________________________________


//CHANGE SOD BARD'S HAT______________________________________________________________
//
// ... have to do something with Wondrous Gloves too

COPY ~might_and_guile/nubards/bdhelm11.itm~ ~override~
	SAY IDENTIFIED_DESC @21900
COPY ~might_and_guile/nubards/d5bdh11.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/nubards/d5bdh11.eff~ ~override~
//	SAY NAME1 @7
//___________________________________________________________________________________


//MAKE +SPELL SLOT ITEMS WORK________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src1e.eff~ BEGIN
  CREATE EFF ~d5src1e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 16)
	WRITE_LONG 0x20 (106 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC1E~ #8
  CREATE EFF ~d5src2e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 20)
	WRITE_LONG 0x20 (106 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC2E~ #8
  CREATE EFF ~d5src3e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 24)
	WRITE_LONG 0x20 (106 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC3E~ #8
  CREATE EFF ~d5src4e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 28)
	WRITE_LONG 0x20 (106 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC4E~ #8
  CREATE EFF ~d5src5e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 8)
	WRITE_LONG 0x20 (107 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC5E~ #8
  CREATE EFF ~d5src6e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 12)
	WRITE_LONG 0x20 (107 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC6E~ #8
  CREATE EFF ~d5src7e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 16)
	WRITE_LONG 0x20 (107 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC7E~ #8
  CREATE EFF ~d5src8e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 20)
	WRITE_LONG 0x20 (107 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC8E~ #8
  CREATE EFF ~d5src9e~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (1 << 24)
	WRITE_LONG 0x20 (107 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC9E~ #8
  CREATE EFF ~d5src1f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 16)
	WRITE_LONG 0x20 (106 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC1F~ #8
  CREATE EFF ~d5src2f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 20)
	WRITE_LONG 0x20 (106 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC2F~ #8
  CREATE EFF ~d5src3f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 24)
	WRITE_LONG 0x20 (106 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC3F~ #8
  CREATE EFF ~d5src4f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 28)
	WRITE_LONG 0x20 (106 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC4F~ #8
  CREATE EFF ~d5src5f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 8)
	WRITE_LONG 0x20 (107 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC5F~ #8
  CREATE EFF ~d5src6f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 12)
	WRITE_LONG 0x20 (107 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC6F~ #8
  CREATE EFF ~d5src7f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 16)
	WRITE_LONG 0x20 (107 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC7F~ #8
  CREATE EFF ~d5src8f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 20)
	WRITE_LONG 0x20 (107 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC8F~ #8
  CREATE EFF ~d5src9f~
	WRITE_LONG 0x10 233
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c (2 << 24)
	WRITE_LONG 0x20 (107 + (0x10000 * 1))
	WRITE_LONG 0x24 2
	WRITE_SHORT 0x2c 100
	WRITE_LONG 0x90 1
	WRITE_EVALUATED_ASCII 0x94 ~D5SRC9F~ #8

  COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
   PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 1 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src1e~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 2 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src2e~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 4 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src3e~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 8 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src4e~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 16 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src5e~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 32 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src6e~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 64 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src7e~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src8e~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 1 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src9e~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 1 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src1f~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 2 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src2f~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 4 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src3f~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 8 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src4f~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 16 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src5f~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 32 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src6f~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 64 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src7f~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 128 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src8f~ END
	LPF CLONE_EFFECT INT_VAR silent = 1 multi_match = 1 match_opcode = 42 match_parameter1 = 2 match_parameter2 = 256 opcode = 177 parameter1 = 0 parameter2 = 2 timing = 2 STR_VAR resource = ~d5src9f~ END
   END
  BUT_ONLY
END
//___________________________________________________________________________________


//HUMANS CAN BE MULTICLASS BARDS______________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~CLSRCREQ.2da~ BEGIN
  COPY_EXISTING ~clsrcreq.2da~ ~override~
	COUNT_2DA_ROWS 8 rows
	FOR (row = 0 ; row < rows ; ++row) BEGIN
      READ_2DA_ENTRY row 0 8 entry
      PATCH_IF (("%entry%" STRING_COMPARE_CASE "FIGHTER_THIEF"      = 0) OR
                ("%entry%" STRING_COMPARE_CASE "CLERIC_THIEF" 	 = 0)) BEGIN
    	SET_2DA_ENTRY  row 1 8 1
      END
	END
  BUT_ONLY
END

ACTION_FOR_EACH multi IN ~FT~ ~CT~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~K_%multi%_H.2da~ BEGIN
	COPY_EXISTING ~K_%multi%_H.2da~ ~override~
	  COUNT_2DA_COLS cols
	  READ_2DA_ENTRIES_NOW rows cols
	  SET rows_removed = 0
	  FOR (row = 1; row < rows; ++row) BEGIN
		READ_2DA_ENTRY_FORMER rows row 1 kit
		PATCH_IF (%kit% = 0) BEGIN
		  REMOVE_2DA_ROW (row - rows_removed) cols
		  SET rows_removed += 1
		END
	  END
	BUT_ONLY
  END
END
//____________________________________________________________________________________


//DISABLE OLD BARD KITS_______________________________________________________________
//
ACTION_FOR_EACH race IN ~D~ ~E~ ~G~ ~H~ ~HE~ ~HL~ ~HO~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~K_B_%race%.2da~ BEGIN
	COPY_EXISTING ~K_B_%race%.2da~ ~override~
	  COUNT_2DA_COLS cols
	  READ_2DA_ENTRIES_NOW rows cols
	  SET rows_removed = 0
	  FOR (row = 1; row < rows; ++row) BEGIN
		READ_2DA_ENTRY_FORMER rows row 1 kit
		PATCH_IF (%kit% = 0) OR 
		  		 (%kit% = 13) OR 
		  		 (%kit% = 14) OR 
		  		 (%kit% = 15) BEGIN
		  REMOVE_2DA_ROW (row - rows_removed) cols
		  SET rows_removed += 1
		END
	  END
	BUT_ONLY
  END
END

// ***** and change clsrcreq.2da etc.
ACTION_IF FILE_EXISTS_IN_GAME ~CLSRCREQ.2da~ BEGIN
  COPY_EXISTING ~clsrcreq.2da~ ~override~
	COUNT_2DA_ROWS 8 rows
	FOR (row = 0 ; row < rows ; ++row) BEGIN
      READ_2DA_ENTRY row 0 8 entry
      PATCH_IF (("%entry%" STRING_COMPARE_CASE "BLADE"		= 0) OR
                ("%entry%" STRING_COMPARE_CASE "JESTER"		= 0) OR
                ("%entry%" STRING_COMPARE_CASE "SKALD"		= 0)) BEGIN
		SET_2DA_ENTRY  row 1 8 0
		SET_2DA_ENTRY  row 2 8 0
		SET_2DA_ENTRY  row 3 8 0
		SET_2DA_ENTRY  row 4 8 0
		SET_2DA_ENTRY  row 5 8 0
		SET_2DA_ENTRY  row 6 8 0
		SET_2DA_ENTRY  row 7 8 0
      END
	END
  BUT_ONLY
END
//___________________________________________________________________________________


