
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								REVISED STALKER
//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION revised_stalker BEGIN


//EDIT STALKER KIT 2DA FILES________________________________________________________
//
COPY_EXISTING ~weapprof.2da~ ~override~
	SET_2DA_ENTRY 13 37 1 ~3~
	SET_2DA_ENTRY 18 37 1 ~3~
BUT_ONLY
//___________________________________________________________________________________


//UPDATE EXISTING STRINGS__________________________________________________________
// 
ACTION_FOR_EACH text_file IN ~clastext~ ~sodcltxt~ ~bgclatxt~ ~kitlist~ BEGIN
  COPY_EXISTING ~%text_file%.2da~ ~override~
    COUNT_2DA_COLS cols
    COUNT_2DA_ROWS cols rows
    FOR (row = 1; row < rows; ++row) BEGIN
      READ_2DA_ENTRY row 0 cols kit_name
      READ_2DA_ENTRY row 1 cols kitlist_name
      PATCH_IF (~%kit_name%~ STRING_EQUAL_CASE ~STALKER~) OR (~%kitlist_name%~ STRING_EQUAL_CASE ~STALKER~)BEGIN
        SET_2DA_ENTRY row 4 cols RESOLVE_STR_REF (@2251)
      END
    END
  IF_EXISTS BUT_ONLY
END
//__________________________________________________________________________________


//2DA MODIFICATIONS___________________________________________________________________
//
ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
	COPY_EXISTING ~clabrn03.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/ranger/tracking.txt~
	BUT_ONLY
END
ACTION_IF (FILE_EXISTS_IN_GAME ~clabrn01.2da~) THEN BEGIN
	COPY_EXISTING ~clabrn01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/ranger/ranstab.txt~
	BUT_ONLY
END
ACTION_IF (GAME_IS ~bgee bg2ee eet iwdee~) THEN BEGIN
	COPY_EXISTING ~clabrn03.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_SPCL332 ~ ~****       ~
		REPLACE_TEXTUALLY ~GA_SPCL311 ~ ~****       ~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/ranger/stalker_no_feats.txt~
END
ACTION_IF (GAME_IS ~tob bgt tutu~) THEN BEGIN
	COPY_EXISTING ~clabrn03.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/ranger/stlkstab.txt~
	BUT_ONLY
END
//____________________________________________________________________________________


//STALKER ABILITY FILES_______________________________________________________________
//
COPY ~might_and_guile/ranger/d5_trp40.spl~ ~override~
COPY ~might_and_guile/ranger/d5_trp3.spl~ ~override~
COPY ~might_and_guile/ranger/d5_rnosp.eff~ ~override~
COPY ~might_and_guile/ranger/d5_rnosp.spl~ ~override~
COPY ~might_and_guile/ranger/d5_rasp1.spl~ ~override~
COPY ~might_and_guile/ranger/d5_rasp2.spl~ ~override~
COPY ~might_and_guile/ranger/d5_rasp3.spl~ ~override~
COPY ~might_and_guile/ranger/d5_stsp1.spl~ ~override~
COPY ~might_and_guile/ranger/d5_stsp2.spl~ ~override~
COPY ~might_and_guile/ranger/d5_stsp3.spl~ ~override~
//___________________________________________________________________________________


END	//	end function