
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//								QUICKSTRIDE
//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION 245_quickstride BEGIN

//COPY MARKER FILE_________________________________________________________________
//
COPY ~might_and_guile/lib/markers/d5_marker.d5~ ~override/d5_stride.d5~
//__________________________________________________________________________________


LAM JOINABLE_NPC_ARRAYS


LAM d5_quickstride_speed

COPY ~might_and_guile/feats/d5_wfc1b.bam~ ~override~
COPY ~might_and_guile/misc/d5strid.spl~ ~override~
	SAY NAME1 @2450
	SAY UNIDENTIFIED_DESC @20110
	WRITE_ASCII 0x3a ~d5_wfc1b~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wfc1b~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 176 parameter1 = %d5_quickstride_bonus% END
	LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = ~d5swalk~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = ~d5strid~ END

COPY ~might_and_guile/misc/d5_rwlkb.bam~ ~override~
COPY ~might_and_guile/misc/d5swalk.spl~ ~override~
	SAY NAME1 @2451
	SAY UNIDENTIFIED_DESC @2451
	WRITE_ASCII 0x3a ~d5_rwlkb~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_rwlkb~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = ~d5strid~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 171 STR_VAR resource = ~d5strid~ END
	LPF ALTER_EFFECT INT_VAR match_opcode = 172 STR_VAR resource = ~d5swalk~ END


ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
	  LPF DELETE_CRE_EFFECT INT_VAR opcode_to_delete = 176 END
	END
  BUT_ONLY
END


COPY_EXISTING ~spcl151.spl~ ~override~
			  ~spcl812.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR silent = 1 match_probability1 = 100 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = ~d5strid~ END

ACTION_FOR_EACH stride_kit IN ~clabrn01~ ~clabmo01~ ~d5shmbb~ ~QDMONK~ ~QDMONKSS~ ~QDMONKDM~ ~QDMONKHF~ ~QDMONKSH~ ~QDMONKLD~ ~QDMONKBO~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%stride_kit%.2da~ BEGIN
	COPY_EXISTING ~%stride_kit%.2da~ ~override~
	  REPLACE_TEXTUALLY ~AP_SPCL813 ~ ~****       ~
	BUT_ONLY
	APPEND ~%stride_kit%.2da~ ~STRIDE      AP_SPCL151  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****         ****        ****        ****        ****        ****        ****  ~ UNLESS ~STRIDE~
  END
END

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS 9 rows
  FOR (row = 3 ; row < rows ; ++row ) BEGIN
	READ_2DA_ENTRY row 5 9 clab
	READ_2DA_ENTRY row 8 9 class
	PATCH_IF (class = 20) OR (class = 12) BEGIN
	  INNER_ACTION BEGIN
		COPY_EXISTING ~%clab%.2da~ ~override~
		  REPLACE_TEXTUALLY ~AP_SPCL813~ ~****      ~
		BUT_ONLY
		APPEND ~%clab%.2da~ ~STRIDE      AP_SPCL151  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****         ****        ****        ****        ****        ****        ****  ~ UNLESS ~STRIDE~
	  END
	END
  END
BUT_ONLY

OUTER_SET speed_item_ind = 0
OUTER_SPRINT $speed_boost_items(~%speed_item_ind%~) ~speed_boost_item~
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (%SOURCE_SIZE% > 0x71) BEGIN
  	SET speed_boost = 0
	READ_LONG 0x6a effectsoffset ELSE 0
	READ_SHORT 0x70 effectscount ELSE 0
	FOR (effcyc = 0; effcyc < effectscount; effcyc = effcyc + 1) BEGIN
	  READ_SHORT (effectsoffset + (effcyc * 0x30)) opcode ELSE 0
	  READ_SHORT (effectsoffset + (effcyc * 0x30)) + 0x04 param1 ELSE 0
	  PATCH_IF (opcode = 126) && (param1 > 0) BEGIN
		SET speed_boost = 1
	  END
	END
	PATCH_IF (speed_boost = 1) BEGIN
	  SPRINT $speed_boost_items(~%speed_item_ind%~) ~%SOURCE_RES%~
	  SET ++speed_item_ind
	END
  END
BUT_ONLY
ACTION_PHP_EACH speed_boost_items AS ind => speed_item BEGIN
  COPY_EXISTING ~%speed_item%.itm~ ~override~
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5swalk~ END
	LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = ~d5strid~ END
  IF_EXISTS BUT_ONLY
END

END // end new engine function


//__________________________________________________________________________________
//__________________________________________________________________________________


// old quickstride

DEFINE_ACTION_FUNCTION old_quickstride BEGIN

COPY ~might_and_guile/lib/markers/d5_marker.d5~ ~override/d5_stride.d5~

LAM JOINABLE_NPC_ARRAYS

ACTION_FOR_EACH stride IN ~d5_stri2~ ~d5_stri3~ ~d5_stri4~ ~d5_stri5~ ~d5_stri6~ ~d5_strim~ BEGIN
  ACTION_IF ENGINE_IS ~tob bgt~ BEGIN
	COPY ~might_and_guile/misc/%stride%.spl~ ~override/%stride%.spl~
	  SAY NAME1 @2210
	  SAY UNIDENTIFIED_DESC @2210
  END
  ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ BEGIN
	COPY ~might_and_guile/misc/%stride%ee.spl~ ~override/%stride%.spl~
	  SAY NAME1 @2210
	  SAY UNIDENTIFIED_DESC @2210
  END
END
ACTION_FOR_EACH walk IN ~d5_walk2~ ~d5_walk3~ ~d5_walk4~ ~d5_walk5~ ~d5_walk6~ ~d5_walkm~ BEGIN
  ACTION_IF ENGINE_IS ~tob bgt~ BEGIN
	COPY ~might_and_guile/misc/%walk%.spl~ ~override/%walk%.spl~
	  SAY NAME1 @2211
	  SAY UNIDENTIFIED_DESC @2211
  END
  ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ BEGIN
	COPY ~might_and_guile/misc/%walk%ee.spl~ ~override/%walk%.spl~
	  SAY NAME1 @2211
	  SAY UNIDENTIFIED_DESC @2211
  END
END
COPY ~might_and_guile/misc/d5_nstr2.spl~ ~override~
COPY ~might_and_guile/misc/d5_nstr3.spl~ ~override~
COPY ~might_and_guile/misc/d5_nstr4.spl~ ~override~
COPY ~might_and_guile/misc/d5_nstr5.spl~ ~override~

ACTION_PHP_EACH JOINABLE_NPC_ARRAY AS cre => dv BEGIN
  COPY_EXISTING ~%cre%~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x2d3) BEGIN
	  LPF DELETE_CRE_EFFECT INT_VAR opcode_to_delete = 176 END
	END
  BUT_ONLY
END

COPY_EXISTING ~spcl151.spl~ ~override~
			  ~spcl812.spl~ ~override~
  LPF DELETE_EFFECT INT_VAR silent = 1 match_probability1 = 100 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 171 target = 1 timing = 1 STR_VAR resource = ~d5_stri4~ END

ACTION_FOR_EACH stride_kit IN ~clabrn01~ ~clabmo01~ ~QDMONK~ ~QDMONKSS~ ~QDMONKDM~ ~QDMONKHF~ ~QDMONKSH~ ~QDMONKLD~ ~QDMONKBO~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~%stride_kit%.2da~ BEGIN
	COPY_EXISTING ~%stride_kit%.2da~ ~override~
	  REPLACE_TEXTUALLY ~AP_SPCL813 ~ ~****       ~
	BUT_ONLY
	APPEND ~%stride_kit%.2da~ ~STRIDE      AP_SPCL151  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****         ****        ****        ****        ****        ****        ****  ~
  END
END

COPY_EXISTING ~kitlist.2da~ ~override~
//  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS 9 rows
  FOR (row = 3 ; row < rows ; ++row ) BEGIN
	READ_2DA_ENTRY row 5 9 clab
	READ_2DA_ENTRY row 8 9 class
	PATCH_IF (class = 20) OR (class = 12) BEGIN
	  INNER_ACTION BEGIN
		COPY_EXISTING ~%clab%.2da~ ~override~
		  REPLACE_TEXTUALLY ~AP_SPCL813~ ~****      ~
		BUT_ONLY
		APPEND ~%clab%.2da~ ~STRIDE      AP_SPCL151  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****         ****        ****        ****        ****        ****        ****  ~
	  END
	END
  END
BUT_ONLY

END	//	end old engine function