
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						KENSAI WEAPON FOCUS
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________________________________________________________________
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

COPY ~might_and_guile/kensai/d5_kenfo.2da~ ~override~

//___________________________________________________________________________________
ADD_KIT ~D5KBSWO~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KBSWO       5 1 1 1 1 1 1 1~
~D5KBSWO       5 1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
~D5KBSWO    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBSWO           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBSWO           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBSWO  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KBSWO           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KBSWO           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kbswo.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2601
SAY @2601
SAY @2602
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@2603)
		STR_VAR
			kit_name = D5KBSWO
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KLSWO~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KLSWO       5 1 1 1 1 1 1 1~
~D5KLSWO       5 1 1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KLSWO    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KLSWO           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KLSWO           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KLSWO  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KLSWO           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KLSWO           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_klswo.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2604
SAY @2604
SAY @2605
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@2603)
		STR_VAR
			kit_name = D5KLSWO
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KKATA~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KKATA       5 1 1 1 1 1 1 1~
~D5KKATA       5 1 1 1 1 1 1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KKATA    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KKATA           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KKATA           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KKATA  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KKATA           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KKATA           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kkata.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2606
SAY @2606
SAY @2607
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KKATA
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KSCIM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KSCIM       1 5 1 1 1 1 1 1~
~D5KSCIM       1 5 1 1 1 1 1 1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSCIM    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSCIM           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSCIM           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSCIM  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KSCIM           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KSCIM           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kscim.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2608
SAY @2608
SAY @2609
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KSCIM
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KSSWO~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KSSWO       1 5 1 1 1 1 1 1~
~D5KSSWO       1 5 1 1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSSWO    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSSWO           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSSWO           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSSWO  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KSSWO           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KSSWO           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_ksswo.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2610
SAY @2610
SAY @2611
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KSSWO
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5K2SWO~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5K2SWO       5 1 1 1 1 1 1 1~
~D5K2SWO       5 1 1 1 1 1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5K2SWO    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5K2SWO           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5K2SWO           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5K2SWO  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5K2SWO           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5K2SWO           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_k2swo.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2612
SAY @2612
SAY @2613
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5K2SWO
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KDAGG~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KDAGG       1 5 1 1 1 1 1 1~
~D5KDAGG       1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KDAGG    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KDAGG           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KDAGG           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KDAGG  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KDAGG           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KDAGG           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kdagg.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2614
SAY @2614
SAY @2615
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KDAGG
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KBAXE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KBAXE       1 1 1 1 5 1 1 1~
~D5KBAXE       1 1 1 1 5 1 1 1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBAXE    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBAXE           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBAXE           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBAXE  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KBAXE           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KBAXE           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kbaxe.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2616
SAY @2616
SAY @2617
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KBAXE
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KFLAI~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KFLAI       1 1 1 1 1 5 1 1~
~D5KFLAI       1 1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KFLAI    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KFLAI           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KFLAI           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KFLAI  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KFLAI           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KFLAI           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kflai.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2618
SAY @2618
SAY @2619
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KFLAI
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KHAMM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KHAMM       1 1 1 1 5 1 1 1~
~D5KHAMM       1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 5 1 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHAMM    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHAMM           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHAMM           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHAMM  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KHAMM           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KHAMM           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_khamm.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2620
SAY @2620
SAY @2621
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KHAMM
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KMACE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KMACE       1 1 1 1 5 1 1 1~
~D5KMACE       1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KMACE    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KMACE           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KMACE           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KMACE  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KMACE           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KMACE           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kmace.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2622
SAY @2622
SAY @2623
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KMACE
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KCLUB~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KCLUB       1 1 1 1 5 1 1 1~
~D5KCLUB       1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 5 1 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KCLUB           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KCLUB           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KCLUB           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KCLUB  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KCLUB           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KCLUB           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kclub.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2624
SAY @2624
SAY @2625
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KCLUB
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KSTAF~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KSTAF       1 1 1 1 5 1 1 1~
~D5KSTAF       1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSTAF           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSTAF           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSTAF           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSTAF           15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KSTAF           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KSTAF           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kstaf.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2626
SAY @2626
SAY @2627
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KSTAF
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KSPEA~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KSPEA       1 1 1 5 1 1 1 1~
~D5KSPEA       1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 1 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSPEA           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSPEA           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSPEA           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSPEA  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KSPEA           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KSPEA           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kspea.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2628
SAY @2628
SAY @2629
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KSPEA
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KHALB~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KHALB       1 1 1 5 1 1 1 1~
~D5KHALB       1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 1 1 1 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHALB   	       9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHALB           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHALB           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHALB  	        15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KHALB           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KHALB           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_khalb.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2630
SAY @2630
SAY @2631
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KHALB
		clswpbon = ~1 0 2~
	END
END
//___________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

COPY ~might_and_guile/kensai/d5_kenf2.2da~ ~override/d5_kenfo.2da~

//___________________________________________________________________________________
ADD_KIT ~D5KLSWO~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KLSWO       5 2 0 2 2 2 2 0~
~D5KLSWO       5 2 0 2 2 2 2 0 0 5 2 2 2 0 2 2 2 2 2 0 2 2 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KLSWO    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KLSWO           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KLSWO           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KLSWO  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KLSWO           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KLSWO           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_klswo.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2604
SAY @2604
SAY @2605
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KLSWO
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KSCIM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KSCIM       2 5 0 2 2 2 2 0~
~D5KSCIM       2 5 2 2 2 2 2 0 0 2 2 2 2 0 5 2 2 2 2 0 2 2 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSCIM    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSCIM           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSCIM           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSCIM  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KSCIM           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KSCIM           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kscim.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2608
SAY @2608
SAY @2609
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KSCIM
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KSSWO~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KSSWO       2 5 0 2 2 2 2 0~
~D5KSSWO       2 5 0 2 2 2 2 0 0 2 5 2 2 0 2 2 2 2 2 0 2 2 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSSWO    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSSWO           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSSWO           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSSWO  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KSSWO           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KSSWO           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_ksswo.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2610
SAY @2610
SAY @2611
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KSSWO
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5K2SWO~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5K2SWO       5 2 0 2 2 2 2 0~
~D5K2SWO       5 2 0 2 2 2 2 0 0 2 2 2 5 0 2 2 2 2 2 0 2 2 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5K2SWO    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5K2SWO           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5K2SWO           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5K2SWO  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5K2SWO           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5K2SWO           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_k2swo.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2612
SAY @2612
SAY @2613
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5K2SWO
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KDAGG~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KDAGG       2 5 0 2 2 2 2 0~
~D5KDAGG       2 5 0 2 2 2 2 0 0 2 2 2 2 0 2 5 2 2 2 0 2 2 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KDAGG    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KDAGG           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KDAGG           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KDAGG  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KDAGG           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KDAGG           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kdagg.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2614
SAY @2614
SAY @2615
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KDAGG
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KBAXE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KBAXE       2 2 0 2 5 2 2 0~
~D5KBAXE       2 2 0 2 5 2 2 0 0 2 2 5 2 0 2 2 2 2 2 0 2 2 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBAXE    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBAXE           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBAXE           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KBAXE  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KBAXE           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KBAXE           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kbaxe.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2616
SAY @2616
SAY @2617
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KBAXE
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KFLAI~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KFLAI       2 2 2 2 2 5 2 2~
~D5KFLAI       2 2 2 2 2 5 2 2 0 2 2 2 2 0 2 2 2 2 2 0 5 2 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KFLAI    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KFLAI           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KFLAI           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KFLAI  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KFLAI           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KFLAI           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kflai.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2618
SAY @2618
SAY @2619
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KFLAI
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KHAMM~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KHAMM       2 2 0 2 5 2 2 0~
~D5KHAMM       2 2 0 2 5 2 2 0 0 2 2 2 2 0 2 2 5 2 2 0 2 2 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHAMM    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHAMM           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHAMM           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KHAMM  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KHAMM           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KHAMM           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_khamm.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2620
SAY @2620
SAY @2621
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KHAMM
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KMACE~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KMACE       2 2 0 2 5 2 2 0~
~D5KMACE       2 2 2 2 5 2 2 0 0 2 2 2 2 0 2 2 2 2 2 0 2 5 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KMACE    	   9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KMACE           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KMACE           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KMACE  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KMACE           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KMACE           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kmace.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2622
SAY @2622
SAY @2623
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KMACE
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KCLUB~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KCLUB       2 2 0 2 5 2 2 0~
~D5KCLUB       2 2 0 2 5 2 2 0 0 2 2 2 2 0 2 2 2 5 2 0 2 2 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KCLUB           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KCLUB           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KCLUB           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KCLUB  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KCLUB           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KCLUB           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kclub.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2624
SAY @2624
SAY @2625
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KCLUB
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KSTAF~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KSTAF       2 2 0 2 5 2 2 0~
~D5KSTAF       2 2 2 2 5 2 2 0 0 2 2 2 2 0 2 2 2 2 2 0 2 2 5 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSTAF           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSTAF           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSTAF           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSTAF           15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KSTAF           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KSTAF           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kstaf.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2626
SAY @2626
SAY @2627
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KSTAF
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//___________________________________________________________________________________
ADD_KIT ~D5KSPEA~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5KSPEA       2 2 0 5 2 2 2 0~
~D5KSPEA       2 2 0 5 2 2 2 0 0 2 2 2 2 0 2 2 2 2 5 0 2 2 2 0 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSPEA           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSPEA           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSPEA           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5KSPEA  	       15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5KSPEA          1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5KSPEA           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/kensai/d5_kspea.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000004 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi4~

//TOB STARTING EQUIPMENT_____________________________________________________________
~* * HELM19 BAG22 RING06 RING29 CLCK02 BOOT01 AMUL19 BRAC14 BELT06 * * * POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @2628
SAY @2628
SAY @2629
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
	INT_VAR
		briefdesc = RESOLVE_STR_REF (@2603)
	STR_VAR
		kit_name = D5KSPEA
		clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

END

//KENSAI ABILITY FILES______________________________________________________________
//
COPY ~might_and_guile/kensai/d5_kbswo.2da~ ~override~
COPY ~might_and_guile/kensai/d5_klswo.2da~ ~override~
COPY ~might_and_guile/kensai/d5_kkata.2da~ ~override~
COPY ~might_and_guile/kensai/d5_kscim.2da~ ~override~
COPY ~might_and_guile/kensai/d5_ksswo.2da~ ~override~
COPY ~might_and_guile/kensai/d5_k2swo.2da~ ~override~
COPY ~might_and_guile/kensai/d5_kdagg.2da~ ~override~
COPY ~might_and_guile/kensai/d5_kbaxe.2da~ ~override~
COPY ~might_and_guile/kensai/d5_khamm.2da~ ~override~
COPY ~might_and_guile/kensai/d5_kflai.2da~ ~override~
COPY ~might_and_guile/kensai/d5_kmace.2da~ ~override~
COPY ~might_and_guile/kensai/d5_kclub.2da~ ~override~
COPY ~might_and_guile/kensai/d5_kstaf.2da~ ~override~
COPY ~might_and_guile/kensai/d5_kspea.2da~ ~override~
COPY ~might_and_guile/kensai/d5_khalb.2da~ ~override~
COPY ~might_and_guile/misc/d5_numat.spl~ ~override~
COPY ~might_and_guile/kensai/clabfi04.2da~ ~override~
COPY ~might_and_guile/misc/d5_acbon.spl~ ~override~
COPY ~might_and_guile/misc/d5_thac0.spl~ ~override~
COPY ~might_and_guile/misc/d5_damag.spl~ ~override~
COPY ~might_and_guile/kensai/d5_kenfo.spl~ ~override~
	SAY NAME1 @2632
	SAY UNIDENTIFIED_DESC @2632
COPY ~might_and_guile/kensai/d5_kbswo.spl~ ~override~
COPY ~might_and_guile/kensai/d5_klswo.spl~ ~override~
COPY ~might_and_guile/kensai/d5_kkata.spl~ ~override~
COPY ~might_and_guile/kensai/d5_kscim.spl~ ~override~
COPY ~might_and_guile/kensai/d5_ksswo.spl~ ~override~
COPY ~might_and_guile/kensai/d5_k2swo.spl~ ~override~
COPY ~might_and_guile/kensai/d5_kdagg.spl~ ~override~
COPY ~might_and_guile/kensai/d5_kbaxe.spl~ ~override~
COPY ~might_and_guile/kensai/d5_khamm.spl~ ~override~
COPY ~might_and_guile/kensai/d5_kflai.spl~ ~override~
COPY ~might_and_guile/kensai/d5_kmace.spl~ ~override~
COPY ~might_and_guile/kensai/d5_kclub.spl~ ~override~
COPY ~might_and_guile/kensai/d5_kstaf.spl~ ~override~
COPY ~might_and_guile/kensai/d5_kspea.spl~ ~override~
COPY ~might_and_guile/kensai/d5_khalb.spl~ ~override~
COPY ~might_and_guile/kensai/d5_k2bsw.spl~ ~override~
	SAY NAME1 @2633
	SAY UNIDENTIFIED_DESC @2633
COPY ~might_and_guile/kensai/d5_k2lsw.spl~ ~override~
	SAY NAME1 @2634
	SAY UNIDENTIFIED_DESC @2634
COPY ~might_and_guile/kensai/d5_k2kat.spl~ ~override~
	SAY NAME1 @2635
	SAY UNIDENTIFIED_DESC @2635
COPY ~might_and_guile/kensai/d5_k2sci.spl~ ~override~
	SAY NAME1 @2636
	SAY UNIDENTIFIED_DESC @2636
COPY ~might_and_guile/kensai/d5_k2ssw.spl~ ~override~
	SAY NAME1 @2637
	SAY UNIDENTIFIED_DESC @2637
COPY ~might_and_guile/kensai/d5_k22sw.spl~ ~override~
	SAY NAME1 @2638
	SAY UNIDENTIFIED_DESC @2638
COPY ~might_and_guile/kensai/d5_k2dag.spl~ ~override~
	SAY NAME1 @2639
	SAY UNIDENTIFIED_DESC @2639
COPY ~might_and_guile/kensai/d5_k2bax.spl~ ~override~
	SAY NAME1 @2640
	SAY UNIDENTIFIED_DESC @2640
COPY ~might_and_guile/kensai/d5_k2ham.spl~ ~override~
	SAY NAME1 @2641
	SAY UNIDENTIFIED_DESC @2641
COPY ~might_and_guile/kensai/d5_k2fla.spl~ ~override~
	SAY NAME1 @2642
	SAY UNIDENTIFIED_DESC @2642
COPY ~might_and_guile/kensai/d5_k2mac.spl~ ~override~
	SAY NAME1 @2643
	SAY UNIDENTIFIED_DESC @2643
COPY ~might_and_guile/kensai/d5_k2clu.spl~ ~override~
	SAY NAME1 @2644
	SAY UNIDENTIFIED_DESC @2644
COPY ~might_and_guile/kensai/d5_k2sta.spl~ ~override~
	SAY NAME1 @2645
	SAY UNIDENTIFIED_DESC @2645
COPY ~might_and_guile/kensai/d5_k2spe.spl~ ~override~
	SAY NAME1 @2646
	SAY UNIDENTIFIED_DESC @2646
COPY ~might_and_guile/kensai/d5_k2hal.spl~ ~override~
	SAY NAME1 @2647
	SAY UNIDENTIFIED_DESC @2647
COPY ~might_and_guile/kensai/d5_k3lsw.spl~ ~override~
	SAY NAME1 @2634
	SAY UNIDENTIFIED_DESC @2634
COPY ~might_and_guile/kensai/d5_k3sci.spl~ ~override~
	SAY NAME1 @2636
	SAY UNIDENTIFIED_DESC @2636
COPY ~might_and_guile/kensai/d5_k3ssw.spl~ ~override~
	SAY NAME1 @2637
	SAY UNIDENTIFIED_DESC @2637
COPY ~might_and_guile/kensai/d5_k32sw.spl~ ~override~
	SAY NAME1 @2638
	SAY UNIDENTIFIED_DESC @2638
COPY ~might_and_guile/kensai/d5_k3dag.spl~ ~override~
	SAY NAME1 @2639
	SAY UNIDENTIFIED_DESC @2639
COPY ~might_and_guile/kensai/d5_k3bax.spl~ ~override~
	SAY NAME1 @2640
	SAY UNIDENTIFIED_DESC @2640
COPY ~might_and_guile/kensai/d5_k3ham.spl~ ~override~
	SAY NAME1 @2641
	SAY UNIDENTIFIED_DESC @2641
COPY ~might_and_guile/kensai/d5_k3fla.spl~ ~override~
	SAY NAME1 @2642
	SAY UNIDENTIFIED_DESC @2642
COPY ~might_and_guile/kensai/d5_k3mac.spl~ ~override~
	SAY NAME1 @2643
	SAY UNIDENTIFIED_DESC @2643
COPY ~might_and_guile/kensai/d5_k3clu.spl~ ~override~
	SAY NAME1 @2644
	SAY UNIDENTIFIED_DESC @2644
COPY ~might_and_guile/kensai/d5_k3sta.spl~ ~override~
	SAY NAME1 @2645
	SAY UNIDENTIFIED_DESC @2645
COPY ~might_and_guile/kensai/d5_k3spe.spl~ ~override~
	SAY NAME1 @2646
	SAY UNIDENTIFIED_DESC @2646
COPY ~might_and_guile/kensai/d5_kbswo.cre~ ~override~
COPY ~might_and_guile/kensai/d5_klswo.cre~ ~override~
COPY ~might_and_guile/kensai/d5_kkata.cre~ ~override~
COPY ~might_and_guile/kensai/d5_kscim.cre~ ~override~
COPY ~might_and_guile/kensai/d5_ksswo.cre~ ~override~
COPY ~might_and_guile/kensai/d5_k2swo.cre~ ~override~
COPY ~might_and_guile/kensai/d5_kdagg.cre~ ~override~
COPY ~might_and_guile/kensai/d5_kbaxe.cre~ ~override~
COPY ~might_and_guile/kensai/d5_khamm.cre~ ~override~
COPY ~might_and_guile/kensai/d5_kflai.cre~ ~override~
COPY ~might_and_guile/kensai/d5_kmace.cre~ ~override~
COPY ~might_and_guile/kensai/d5_kclub.cre~ ~override~
COPY ~might_and_guile/kensai/d5_kstaf.cre~ ~override~
COPY ~might_and_guile/kensai/d5_kspea.cre~ ~override~
COPY ~might_and_guile/kensai/d5_khalb.cre~ ~override~
COMPILE ~might_and_guile/kensai/d5_klswo.baf~
COMPILE ~might_and_guile/kensai/d5_kscim.baf~
COMPILE ~might_and_guile/kensai/d5_ksswo.baf~
COMPILE ~might_and_guile/kensai/d5_k2swo.baf~
COMPILE ~might_and_guile/kensai/d5_kdagg.baf~
COMPILE ~might_and_guile/kensai/d5_kbaxe.baf~
COMPILE ~might_and_guile/kensai/d5_khamm.baf~
COMPILE ~might_and_guile/kensai/d5_kflai.baf~
COMPILE ~might_and_guile/kensai/d5_kmace.baf~
COMPILE ~might_and_guile/kensai/d5_kclub.baf~
COMPILE ~might_and_guile/kensai/d5_kstaf.baf~
COMPILE ~might_and_guile/kensai/d5_kspea.baf~
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
	COMPILE ~might_and_guile/kensai/d5_kbswo.baf~
	COMPILE ~might_and_guile/kensai/d5_kkata.baf~
	COMPILE ~might_and_guile/kensai/d5_khalb.baf~
END
/*
ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
	COPY_EXISTING ~d5_klswo.2da~ ~override~
				 ~d5_kscim.2da~ ~override~
				 ~d5_ksswo.2da~ ~override~
				 ~d5_k2swo.2da~ ~override~
				 ~d5_kdagg.2da~ ~override~
				 ~d5_kbaxe.2da~ ~override~
				 ~d5_khamm.2da~ ~override~
				 ~d5_kflai.2da~ ~override~
				 ~d5_kmace.2da~ ~override~
				 ~d5_kclub.2da~ ~override~
				 ~d5_kstaf.2da~ ~override~
				 ~d5_kspea.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/profs/w2apr.txt~
		BUT_ONLY
END
*/
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
	ACTION_IF (FILE_EXISTS_IN_GAME ~d5_apr.d5~) OR (FILE_EXISTS_IN_GAME ~TB#TATT.spl~) THEN BEGIN
		COPY_EXISTING ~d5_kbswo.2da~ ~override~
					 ~d5_klswo.2da~ ~override~
					 ~d5_kkata.2da~ ~override~
					 ~d5_kscim.2da~ ~override~
					 ~d5_ksswo.2da~ ~override~
					 ~d5_k2swo.2da~ ~override~
					 ~d5_kdagg.2da~ ~override~
					 ~d5_kbaxe.2da~ ~override~
					 ~d5_khamm.2da~ ~override~
					 ~d5_kflai.2da~ ~override~
					 ~d5_kmace.2da~ ~override~
					 ~d5_kclub.2da~ ~override~
					 ~d5_kstaf.2da~ ~override~
					 ~d5_kspea.2da~ ~override~
					 ~d5_khalb.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/profs/w1apr.txt~
			BUT_ONLY
	END
END
//______________________________________________________________________________

//__________________________________________________________________________________
COPY_EXISTING ~WEAPPROF.2da~ ~override~
//	SET_2DA_ENTRY 3 32 1 ~2~
//	SET_2DA_ENTRY 4 32 1 ~2~
//	SET_2DA_ENTRY 5 32 1 ~2~
//	SET_2DA_ENTRY 6 32 1 ~2~
//	SET_2DA_ENTRY 7 32 1 ~2~
//	SET_2DA_ENTRY 8 32 1 ~2~
//	SET_2DA_ENTRY 9 32 1 ~2~
//	SET_2DA_ENTRY 10 32 1 ~2~
//	SET_2DA_ENTRY 11 32 1 ~2~
//	SET_2DA_ENTRY 12 32 1 ~2~
//	SET_2DA_ENTRY 13 32 1 ~2~
//	SET_2DA_ENTRY 14 32 1 ~2~
//	SET_2DA_ENTRY 15 32 1 ~2~
//	SET_2DA_ENTRY 16 32 1 ~2~
//	SET_2DA_ENTRY 17 32 1 ~2~
//	SET_2DA_ENTRY 18 32 1 ~2~
//	SET_2DA_ENTRY 19 32 1 ~2~
//	SET_2DA_ENTRY 20 32 1 ~2~
//	SET_2DA_ENTRY 21 32 1 ~2~
//	SET_2DA_ENTRY 22 32 1 ~2~
//	SET_2DA_ENTRY 23 32 1 ~2~
//	SET_2DA_ENTRY 24 32 1 ~2~
//	SET_2DA_ENTRY 25 32 1 ~2~
	SET_2DA_ENTRY 31 32 1 ~0~
	SET_2DA_ENTRY 32 32 1 ~0~
	SET_2DA_ENTRY 33 32 1 ~0~
	SET_2DA_ENTRY 34 32 1 ~0~
//	BUT_ONLY
//__________________________________________________________________________________


//EDIT STRINGS______________________________________________________________________
ACTION_IF GAME_IS ~bgee~ THEN BEGIN
	STRING_SET 25362 @2648
END
ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
	STRING_SET 25204 @2648
END
ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
	STRING_SET 37100 @2648
END
//__________________________________________________________________________________

//NPC KENSAI________________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~chloe7.cre~ THEN BEGIN
	COPY_EXISTING ~chloe7.cre~ ~override~
				~chloe9.cre~ ~override~
				~chloe13.cre~ ~override~
				~chloe15.cre~ ~override~
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_KENFO~ END
END
ACTION_IF FILE_EXISTS_IN_GAME ~nath07.cre~ THEN BEGIN
	COPY_EXISTING ~nath07.cre~ ~override~
				~nath08.cre~ ~override~
				~nath10.cre~ ~override~
				~nath25.cre~ ~override~
		LPF ADD_CRE_EFFECT INT_VAR opcode=171 target=1 timing=9 power=1 STR_VAR resource=~d5_KENFO~ END
END
//__________________________________________________________________________________

//______________________HLAS________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~TG#TOUG.spl~ THEN BEGIN
	COPY_EXISTING ~LUFI0.2da~ ~override/LUFI4.2da~	
END
//__________________________________________________________________________________
