
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						    	MONK FIST TWEAKS
//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_FUNCTION revised_monk_fists_ee BEGIN

//COPY MARKER FILE_________________________________________________________________
//
COPY ~might_and_guile/lib/markers/d5_marker.d5~ ~override/d5__mfist.d5~
//__________________________________________________________________________________


//CHANGE MONK FISTS_________________________________________________________________
//
COPY ~might_and_guile/monk/mfist1.itm~ ~override~
COPY ~might_and_guile/monk/mfist2.itm~ ~override~
COPY ~might_and_guile/monk/mfist3.itm~ ~override~
COPY ~might_and_guile/monk/mfist4.itm~ ~override~
COPY ~might_and_guile/monk/mfist5.itm~ ~override~
COPY ~might_and_guile/monk/mfist6.itm~ ~override~
COPY ~might_and_guile/monk/mfist7.itm~ ~override~
COPY ~might_and_guile/monk/mfist8.itm~ ~override~
/*
	SAY NAME1 @2655
	SAY NAME2 @2655
*/

COPY ~might_and_guile/monk/d5mfst.bam~ ~override~

COPY ~might_and_guile/monk/d5mfst1.spl~ ~override~
COPY ~might_and_guile/monk/d5mfst2.spl~ ~override~
COPY ~might_and_guile/monk/d5mfst3.spl~ ~override~
COPY ~might_and_guile/monk/d5mfst4.spl~ ~override~
COPY ~might_and_guile/monk/d5mfst1.eff~ ~override~
COPY ~might_and_guile/monk/d5mfst2.eff~ ~override~
COPY ~might_and_guile/monk/d5mfst3.eff~ ~override~
COPY ~might_and_guile/monk/d5mfst4.eff~ ~override~
/*
	SAY NAME1 @2653
	SAY UNIDENTIFIED_DESC @2654
*/
COPY ~might_and_guile/monk/d5nfist.spl~ ~override~
	SAY NAME1 @2655
	SAY UNIDENTIFIED_DESC @2656

COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  PATCH_IF (~%SOURCE_SIZE%~ > ~0x71~) BEGIN
	READ_BYTE 0x31 prof
	PATCH_IF (prof = 89) || (prof = 90) || (prof = 91) || (prof = 91) || (prof = 93) || (prof = 94) || (prof = 95) || (prof = 96) || (prof = 97) || (prof = 98) || (prof = 99) || (prof = 100) || (prof = 101) || (prof = 102) || (prof = 103) || (prof = 104) || (prof = 105) || (prof = 106) || (prof = 107) BEGIN
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5mfst1~ END
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5mfst2~ END
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5mfst3~ END
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 321 target = 1 timing = 1 STR_VAR resource = ~d5mfst4~ END
	  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 172 target = 1 timing = 1 STR_VAR resource = ~d5nfist~ END
	END
  END
BUT_ONLY

/*
ACTION_FOR_EACH monk_kit IN ~clabmo01~ ~QDMONK~ ~QDMONKSS~ ~QDMONKDM~ ~QDMONKHF~ ~QDMONKSH~ ~QDMONKLD~ ~QDMONKBO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%monk_kit%.2da~ BEGIN
	  COPY_EXISTING ~%monk_kit%.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/monk/mfist.txt~
	  BUT_ONLY
	END
END

COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~10~ "rows"
	FOR ( index = 1 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 10 modclab
		READ_2DA_ENTRY %index% 8 10 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_monk_clabs BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY
ACTION_PHP_EACH d5_monk_clabs AS woo => soo BEGIN
	ACTION_IF (%soo% = 20) AND (FILE_EXISTS_IN_GAME ~%woo%.2da~) THEN BEGIN
		COPY_EXISTING ~%woo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/monk/mfist.txt~
		BUT_ONLY
	END
END
*/
//__________________________________________________________________________________


//UPDATE EXISTING STRINGS__________________________________________________________
// 
ACTION_FOR_EACH text_file IN ~clastext~ ~sodcltxt~ ~bgclatxt~ BEGIN
  COPY_EXISTING ~%text_file%.2da~ ~override~
    COUNT_2DA_COLS cols
    COUNT_2DA_ROWS cols rows
    FOR (row = 1; row < rows; ++row) BEGIN
      READ_2DA_ENTRY row 0 cols kit_name
      PATCH_IF (~%kit_name%~ STRING_EQUAL_CASE ~MONK~) BEGIN
        SET_2DA_ENTRY row 4 cols RESOLVE_STR_REF (@2651)
      END
    END
  IF_EXISTS BUT_ONLY
END
//__________________________________________________________________________________


//MONASTIC ORDERS OF FAERUN 0.3 COMPATIBILITY_______________________________________
// 
ACTION_IF FILE_EXISTS_IN_GAME ~qdmnk02.2da~ THEN BEGIN
	COPY_EXISTING ~qdmnk02.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
	ACTION_IF FILE_EXISTS_IN_GAME ~clabmo02.2da~ THEN BEGIN
		COPY_EXISTING ~clabmo02.2da~ ~override~
			REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
			REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
			BUT_ONLY
	END
	ACTION_IF FILE_EXISTS_IN_GAME ~clabmo03.2da~ THEN BEGIN
	COPY_EXISTING ~clabmo03.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
	END
END
ACTION_IF FILE_EXISTS_IN_GAME ~qdbrkone.2da~ THEN BEGIN
	COPY_EXISTING ~qdbrkone.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~qdhinfst.2da~ THEN BEGIN
	COPY_EXISTING ~qdhinfst.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~qdlngdth.2da~ THEN BEGIN
	COPY_EXISTING ~qdlngdth.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~qdoldord.2da~ THEN BEGIN
	COPY_EXISTING ~qdoldord.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~qdshnhnd.2da~ THEN BEGIN
	COPY_EXISTING ~qdshnhnd.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
END

END	//	end new function


//__________________________________________________________________________________
//__________________________________________________________________________________


// old monk fists

DEFINE_ACTION_FUNCTION old_monk_fists BEGIN

COPY ~might_and_guile/monk/mfist1.itm~ ~override~
	SAY NAME1 @2655
	SAY NAME2 @2655
COPY ~might_and_guile/monk/mfist2.itm~ ~override~
	SAY NAME1 @2655
	SAY NAME2 @2655
COPY ~might_and_guile/monk/mfist3.itm~ ~override~
	SAY NAME1 @2655
	SAY NAME2 @2655
COPY ~might_and_guile/monk/mfist4.itm~ ~override~
	SAY NAME1 @2655
	SAY NAME2 @2655
COPY ~might_and_guile/monk/mfist5.itm~ ~override~
	SAY NAME1 @2655
	SAY NAME2 @2655
COPY ~might_and_guile/monk/mfist6.itm~ ~override~
	SAY NAME1 @2655
	SAY NAME2 @2655
COPY ~might_and_guile/monk/mfist7.itm~ ~override~
	SAY NAME1 @2655
	SAY NAME2 @2655
COPY ~might_and_guile/monk/mfist8.itm~ ~override~
	SAY NAME1 @2655
	SAY NAME2 @2655

COPY ~might_and_guile/monk/d5mfist1.itm~ ~override~
	SAY NAME1 @2653
	SAY NAME2 @2653
COPY ~might_and_guile/monk/d5mfist2.itm~ ~override~
	SAY NAME1 @2653
	SAY NAME2 @2653
COPY ~might_and_guile/monk/d5mfist3.itm~ ~override~
	SAY NAME1 @2653
	SAY NAME2 @2653
COPY ~might_and_guile/monk/d5mfist4.itm~ ~override~
	SAY NAME1 @2653
	SAY NAME2 @2653
COPY ~might_and_guile/monk/d5mfist5.itm~ ~override~
	SAY NAME1 @2653
	SAY NAME2 @2653
COPY ~might_and_guile/monk/d5mfist6.itm~ ~override~
	SAY NAME1 @2653
	SAY NAME2 @2653
COPY ~might_and_guile/monk/d5mfist7.itm~ ~override~
	SAY NAME1 @2653
	SAY NAME2 @2653
COPY ~might_and_guile/monk/d5mfist8.itm~ ~override~
	SAY NAME1 @2653
	SAY NAME2 @2653

COPY ~might_and_guile/monk/d5_mfist.spl~ ~override~
	SAY NAME1 @2653
	SAY UNIDENTIFIED_DESC @2654
COPY ~might_and_guile/monk/d5_nofst.spl~ ~override~
	SAY NAME1 @2655
	SAY UNIDENTIFIED_DESC @2656

ACTION_FOR_EACH monk_kit IN ~clabmo01~ ~QDMONK~ ~QDMONKSS~ ~QDMONKDM~ ~QDMONKHF~ ~QDMONKSH~ ~QDMONKLD~ ~QDMONKBO~ BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%monk_kit%.2da~ BEGIN
	  COPY_EXISTING ~%monk_kit%.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/monk/mfist.txt~
	  BUT_ONLY
	END
END

COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~10~ "rows"
	FOR ( index = 1 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 10 modclab
		READ_2DA_ENTRY %index% 8 10 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_monk_clabs BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY
ACTION_PHP_EACH d5_monk_clabs AS woo => soo BEGIN
	ACTION_IF (%soo% = 20) AND (FILE_EXISTS_IN_GAME ~%woo%.2da~) THEN BEGIN
		COPY_EXISTING ~%woo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/monk/mfist.txt~
		BUT_ONLY
	END
END
//__________________________________________________________________________________


//UPDATE EXISTING STRINGS__________________________________________________________
// 
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5__mro.d5~ THEN BEGIN
 ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~MONK~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@2651)
	  END
	END
  BUT_ONLY
 END
 ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
  COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~MONK~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@2651)
	  END
	END
  BUT_ONLY
 END
//ACTION_IF ENGINE_IS ~tob~ BEGIN
//	STRING_SET 45867 @2651
//END
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5__mro.d5~ THEN BEGIN
 ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~MONK~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@2652)
	  END
	END
  BUT_ONLY
 END
 ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
  COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~MONK~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@2652)
	  END
	END
  BUT_ONLY
 END
//ACTION_IF ENGINE_IS ~tob~ BEGIN
//	STRING_SET 45867 @2652
//END
END
//__________________________________________________________________________________


//MONASTIC ORDERS OF FAERUN 0.3 COMPATIBILITY_______________________________________
// 
ACTION_IF FILE_EXISTS_IN_GAME ~qdmnk02.2da~ THEN BEGIN
	COPY_EXISTING ~qdmnk02.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
	ACTION_IF FILE_EXISTS_IN_GAME ~clabmo02.2da~ THEN BEGIN
		COPY_EXISTING ~clabmo02.2da~ ~override~
			REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
			REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
			BUT_ONLY
	END
	ACTION_IF FILE_EXISTS_IN_GAME ~clabmo03.2da~ THEN BEGIN
	COPY_EXISTING ~clabmo03.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
	END
END
ACTION_IF FILE_EXISTS_IN_GAME ~qdbrkone.2da~ THEN BEGIN
	COPY_EXISTING ~qdbrkone.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~qdhinfst.2da~ THEN BEGIN
	COPY_EXISTING ~qdhinfst.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~qdlngdth.2da~ THEN BEGIN
	COPY_EXISTING ~qdlngdth.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~qdoldord.2da~ THEN BEGIN
	COPY_EXISTING ~qdoldord.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~qdshnhnd.2da~ THEN BEGIN
	COPY_EXISTING ~qdshnhnd.2da~ ~override~
		REPLACE_TEXTUALLY ~AP_QDMNK02~ ~****      ~
		REPLACE_TEXTUALLY ~AP_QDMNK03~ ~****       ~
		BUT_ONLY
END


END	//	end new function
