
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						REVISED SHADOWDANCER
//__________________________________________________________________________________
//__________________________________________________________________________________


//UPDATE KIT STRINGS_______________________________________________________________
// 
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
	ACTION_IF GAME_IS ~bgee~ THEN BEGIN
		STRING_SET 31972 @2751
	END
	ACTION_IF ENGINE_IS ~tob bg2ee~ THEN BEGIN
		STRING_SET 25220 @2751
	END
	ACTION_IF ENGINE_IS ~iwdee~ THEN BEGIN
		STRING_SET 37246 @2751
	END
END
//___________________________________________________________________________________


//NEW SHADOWDANCER KIT_______________________________________________________________
// 
COPY_KIT SHADOWDANCER D5SHADOWDANCER ( CLAB ~might_and_guile/thief/d5_shadd.2da~ )
//___________________________________________________________________________________


//COPY SHADOW POOL FILES_____________________________________________________________
//
COPY_EXISTING ~clabth05.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~might_and_guile/thief/shadowdance.txt~
	BUT_ONLY
COPY ~might_and_guile/thief/d5_shadd.2da~ ~override~
COPY ~might_and_guile/thief/d5_shad1.spl~ ~override~
	SAY NAME1 @2752
	SAY UNIDENTIFIED_DESC @2753
COPY ~might_and_guile/thief/d5_shad1.2da~ ~override~
COPY ~might_and_guile/thief/d5_shadd.spl~ ~override~
	SAY NAME1 @9
COPY ~might_and_guile/thief/d5_shadd.cre~ ~override~
COMPILE ~might_and_guile/thief/d5_shadd.baf~
//__________________________________________________________________________________


