
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						  			MARKSMAN
//__________________________________________________________________________________
//__________________________________________________________________________________


//ADD MARKSMAN_______________________________________________________________________

LAF check_kit_conflict END

ADD_KIT ~D5MARKS~

//WEAPON PROFICIENCIES_______________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MARKS       0 0 0 0 0 0 0 0~
~D5MARKS       0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 5 5 5 2 2 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MARKS           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MARKS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT__________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MARKS           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MARKS           15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MARKS           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MARKS           0  1  1  1  1  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/fighter/d5_marks.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_F_H K_F_G K_F_D K_F_HE K_F_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x40000000 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @3202
SAY @3203
SAY @3204
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@3204)
		STR_VAR
			kit_name = D5MARKS
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//MARKSMAN ABILITY FILES______________________________________________________________
//
COPY ~might_and_guile/fighter/d5_marks.2da~ ~override~

COPY ~might_and_guile/misc/d5_mthac.spl~ ~override~
//___________________________________________________________________________________

//WILD TALENT_________________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_psionics.d5~) BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5_marks.2da~) BEGIN
	APPEND ~d5_marks.2da~ ~WILD_TLNT   AP_D5PSWT_  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
  END
END
//____________________________________________________________________________________


// get kit identifiers________________________________________________________________
//
OUTER_SET marksman_code = (0x4000 + %D5MARKS%)
//____________________________________________________________________________________

/*
//REVISED ARCHERY____________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rarchery.d5~ BEGIN

  COPY_EXISTING ~d5_marks.2da~ ~override~
	REPLACE_TEXTUALLY ~GA_SPCL121~ ~****      ~
	REPLACE_TEXTUALLY ~AP_SPCL122~ ~****      ~
	LPM remove_blank_lines
	APPEND_FILE ~might_and_guile/feats/feats_archer.txt~
  APPEND ~d5_marks.2da~ ~ABILITY1    ****        ****        AP_D5_MTHAC ****        ****        AP_D5_MTHAC ****        ****        ****        AP_D5_MTHAC ****        ****        ****        ****        AP_D5_MTHAC ****        ****        ****        ****        ****        AP_D5_MTHAC ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

  ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
   COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols  
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ 
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5MARKS~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@3206)
	  END
	END
   BUT_ONLY
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
   COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols 
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ 
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5MARKS~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@3206)
	  END
	END
   BUT_ONLY
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~kitlist.2da~) BEGIN
   COPY_EXISTING ~kitlist.2da~ ~override~
//	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows 9
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~text~
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5MARKS~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 9 RESOLVE_STR_REF (@3206)
	  END
	END
   BUT_ONLY
  END

  INCLUDE ~might_and_guile/lib/sequencer_menu_d5.tpa~

  APPEND ~splprot.2da~ ~D5_KIT_IS%TAB%152%TAB%-1%TAB%1~ UNLESS ~D5_KIT_IS~
  COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW r2en_splprot cols
	FOR (row = 1; row < r2en_splprot; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER r2en_splprot row 0 ~stat~
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_KIT_IS~ BEGIN
	    SET kit_is_row = %row%
	  END
	END
  BUT_ONLY

  OUTER_SPRINT feat_select_string @20011 // ~Feat Selection~ 
  OUTER_SET feat_select_strref = RESOLVE_STR_REF (%feat_select_string%)
  OUTER_SPRINT feat_title_string @20012 
  OUTER_SPRINT feat_label_string @20013 

  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_rfeat.d5~) BEGIN
	ACTION_IF !(FILE_EXISTS_IN_GAME ~d5flsta.2da~) BEGIN
	  COPY ~might_and_guile/feats/d5flsta.2da~ ~override~
	END
   COPY_EXISTING ~kitlist.2da~ ~override~
	READ_2DA_ENTRIES_NOW r2en_kitlist 10
	FOR (row = 2; row < r2en_kitlist; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER r2en_kitlist row 5 kitlist_2da
	  PATCH_IF (~%kitlist_2da%~ STRING_EQUAL_CASE ~d5_marks~) BEGIN
		READ_2DA_ENTRY_FORMER r2en_kitlist row 0 kitlist_index
		READ_2DA_ENTRY_FORMER r2en_kitlist row 3 kitlist_name
		READ_2DA_ENTRY_FORMER r2en_kitlist row 9 kitids_num
		GET_STRREF %kitlist_name% kit_name_strref
		SPRINT feat_select_name ~%kit_name_strref% %feat_select_string%~
		SET kit_seq_name = RESOLVE_STR_REF (~%feat_select_name%~) 
		SET kit_seq_tip = RESOLVE_STR_REF (~%feat_select_name%~) 
		SET kit_seq_index = %kitlist_index% 
		INNER_ACTION BEGIN
		  COPY_EXISTING ~d5flsta.2da~ ~override~
			COUNT_2DA_COLS cols
			COUNT_2DA_ROWS cols rows
			FOR (col = 1; col < (cols - 1); ++col) BEGIN
			  READ_2DA_ENTRY 0 (col - 1) (cols - 1) feat_kit_2da
			  PATCH_IF (~%feat_kit_2da%~ STRING_EQUAL_CASE ~d5_marks~) BEGIN
				SET this_col = %col%
				INNER_ACTION BEGIN
				  LAF CREATE_SEQUENCER_MENU 
				   INT_VAR 
					name = %kit_seq_name%
					tip = %kit_seq_tip%
					desc = RESOLVE_STR_REF (~blah~) 
					column = %this_col% 
					class = 2
				   STR_VAR 
					resref = EVAL ~d5ft%kit_seq_index%~
					icon = ~spcl919b~
					spelltable = ~d5ftskn~ 
					spelllist = ~d5flsta~
					title = EVAL ~%feat_title_string%~
					label = EVAL ~%feat_label_string%~
				  END
				  COPY_EXISTING ~d5ft%kit_seq_index%.spl~ ~override~
					LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~d5ft%kit_seq_index%~ END
				  IF_EXISTS BUT_ONLY
				  ACTION_FOR_EACH letter IN ~A~ ~B~ ~C~ ~D~ ~E~ ~F~ ~G~ ~H~ ~I~ ~J~ ~K~ ~L~ ~M~ ~N~ ~O~ ~P~ ~Q~ ~R~ ~S~ ~T~ BEGIN
					COPY_EXISTING ~d5feat%letter%.spl~ ~override~
					  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %marksman_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~d5ft%kit_seq_index%~ END
					IF_EXISTS BUT_ONLY
				  END
				END
			  END
			END
		  BUT_ONLY
		END
	  END
	END
   BUT_ONLY
   COPY_EXISTING ~d5flsta.2da~ ~override~
	COUNT_2DA_COLS cols
	COUNT_2DA_ROWS cols rows
	FOR (row = 1; row < rows; ++row) BEGIN
  	  READ_2DA_ENTRY row 0 cols ~book_feat~
	  INNER_ACTION BEGIN
		COPY_EXISTING ~%book_feat%.spl~ ~override/%book_feat%L.spl~
		  WRITE_SHORT 0x1c 4
		  WRITE_LONG 0x34 1
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%book_feat%~ END
		IF_EXISTS BUT_ONLY
	  END
	END
   BUT_ONLY
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5_rfeat.d5~) BEGIN
   ACTION_IF !(FILE_EXISTS_IN_GAME ~d5flstaf.2da~) BEGIN
	COPY ~might_and_guile/feats/d5flstaf.2da~ ~override~
   END
   COPY_EXISTING ~kitlist.2da~ ~override~
	READ_2DA_ENTRIES_NOW r2en_kitlist 10
	FOR (row = 2; row < r2en_kitlist; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER r2en_kitlist row 5 kitlist_2da
	  PATCH_IF (~%kitlist_2da%~ STRING_EQUAL_CASE ~d5_marks~) BEGIN
		READ_2DA_ENTRY_FORMER r2en_kitlist row 0 kitlist_index
		READ_2DA_ENTRY_FORMER r2en_kitlist row 3 kitlist_name
		READ_2DA_ENTRY_FORMER r2en_kitlist row 9 kitids_num
		GET_STRREF %kitlist_name% kit_name_strref
		SPRINT feat_select_name ~%kit_name_strref% %feat_select_string%~
		SET kit_seq_name = RESOLVE_STR_REF (~%feat_select_name%~) 
		SET kit_seq_tip = RESOLVE_STR_REF (~%feat_select_name%~) 
		SET kit_seq_index = %kitlist_index% 
		INNER_ACTION BEGIN
		  COPY_EXISTING ~d5flstaf.2da~ ~override~
			COUNT_2DA_COLS cols
			COUNT_2DA_ROWS cols rows
			FOR (col = 1; col < (cols - 1); ++col) BEGIN
			  READ_2DA_ENTRY 0 (col - 1) (cols - 1) feat_kit_2da
			  PATCH_IF (~%feat_kit_2da%~ STRING_EQUAL_CASE ~d5_marks~) BEGIN
				SET this_col = %col%
				INNER_ACTION BEGIN
				  LAF CREATE_SEQUENCER_MENU 
				   INT_VAR 
					name = %kit_seq_name%
					tip = %kit_seq_tip%
					desc = RESOLVE_STR_REF (~blah~) 
					column = %this_col% 
					class = 2
				   STR_VAR 
					resref = EVAL ~d5ft%kit_seq_index%~
					icon = ~spcl919b~
					spelltable = ~d5ftskn~ 
					spelllist = ~d5flstaf~
					title = EVAL ~%feat_title_string%~
					label = EVAL ~%feat_label_string%~
				  END
				  COPY_EXISTING ~d5ft%kit_seq_index%.spl~ ~override~
					LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~d5ft%kit_seq_index%~ END
				  IF_EXISTS BUT_ONLY
				  ACTION_FOR_EACH letter IN ~A~ ~B~ ~C~ ~D~ ~E~ ~F~ ~G~ ~H~ ~I~ ~J~ ~K~ ~L~ ~M~ ~N~ ~O~ ~P~ ~Q~ ~R~ ~S~ ~T~ BEGIN
					COPY_EXISTING ~d5feat%letter%.spl~ ~override~
					  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %marksman_code% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~d5ft%kit_seq_index%~ END
					IF_EXISTS BUT_ONLY
				  END
				END
			  END
			END
		  BUT_ONLY
		END
	  END
	END
   BUT_ONLY
   COPY_EXISTING ~d5flstaf.2da~ ~override~
	COUNT_2DA_COLS cols
	COUNT_2DA_ROWS cols rows
	FOR (row = 1; row < rows; ++row) BEGIN
  	  READ_2DA_ENTRY row 0 cols ~book_feat~
	  INNER_ACTION BEGIN
		COPY_EXISTING ~%book_feat%.spl~ ~override/%book_feat%L.spl~
		  WRITE_SHORT 0x1c 4
		  WRITE_LONG 0x34 1
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%book_feat%~ END
		IF_EXISTS BUT_ONLY
	  END
	END
   BUT_ONLY
  END

END
//___________________________________________________________________________________
*/

/*
	WHAT WAS THE PURPOSE OF THIS???
//FIX BARB USABILITY__________________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
		READ_BYTE 0x1f class
		READ_BYTE 0x29 kit
		PATCH_IF (%kit% BAND 0b01000000 = 0b01000000) BEGIN
			PATCH_IF (%class% BAND 0b00001000 = 0b00001000) BEGIN
				WRITE_BYTE 0x29 (%kit% BAND 0b10111111) 
			END
		END
	END
BUT_ONLY
//____________________________________________________________________________________
*/
