
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						HALFLING SLINGER
//__________________________________________________________________________________
//__________________________________________________________________________________


//___________________________________________________________________________________
//
ACTION_IF ENGINE_IS ~tob~ THEN BEGIN
	COPY_EXISTING ~K_R_HL.2da~ ~override~
		SET_2DA_ENTRY 2 1 2 ~0~
		SET_2DA_ENTRY 3 1 2 ~0~
		SET_2DA_ENTRY 4 1 2 ~0~
	BUT_ONLY
END
//___________________________________________________________________________________

ACTION_IF FILE_EXISTS_IN_GAME ~CLSRCREQ.2da~ THEN BEGIN

	ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
		COPY_EXISTING ~clsrcreq.2da~ ~override~
			SET_2DA_ENTRY 42 5 8 ~1~
		BUT_ONLY
	END
	ACTION_IF ENGINE_IS ~tob~ THEN BEGIN
		COPY_EXISTING ~clsrcreq.2da~ ~override~
			SET_2DA_ENTRY 7 5 8 ~1~
		BUT_ONLY
	END

	COPY_EXISTING ~clabrn01.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/ranger/halfnosp.txt~
	BUT_ONLY

//ADD SLINGER RANGER_________________________________________________________________

ADD_KIT ~D5SLING~

//WEAPON PROFICIENCIES_______________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5SLING       0 0 0 0 0 0 0 0~
~D5SLING       0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 5 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           9   12  9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5SLING           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5SLING           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/ranger/d5_sling.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00008000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ra2~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @3241
SAY @3242
SAY @3243
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@3243)
		STR_VAR
			kit_name = D5SLING
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~CLSRCREQ.2da~ THEN BEGIN

//ADD SLINGER FIGHTER_________________________________________________________________

ADD_KIT ~D5SLING~

//WEAPON PROFICIENCIES_______________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5SLING       0 0 0 0 0 0 0 0~
~D5SLING       0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 5 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           9   12  9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SLING           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5SLING           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5SLING           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/ranger/d5_sling.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_F_HL~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x40000000 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG24 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @3241
SAY @3242
SAY @3243
//___________________________________________________________________________________

END

//ARCHER+SLINGER ABILITY FILES________________________________________________________
//
COPY ~might_and_guile/ranger/d5_sling.2da~ ~override~
COPY ~might_and_guile/ranger/d5_pslin.spl~ ~override~
COPY ~might_and_guile/ranger/d5_rnosp.eff~ ~override~
COPY ~might_and_guile/ranger/d5_rnosp.spl~ ~override~
COPY ~might_and_guile/ranger/d5_hnosp.eff~ ~override~
COPY ~might_and_guile/ranger/d5_hnosp.spl~ ~override~

COPY ~might_and_guile/misc/d5_mthac.spl~ ~override~
//___________________________________________________________________________________


//REVISED ARCHERY____________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rarchery.d5~ BEGIN
 ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_archy.d5~ BEGIN
  INCLUDE ~might_and_guile/lib/archery_feats.tpa~
 END
 COPY_EXISTING ~d5_sling.2da~ ~override~
  REPLACE_TEXTUALLY ~GA_SPCL121~ ~****      ~
  REPLACE_TEXTUALLY ~AP_SPCL122~ ~****      ~
 APPEND ~d5_sling.2da~ ~ABILITY1    ****        ****        AP_D5_MTHAC ****        ****        AP_D5_MTHAC ****        ****        ****        AP_D5_MTHAC ****        ****        ****        ****        AP_D5_MTHAC ****        ****        ****        ****        ****        AP_D5_MTHAC ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~

 ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ THEN BEGIN
  COPY_EXISTING ~d5_sling.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~might_and_guile/ranger/slinger_shots.txt~
  BUT_ONLY
  ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
   COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5SLING~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@3244)
	  END
	END
   BUT_ONLY
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
   COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5SLING~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@3244)
	  END
	END
   BUT_ONLY
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~kitlist.2da~) BEGIN
   COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 1 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5SLING~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@3244)
	  END
	END
   BUT_ONLY
  END
 END

 ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ THEN BEGIN
  COPY_EXISTING ~d5_sling.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~might_and_guile/feats/feats_archer.txt~
  BUT_ONLY
  ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
   COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5SLING~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@3245)
	  END
	END
   BUT_ONLY
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
   COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5SLING~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@3245)
	  END
	END
   BUT_ONLY
  END
  ACTION_IF (FILE_EXISTS_IN_GAME ~kitlist.2da~) BEGIN
   COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_COLS cols // amount of columns
	READ_2DA_ENTRIES_NOW rows cols // read all file into memory  
	FOR (row = 1; row < rows; ++row) BEGIN // iterate over rows
	  READ_2DA_ENTRY_FORMER rows row 1 ~text~ // read column value
	  PATCH_IF ~%text%~ STRING_EQUAL_CASE ~D5SLING~ BEGIN
	    SET patch_row = %row%
		SET_2DA_ENTRY (%patch_row%) 4 cols RESOLVE_STR_REF (@3245)
	  END
	END
   BUT_ONLY
  END
  EXTEND_TOP ~d5_feat.bcs~ ~might_and_guile/feats/dialog/d5_sling.baf~
  COMPILE ~might_and_guile/feats/dialog/d5_sling.d~
 END
END
//___________________________________________________________________________________

//DEFINE SPHERE ACCESS______________________________________________________________
//
ACTION_INCLUDE ~%MOD_FOLDER%/lib/fnp_compat.tpa~
COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS 1 rows
	READ_2DA_ENTRY (%rows% - 1) 5 1 mod_clab
BUT_ONLY
LAF ~DEFINE_FNP_KIT_INFO~
  INT_VAR
	c_cleric 		= 0   // put a '1' next to the kit's class
	c_acolyte 		= 0
	c_fighter_cleric = 0   // only choose ONE of these classes!
	c_cleric_mage	= 0
	c_cleric_thief 	= 0
	c_ranger_cleric	= 0
    c_druid 		= 0
    c_mystic 		= 0
    c_occultist 	= 0
    c_champion 		= 0
    c_zealot 		= 0
    c_ranger 		= 0
    c_scout 		= 1
  STR_VAR
    clab_name = EVAL ~%mod_clab%~
	race 			= ~all~  // enter 'all' 'human' 'elf' 'dwarf' 'gnome' 'halfling' or 'orc'
	s_Life 			= ~ranger~   // for chosen spheres, enter 'focus' or 'major' or 'minor'
	s_Death 		= ~x~   // (or 'paladin' or 'ranger' for those classes)
	s_Benediction 	= ~x~
	s_Destruction 	= ~x~
	s_Protection 	= ~ranger~
	s_War 			= ~x~
	s_Knowledge 	= ~x~
	s_Deception 	= ~x~
	s_Thought 		= ~x~
	s_Dread 		= ~x~
	s_Vigor 		= ~ranger~
	s_Affliction 	= ~x~
	s_Animal 		= ~x~
	s_Plant 		= ~x~
	s_Earth 		= ~x~
	s_Water 		= ~x~
	s_Air 			= ~ranger~
	s_Fire 			= ~x~
	s_Light 		= ~x~
	s_Shadow 		= ~x~
	s_Magic 		= ~x~
END
//__________________________________________________________________________________

//FNP SHPERE ACCESS_________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_spheres.d5~ BEGIN
  OUTER_SPRINT sphere_access @1002
  OUTER_SPRINT focus_access @1003
  OUTER_SPRINT major_access @1004
  OUTER_SPRINT minor_access @1005
  OUTER_SPRINT advantages @1006
  OUTER_SPRINT abilities @1007
  OUTER_SPRINT disadvantages @1008
  OUTER_SPRINT restrictions @1009
  OUTER_TEXT_SPRINT focus_sphere_list ~~
  OUTER_TEXT_SPRINT major_sphere_list ~~
  OUTER_TEXT_SPRINT minor_sphere_list ~~
  OUTER_TEXT_SPRINT paladin_sphere_list ~~
  OUTER_TEXT_SPRINT ranger_sphere_list ~~
  OUTER_TEXT_SPRINT total_sphere_list ~~
  LAM ~READ_FNP_KIT_INFO~
  INCLUDE ~%MOD_FOLDER%/lib/add_fnp_spheres.tpa~
END
//___________________________________________________________________________________

/*
//DON'T USE SCROLLS/WANDS___________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rf84n.spl~ BEGIN
	APPEND ~d5_sling.2da~ ~ABILITY    AP_D5_RF84N ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
	APPEND ~d5_sling.2da~ ~ABILITY    AP_D5_RF83N ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****  ~
END
//__________________________________________________________________________________
*/

//REPLACE BASE RANGER WITH THIS KIT___________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~CLSRCREQ.2da~ THEN BEGIN
	COPY_EXISTING ~kitlist.2da~ ~override~
		COUNT_2DA_ROWS ~7~ "kit_row"
	OUTER_SET kit_row -= 2
	COPY_EXISTING ~K_R_HL.2da~ ~override~
		REPLACE_TEXTUALLY ~[ %TAB%]0~ ~%TAB%%kit_row%~
	BUT_ONLY
END
//___________________________________________________________________________________
