
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						WARRIOR FEATS
//__________________________________________________________________________________
//__________________________________________________________________________________


//COPY MARKER FILE_________________________________________________________________
//
COPY ~might_and_guile/fighter/d5_wfeat.d5~ ~override~
//__________________________________________________________________________________


//FEAT ABILITY FILES________________________________________________________________
//
COPY ~might_and_guile/fighter/d5_fifx.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/fighter/d5_fifz.spl~ ~override~
	SAY NAME1 @7

COPY ~might_and_guile/fighter/d5_waf.bam~ ~override~
ACTION_FOR_EACH wfeatspell IN ~d5_fif1~ ~d5_fif2~ ~d5_fif3~ ~d5_fif4~ ~d5_fif5~ ~d5_fif6~ ~d5_fif7~ BEGIN
  COPY ~might_and_guile/fighter/%wfeatspell%.spl~ ~override~
	SAY NAME1 @3909
	SAY UNIDENTIFIED_DESC @3910
	WRITE_ASCII 0x3a ~d5_waf~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_waf~ END
  COPY ~might_and_guile/fighter/%wfeatspell%.eff~ ~override~
END
ACTION_FOR_EACH wfeatclab IN ~d5_fifa~ ~d5_fifb~ ~d5_fifc~ ~d5_fifd~ ~d5_fife~ ~d5_fiff~ ~d5_fifg~ BEGIN
  COPY ~might_and_guile/fighter/%wfeatclab%.spl~ ~override~
	SAY NAME1 @6
	SAY UNIDENTIFIED_DESC @6
END

COPY ~might_and_guile/fighter/d5_wfa.spl~ ~override~ 		//			flurry
	SAY NAME1 @3911
	SAY UNIDENTIFIED_DESC @3912
	WRITE_ASCII 0x3a ~d5_wf01~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf01~ END
COPY ~might_and_guile/fighter/d5_wf01.spl~ ~override~
	SAY NAME1 @3911
	SAY UNIDENTIFIED_DESC @3912
	WRITE_ASCII 0x3a ~d5_wf01~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf01~ END
COPY ~might_and_guile/fighter/d5_wf01.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wfb.spl~ ~override~
	SAY NAME1 @3913
	SAY UNIDENTIFIED_DESC @3914
	WRITE_ASCII 0x3a ~d5_wf02~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf02~ END
COPY ~might_and_guile/fighter/d5_wf02.spl~ ~override~
	SAY NAME1 @3913
	SAY UNIDENTIFIED_DESC @3914
	WRITE_ASCII 0x3a ~d5_wf02~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf02~ END
COPY ~might_and_guile/fighter/d5_wf02.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wfc.spl~ ~override~ 		//			parry
	SAY NAME1 @3915
	SAY UNIDENTIFIED_DESC @3916
	WRITE_ASCII 0x3a ~d5_wf03~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf03~ END
COPY ~might_and_guile/fighter/d5_wf03.spl~ ~override~
	SAY NAME1 @3915
	SAY UNIDENTIFIED_DESC @3916
	WRITE_ASCII 0x3a ~d5_wf03~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf03~ END
COPY ~might_and_guile/fighter/d5_wf03.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wfd.spl~ ~override~ 		//			resistance
	SAY NAME1 @3917
	SAY UNIDENTIFIED_DESC @3918
	WRITE_ASCII 0x3a ~d5_wf04~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf04~ END
COPY ~might_and_guile/fighter/d5_wf04.spl~ ~override~
	SAY NAME1 @3917
	SAY UNIDENTIFIED_DESC @3918
	WRITE_ASCII 0x3a ~d5_wf04~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf04~ END
COPY ~might_and_guile/fighter/d5_wf04.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wfe.spl~ ~override~ 		//			resolve
	SAY NAME1 @3919
	SAY UNIDENTIFIED_DESC @3920
	WRITE_ASCII 0x3a ~d5_wf05~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf05~ END
COPY ~might_and_guile/fighter/d5_wf05.spl~ ~override~
	SAY NAME1 @3919
	SAY UNIDENTIFIED_DESC @3920
	WRITE_ASCII 0x3a ~d5_wf05~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf05~ END
COPY ~might_and_guile/fighter/d5_wf05a.spl~ ~override~
	SAY NAME1 @3919
COPY ~might_and_guile/fighter/d5_wf05.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wff.spl~ ~override~ 		//			willpower
	SAY NAME1 @3921
	SAY UNIDENTIFIED_DESC @3922
	WRITE_ASCII 0x3a ~d5_wf06~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf06~ END
COPY ~might_and_guile/fighter/d5_wf06.spl~ ~override~
	SAY NAME1 @3921
	SAY UNIDENTIFIED_DESC @3922
	WRITE_ASCII 0x3a ~d5_wf06~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf06~ END
COPY ~might_and_guile/fighter/d5_wf06.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wfg.spl~ ~override~		//			knockdown
	SAY NAME1 @3923
	SAY UNIDENTIFIED_DESC @3924
	WRITE_ASCII 0x3a ~d5_wf07~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf07~ END
COPY ~might_and_guile/fighter/d5_wf07.spl~ ~override~
	SAY NAME1 @3923
	SAY UNIDENTIFIED_DESC @3924
	WRITE_ASCII 0x3a ~d5_wf07~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf07~ END
COPY ~might_and_guile/fighter/d5_wf07.eff~ ~override~
COPY ~might_and_guile/fighter/d5_wf07.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wfh.spl~ ~override~		//			knockback
	SAY NAME1 @3925
	SAY UNIDENTIFIED_DESC @3926
	WRITE_ASCII 0x3a ~d5_wf08~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf08~ END
COPY ~might_and_guile/fighter/d5_wf08.spl~ ~override~
	SAY NAME1 @3925
	SAY UNIDENTIFIED_DESC @3926
	WRITE_ASCII 0x3a ~d5_wf08~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf08~ END
COPY ~might_and_guile/fighter/d5_wf08.eff~ ~override~
COPY ~might_and_guile/fighter/d5_wf08.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wfi.spl~ ~override~ 		//			cutting blow
	SAY NAME1 @3927
	SAY UNIDENTIFIED_DESC @3928
	WRITE_ASCII 0x3a ~d5_wf09~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf09~ END
COPY ~might_and_guile/fighter/d5_wf09.spl~ ~override~
	SAY NAME1 @3927
	SAY UNIDENTIFIED_DESC @3928
	WRITE_ASCII 0x3a ~d5_wf09~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf09~ END
COPY ~might_and_guile/fighter/d5_wf09.eff~ ~override~
COPY ~might_and_guile/fighter/d5_wf09a.spl~ ~override~
	SAY NAME1 @3927
COPY ~might_and_guile/fighter/d5_wf09.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wfj.spl~ ~override~ 		//			tempo
	SAY NAME1 @3929
	SAY UNIDENTIFIED_DESC @3930
	WRITE_ASCII 0x3a ~d5_wf10~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf10~ END
COPY ~might_and_guile/fighter/d5_wf10.spl~ ~override~
	SAY NAME1 @3929
	SAY UNIDENTIFIED_DESC @3930
	WRITE_ASCII 0x3a ~d5_wf10~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf10~ END
COPY ~might_and_guile/fighter/d5_wf10.eff~ ~override~
COPY ~might_and_guile/fighter/d5_wf10.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wfk.spl~ ~override~ 		//			disrupt
	SAY NAME1 @3931
	SAY UNIDENTIFIED_DESC @3932
	WRITE_ASCII 0x3a ~d5_wf11~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf11~ END
COPY ~might_and_guile/fighter/d5_wf11.spl~ ~override~
	SAY NAME1 @3931
	SAY UNIDENTIFIED_DESC @3932
	WRITE_ASCII 0x3a ~d5_wf11~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf11~ END
COPY ~might_and_guile/fighter/d5_wf11.eff~ ~override~
COPY ~might_and_guile/fighter/d5_wf11.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wfl.spl~ ~override~ 		//			tactics
	SAY NAME1 @3933
	SAY UNIDENTIFIED_DESC @3934
	WRITE_ASCII 0x3a ~d5_wf12~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf12~ END
COPY ~might_and_guile/fighter/d5_wf12.spl~ ~override~
	SAY NAME1 @3935
	SAY UNIDENTIFIED_DESC @3936
	WRITE_ASCII 0x3a ~d5_wf12~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf12~ END
COPY ~might_and_guile/fighter/d5_wf12a.spl~ ~override~
	WRITE_ASCII 0x3a ~d5_wf12~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf12~ END
COPY ~might_and_guile/fighter/d5_wf12.eff~ ~override~
COPY ~might_and_guile/fighter/d5_wf12.bam~ ~override~
COPY ~might_and_guile/fighter/d5_wf13.spl~ ~override~ 		//			tactics
	SAY NAME1 @3937
	SAY UNIDENTIFIED_DESC @3938
	WRITE_ASCII 0x3a ~d5_wf13~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf13~ END
COPY ~might_and_guile/fighter/d5_wf13a.spl~ ~override~
	WRITE_ASCII 0x3a ~d5_wf13~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_wf13~ END
COPY ~might_and_guile/fighter/d5_wf13.eff~ ~override~
COPY ~might_and_guile/fighter/d5_wf13.bam~ ~override~
//__________________________________________________________________________________


//APPLY FEATS IN CLABS______________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~clabfi01.2da~ BEGIN
	COPY_EXISTING ~clabfi01.2da~ ~override~
	  LPM remove_blank_lines
	  APPEND_FILE ~might_and_guile/fighter/fighter_feats.txt~
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~clabrn01.2da~ BEGIN
	COPY_EXISTING ~clabrn01.2da~ ~override~
	  LPM remove_blank_lines
	  APPEND_FILE ~might_and_guile/fighter/ranger_feats.txt~
	BUT_ONLY
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ BEGIN
  ACTION_IF FILE_EXISTS_IN_GAME ~d5_corsa.2da~ BEGIN
	COPY_EXISTING ~d5_corsa.2da~ ~override~
	  LPM remove_blank_lines
	  APPEND_FILE ~might_and_guile/fighter/ranger_feats.txt~
	BUT_ONLY
  END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabma01.2da~ THEN BEGIN
	COPY ~might_and_guile/misc/clabma01.2da~ ~override~
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabma02.2da~ THEN BEGIN
	COPY ~might_and_guile/misc/clabma02.2da~ ~override~
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabma03.2da~ THEN BEGIN
	COPY ~might_and_guile/misc/clabma03.2da~ ~override~
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabma04.2da~ THEN BEGIN
	COPY ~might_and_guile/misc/clabma04.2da~ ~override~
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabma05.2da~ THEN BEGIN
	COPY ~might_and_guile/misc/clabma05.2da~ ~override~
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabma06.2da~ THEN BEGIN
	COPY ~might_and_guile/misc/clabma06.2da~ ~override~
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabma07.2da~ THEN BEGIN
	COPY ~might_and_guile/misc/clabma07.2da~ ~override~
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabma08.2da~ THEN BEGIN
	COPY ~might_and_guile/misc/clabma08.2da~ ~override~
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~clabma09.2da~ THEN BEGIN
	COPY ~might_and_guile/misc/clabma09.2da~ ~override~
END
COPY_EXISTING ~clabma01.2da~ ~override~
			~clabma02.2da~ ~override~
			~clabma03.2da~ ~override~
			~clabma04.2da~ ~override~
			~clabma05.2da~ ~override~
			~clabma06.2da~ ~override~
			~clabma07.2da~ ~override~
			~clabma08.2da~ ~override~
			~clabma09.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~might_and_guile/fighter/no_feats.txt~
BUT_ONLY

COPY_EXISTING ~kitlist.2da~ ~override~
	COUNT_2DA_ROWS ~9~ "rows"
	FOR ( index = 31 ; index < rows ; index = index + 1 ) BEGIN
		READ_2DA_ENTRY %index% 5 9 modclab
		READ_2DA_ENTRY %index% 8 9 modclass
		DEFINE_ASSOCIATIVE_ARRAY d5_feat_array BEGIN "%modclab%" => "%modclass%" END
	END
BUT_ONLY
ACTION_PHP_EACH d5_feat_array AS bo => zo BEGIN
	ACTION_IF (%zo% = 1) AND (FILE_EXISTS_IN_GAME ~%bo%.2da~) BEGIN
		COPY_EXISTING ~%bo%.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/fighter/no_feats.txt~
	END
END
//__________________________________________________________________________________

CLEAR_ARRAYS
