
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					    	ROGUE KITS
//__________________________________________________________________________________
//__________________________________________________________________________________


//____________________________SNIPER________________________________________________

ADD_KIT ~D5SNIPE~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5SNIPE       0 0 0 0 0 0 0 0~
~D5SNIPE       0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 0 0 3 3 3 1 3 1 1 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SNIPE    	   0   12  0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SNIPE           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SNIPE           0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5SNIPE  	       0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5SNIPE           1  1  1  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5SNIPE           1  1  1  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/thief/d5_snipe.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_T_D K_T_E K_T_G K_T_H K_T_HE K_T_HL K_T_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00080000 4~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Th0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14 * HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @4101
SAY @4102
SAY @4103
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@4106)
		STR_VAR
			kit_name = D5SNIPE
			backstab = ~1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4~
			clswpbon = ~0 0 3~
			thiefskl = ~40 20~
	END
END
//____________________________________________________________________________________


//SNIPER ABILITY FILES________________________________________________________________
//
COPY ~might_and_guile/thief/d5_snipe.2da~ ~override~
COPY ~might_and_guile/misc/d5_mthac.spl~ ~override~

COPY ~might_and_guile/fighter/d5_artrp.eff~ ~override~
COPY ~might_and_guile/fighter/d5_artrp.spl~ ~override~
	SAY NAME1 @3213
	SAY UNIDENTIFIED_DESC @3214
	WRITE_ASCII 0x3a ~d5_artrp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_artrp~ END
COPY ~might_and_guile/fighter/d5_artrp.bam~ ~override~

COPY ~might_and_guile/fighter/d5_armv1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_armv2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_armov.spl~ ~override~
	SAY NAME1 @3211
	SAY UNIDENTIFIED_DESC @3212
	WRITE_ASCII 0x3a ~d5_armov~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_armov~ END
COPY ~might_and_guile/fighter/d5_armov.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arslo.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arslo.spl~ ~override~
	SAY NAME1 @3219
	SAY UNIDENTIFIED_DESC @3220
	WRITE_ASCII 0x3a ~d5_arslo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslo~ END
COPY ~might_and_guile/fighter/d5_arslo.bam~ ~override~

COPY ~might_and_guile/fighter/d5_ards1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ards2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ards3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ardis.spl~ ~override~
	SAY NAME1 @3215
	SAY UNIDENTIFIED_DESC @3216
	WRITE_ASCII 0x3a ~d5_ardis~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_ardis~ END
COPY ~might_and_guile/fighter/d5_ardis.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arbli.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arbli.spl~ ~override~
	SAY NAME1 @4111
	SAY UNIDENTIFIED_DESC @4112
	WRITE_ASCII 0x3a ~d5_arbli~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arbli~ END
COPY ~might_and_guile/fighter/d5_arbli.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arhm1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arhm2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arhm3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arham.spl~ ~override~
	SAY NAME1 @3217
	SAY UNIDENTIFIED_DESC @3218
	WRITE_ASCII 0x3a ~d5_arham~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arham~ END
COPY ~might_and_guile/fighter/d5_arham.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arstn.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arstn.spl~ ~override~
	SAY NAME1 @3251
	SAY UNIDENTIFIED_DESC @3252
	WRITE_ASCII 0x3a ~d5_arstn~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arstn~ END
COPY ~might_and_guile/fighter/d5_arstn.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arnt1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arnt2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arent.spl~ ~override~
	SAY NAME1 @3231
	SAY UNIDENTIFIED_DESC @3232
	WRITE_ASCII 0x3a ~d5_arent~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arent~ END
COPY ~might_and_guile/fighter/d5_arent.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arslp.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arslp.spl~ ~override~
	SAY NAME1 @3233
	SAY UNIDENTIFIED_DESC @3234
	WRITE_ASCII 0x3a ~d5_arslp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslp~ END
COPY ~might_and_guile/fighter/d5_arslp.bam~ ~override~

COPY ~might_and_guile/fighter/d5_ffire.vvc~ ~override~
COPY ~might_and_guile/fighter/d5_arff1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff4.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff5.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ffire.vvc~ ~override~
COPY ~might_and_guile/fighter/d5_arffi.spl~ ~override~
	SAY NAME1 @3235
	SAY UNIDENTIFIED_DESC @3236
	WRITE_ASCII 0x3a ~d5_arffi~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arffi~ END
COPY ~might_and_guile/fighter/d5_arffi.bam~ ~override~

COPY ~might_and_guile/fighter/d5_csa.spl~ ~override~
	SAY NAME1 @3213
	SAY UNIDENTIFIED_DESC @3214
	WRITE_ASCII 0x3a ~d5_artrp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_artrp~ END
COPY ~might_and_guile/fighter/d5_csb.spl~ ~override~
	SAY NAME1 @3211
	SAY UNIDENTIFIED_DESC @3212
	WRITE_ASCII 0x3a ~d5_armov~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_armov~ END
COPY ~might_and_guile/fighter/d5_csc.spl~ ~override~
	SAY NAME1 @3219
	SAY UNIDENTIFIED_DESC @3220
	WRITE_ASCII 0x3a ~d5_arslo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslo~ END
COPY ~might_and_guile/fighter/d5_csd.spl~ ~override~
	SAY NAME1 @3215
	SAY UNIDENTIFIED_DESC @3216
	WRITE_ASCII 0x3a ~d5_ardis~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_ardis~ END
COPY ~might_and_guile/fighter/d5_cse.spl~ ~override~
	SAY NAME1 @4111
	SAY UNIDENTIFIED_DESC @4112
	WRITE_ASCII 0x3a ~d5_arbli~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arbli~ END
COPY ~might_and_guile/fighter/d5_csf.spl~ ~override~
	SAY NAME1 @3217
	SAY UNIDENTIFIED_DESC @3218
	WRITE_ASCII 0x3a ~d5_arham~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arham~ END
COPY ~might_and_guile/fighter/d5_csg.spl~ ~override~
	SAY NAME1 @3251
	SAY UNIDENTIFIED_DESC @3252
	WRITE_ASCII 0x3a ~d5_arstn~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arstn~ END
COPY ~might_and_guile/fighter/d5_csh.spl~ ~override~
	SAY NAME1 @3231
	SAY UNIDENTIFIED_DESC @3232
	WRITE_ASCII 0x3a ~d5_arent~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arent~ END
COPY ~might_and_guile/fighter/d5_csi.spl~ ~override~
	SAY NAME1 @3233
	SAY UNIDENTIFIED_DESC @3234
	WRITE_ASCII 0x3a ~d5_arslp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslp~ END
COPY ~might_and_guile/fighter/d5_csj.spl~ ~override~
	SAY NAME1 @3235
	SAY UNIDENTIFIED_DESC @3236
	WRITE_ASCII 0x3a ~d5_arffi~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arffi~ END

COPY ~might_and_guile/fighter/d5_rafx.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/fighter/d5_rafy.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/fighter/d5_rafz.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/fighter/d5_raf1.spl~ ~override~
	SAY NAME1 @3210
	SAY UNIDENTIFIED_DESC @3210
COPY ~might_and_guile/fighter/d5_rafa.spl~ ~override~
	SAY NAME1 @7

COPY ~might_and_guile/fighter/d5_raf.bam~ ~override~
ACTION_FOR_EACH shotclab IN ~d5_rafa~ ~d5_rafb~ ~d5_rafc~ ~d5_rafd~ ~d5_rafe~ ~d5_raff~ ~d5_rafg~ ~d5_refh~ ~d5_refa~ ~d5_refb~ ~d5_refc~ ~d5_refd~ ~d5_refe~ ~d5_reff~ ~d5_refg~ ~d5_refh~ BEGIN
  COPY ~might_and_guile/fighter/%shotclab%.spl~ ~override~
	SAY NAME1 @7
	SAY UNIDENTIFIED_DESC @7
	WRITE_ASCII 0x3a ~d5_raf~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_raf~ END
END
ACTION_FOR_EACH shoteff IN ~d5_raf1~ ~d5_raf2~ ~d5_raf3~ ~d5_raf4~ ~d5_raf5~ ~d5_raf6~ ~d5_raf7~ ~d5_ref1~ ~d5_ref2~ ~d5_ref3~ ~d5_ref4~ ~d5_ref5~ ~d5_ref6~ ~d5_ref7~ ~d5_ref8~ BEGIN
  COPY ~might_and_guile/fighter/%shoteff%.eff~ ~override~
END
ACTION_FOR_EACH shotspell IN ~d5_raf1~ ~d5_raf2~ ~d5_raf3~ ~d5_raf4~ ~d5_raf5~ ~d5_raf6~ ~d5_raf7~ ~d5_ref1~ ~d5_ref2~ ~d5_ref3~ ~d5_ref4~ ~d5_ref5~ ~d5_ref6~ ~d5_ref7~ ~d5_ref8~ BEGIN
  COPY ~might_and_guile/fighter/%shotspell%.spl~ ~override~
	SAY NAME1 @3210
	SAY UNIDENTIFIED_DESC @3210
	WRITE_ASCII 0x3a ~d5_raf~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_raf~ END
END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_snipe.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
	BUT_ONLY
END
//______________________________________________________________________________
