
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//					    	ROGUE KITS
//__________________________________________________________________________________
//__________________________________________________________________________________


//____________________________GALLANT_______________________________________________

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5GALLA~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5GALLA       1 1 1 1 1 1 1 1~
~D5GALLA       1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5GALLA    	   12  0   0   0   0   15~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5GALLA           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5GALLA           15  0   0   0   0   15~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5GALLA  	       15  0   0   0   0   15~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5GALLA           1  0  0  1  0  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5GALLA           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/bard/d5_galla.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_B_H K_B_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 5~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ba0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @4702
SAY @4703
SAY @4704
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@4705)
		STR_VAR
			kit_name = D5GALLA
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5GALLA~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5GALLA       3 3 3 3 3 3 3 3~
~D5GALLA       3 3 3 3 3 3 3 3 0 3 3 3 3 0 3 3 3 3 3 0 3 3 0 3 0 3 0 3 2 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5GALLA    	   12  0   0   0   0   15~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5GALLA           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5GALLA           15  0   0   0   0   15~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5GALLA  	       15  0   0   0   0   15~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5GALLA           1  0  0  1  0  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5GALLA           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/bard/d5_galla.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~K_B_H K_B_HE~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 5~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ba0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @4702
SAY @4703
SAY @4704
//___________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@4705)
		STR_VAR
			kit_name = D5GALLA
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

//GALLANT ABILITY FILES_______________________________________________________________
//
COPY ~might_and_guile/bard/d5_galla.2da~ ~override~
COPY ~might_and_guile/misc/d5_luckp.spl~ ~override~
	SAY NAME1 @3108
	SAY UNIDENTIFIED_DESC @3108
COPY ~might_and_guile/misc/d5_thac0.spl~ ~override~
COPY ~might_and_guile/misc/d5_1hpbo.spl~ ~override~
COPY ~might_and_guile/misc/d5_cstpn.spl~ ~override~
COPY ~might_and_guile/misc/d5_dsvbo.spl~ ~override~
COPY ~might_and_guile/bard/d5_nopp.spl~ ~override~
COPY ~might_and_guile/bard/d5_pp-5.spl~ ~override~
COPY ~might_and_guile/bard/d5_pp-15.spl~ ~override~
COPY ~might_and_guile/bard/d5_galai.spl~ ~override~
	SAY NAME1 @4706
	SAY UNIDENTIFIED_DESC @4706
COPY_EXISTING ~sppr409.spl~ ~override/d5_galdw.spl~
	LPM spell_to_innate
//COPY ~might_and_guile/bard/d5_galdw.spl~ ~override~
//	SAY NAME1 @4707
//	SAY UNIDENTIFIED_DESC @4707
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_galla.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
		APPEND_FILE ~might_and_guile/misc/intelligence_bards.txt~
	BUT_ONLY
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_taspl.d5~ THEN BEGIN
	ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_skspl.d5~ THEN BEGIN
		COPY_EXISTING ~mxsplbrd.2da~ ~override~
			REPLACE_TEXTUALLY ~ 2~ ~ 1~
			REPLACE_TEXTUALLY ~ 3~ ~ 2~
			REPLACE_TEXTUALLY ~ 4~ ~ 3~
			REPLACE_TEXTUALLY ~ 5~ ~ 4~
			REPLACE_TEXTUALLY ~ 6~ ~ 5~
			REPLACE_TEXTUALLY ~ 7~ ~ 6~
			REPLACE_TEXTUALLY ~ 8~ ~ 7~
			COUNT_2DA_COLS s_cols
			FOR (s_col = 1; s_col < s_cols; ++s_col) BEGIN // iterate over columns
				SET_2DA_ENTRY 2 (s_col - 1) 1 s_col
			END	
		PRETTY_PRINT_2DA
		COPY_EXISTING ~clabba01.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/bard/baspl1.txt~
			BUT_ONLY
		COPY_EXISTING ~clabba02.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/bard/baspl1.txt~
			BUT_ONLY
		COPY_EXISTING ~clabba03.2da~ ~override~
			LPM remove_blank_lines
			APPEND_FILE ~might_and_guile/bard/baspl1.txt~
			BUT_ONLY
		COPY ~might_and_guile/bard/d5_skspl.d5~ ~override~
		ACTION_IF GAME_IS ~bgee~ THEN BEGIN
			COPY_EXISTING ~kitlist.2da~ ~override~
				COUNT_2DA_ROWS ~10~ "rows"
				PATCH_IF ( rows > 37 ) BEGIN
					FOR ( index = 38 ; index < rows ; index = index + 1 ) BEGIN
						READ_2DA_ENTRY %index% 5 10 modclab
						READ_2DA_ENTRY %index% 8 10 modclass
						DEFINE_ASSOCIATIVE_ARRAY d5_bardspell_clabs BEGIN "%modclab%" => "%modclass%" END
					END
				END
				BUT_ONLY
			ACTION_PHP_EACH d5_bardspell_clabs AS coo => koo BEGIN
				ACTION_IF (%koo% = 5) AND (FILE_EXISTS_IN_GAME ~%coo%.2da~) THEN BEGIN
					COPY_EXISTING ~%coo%.2da~ ~override~
						LPM remove_blank_lines
						APPEND_FILE ~might_and_guile/bard/baspl1.txt~
						BUT_ONLY
				END
			END
		END
		ACTION_IF GAME_IS ~bg2ee~ THEN BEGIN
			COPY_EXISTING ~kitlist.2da~ ~override~
				COUNT_2DA_ROWS ~10~ "rows"
				PATCH_IF ( rows > 40 ) BEGIN
					FOR ( index = 41 ; index < rows ; index = index + 1 ) BEGIN
						READ_2DA_ENTRY %index% 5 10 modclab
						READ_2DA_ENTRY %index% 8 10 modclass
						DEFINE_ASSOCIATIVE_ARRAY d5_bardspell_clabs BEGIN "%modclab%" => "%modclass%" END
					END
				END
				BUT_ONLY
			ACTION_PHP_EACH d5_bardspell_clabs AS coo => koo BEGIN
				ACTION_IF (%koo% = 5) AND (FILE_EXISTS_IN_GAME ~%coo%.2da~) THEN BEGIN
					COPY_EXISTING ~%coo%.2da~ ~override~
						LPM remove_blank_lines
						APPEND_FILE ~might_and_guile/bard/baspl1.txt~
						BUT_ONLY
				END
			END
		END
		ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
			COPY_EXISTING ~kitlist.2da~ ~override~
				COUNT_2DA_ROWS ~10~ "rows"
				PATCH_IF ( rows > 41 ) BEGIN
					FOR ( index = 42 ; index < rows ; index = index + 1 ) BEGIN
						READ_2DA_ENTRY %index% 5 10 modclab
						READ_2DA_ENTRY %index% 8 10 modclass
						DEFINE_ASSOCIATIVE_ARRAY d5_bardspell_clabs BEGIN "%modclab%" => "%modclass%" END
					END
				END
				BUT_ONLY
			ACTION_PHP_EACH d5_bardspell_clabs AS coo => koo BEGIN
				ACTION_IF (%koo% = 5) AND (FILE_EXISTS_IN_GAME ~%coo%.2da~) THEN BEGIN
					COPY_EXISTING ~%coo%.2da~ ~override~
						LPM remove_blank_lines
						APPEND_FILE ~might_and_guile/bard/baspl1.txt~
						BUT_ONLY
				END
			END
		END
		ACTION_IF GAME_IS ~tob bgt tutu~ THEN BEGIN
			COPY_EXISTING ~kitlist.2da~ ~override~
				COUNT_2DA_ROWS ~9~ "rows"
				PATCH_IF ( rows > 31 ) BEGIN
					FOR ( index = 32 ; index < rows ; index = index + 1 ) BEGIN
						READ_2DA_ENTRY %index% 5 9 modclab
						READ_2DA_ENTRY %index% 8 9 modclass
						DEFINE_ASSOCIATIVE_ARRAY d5_bardspell_clabs BEGIN "%modclab%" => "%modclass%" END
					END
				END
				BUT_ONLY
			ACTION_PHP_EACH d5_bardspell_clabs AS coo => koo BEGIN
				ACTION_IF (%koo% = 5) AND (FILE_EXISTS_IN_GAME ~%coo%.2da~) THEN BEGIN
					COPY_EXISTING ~%coo%.2da~ ~override~
						LPM remove_blank_lines
						APPEND_FILE ~might_and_guile/bard/baspl1.txt~
						BUT_ONLY
				END
			END
		END
	END
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_taspl.d5~ THEN BEGIN
	COPY_EXISTING ~d5_galla.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/bard/baspl2.txt~
END
//__________________________________________________________________________________
CLEAR_ARRAYS
