
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//						MULTICLASS TWEAKS
//__________________________________________________________________________________
//__________________________________________________________________________________


//COPY MARKER FILE_________________________________________________________________
//
COPY ~might_and_guile/mc/d5_multi.d5~ ~override~
//__________________________________________________________________________________

/*
//EDIT DEMIHUMAN STATS______________________________________________________________
//
COPY ~might_and_guile/mc/abracead.2da~ ~override~
//__________________________________________________________________________________
*/

//KIT DESCRIPTION PATCHING__________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN
	OUTER_SPRINT advantages @36
	OUTER_SPRINT abilities @37
	OUTER_SPRINT disadvantages @38
	OUTER_SPRINT restrictions @39
END
//__________________________________________________________________________________

//ENABLE MORE MULTICLASSES___________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	COPY_EXISTING ~CLSRCREQ.2da~ ~override~
		SET_2DA_ENTRY 34 1 8 ~1~
		SET_2DA_ENTRY 35 1 8 ~1~
		SET_2DA_ENTRY 36 1 8 ~1~
		SET_2DA_ENTRY 37 1 8 ~1~
		SET_2DA_ENTRY 46 1 8 ~1~
		SET_2DA_ENTRY 47 1 8 ~1~
		SET_2DA_ENTRY 48 1 8 ~1~
		SET_2DA_ENTRY 49 1 8 ~1~
		SET_2DA_ENTRY 50 1 8 ~1~
		SET_2DA_ENTRY 51 1 8 ~1~
		SET_2DA_ENTRY 25 2 8 ~1~
		SET_2DA_ENTRY 35 2 8 ~1~
		SET_2DA_ENTRY 47 2 8 ~1~
		SET_2DA_ENTRY 48 2 8 ~1~
		SET_2DA_ENTRY 50 2 8 ~1~
		SET_2DA_ENTRY 51 2 8 ~1~
		SET_2DA_ENTRY 48 3 8 ~1~
		SET_2DA_ENTRY 48 4 8 ~1~
		SET_2DA_ENTRY 35 5 8 ~1~
		SET_2DA_ENTRY 48 5 8 ~1~
		BUT_ONLY
END
ACTION_IF ENGINE_IS ~tob~ THEN BEGIN
	COPY_EXISTING ~CLSRCREQ.2da~ ~override~
		SET_2DA_ENTRY 11 1 7 ~1~
		SET_2DA_ENTRY 12 1 7 ~1~
		SET_2DA_ENTRY 13 1 7 ~1~
		SET_2DA_ENTRY 14 1 7 ~1~
		SET_2DA_ENTRY 15 1 7 ~1~
		SET_2DA_ENTRY 16 1 7 ~1~
		SET_2DA_ENTRY 17 1 7 ~1~
		SET_2DA_ENTRY 18 1 7 ~1~
		SET_2DA_ENTRY 19 1 7 ~1~
		SET_2DA_ENTRY 20 1 7 ~1~
		SET_2DA_ENTRY 5 2 7 ~1~
		SET_2DA_ENTRY 12 2 7 ~1~
		SET_2DA_ENTRY 15 2 7 ~1~
		SET_2DA_ENTRY 16 2 7 ~1~
		SET_2DA_ENTRY 18 2 7 ~1~
		SET_2DA_ENTRY 20 2 7 ~1~
		SET_2DA_ENTRY 16 3 7 ~1~
		SET_2DA_ENTRY 16 4 7 ~1~
		SET_2DA_ENTRY 12 5 7 ~1~
		SET_2DA_ENTRY 16 5 7 ~1~
		BUT_ONLY
END
//___________________________________________________________________________________

/*
//CHECK FOR R/C DRUID SPELLS____________________________________________________________
//
ACTION_IF FILE_EXISTS ~%USER_DIRECTORY%/Baldur.ini~ THEN BEGIN

COPY - ~%USER_DIRECTORY%/Baldur.ini~ ~%USER_DIRECTORY%~
  COUNT_REGEXP_INSTANCES ~'Cleric Ranger Spells',[ %TAB%]*'1'~ cr_bugfix_enabled

ACTION_IF (cr_bugfix_enabled) BEGIN // no druid spells for cleric/rangers
	PRINT @13
END
ELSE BEGIN

//CHANGE RANGERS_____________________________________________________________________
//
//ACTION_IF NOT GAME_IS ~iwdee bg2ee~ THEN BEGIN

	COPY_EXISTING ~dualclas.2da~ ~override~
		SET_2DA_ENTRY 8 2 6 ~0~
		SET_2DA_ENTRY 33 2 6 ~0~
		SET_2DA_ENTRY 34 2 6 ~0~
		SET_2DA_ENTRY 35 2 6 ~0~

	STRING_SET 9580 @5010

//END
//___________________________________________________________________________________

//ADD WOODSCOUT______________________________________________________________________
//
//ACTION_IF NOT GAME_IS ~iwdee bg2ee~ THEN BEGIN

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MIELI~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MIELI       2 2 2 2 2 2 2 2~
~D5MIELI       2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   9   9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MIELI           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MIELI           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_mieli.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CR0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5011
SAY @5011
SAY @5011
//__________________________________________________________________________________

END

//__________________________________________________________________________________
ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MIELI~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MIELI       3 3 3 3 3 3 3 3~
~D5MIELI       3 3 3 3 3 3 3 3 0 3 3 3 0 0 3 3 0 3 3 0 3 3 3 0 0 3 0 3 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   9   9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MIELI           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MIELI           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MIELI           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_mieli.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CR0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5011
SAY @5011
SAY @5011
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5011)
		STR_VAR
			kit_name = D5MIELI
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//WOODSCOUT ABILITY FILES_____________________________________________________________
//
COPY ~might_and_guile/mc/d5_mieli.2da~ ~override~
COPY_EXISTING ~clabpr01.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~might_and_guile/mc/rcclab.txt~
	BUT_ONLY
COPY ~might_and_guile/mc/d5_rc.spl~ ~override~
	SAY NAME1 @6
COPY ~might_and_guile/mc/d5_rc.eff~ ~override~
COPY ~might_and_guile/mc/d5_rcns.spl~ ~override~
	SAY NAME1 @6
COPY ~might_and_guile/mc/d5_rcns.eff~ ~override~
COPY ~might_and_guile/mc/d5_latns.spl~ ~override~
	SAY NAME1 @6
COPY ~might_and_guile/mc/d5_mieli.itm~ ~override~
	SAY NAME1 @5012
	SAY NAME2 @5012
	SAY UNIDENTIFIED_DESC @5013
	SAY IDENTIFIED_DESC @5013
COPY ~might_and_guile/mc/d5_mieli.spl~ ~override~
	SAY NAME1 @9
COPY ~might_and_guile/mc/d5_mieli.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_mieli.baf~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_mieli.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_strid.d5~ THEN BEGIN
	COPY_EXISTING ~d5_mieli.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/strirang.txt~
		BUT_ONLY
END
//____________________________________________________________________________________

//ADD FORESTWALKER____________________________________________________________________
//
//ACTION_IF NOT GAME_IS ~iwdee bg2ee~ THEN BEGIN

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5RILLI~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5RILLI       2 2 2 2 2 2 2 2~
~D5RILLI       2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   9   9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5RILLI           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5RILLI           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_rilli.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CR0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5014
SAY @5014
SAY @5014
//__________________________________________________________________________________

END

//__________________________________________________________________________________
ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5RILLI~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5RILLI       3 3 3 3 3 3 3 3~
~D5RILLI       3 3 3 3 3 3 3 3 0 3 3 3 0 0 3 3 0 3 3 0 3 3 3 0 0 3 0 3 2 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   9   9   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   15  15  0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5RILLI           0   15  15  0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5RILLI           1  0  0  1  0  0  1  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5RILLI           0  1  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_rilli.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 12~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CR0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5014
SAY @5014
SAY @5014
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5014)
		STR_VAR
			kit_name = D5RILLI
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//FORESTWALKER ABILITY FILES__________________________________________________________
//
COPY ~might_and_guile/mc/d5_rilli.2da~ ~override~
COPY ~might_and_guile/mc/d5_rc.spl~ ~override~
	SAY NAME1 @6
COPY ~might_and_guile/mc/d5_rc.eff~ ~override~
COPY ~might_and_guile/mc/d5_rilli.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_rilli.baf~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_rilli.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
	BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_strid.d5~ THEN BEGIN
	COPY_EXISTING ~d5_rilli.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/strirang.txt~
		BUT_ONLY
END

//RANGER/CLERIC WEAPONS____________________________________________________________
//
COPY_EXISTING_REGEXP GLOB ~.*\.itm~ ~override~ // copies all item files
	PATCH_IF (SOURCE_SIZE > 0x71) BEGIN // avoid crashing on empty items
		READ_BYTE  0x1f multi 
		READ_SHORT  ~0x1c~ type 
		PATCH_IF (type = 15) BEGIN // bows
			WRITE_BYTE 0x1f (multi BAND 0b11111011)
		END
		PATCH_IF (type = 29) BEGIN // spears
			WRITE_BYTE 0x1f (multi BAND 0b11111011)
		END
		PATCH_IF (type = 19) BEGIN // small swords
			WRITE_BYTE 0x1f (multi BAND 0b11111011)
		END
		PATCH_IF (type = 20) BEGIN // large swords
			WRITE_BYTE 0x1f (multi BAND 0b11111011)
		END
		PATCH_IF (type = 16) BEGIN // daggers
			WRITE_BYTE 0x1f (multi BAND 0b11111011)
		END
	END
	BUT_ONLY
//___________________________________________________________________________________

END
//___________________________________________________________________________________
END
*/

//ADD BLADESINGER____________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5BLADS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5BLADS       5 5 1 1 1 1 1 1~
~D5BLADS       5 5 1 1 1 1 1 1 5 5 5 1 0 5 5 5 1 1 0 0 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5BLADS           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5BLADS           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_blads.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00014000 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FM0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5020
SAY @5020
SAY @5020
//__________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5BLADS~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5BLADS       5 5 1 0 1 1 1 1~
~D5BLADS       5 5 1 0 1 1 1 1 0 5 5 1 0 0 5 5 1 1 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           9   9   0   0   0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BLADS           15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5BLADS           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5BLADS           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_blads.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00014000 2~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FM0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5020
SAY @5020
SAY @5020
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5020)
		STR_VAR
			kit_name = D5BLADS
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//BLADESINGER ABILITY FILES_____________________________________________________________
//
COPY ~might_and_guile/mc/d5_blads.2da~ ~override~
COPY ~might_and_guile/misc/d5_acbon.spl~ ~override~
COPY ~might_and_guile/misc/d5_acmel.spl~ ~override~
COPY ~might_and_guile/mc/d5_blads.itm~ ~override~
	SAY NAME1 @5021
	SAY NAME2 @5021
	SAY UNIDENTIFIED_DESC @5022
	SAY IDENTIFIED_DESC @5022
COPY ~might_and_guile/mc/d5_blads.spl~ ~override~
	SAY NAME1 @9
COPY ~might_and_guile/mc/d5_blads.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_blads.baf~
COPY ~might_and_guile/mc/d5_blad1.spl~ ~override~
	SAY NAME1 @5023
	SAY NAME2 @5023
	SAY UNIDENTIFIED_DESC @5024
COPY ~might_and_guile/mc/d5_bspr1.spl~ ~override~
	SAY NAME1 @6
COPY ~might_and_guile/mc/d5_bspr2.spl~ ~override~
	SAY NAME1 @6
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_blads.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
	BUT_ONLY
END
//____________________________________________________________________________________


//ADD SPELLFILCHER____________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5FILCH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5FILCH       1 1 1 0 1 0 0 1~
~D5FILCH       1 1 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH    	   0   12  0   12  0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH           0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH  	       0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5FILCH           0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5FILCH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_filch.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~MT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5031
SAY @5031
SAY @5031
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5031)
		STR_VAR
			kit_name = D5FILCH
			clswpbon = ~0 0 3~
			thiefskl = ~50 25~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5FILCH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5FILCH       3 3 3 0 3 0 0 3~
~D5FILCH       3 3 3 0 3 0 0 3 0 3 3 0 0 0 3 3 0 3 0 0 0 0 3 3 0 3 0 3 0 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH    	   0   12  0   12  0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH           0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5FILCH  	       0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5FILCH           0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5FILCH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_filch.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 4~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~MT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5031
SAY @5031
SAY @5031
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5031)
		STR_VAR
			kit_name = D5FILCH
			clswpbon = ~1 0 3~
			thiefskl = ~50 25~
	END
END
//____________________________________________________________________________________

END

//SPELLFILCHER ABILITY FILES__________________________________________________________
//
COPY ~might_and_guile/mc/d5_filch.2da~ ~override~
COPY ~might_and_guile/mc/d5_filch.itm~ ~override~
	SAY NAME1 @5032
	SAY NAME2 @5032
	SAY UNIDENTIFIED_DESC @5033
	SAY IDENTIFIED_DESC @5033
COPY ~might_and_guile/mc/d5_filch.spl~ ~override~
	SAY NAME1 @9
COPY ~might_and_guile/mc/d5_filch.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_filch.baf~
COPY ~might_and_guile/misc/d5_ssvbo.spl~ ~override~
	SAY NAME1 @15
COPY ~might_and_guile/mc/d5_flch1.spl~ ~override~
	SAY NAME1 @5034
	SAY NAME2 @5034
	SAY UNIDENTIFIED_DESC @5035
COPY ~might_and_guile/mc/d5_flch2.spl~ ~override~
	SAY NAME1 @5036
	SAY NAME2 @5036
	SAY UNIDENTIFIED_DESC @5037
COPY ~might_and_guile/mc/d5_flch3.spl~ ~override~
COPY ~might_and_guile/mc/d5_flch4.spl~ ~override~
COPY ~might_and_guile/mc/d5_flch5.spl~ ~override~
COPY ~might_and_guile/mc/d5_flch4.eff~ ~override~
COPY ~might_and_guile/mc/d5_flch5.eff~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_filch.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
	BUT_ONLY
END
//__________________________________________________________________________________


//ADD NIGHTRUNNER___________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MASK~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MASK        1 1 1 0 1 0 0 1~
~D5MASK        1 1 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK    	       0   12  0   12  0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MASK            0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MASK            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE____________________________________________________________
~might_and_guile/mc/d5_mask.2da~

//RACIAL KIT AVAILABILITY___________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5041
SAY @5041
SAY @5041
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5041)
		STR_VAR
			kit_name = D5MASK
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MASK~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MASK        3 3 3 0 3 0 0 3~
~D5MASK        3 3 3 0 3 0 0 3 0 0 3 0 0 0 3 3 3 3 0 0 0 3 3 3 0 3 0 3 0 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK    	       0   12  0   12  0   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MASK            0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MASK            0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MASK            0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_mask.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5041
SAY @5041
SAY @5041
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5041)
		STR_VAR
			kit_name = D5MASK
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

//NIGHTRUNNER ABILITY FILES__________________________________________________________
//
COPY ~might_and_guile/mc/d5_mask.2da~ ~override~
COPY ~might_and_guile/mc/d5_shans.spl~ ~override~
COPY ~might_and_guile/mc/d5_mask.itm~ ~override~
	SAY NAME1 @5042
	SAY NAME2 @5042
	SAY UNIDENTIFIED_DESC @5043
	SAY IDENTIFIED_DESC @5043
COPY ~might_and_guile/mc/d5_mask.spl~ ~override~
	SAY NAME1 @9
COPY ~might_and_guile/mc/d5_mask.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_mask.baf~
COPY ~might_and_guile/mc/d5_his20.spl~ ~override~
COPY ~might_and_guile/mc/d5_mask1.spl~ ~override~
	SAY NAME1 @5044
	SAY NAME2 @5044
	SAY UNIDENTIFIED_DESC @5045
COPY ~might_and_guile/mc/d5_mask2.spl~ ~override~
	SAY NAME1 @5046
	SAY NAME2 @5046
	SAY UNIDENTIFIED_DESC @5047
COPY ~might_and_guile/mc/d5_mask3.spl~ ~override~
	SAY NAME1 @5048
	SAY NAME2 @5048
	SAY UNIDENTIFIED_DESC @5049
COPY ~might_and_guile/mc/d5_mask3.eff~ ~override~
COPY ~might_and_guile/mc/d5_mask3.cre~ ~override~
	SAY NAME1 @5050
//Nightrunner's Summon Shadow ability generously provided by Demivrgvs of Item/Spell/Kit Revisions fame. Big thanks!
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_mask.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
	BUT_ONLY
END
//__________________________________________________________________________________

//FnP SPHERE SYSTEM COMPATIBILITY____________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN

ACTION_IF GAME_IS ~iwdee~ BEGIN
	OUTER_SPRINT game ~iwd~
END
ELSE BEGIN
	OUTER_SPRINT game ~bg2~
END

OUTER_SPRINT this_kit ~D5MASK~ // ..............................KIT NAME HERE
OUTER_SPRINT kit_clab ~d5_mask~ // .....................KIT CLAB FILE HERE (without .2da extension)
OUTER_SPRINT kit_spheres @5051 // ..........................KIT SPHERES TRA REF HERE

//add spheres_______________________________________________________________________
//
COPY_EXISTING ~%kit_clab%.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~f_n_p/spheres/%game%/divine_aid_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/knowledge_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/thought_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/dread_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/shadow_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/deception_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/life_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/death_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/war_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/protection_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/vigor_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/affliction_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/magic_minor.txt~
BUT_ONLY

//__________________________________________________________________________________

OUTER_SET strref = (0 - 1)

COPY_EXISTING - ~kitlist.2da~ ~override~
	COUNT_2DA_COLS num_cols
	READ_2DA_ENTRIES_NOW ~r2en_kitlist~ num_cols
	FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
		READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kitname
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~%this_kit%~) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 strref
		END
	END
BUT_ONLY

ACTION_IF (strref >= 0) BEGIN
	ACTION_GET_STRREF %strref% kit_description 
	OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
		REPLACE_TEXTUALLY ~%disadvantages%~ ~%restrictions%~
		REPLACE_TEXTUALLY ~%abilities%~ ~%kit_spheres%~
		REPLACE_TEXTUALLY ~%advantages%~ ~%kit_spheres%~
	END
	STRING_SET_EVALUATE %strref% ~%kit_description%~
END

END
//__________________________________________________________________________________


//ADD MISADVENTURER__________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MSADV~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MSADV       1 1 1 0 1 0 0 1~
~D5MSADV       1 1 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 1 1 1 1 1 1 1 1 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV   	       0   12  0   0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MSADV           0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MSADV           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_msadv.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5060
SAY @5060
SAY @5060
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5060)
		STR_VAR
			kit_name = D5MSADV
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5MSADV~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MSADV       3 3 3 0 3 0 0 3~
~D5MSADV       3 3 3 0 3 0 0 3 0 3 3 0 0 0 3 3 0 3 0 0 0 3 3 3 0 3 0 3 0 0 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   12  0   0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MSADV           0   15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MSADV           0  0  0  1  1  1  1  1  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MSADV           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_msadv.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~CT0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5060
SAY @5060
SAY @5060
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5060)
		STR_VAR
			kit_name = D5MSADV
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

//MISADVENTURER ABILITY FILES_________________________________________________________
//
COPY ~might_and_guile/mc/d5_msadv.2da~ ~override~
COPY ~might_and_guile/mc/d5_selns.spl~ ~override~
COPY ~might_and_guile/misc/d5_luckp.spl~ ~override~
	SAY NAME1 @3108
	SAY UNIDENTIFIED_DESC @3108
COPY ~might_and_guile/mc/d5_msadv.itm~ ~override~
	SAY NAME1 @5061
	SAY NAME2 @5061
	SAY UNIDENTIFIED_DESC @5062
	SAY IDENTIFIED_DESC @5062
COPY ~might_and_guile/mc/d5_msadv.spl~ ~override~
	SAY NAME1 @9
COPY ~might_and_guile/mc/d5_msadv.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_msadv.baf~
COPY ~might_and_guile/mc/d5_msad2.spl~ ~override~
	SAY NAME1 @5063
	SAY NAME2 @5063
	SAY UNIDENTIFIED_DESC @5064
COPY ~might_and_guile/mc/d5_msad3.spl~ ~override~
	SAY NAME1 @5065
	SAY NAME2 @5065
	SAY UNIDENTIFIED_DESC @5066
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_msadv.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
	BUT_ONLY
END
//__________________________________________________________________________________

//FnP SPHERE SYSTEM COMPATIBILITY____________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN

ACTION_IF GAME_IS ~iwdee~ BEGIN
	OUTER_SPRINT game ~iwd~
END
ELSE BEGIN
	OUTER_SPRINT game ~bg2~
END

OUTER_SPRINT this_kit ~D5MSADV~ // ..............................KIT NAME HERE
OUTER_SPRINT kit_clab ~d5_msadv~ // .....................KIT CLAB FILE HERE (without .2da extension)
OUTER_SPRINT kit_spheres @5067 // ..........................KIT SPHERES TRA REF HERE

//add spheres_______________________________________________________________________
//
COPY_EXISTING ~%kit_clab%.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~f_n_p/spheres/%game%/divine_aid_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/life_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/protection_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/thought_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/air_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/light_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/knowledge_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/vigor_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/animal_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/shadow_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/deception_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/magic_minor.txt~
BUT_ONLY

//__________________________________________________________________________________

OUTER_SET strref = (0 - 1)

COPY_EXISTING - ~kitlist.2da~ ~override~
	COUNT_2DA_COLS num_cols
	READ_2DA_ENTRIES_NOW ~r2en_kitlist~ num_cols
	FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
		READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kitname
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~%this_kit%~) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 strref
		END
	END
BUT_ONLY

ACTION_IF (strref >= 0) BEGIN
	ACTION_GET_STRREF %strref% kit_description 
	OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
		REPLACE_TEXTUALLY ~%disadvantages%~ ~%restrictions%~
		REPLACE_TEXTUALLY ~%abilities%~ ~%kit_spheres%~
		REPLACE_TEXTUALLY ~%advantages%~ ~%kit_spheres%~
	END
	STRING_SET_EVALUATE %strref% ~%kit_description%~
END

END
//__________________________________________________________________________________


//ADD HEARTHGUARD____________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5HARTH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5HARTH       0 0 0 0 2 2 0 2~
~D5HARTH       0 0 0 0 2 2 0 2 0 0 0 0 0 0 0 0 2 2 0 0 2 2 2 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           9   0   0   0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           15  0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           15  0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5HARTH           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5HARTH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_harth.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5070
SAY @5070
SAY @5070
//__________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5HARTH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5HARTH       0 0 0 0 3 3 0 3~
~D5HARTH       0 0 0 0 3 3 0 3 0 0 0 0 0 0 0 0 3 3 0 0 3 3 3 0 0 0 0 4 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           9   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           15  0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5HARTH           15  0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5HARTH           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5HARTH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_harth.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5070
SAY @5070
SAY @5070
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5070)
		STR_VAR
			kit_name = D5HARTH
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

//HEARTHGUARD ABILITY FILES___________________________________________________________
//
COPY ~might_and_guile/mc/d5_harth.2da~ ~override~
COPY ~might_and_guile/mc/d5_latns.spl~ ~override~
COPY ~might_and_guile/mc/d5_harth.itm~ ~override~
	SAY NAME1 @5071
	SAY NAME2 @5071
	SAY UNIDENTIFIED_DESC @5072
	SAY IDENTIFIED_DESC @5072
COPY ~might_and_guile/mc/d5_harth.spl~ ~override~
	SAY NAME1 @9
COPY ~might_and_guile/mc/d5_harth.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_harth.baf~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_harth.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
	BUT_ONLY
END
//____________________________________________________________________________________

//FnP SPHERE SYSTEM COMPATIBILITY____________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN

ACTION_IF GAME_IS ~iwdee~ BEGIN
	OUTER_SPRINT game ~iwd~
END
ELSE BEGIN
	OUTER_SPRINT game ~bg2~
END

OUTER_SPRINT this_kit ~D5HARTH~ // ..............................KIT NAME HERE
OUTER_SPRINT kit_clab ~d5_harth~ // .....................KIT CLAB FILE HERE (without .2da extension)
OUTER_SPRINT kit_spheres @5073 // ..........................KIT SPHERES TRA REF HERE

//add spheres_______________________________________________________________________
//
COPY_EXISTING ~%kit_clab%.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~f_n_p/spheres/%game%/divine_aid_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/life_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/war_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/protection_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/vigor_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/light_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/knowledge_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/thought_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/animal_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/plant_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/earth_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/magic_minor.txt~
BUT_ONLY

//__________________________________________________________________________________

OUTER_SET strref = (0 - 1)

COPY_EXISTING - ~kitlist.2da~ ~override~
	COUNT_2DA_COLS num_cols
	READ_2DA_ENTRIES_NOW ~r2en_kitlist~ num_cols
	FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
		READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kitname
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~%this_kit%~) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 strref
		END
	END
BUT_ONLY

ACTION_IF (strref >= 0) BEGIN
	ACTION_GET_STRREF %strref% kit_description 
	OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
		REPLACE_TEXTUALLY ~%disadvantages%~ ~%restrictions%~
		REPLACE_TEXTUALLY ~%abilities%~ ~%kit_spheres%~
		REPLACE_TEXTUALLY ~%advantages%~ ~%kit_spheres%~
	END
	STRING_SET_EVALUATE %strref% ~%kit_description%~
END

END
//__________________________________________________________________________________


//ADD ALAGHOR_________________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5ALAGH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5ALAGH       0 0 0 0 2 2 0 2~
~D5ALAGH       0 0 0 0 2 2 0 2 0 0 0 0 0 0 0 0 2 2 0 0 2 2 2 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           9   0   0   0   9   0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           15  0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           15  0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5ALAGH           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5ALAGH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_alagh.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5080
SAY @5080
SAY @5080
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5ALAGH~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5ALAGH       0 0 0 0 3 3 0 3~
~D5ALAGH       0 0 0 0 3 3 0 3 0 0 0 4 0 0 0 0 3 3 0 0 3 3 3 0 0 0 0 3 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           9   0   0   0   12  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           15  0   0   0   15  0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5ALAGH           15  0   0   0   15  0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5ALAGH           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5ALAGH           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_alagh.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00004000 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~FC0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5080
SAY @5080
SAY @5080
//____________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5080)
		STR_VAR
			kit_name = D5ALAGH
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

//ALAGHOR ABILITY FILES_______________________________________________________________
//
COPY ~might_and_guile/mc/d5_alagh.2da~ ~override~
COPY ~might_and_guile/mc/d5_temns.spl~ ~override~
COPY ~might_and_guile/mc/d5_alagh.itm~ ~override~
	SAY NAME1 @5081
	SAY NAME2 @5081
	SAY UNIDENTIFIED_DESC @5082
	SAY IDENTIFIED_DESC @5082
COPY ~might_and_guile/mc/d5_alagh.spl~ ~override~
	SAY NAME1 @9
COPY ~might_and_guile/mc/d5_alagh.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_alagh.baf~
COPY ~might_and_guile/mc/d5_alag1.spl~ ~override~
	SAY NAME1 @5083
	SAY UNIDENTIFIED_DESC @5084
COPY ~might_and_guile/mc/d5_alag2.spl~ ~override~
	SAY NAME1 @5085
	SAY UNIDENTIFIED_DESC @5086
COPY ~might_and_guile/mc/d5_alag1.itm~ ~override~
	SAY NAME1 @5087
	SAY NAME2 @5087
COPY ~might_and_guile/mc/d5_alag2.itm~ ~override~
	SAY NAME1 @5087
	SAY NAME2 @5087
COPY ~might_and_guile/mc/d5_alag3.itm~ ~override~
	SAY NAME1 @5087
	SAY NAME2 @5087
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_alagh.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
	BUT_ONLY
END
//____________________________________________________________________________________

//FnP SPHERE SYSTEM COMPATIBILITY____________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN

ACTION_IF GAME_IS ~iwdee~ BEGIN
	OUTER_SPRINT game ~iwd~
END
ELSE BEGIN
	OUTER_SPRINT game ~bg2~
END

OUTER_SPRINT this_kit ~D5ALAGH~ // ..............................KIT NAME HERE
OUTER_SPRINT kit_clab ~d5_alagh~ // .....................KIT CLAB FILE HERE (without .2da extension)
OUTER_SPRINT kit_spheres @5088 // ..........................KIT SPHERES TRA REF HERE

//add spheres_______________________________________________________________________
//
COPY_EXISTING ~%kit_clab%.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~f_n_p/spheres/%game%/divine_aid_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/protection_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/destruction_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/war_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/vigor_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/earth_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/life_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/knowledge_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/thought_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/dread_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/light_major.txt~
BUT_ONLY

//__________________________________________________________________________________

OUTER_SET strref = (0 - 1)

COPY_EXISTING - ~kitlist.2da~ ~override~
	COUNT_2DA_COLS num_cols
	READ_2DA_ENTRIES_NOW ~r2en_kitlist~ num_cols
	FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
		READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kitname
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~%this_kit%~) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 strref
		END
	END
BUT_ONLY

ACTION_IF (strref >= 0) BEGIN
	ACTION_GET_STRREF %strref% kit_description 
	OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
		REPLACE_TEXTUALLY ~%disadvantages%~ ~%restrictions%~
		REPLACE_TEXTUALLY ~%abilities%~ ~%kit_spheres%~
		REPLACE_TEXTUALLY ~%advantages%~ ~%kit_spheres%~
	END
	STRING_SET_EVALUATE %strref% ~%kit_description%~
END

END
//__________________________________________________________________________________


//ADD GLORYBLOOD______________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5TEMPU~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0

~D5TEMPU       0 0 0 0 2 2 0 2~
~D5TEMPU       0 0 0 0 2 2 0 2 0 0 0 0 0 0 0 0 2 2 0 0 2 2 2 0 0 0 0 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
//__________________________________________________________________________________

//MINIMUM KIT STATS_________________________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU          0   0   0   0   9   0~
//__________________________________________________________________________________

//KIT STAT MODIFIERS________________________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   0   0~
//__________________________________________________________________________________

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   15  0~
//_________________________________________________________________________________

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   15  0~
//_________________________________________________________________________________

//ALIGNMENT RESTRICTIONS____________________________________________________________
//
//                 LG LN LE NG TN NE CG CN CE
~D5TEMPU           0  0  0  1  1  1  1  1  1~
//________________________________________________________________________________

//DUAL CLASS OPTIONS________________________________________________________________
//
//                 FT CL MA TH DR RA
~D5TEMPU           1  0  0  0  0  0~
//____________________________________________________________________________________

//KIT ABILITIES 2DA FILE______________________________________________________________
//
~might_and_guile/mc/d5_tempu.2da~
//___________________________________________________________________________________

//RACIAL KIT AVAILABILITY_____________________________________________________________
//
~~
//___________________________________________________________________________________

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
//
~0x00004000 3~
//___________________________________________________________________________________

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
//
~Cl0~
//__________________________________________________________________________________

//TOB STARTING EQUIPMENT_____________________________________________________________
//
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
//____________________________________________________________________________________

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
//
SAY @5090
SAY @5090
SAY @5090
//___________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5TEMPU~
//___________________________________________________________________________________

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0

~D5TEMPU       0 0 0 0 3 3 0 3~
~D5TEMPU       0 0 0 0 3 3 0 3 0 0 0 4 0 0 0 0 3 3 0 0 3 3 3 1 0 0 0 1 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
//__________________________________________________________________________________

//MINIMUM KIT STATS_________________________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           12  0   0   0   9   0~
//__________________________________________________________________________________

//KIT STAT MODIFIERS________________________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   0   0~
//__________________________________________________________________________________

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   15  0~
//_________________________________________________________________________________

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//
//                 STR DEX CON INT WIS CHR
~D5TEMPU           0   0   0   0   15  0~
//_________________________________________________________________________________

//ALIGNMENT RESTRICTIONS____________________________________________________________
//
//                 LG LN LE NG TN NE CG CN CE
~D5TEMPU           0  0  0  1  1  1  1  1  1~
//________________________________________________________________________________

//DUAL CLASS OPTIONS________________________________________________________________
//
//                 FT CL MA TH DR RA
~D5TEMPU           1  0  0  0  0  0~
//____________________________________________________________________________________

//KIT ABILITIES 2DA FILE______________________________________________________________
//
~might_and_guile/mc/d5_tempu.2da~
//___________________________________________________________________________________

//RACIAL KIT AVAILABILITY_____________________________________________________________
//
~~
//___________________________________________________________________________________

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
//
~0x00004000 3~
//___________________________________________________________________________________

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
//
~Cl0~
//__________________________________________________________________________________

//TOB STARTING EQUIPMENT_____________________________________________________________
//
~CHAN09	* HELM07 BAG26 RING06 RING31 * BOOT01 AMUL20 BRAC10 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H27 STAF08~
//____________________________________________________________________________________

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
//
SAY @5090
SAY @5090
SAY @5090
//___________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
// 
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5090)
		STR_VAR
			kit_name = D5TEMPU
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

//GLORYBLOOD ABILITY FILES______________________________________________________________
//
COPY ~might_and_guile/mc/d5_tempu.2da~ ~override~
COPY ~might_and_guile/mc/d5_temns.spl~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
	COPY_EXISTING ~d5_tempu.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/mc/tempaxe.txt~
		BUT_ONLY
END
COPY ~might_and_guile/mc/d5_tempu.itm~ ~override~
	SAY NAME1 @5091
	SAY NAME2 @5091
	SAY UNIDENTIFIED_DESC @5092
	SAY IDENTIFIED_DESC @5092
COPY ~might_and_guile/mc/d5_tempu.spl~ ~override~
	SAY NAME1 @9
	SAY UNIDENTIFIED_DESC @9
COPY ~might_and_guile/mc/d5_tempu.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_tempu.baf~ ~override~
COPY ~might_and_guile/mc/d5_temp1.spl~ ~override~
COPY ~might_and_guile/mc/d5_temp1.itm~ ~override~
COPY ~might_and_guile/mc/d5_temp2.itm~ ~override~
COPY ~might_and_guile/mc/d5_temp3.itm~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_tempu.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
	BUT_ONLY
END
//____________________________________________________________________________________

//FnP SPHERE SYSTEM COMPATIBILITY____________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN

ACTION_IF GAME_IS ~iwdee~ BEGIN
	OUTER_SPRINT game ~iwd~
END
ELSE BEGIN
	OUTER_SPRINT game ~bg2~
END

OUTER_SPRINT this_kit ~D5TEMPU~ // ..............................KIT NAME HERE
OUTER_SPRINT kit_clab ~d5_tempu~ // .....................KIT CLAB FILE HERE (without .2da extension)
OUTER_SPRINT kit_spheres @5095 // ..........................KIT SPHERES TRA REF HERE

//add spheres_______________________________________________________________________
//
COPY_EXISTING ~%kit_clab%.2da~ ~override~
	LPM remove_blank_lines
		APPEND_FILE ~f_n_p/spheres/%game%/war_major.txt~
		APPEND_FILE ~f_n_p/spheres/%game%/divine_aid_major.txt~
		APPEND_FILE ~f_n_p/spheres/%game%/protection_major.txt~
		APPEND_FILE ~f_n_p/spheres/%game%/destruction_major.txt~
		APPEND_FILE ~f_n_p/spheres/%game%/dread_major.txt~
		APPEND_FILE ~f_n_p/spheres/%game%/vigor_major.txt~
		APPEND_FILE ~f_n_p/spheres/%game%/life_minor.txt~
		APPEND_FILE ~f_n_p/spheres/%game%/death_minor.txt~
		APPEND_FILE ~f_n_p/spheres/%game%/knowledge_minor.txt~
		APPEND_FILE ~f_n_p/spheres/%game%/thought_minor.txt~
		APPEND_FILE ~f_n_p/spheres/%game%/earth_minor.txt~
BUT_ONLY

//__________________________________________________________________________________

OUTER_SET strref = (0 - 1)

COPY_EXISTING - ~kitlist.2da~ ~override~
	COUNT_2DA_COLS num_cols
	READ_2DA_ENTRIES_NOW ~r2en_kitlist~ num_cols
	FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
		READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kitname
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~%this_kit%~) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 strref
		END
	END
BUT_ONLY

ACTION_IF (strref >= 0) BEGIN
	ACTION_GET_STRREF %strref% kit_description 
	OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
		REPLACE_TEXTUALLY ~%disadvantages%~ ~%restrictions%~
		REPLACE_TEXTUALLY ~%abilities%~ ~%kit_spheres%~
		REPLACE_TEXTUALLY ~%advantages%~ ~%kit_spheres%~
	END
	STRING_SET_EVALUATE %strref% ~%kit_description%~
END

END
//__________________________________________________________________________________


//ADD MONITOR_________________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ACTION_IF NOT FILE_EXISTS_IN_GAME ~qdtnb00.qd~ THEN BEGIN

ADD_KIT ~D5MYSTR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MYSTR       1 1 1 1 1 1 1 1~
~D5MYSTR       1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MYSTR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MYSTR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_mystr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000400 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5100
SAY @5101
SAY @5102
//__________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~qdtnb00.qd~ THEN BEGIN

ADD_KIT ~D5MYSTR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MYSTR       1 1 1 1 1 1 1 1~
~D5MYSTR       1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MYSTR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MYSTR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_mystr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000080 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5100
SAY @5101
SAY @5102
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5102)
		STR_VAR
			kit_name = D5MYSTR
			clswpbon = ~0 0 3~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ACTION_IF NOT FILE_EXISTS_IN_GAME ~qdtnb00.qd~ THEN BEGIN

ADD_KIT ~D5MYSTR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MYSTR       2 2 2 0 2 2 0 2~
~D5MYSTR       2 2 2 2 2 2 0 2 0 0 0 0 0 0 0 2 2 2 0 0 2 2 2 2 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MYSTR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MYSTR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_mystr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000400 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5100
SAY @5101
SAY @5102
//__________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~qdtnb00.qd~ THEN BEGIN

ADD_KIT ~D5MYSTR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5MYSTR       2 2 2 0 2 2 0 2~
~D5MYSTR       2 2 2 2 2 2 0 2 0 0 0 0 0 0 0 2 2 2 0 0 2 2 2 2 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5MYSTR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5MYSTR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5MYSTR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_mystr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000080 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5100
SAY @5101
SAY @5102
//__________________________________________________________________________________

END

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5102)
		STR_VAR
			kit_name = D5MYSTR
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

//MONITOR ABILITY FILES_______________________________________________________________
//
COPY ~might_and_guile/mc/d5_mystr.2da~ ~override~
COPY ~might_and_guile/mc/d5_selns.spl~ ~override~
COPY ~might_and_guile/mc/d5_mystr.itm~ ~override~
	SAY NAME1 @5103
	SAY NAME2 @5103
	SAY UNIDENTIFIED_DESC @5104
	SAY IDENTIFIED_DESC @5104
COPY ~might_and_guile/mc/d5_mystr.spl~ ~override~
	SAY NAME1 @9
COPY ~might_and_guile/mc/d5_mystr.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_mystr.baf~
COPY ~might_and_guile/misc/d5_cllv1.spl~ ~override~
COPY ~might_and_guile/misc/d5_cllv2.spl~ ~override~
COPY ~might_and_guile/misc/d5_cllv3.spl~ ~override~
COPY ~might_and_guile/misc/d5_cllv4.spl~ ~override~
COPY ~might_and_guile/misc/d5_cllv5.spl~ ~override~
COPY ~might_and_guile/misc/d5_mglv1.spl~ ~override~
COPY ~might_and_guile/misc/d5_mglv2.spl~ ~override~
COPY ~might_and_guile/misc/d5_mglv3.spl~ ~override~
COPY ~might_and_guile/misc/d5_mglv4.spl~ ~override~
COPY ~might_and_guile/misc/d5_mglv5.spl~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN
	COPY ~might_and_guile/mc/d5_mystr.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/profs/pcstaf.txt~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_mystr.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
	BUT_ONLY
END
//____________________________________________________________________________________

//FnP SPHERE SYSTEM COMPATIBILITY____________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN

ACTION_IF GAME_IS ~iwdee~ BEGIN
	OUTER_SPRINT game ~iwd~
END
ELSE BEGIN
	OUTER_SPRINT game ~bg2~
END

OUTER_SPRINT this_kit ~D5MYSTR~ // ..............................KIT NAME HERE
OUTER_SPRINT kit_clab ~d5_mystr~ // .....................KIT CLAB FILE HERE (without .2da extension)
OUTER_SPRINT kit_spheres @5105 // ..........................KIT SPHERES TRA REF HERE

//add spheres_______________________________________________________________________
//
COPY_EXISTING ~%kit_clab%.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~f_n_p/spheres/%game%/magic_focus.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/divine_aid_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/life_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/protection_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/destruction_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/knowledge_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/light_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/thought_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/dread_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/vigor_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/air_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/fire_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/shadow_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/deception_minor.txt~
BUT_ONLY

//__________________________________________________________________________________

OUTER_SET strref = (0 - 1)

COPY_EXISTING - ~kitlist.2da~ ~override~
	COUNT_2DA_COLS num_cols
	READ_2DA_ENTRIES_NOW ~r2en_kitlist~ num_cols
	FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
		READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kitname
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~%this_kit%~) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 strref
		END
	END
BUT_ONLY

ACTION_IF (strref >= 0) BEGIN
	ACTION_GET_STRREF %strref% kit_description 
	OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
		REPLACE_TEXTUALLY ~%disadvantages%~ ~%restrictions%~
		REPLACE_TEXTUALLY ~%abilities%~ ~%kit_spheres%~
		REPLACE_TEXTUALLY ~%advantages%~ ~%kit_spheres%~
	END
	STRING_SET_EVALUATE %strref% ~%kit_description%~
END

END
//__________________________________________________________________________________


//ADD SPELLBENDER_____________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5BENDR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5BENDR       1 1 1 1 1 1 1 1~
~D5BENDR       1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5BENDR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5BENDR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_bendr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000400 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5100
SAY @5101
SAY @5102
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5112)
		STR_VAR
			kit_name = D5BENDR
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

ACTION_IF FILE_EXISTS_IN_GAME ~d5_profs.d5~ THEN BEGIN

ADD_KIT ~D5BENDR~

//WEAPON PROFICIENCIES________________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5BENDR       2 2 2 0 2 2 0 2~
~D5BENDR       2 2 2 0 2 2 0 2 0 0 0 0 0 0 0 2 2 2 0 0 2 2 2 2 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   14  13  0~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT_________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5BENDR           0   0   0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5BENDR           1  1  1  1  1  0  0  0  0~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5BENDR           0  0  0  0  0  0~

//KIT ABILITIES 2DA FILE______________________________________________________________
~might_and_guile/mc/d5_bendr.2da~

//RACIAL KIT AVAILABILITY_____________________________________________________________
~~

//UNUSABLE FLAGS AND KIT BASE CLASS_________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00000080 3~

//HIGH LEVEL ABILITIES ABBREVIATION_________________________________________________
~Ma0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG25 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 BOW18 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5111
SAY @5111
SAY @5112
//__________________________________________________________________________________

//EE KIT EXTRAS_____________________________________________________________________
ACTION_IF GAME_IS ~bgee bg2ee iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5112)
		STR_VAR
			kit_name = D5BENDR
			clswpbon = ~1 0 3~
	END
END
//____________________________________________________________________________________

END

//SPELLBENDER ABILITY FILES___________________________________________________________
//
COPY ~might_and_guile/mc/d5_bendr.2da~ ~override~
COPY ~might_and_guile/mc/d5_bendr.itm~ ~override~
	SAY NAME1 @5113
	SAY NAME2 @5113
	SAY UNIDENTIFIED_DESC @5114
	SAY IDENTIFIED_DESC @5114
COPY ~might_and_guile/mc/d5_bendr.spl~ ~override~
	SAY NAME1 @9
COPY ~might_and_guile/mc/d5_bendr.cre~ ~override~
COMPILE ~might_and_guile/mc/d5_bendr.baf~
//Huge thanks to DreamSlaveOne at forums.gibberlings3.net for providing the .BAMs for the Spellbender's abilities!
COPY ~might_and_guile/mc/d5_arcm1.spl~ ~override~
	SAY NAME1 @5115
	SAY UNIDENTIFIED_DESC @5116
COPY ~might_and_guile/mc/d5_arcm1.2da~ ~override~
COPY ~might_and_guile/mc/d5_arc1b.bam~ ~override~
COPY ~might_and_guile/mc/d5_arc1c.bam~ ~override~
COPY ~might_and_guile/mc/d5_arcm2.spl~ ~override~
	SAY NAME1 @5117
	SAY UNIDENTIFIED_DESC @5118
COPY ~might_and_guile/mc/d5_arcm2.2da~ ~override~
COPY ~might_and_guile/mc/d5_arc2b.bam~ ~override~
COPY ~might_and_guile/mc/d5_arc2c.bam~ ~override~
COPY ~might_and_guile/mc/d5_arcm3.spl~ ~override~
	SAY NAME1 @5119
	SAY UNIDENTIFIED_DESC @5120
COPY ~might_and_guile/mc/d5_arcm3.2da~ ~override~
COPY ~might_and_guile/mc/d5_arc3b.bam~ ~override~
COPY ~might_and_guile/mc/d5_arc3c.bam~ ~override~
COPY ~might_and_guile/mc/d5_arcm4.spl~ ~override~
	SAY NAME1 @5121
	SAY UNIDENTIFIED_DESC @5122
COPY ~might_and_guile/mc/d5_arcm4.2da~ ~override~
COPY ~might_and_guile/mc/d5_arc4b.bam~ ~override~
COPY ~might_and_guile/mc/d5_arc4c.bam~ ~override~
COPY ~might_and_guile/mc/d5_arcm5.spl~ ~override~
	SAY NAME1 @5123
	SAY UNIDENTIFIED_DESC @5124
COPY ~might_and_guile/mc/d5_arcm5.2da~ ~override~
COPY ~might_and_guile/mc/d5_arc5b.bam~ ~override~
COPY ~might_and_guile/mc/d5_arc5c.bam~ ~override~
COPY ~might_and_guile/mc/d5_arcm6.spl~ ~override~
	SAY NAME1 @5125
	SAY UNIDENTIFIED_DESC @5126
COPY ~might_and_guile/mc/d5_arcm6.2da~ ~override~
COPY ~might_and_guile/mc/d5_arc6b.bam~ ~override~
COPY ~might_and_guile/mc/d5_arc6c.bam~ ~override~
COPY ~might_and_guile/mc/d5_divm1.spl~ ~override~
	SAY NAME1 @5127
	SAY UNIDENTIFIED_DESC @5128
COPY ~might_and_guile/mc/d5_divm1.2da~ ~override~
COPY ~might_and_guile/mc/d5_div1b.bam~ ~override~
COPY ~might_and_guile/mc/d5_div1c.bam~ ~override~
COPY ~might_and_guile/mc/d5_divm2.spl~ ~override~
	SAY NAME1 @5129
	SAY UNIDENTIFIED_DESC @5130
COPY ~might_and_guile/mc/d5_divm2.2da~ ~override~
COPY ~might_and_guile/mc/d5_div2b.bam~ ~override~
COPY ~might_and_guile/mc/d5_div2c.bam~ ~override~
COPY ~might_and_guile/mc/d5_divm3.spl~ ~override~
	SAY NAME1 @5131
	SAY UNIDENTIFIED_DESC @5132
COPY ~might_and_guile/mc/d5_divm3.2da~ ~override~
COPY ~might_and_guile/mc/d5_div3b.bam~ ~override~
COPY ~might_and_guile/mc/d5_div3c.bam~ ~override~
COPY ~might_and_guile/mc/d5_divm4.spl~ ~override~
	SAY NAME1 @5133
	SAY UNIDENTIFIED_DESC @5134
COPY ~might_and_guile/mc/d5_divm4.2da~ ~override~
COPY ~might_and_guile/mc/d5_div4b.bam~ ~override~
COPY ~might_and_guile/mc/d5_div4c.bam~ ~override~
COPY ~might_and_guile/mc/d5_divm5.spl~ ~override~
	SAY NAME1 @5135
	SAY UNIDENTIFIED_DESC @5136
COPY ~might_and_guile/mc/d5_divm5.2da~ ~override~
COPY ~might_and_guile/mc/d5_div5b.bam~ ~override~
COPY ~might_and_guile/mc/d5_div5c.bam~ ~override~
COPY ~might_and_guile/mc/d5_divm6.spl~ ~override~
	SAY NAME1 @5137
	SAY UNIDENTIFIED_DESC @5138
COPY ~might_and_guile/mc/d5_divm6.2da~ ~override~
COPY ~might_and_guile/mc/d5_div6b.bam~ ~override~
COPY ~might_and_guile/mc/d5_div6c.bam~ ~override~
ACTION_IF FILE_EXISTS_IN_GAME ~d5_stats.d5~ THEN BEGIN
	COPY_EXISTING ~d5_bendr.2da~ ~override~
		LPM remove_blank_lines
		APPEND_FILE ~might_and_guile/misc/charisma_bonuses.txt~
		APPEND_FILE ~might_and_guile/misc/crit_changes.txt~
		APPEND_FILE ~might_and_guile/misc/intelligence_wizards.txt~
	BUT_ONLY
END
//___________________________________________________________________________________


//FnP SPHERE SYSTEM COMPATIBILITY____________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5_spheres.d5~) BEGIN

ACTION_IF GAME_IS ~iwdee~ BEGIN
	OUTER_SPRINT game ~iwd~
END
ELSE BEGIN
	OUTER_SPRINT game ~bg2~
END

OUTER_SPRINT this_kit ~D5BENDR~ // ..............................KIT NAME HERE
OUTER_SPRINT kit_clab ~d5_bendr~ // .....................KIT CLAB FILE HERE (without .2da extension)
OUTER_SPRINT kit_spheres @5141 // ..........................KIT SPHERES TRA REF HERE

//add spheres_______________________________________________________________________
//
COPY_EXISTING ~%kit_clab%.2da~ ~override~
	LPM remove_blank_lines
	APPEND_FILE ~f_n_p/spheres/%game%/divine_aid_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/life_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/protection_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/destruction_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/knowledge_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/light_major.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/death_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/war_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/thought_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/dread_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/vigor_minor.txt~
	APPEND_FILE ~f_n_p/spheres/%game%/magic_minor.txt~
BUT_ONLY

//__________________________________________________________________________________

OUTER_SET strref = (0 - 1)

COPY_EXISTING - ~kitlist.2da~ ~override~
	COUNT_2DA_COLS num_cols
	READ_2DA_ENTRIES_NOW ~r2en_kitlist~ num_cols
	FOR (row = 1; row < r2en_kitlist; row += 1) BEGIN
		READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 1 kitname
		PATCH_IF (~%kitname%~ STRING_EQUAL_CASE ~%this_kit%~) BEGIN
			READ_2DA_ENTRY_FORMER ~r2en_kitlist~ row 4 strref
		END
	END
BUT_ONLY

ACTION_IF (strref >= 0) BEGIN
	ACTION_GET_STRREF %strref% kit_description 
	OUTER_PATCH_SAVE kit_description ~%kit_description%~ BEGIN
		REPLACE_TEXTUALLY ~%disadvantages%~ ~%restrictions%~
		REPLACE_TEXTUALLY ~%abilities%~ ~%kit_spheres%~
		REPLACE_TEXTUALLY ~%advantages%~ ~%kit_spheres%~
	END
	STRING_SET_EVALUATE %strref% ~%kit_description%~
END

END
//__________________________________________________________________________________


/*
//CHECK FOR NEW WIZARD SLAYER________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_nuwsl.d5~ THEN BEGIN
	COPY ~might_and_guile/mc/d5_nuwsl.itm~ ~override~
		SAY NAME1 @5139
		SAY NAME2 @5139
		SAY UNIDENTIFIED_DESC @5140
		SAY IDENTIFIED_DESC @5140
	COPY ~might_and_guile/mc/d5_nuwsl.spl~ ~override~
		SAY NAME1 @9
	COPY ~might_and_guile/mc/d5_nuwsl.cre~ ~override~
	COMPILE ~might_and_guile/mc/d5_nuwsl.baf~
//
//COPY MARKER FILE__________________________________________________________________
//
	COPY ~might_and_guile/mc/d5_nuwslm.d5~ ~override~
END
//__________________________________________________________________________________
*/


//ADD KIT ITEMS______________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~tem2601.sto~)THEN BEGIN
	COPY_EXISTING ~tem2601.sto~ ~override~
		ADD_STORE_ITEM ~d5_mystr~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_tempu~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_blads~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_filch~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_bendr~ #0 #0 #0 ~identified~ #1
		BUT_ONLY
/*
	ACTION_IF FILE_EXISTS_IN_GAME ~d5_nuwsl.d5~ THEN BEGIN
		COPY_EXISTING ~tem2601.sto~ ~override~
			ADD_STORE_ITEM ~d5_nuwsl~ #0 #0 #0 ~identified~ #1
			BUT_ONLY
	END
*/
END
ACTION_IF (FILE_EXISTS_IN_GAME ~shop08.sto~)THEN BEGIN
	COPY_EXISTING ~shop08.sto~ ~override~
		ADD_STORE_ITEM ~d5_blads~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_filch~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_bendr~ #0 #0 #0 ~identified~ #1
		BUT_ONLY
/*
	ACTION_IF FILE_EXISTS_IN_GAME ~d5_nuwsl.d5~ THEN BEGIN
		COPY_EXISTING ~shop08.sto~ ~override~
			ADD_STORE_ITEM ~d5_nuwsl~ #0 #0 #0 ~identified~ #1
			BUT_ONLY
	END
*/
END
ACTION_IF (FILE_EXISTS_IN_GAME ~kuoswald.sto~) THEN BEGIN
	COPY_EXISTING ~kuoswald.sto~ ~override~
		ADD_STORE_ITEM ~d5_mystr~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_msadv~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_harth~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_mask~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_alagh~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_tempu~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_blads~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_filch~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_bendr~ #0 #0 #0 ~identified~ #1
		BUT_ONLY
/*
	ACTION_IF FILE_EXISTS_IN_GAME ~d5_nuwsl.d5~ THEN BEGIN
		COPY_EXISTING ~kuoswald.sto~ ~override~
			ADD_STORE_ITEM ~d5_nuwsl~ #0 #0 #0 ~identified~ #1
			BUT_ONLY
	END
*/
	COPY_EXISTING ~ehpomab.sto~ ~override~
		ADD_STORE_ITEM ~d5_mystr~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_msadv~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_harth~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_mask~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_alagh~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_tempu~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_blads~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_filch~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_bendr~ #0 #0 #0 ~identified~ #1
		BUT_ONLY
/*
	ACTION_IF FILE_EXISTS_IN_GAME ~d5_nuwsl.d5~ THEN BEGIN
		COPY_EXISTING ~ehpomab.sto~ ~override~
			ADD_STORE_ITEM ~d5_nuwsl~ #0 #0 #0 ~identified~ #1
			BUT_ONLY
	END
*/
END
ACTION_IF FILE_EXISTS_IN_GAME ~shop06.sto~ THEN BEGIN
	COPY_EXISTING ~shop06.sto~ ~override~
		ADD_STORE_ITEM ~d5_msadv~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_harth~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_tempu~ #0 #0 #0 ~identified~ #1
		ADD_STORE_ITEM ~d5_mystr~ #0 #0 #0 ~identified~ #1
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~caldo.cre~ THEN BEGIN
	COPY_EXISTING ~caldo.cre~ ~override~
		ADD_CRE_ITEM ~d5_mieli~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~duecla01.cre~ THEN BEGIN
	COPY_EXISTING ~duecla01.cre~ ~override~
		ADD_CRE_ITEM ~d5_mieli~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		ADD_CRE_ITEM ~d5_alagh~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~zhurlo.cre~ THEN BEGIN
	COPY_EXISTING ~zhurlo.cre~ ~override~
		ADD_CRE_ITEM ~d5_mask~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~irethf05.cre~ THEN BEGIN
	COPY_EXISTING ~irethf05.cre~ ~override~
		ADD_CRE_ITEM ~d5_mask~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~ogrema03.cre~ THEN BEGIN
	COPY_EXISTING ~ogrema03.cre~ ~override~
		ADD_CRE_ITEM ~d5_alagh~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
ACTION_IF FILE_EXISTS_IN_GAME ~jenkal.cre~ THEN BEGIN
	COPY_EXISTING ~jenkal.cre~ ~override~
		ADD_CRE_ITEM ~d5_msadv~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		ADD_CRE_ITEM ~d5_harth~ #0 #0 #0 ~IDENTIFIED~ ~INV~
		BUT_ONLY
END
//____________________________________________________________________________________
