
//_________________________CORSAIR__________________________________________________
//
DEFINE_ACTION_FUNCTION corsair_kit BEGIN

LAF check_kit_conflict END

ADD_KIT ~D5CORSA~

//WEAPON PROFICIENCIES_______________________________________________________________
//11                                   T   S           F   Q             S S
//10           L S                     W   C           L   U             W I
//9            A M             B L S   O   I   W       A   A             O N
//8            R A             A O H   H   M   A       I   R C   S       R G
//7            G L           M S N O   A   I   R     H L   T R L H     2 D L 2                 E E E E E E E E E E E
//6            E L       S   I T G R   N K T D H     A M   E O O O     H A E W E E E E E E E E X X X X X X X X X X X
//5            S S   S B P   S A S T   D A A A A   S L O   R S N R   S A N W E X X X X X X X X T T T T T T T T T T T
//4            W W   P L I   S R W S   E T R G M C P B R M S S G T D L N D E A T T T T T T T T R R R R R R R R R R R
//3            O O B E U K A I D O W A D A W G M L E E N A T B B B A I D S A P R R R R R R R R A A A A A A A A A A A
//2            R R O A N E X L S R O X S N A E E U A R I C A O O O R N E H P O A A A A A A A A 1 1 1 1 1 1 1 1 1 1 2
//1            D D W R T D E E W D R E W A K R R B R D N E F W W W T G D I O N 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0
~D5CORSA       0 0 0 0 0 0 0 0~
~D5CORSA       0 0 0 0 0 0 0 0 0 2 5 2 0 2 5 5 2 2 0 0 0 2 2 2 2 2 2 2 2 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~

//MINIMUM KIT STATS_________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5CORSA           9   12  0   9   0   9~

//KIT STAT MODIFIERS________________________________________________________________
//                 STR DEX CON INT WIS CHR
~D5CORSA           0   0   0   0   0   0~

//REQUIREMENTS TO DUAL TO THIS KIT__________________________________________________
//                 STR DEX CON INT WIS CHR
~D5CORSA           15  15  0   0   0   0~

//REQUIREMENTS TO DUAL FROM THIS KIT________________________________________________
//                 STR DEX CON INT WIS CHR
~D5CORSA           15  15  0   0   0   0~

//ALIGNMENT RESTRICTIONS____________________________________________________________
//                 LG LN LE NG TN NE CG CN CE
~D5CORSA           0  0  0  1  1  1  1  1  1~

//DUAL CLASS OPTIONS________________________________________________________________
//                 FT CL MA TH DR RA
~D5CORSA           0  1  1  1  0  0~

//KIT ABILITIES 2DA FILE_____________________________________________________________
~might_and_guile/fighter/d5_corsa.2da~

//RACIAL KIT AVAILABILITY____________________________________________________________
~K_F_H K_F_G K_F_E K_F_HE K_F_HL K_F_HO~

//UNUSABLE FLAGS AND KIT BASE CLASS__________________________________________________
//CLASSES: Mage = 1, Fighter = 2, Cleric=3, Thief = 4, Bard = 5
//         Paladin 6, Druid = 11, Ranger = 12, Sorcerer = 19
//         Monk = 20
~0x00010000 2~

//HIGH LEVEL ABILITIES ABBREVIATION__________________________________________________
~Fi0~

//TOB STARTING EQUIPMENT_____________________________________________________________
~LEAT14	* HELM07 BAG20 RING06 RING31 CLCK02 BOOT01 AMUL19 BRAC16 BELT06 AROW11,40 BULL03,40 BOLT06,40 POTN52,5 POTN04,2 POTN14,5 HAMM07 SW1H39 STAF08~

//CHARACTER CREATION KIT DESCRIPTION________________________________________________
SAY @5501
SAY @5502
SAY @5503
//___________________________________________________________________________________

//EE KIT EXTRAS______________________________________________________________________
//
ACTION_IF GAME_IS ~bgee bg2ee eet iwdee~ THEN BEGIN
	LAF fl#add_kit_ee
		INT_VAR
			briefdesc = RESOLVE_STR_REF (@5504)
		STR_VAR
			kit_name = D5CORSA
			clswpbon = ~1 0 2~
	END
END
//____________________________________________________________________________________

//CORSAIR ABILITY FILES_______________________________________________________________
//
COPY ~might_and_guile/fighter/d5_corsa.2da~ ~override~
COPY ~might_and_guile/misc/d5bsvbo.spl~ ~override~
	SAY NAME1 @17
COPY ~might_and_guile/misc/d5_acbo1.spl~ ~override~
COPY ~might_and_guile/misc/d5_jluck.spl~ ~override~
	SAY NAME1 @5508
	SAY UNIDENTIFIED_DESC @5508
COPY ~might_and_guile/fighter/d5_swapr.spl~ ~override~
COPY ~might_and_guile/misc/d5swash.spl~ ~override~				//	swashbuckling ability
	SAY NAME1 @5506
	SAY UNIDENTIFIED_DESC @5507
COPY ~might_and_guile/misc/d5swshb.eff~ ~override~
COPY ~might_and_guile/misc/d5swshc.spl~ ~override~
COPY ~might_and_guile/misc/d5swshx.spl~ ~override~
	SAY NAME1 @5514
	SAY UNIDENTIFIED_DESC @5514
COPY ~might_and_guile/misc/d5swshx.bam~ ~override~
//____________________________________________________________________________________
	
//WILD TALENT_________________________________________________________________________
//
ACTION_IF (FILE_EXISTS_IN_GAME ~d5__psionics.d5~) BEGIN
  ACTION_IF (FILE_EXISTS_IN_GAME ~d5_corsa.2da~) BEGIN
	APPEND ~d5_corsa.2da~ ~WILD_TLNT   AP_D5PSWT_  ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        ****        **** ~
  END
END
//____________________________________________________________________________________

END	//	end function

