
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ARCHER FEATS
//__________________________________________________________________________________
//__________________________________________________________________________________


//COPY MARKER FILE_________________________________________________________________
//
COPY ~might_and_guile/lib/markers/d5_archy.d5~ ~override~
//__________________________________________________________________________________

/*

should do: 
- crippling hit = -STR + slow (use ARSLO?)  
- fumble = 0 APR (use ARDIS?)
- trip = fall + slow (ARTRP)
- pin - 0 move (ARMOV)
...
- stun = stun (slinger) (ARSTN)
- blind = blind (sniper) (ARBLI)
- hammer = knockback (marksman) (ARHAM)

*/

//ARCHER ABILITIES___________________________________________________________________
//
COPY ~might_and_guile/fighter/d5_artrp.eff~ ~override~
COPY ~might_and_guile/fighter/d5_artrp.spl~ ~override~ 	//	called shot: trip
	SAY NAME1 @20513
	SAY UNIDENTIFIED_DESC @20514
	WRITE_ASCII 0x3a ~d5_artrp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_artrp~ END
COPY ~might_and_guile/fighter/d5_artrp.bam~ ~override~

COPY ~might_and_guile/fighter/d5_armv1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_armv2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_armov.spl~ ~override~	//	called shot: pin
	SAY NAME1 @20511
	SAY UNIDENTIFIED_DESC @20512
	WRITE_ASCII 0x3a ~d5_armov~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_armov~ END
COPY ~might_and_guile/fighter/d5_armov.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arsl1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arsl2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arsl3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arslo.spl~ ~override~	//	called shot: cripple
	SAY NAME1 @20519
	SAY UNIDENTIFIED_DESC @20520
	WRITE_ASCII 0x3a ~d5_arslo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslo~ END
COPY ~might_and_guile/fighter/d5_arslo.bam~ ~override~

COPY ~might_and_guile/fighter/d5_ards1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ards2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ards3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ardis.spl~ ~override~	//	called shot: disarm
	SAY NAME1 @20515
	SAY UNIDENTIFIED_DESC @20516
	WRITE_ASCII 0x3a ~d5_ardis~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_ardis~ END
COPY ~might_and_guile/fighter/d5_ardis.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arbli.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arbli.spl~ ~override~	//	called shot: blind
	SAY NAME1 @20521
	SAY UNIDENTIFIED_DESC @20522
	WRITE_ASCII 0x3a ~d5_arbli~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arbli~ END
COPY ~might_and_guile/fighter/d5_arbli.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arhm1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arhm2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arhm3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arham.spl~ ~override~	//	called shot: hammer
	SAY NAME1 @20517
	SAY UNIDENTIFIED_DESC @20518
	WRITE_ASCII 0x3a ~d5_arham~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arham~ END
COPY ~might_and_guile/fighter/d5_arham.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arstn.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arstn.spl~ ~override~	//	called shot: stun
	SAY NAME1 @20523
	SAY UNIDENTIFIED_DESC @20524
	WRITE_ASCII 0x3a ~d5_arstn~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arstn~ END
COPY ~might_and_guile/fighter/d5_arstn.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arnt1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arnt2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arent.spl~ ~override~	//	called shot: entangle
	SAY NAME1 @20531
	SAY UNIDENTIFIED_DESC @20532
	WRITE_ASCII 0x3a ~d5_arent~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arent~ END
COPY ~might_and_guile/fighter/d5_arent.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arslp.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arslp.spl~ ~override~	//	called shot: sleep
	SAY NAME1 @20533
	SAY UNIDENTIFIED_DESC @20534
	WRITE_ASCII 0x3a ~d5_arslp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslp~ END
COPY ~might_and_guile/fighter/d5_arslp.bam~ ~override~

COPY ~might_and_guile/fighter/d5_ffire.vvc~ ~override~
COPY ~might_and_guile/fighter/d5_arff1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff4.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff5.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ffire.vvc~ ~override~
COPY ~might_and_guile/fighter/d5_arffi.spl~ ~override~	//	called shot: faerie fire
	SAY NAME1 @20535
	SAY UNIDENTIFIED_DESC @20536
	WRITE_ASCII 0x3a ~d5_arffi~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arffi~ END
COPY ~might_and_guile/fighter/d5_arffi.bam~ ~override~


COPY ~might_and_guile/fighter/d5_csa.spl~ ~override/d5ucsa.spl~		//	give trip
	SAY NAME1 @20513
	SAY UNIDENTIFIED_DESC @20514
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_artrp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_artrp~ END
COPY_EXISTING ~d5ucsa.spl~ ~override/d5vcsa.spl~
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/fighter/d5_csb.spl~ ~override/d5ucsb.spl~		//	give pin
	SAY NAME1 @20511
	SAY UNIDENTIFIED_DESC @20512
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_armov~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_armov~ END
COPY_EXISTING ~d5ucsb.spl~ ~override/d5vcsb.spl~
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/fighter/d5_csc.spl~ ~override/d5ucsc.spl~		//	give cripple
	SAY NAME1 @20519
	SAY UNIDENTIFIED_DESC @20520
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_arslo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslo~ END
COPY_EXISTING ~d5ucsc.spl~ ~override/d5vcsc.spl~
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/fighter/d5_csd.spl~ ~override/d5ucsd.spl~		//	give disarm
	SAY NAME1 @20515
	SAY UNIDENTIFIED_DESC @20516
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_ardis~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_ardis~ END
COPY_EXISTING ~d5ucsd.spl~ ~override/d5vcsd.spl~
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/fighter/d5_cse.spl~ ~override/d5ucse.spl~		//	give blind
	SAY NAME1 @20521
	SAY UNIDENTIFIED_DESC @20522
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_arbli~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arbli~ END
COPY_EXISTING ~d5ucse.spl~ ~override/d5vcse.spl~
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/fighter/d5_csf.spl~ ~override/d5ucsf.spl~		//	give hammer
	SAY NAME1 @20517
	SAY UNIDENTIFIED_DESC @20518
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_arham~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arham~ END
COPY_EXISTING ~d5ucsf.spl~ ~override/d5vcsf.spl~
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/fighter/d5_csg.spl~ ~override/d5ucsg.spl~		//	give stun
	SAY NAME1 @20523
	SAY UNIDENTIFIED_DESC @20524
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 4
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_arstn~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arstn~ END
COPY_EXISTING ~d5ucsg.spl~ ~override/d5vcsg.spl~
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/fighter/d5_csh.spl~ ~override/d5ucsh.spl~		//	give entangle
	SAY NAME1 @20531
	SAY UNIDENTIFIED_DESC @20532
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_arent~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arent~ END
COPY_EXISTING ~d5ucsh.spl~ ~override/d5vcsh.spl~
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/fighter/d5_csi.spl~ ~override/d5ucsi.spl~		//	give sleep
	SAY NAME1 @20533
	SAY UNIDENTIFIED_DESC @20534
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_arslp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslp~ END
COPY_EXISTING ~d5ucsi.spl~ ~override/d5vcsi.spl~
	WRITE_SHORT 0x1c 1
COPY ~might_and_guile/fighter/d5_csj.spl~ ~override/d5ucsj.spl~		//	give faerie fire
	SAY NAME1 @20535
	SAY UNIDENTIFIED_DESC @20536
	WRITE_SHORT 0x1c 2
	PATCH_IF GAME_IS ~iwdee~ BEGIN
	  WRITE_LONG 0x34 3
	END ELSE BEGIN
	  WRITE_LONG 0x34 1
	END
	WRITE_ASCII 0x3a ~d5_arffi~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arffi~ END
COPY_EXISTING ~d5ucsj.spl~ ~override/d5vcsj.spl~
	WRITE_SHORT 0x1c 1

/*
COPY ~might_and_guile/fighter/d5_rafx.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/fighter/d5_rafy.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/fighter/d5_rafz.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/fighter/d5_raf1.spl~ ~override~
	SAY NAME1 @3210
	SAY UNIDENTIFIED_DESC @3210
COPY ~might_and_guile/fighter/d5_rafa.spl~ ~override~
	SAY NAME1 @7

COPY ~might_and_guile/fighter/d5_raf.bam~ ~override~
ACTION_FOR_EACH shotclab IN ~d5_rafa~ ~d5_rafb~ ~d5_rafc~ ~d5_rafd~ ~d5_rafe~ ~d5_raff~ ~d5_rafg~ ~d5_refh~ ~d5_refa~ ~d5_refb~ ~d5_refc~ ~d5_refd~ ~d5_refe~ ~d5_reff~ ~d5_refg~ ~d5_refh~ BEGIN
  COPY ~might_and_guile/fighter/%shotclab%.spl~ ~override~
	SAY NAME1 @7
	SAY UNIDENTIFIED_DESC @7
	WRITE_ASCII 0x3a ~d5_raf~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_raf~ END
END
ACTION_FOR_EACH shoteff IN ~d5_raf1~ ~d5_raf2~ ~d5_raf3~ ~d5_raf4~ ~d5_raf5~ ~d5_raf6~ ~d5_raf7~ ~d5_ref1~ ~d5_ref2~ ~d5_ref3~ ~d5_ref4~ ~d5_ref5~ ~d5_ref6~ ~d5_ref7~ ~d5_ref8~ BEGIN
  COPY ~might_and_guile/fighter/%shoteff%.eff~ ~override~
END
ACTION_FOR_EACH shotspell IN ~d5_raf1~ ~d5_raf2~ ~d5_raf3~ ~d5_raf4~ ~d5_raf5~ ~d5_raf6~ ~d5_raf7~ ~d5_ref1~ ~d5_ref2~ ~d5_ref3~ ~d5_ref4~ ~d5_ref5~ ~d5_ref6~ ~d5_ref7~ ~d5_ref8~ BEGIN
  COPY ~might_and_guile/fighter/%shotspell%.spl~ ~override~
	SAY NAME1 @3210
	SAY UNIDENTIFIED_DESC @3210
	WRITE_ASCII 0x3a ~d5_raf~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_raf~ END
END
*/

//__________________________________________________________________________________

ACTION_DEFINE_ASSOCIATIVE_ARRAY feat_nums_lets BEGIN
	1	=> a
	2	=> b
	3	=> c
	4	=> d
	5	=> e
	6	=> f
	7	=> g
	8	=> h
	9	=> i
	10	=> j
	11	=> k
	12	=> l
	13	=> m
	14	=> n
	15	=> o
	16	=> p
	17	=> q
	18	=> r
	19	=> s
	20	=> t
END

INCLUDE ~might_and_guile/lib/sequencer_menu_d5.tpa~

APPEND ~splprot.2da~ ~D5_KIT_IS%TAB%152%TAB%-1%TAB%1~ UNLESS ~D5_KIT_IS~
COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW r2en_splprot cols
	FOR (row = 1; row < r2en_splprot; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER r2en_splprot row 0 ~stat~
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_KIT_IS~ BEGIN
	    SET kit_is_row = %row%
	  END
	END
BUT_ONLY

COPY ~might_and_guile/feats/d5flsta.2da~ ~override~

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5ftskn.2da~) BEGIN
 ACTION_IF !(GAME_IS ~iwdee~) BEGIN
  COPY ~might_and_guile/feats/d5ftskn.2da~ ~override~
 END
 ACTION_IF (GAME_IS ~iwdee~) BEGIN
  COPY ~might_and_guile/feats/d5ftskn_iwd.2da~ ~override/d5ftskn.2da~
 END
END

OUTER_SPRINT feat_select_string @20011 // ~Feat Selection~ 
OUTER_SET feat_select_strref = RESOLVE_STR_REF (%feat_select_string%)
OUTER_SPRINT feat_title_string @20012 
OUTER_SPRINT feat_label_string @20013 

/*
COPY_EXISTING ~d5flsta.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 1; row < rows; ++row) BEGIN
  	READ_2DA_ENTRY row 0 cols ~book_feat~
	SNPRINT 3 book_feat_prefix ~%book_feat%~
	PATCH_IF (~%book_feat%~ STRING_MATCHES_REGEXP ~[Dd]5[UuVv][Cc][Ss][AaBbCcDdEeFfGgHhIiJj]~ = 0) BEGIN
	  INNER_ACTION BEGIN
		COPY_EXISTING ~%book_feat%.spl~ ~override/%book_feat%L.spl~
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%book_feat%~ END
		COPY_EXISTING ~%book_feat%.spl~ ~override~
		  WRITE_LONG 0x34 3
		  PATCH_IF (~%book_feat_prefix%~ STRING_EQUAL_CASE ~d5u~) BEGIN
			WRITE_SHORT 0x1c 2
		  END
		  PATCH_IF (~%book_feat_prefix%~ STRING_EQUAL_CASE ~d5v~) BEGIN
			WRITE_SHORT 0x1c 1
		  END
		  LPF DELETE_EFFECT END
		IF_EXISTS
	  END
	END
  END
BUT_ONLY
*/

/*
ACTION_FOR_EACH high_level_feat IN 
	~d5ucsf~ 
	~d5vcsf~ 
	~d5ucsg~ 
	~d5vcsg~ BEGIN
  COPY_EXISTING ~%high_level_feat%.spl~ ~override~
	WRITE_LONG 0x34 4
  IF_EXISTS BUT_ONLY
END
*/

//NO FEATS YET________________________________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ THEN BEGIN
 COPY_EXISTING ~d5flsta.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (col = 1; col < (cols - 1); ++col) BEGIN
	READ_2DA_ENTRY 0 (col - 1) (cols - 1) feat_kit_2da
	INNER_ACTION BEGIN
	  COPY_EXISTING ~kitlist.2da~ ~override~
		READ_2DA_ENTRIES_NOW rows 9
		FOR (row = 1; row < rows; ++row) BEGIN
	      READ_2DA_ENTRY_FORMER rows row 0 kitlist_index
	      READ_2DA_ENTRY_FORMER rows row 3 kitlist_name
	      READ_2DA_ENTRY_FORMER rows row 5 kitlist_2da
	      READ_2DA_ENTRY_FORMER rows row 9 kitids_num
	      PATCH_IF (~%kitlist_2da%~ STRING_EQUAL_CASE ~%feat_kit_2da%~) BEGIN
	        SPRINT $feat_archer_list(~%kitlist_index%~)~%kitids_num%~
			GET_STRREF %kitlist_name% kit_name_strref
			SPRINT feat_select_name ~%kit_name_strref% %feat_select_string%~
			SET kit_seq_name = RESOLVE_STR_REF (~%feat_select_name%~) 
			SET kit_seq_tip = RESOLVE_STR_REF (~%feat_select_name%~) 
			SET kit_seq_index = %kitlist_index% 
			INNER_ACTION BEGIN
			  LAF CREATE_SEQUENCER_MENU 
			   INT_VAR 
				name = %kit_seq_name%
				tip = %kit_seq_tip%
				desc = RESOLVE_STR_REF (~blah~) 
				column = %col% 
				class = 2
			   STR_VAR 
				resref = EVAL ~d5ft%kit_seq_index%~
				icon = ~spcl919b~
				spelltable = ~d5ftskn~ 
				spelllist = ~d5flsta~
				title = EVAL ~%feat_title_string%~
				label = EVAL ~%feat_label_string%~
			  END
			END
		  END
		END
	  BUT_ONLY
	END
  END
 BUT_ONLY
 
 COPY_EXISTING ~d5flsta.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 1; row < rows; ++row) BEGIN
  	READ_2DA_ENTRY row 0 cols ~book_feat~
	INNER_ACTION BEGIN
	  COPY_EXISTING ~%book_feat%.spl~ ~override/%book_feat%L.spl~
		WRITE_SHORT 0x1c 4
		WRITE_LONG 0x34 1
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%book_feat%~ END
	  IF_EXISTS BUT_ONLY
	END
  END
 BUT_ONLY

 ACTION_PHP_EACH feat_nums_lets AS num => let BEGIN
  COPY ~might_and_guile/feats/d5feat1.spl~ ~override/d5feat%num%.spl~ 
	LPF DELETE_EFFECT INT_VAR match_opcode = 206 END
	LPF ALTER_EFFECT INT_VAR match_opcode = 177 STR_VAR match_resource = ~d5feat1~ resource = EVAL ~d5feat%num%~ END
  COPY ~might_and_guile/feats/d5feat1.eff~ ~override/d5feat%num%.eff~ 
	WRITE_EVALUATED_ASCII 0x30 ~d5feat%let%~ #8
  COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5feat%let%.spl~
	SAY NAME1 @20099
	SAY UNIDENTIFIED_DESC @20100
	WRITE_ASCII 0x3a ~d5_feat~ #8
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_feat~ END
	LPF ADD_SPELL_CFEFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~d5feat%let%~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5feat%num%~ END
	PHP_EACH feat_archer_list AS ind => ids BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~d5ft%ind%~ END
	END
 END

 ACTION_PHP_EACH feat_archer_list AS ind => ids BEGIN
  COPY_EXISTING ~d5ft%ind%.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~d5ft%ind%~ END
  IF_EXISTS BUT_ONLY
 END

END
//___________________________________________________________________________________

//FEATS ALREADY______________________________________________________________________
//
ACTION_IF FILE_EXISTS_IN_GAME ~d5_rfeat.d5~ THEN BEGIN
 COPY ~might_and_guile/feats/d5flstaf.2da~ ~override~
 COPY_EXISTING ~d5flstaf.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (col = 1; col < (cols - 1); ++col) BEGIN
	READ_2DA_ENTRY 0 (col - 1) (cols - 1) feat_kit_2da
	INNER_ACTION BEGIN
	  COPY_EXISTING ~kitlist.2da~ ~override~
		READ_2DA_ENTRIES_NOW rows 9
		FOR (row = 1; row < rows; ++row) BEGIN
	      READ_2DA_ENTRY_FORMER rows row 0 kitlist_index
	      READ_2DA_ENTRY_FORMER rows row 3 kitlist_name
	      READ_2DA_ENTRY_FORMER rows row 5 kitlist_2da
	      READ_2DA_ENTRY_FORMER rows row 9 kitids_num
	      PATCH_IF (~%kitlist_2da%~ STRING_EQUAL_CASE ~%feat_kit_2da%~) BEGIN
	        SPRINT $feat_archer_list(~%kitlist_index%~)~%kitids_num%~
			GET_STRREF %kitlist_name% kit_name_strref
			SPRINT feat_select_name ~%kit_name_strref% %feat_select_string%~
			SET kit_seq_name = RESOLVE_STR_REF (~%feat_select_name%~) 
			SET kit_seq_tip = RESOLVE_STR_REF (~%feat_select_name%~) 
			SET kit_seq_index = %kitlist_index% 
			INNER_ACTION BEGIN
			  LAF CREATE_SEQUENCER_MENU 
			   INT_VAR 
				name = %kit_seq_name%
				tip = %kit_seq_tip%
				desc = RESOLVE_STR_REF (~blah~) 
				column = %col% 
				class = 1
			   STR_VAR 
				resref = EVAL ~d5ft%kit_seq_index%~
				icon = ~spcl919b~
				spelltable = ~d5ftskn~ 
				spelllist = ~d5flstaf~
				title = EVAL ~%feat_title_string%~
				label = EVAL ~%feat_label_string%~
			  END
			END
		  END
		END
	  BUT_ONLY
	END
  END
 BUT_ONLY

 COPY_EXISTING ~d5flstaf.2da~ ~override~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 1; row < rows; ++row) BEGIN
  	READ_2DA_ENTRY row 0 cols ~book_feat~
	INNER_ACTION BEGIN
	  COPY_EXISTING ~%book_feat%.spl~ ~override/%book_feat%L.spl~
		WRITE_SHORT 0x1c 4
		WRITE_LONG 0x34 1
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 171 target = 1 timing = 9 STR_VAR resource = EVAL ~%book_feat%~ END
	  IF_EXISTS BUT_ONLY
	END
  END
 BUT_ONLY

 ACTION_PHP_EACH feat_nums_lets AS num => let BEGIN
  COPY_EXISTING ~d5feat%let%.spl~ ~override~
	PHP_EACH feat_archer_list AS ind => ids BEGIN
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %ids% parameter2 = %kit_is_row% timing = 1 STR_VAR resource = EVAL ~d5ft%ind%~ END
	END
  IF_EXISTS BUT_ONLY
 END

 ACTION_PHP_EACH feat_archer_list AS ind => ids BEGIN
  COPY_EXISTING ~d5ft%ind%.spl~ ~override~
	LPF DELETE_EFFECT INT_VAR match_opcode = 171 STR_VAR match_resource = EVAL ~d5ft%ind%~ END
  IF_EXISTS BUT_ONLY
 END

END
//___________________________________________________________________________________


//FINISH UP___________________________________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5featx.spl~) BEGIN
  COPY ~might_and_guile/misc/d5_base.spl~ ~override/d5featx.spl~
END
COPY ~might_and_guile/feats/d5flsta.2da~ ~might_and_guile/temp/d5flsta.2da~
  COUNT_2DA_COLS cols
  COUNT_2DA_ROWS cols rows
  FOR (row = 1; row < rows; ++row) BEGIN
  	READ_2DA_ENTRY row 0 cols spellbook_feat
	INNER_ACTION BEGIN
	  COPY_EXISTING ~d5featx.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%spellbook_feat%~ END
	  BUT_ONLY
	END
  END
BUT_ONLY
//___________________________________________________________________________________
