
//__________________________________________________________________________________
//__________________________________________________________________________________
//
//							ARCHER FEATS
//__________________________________________________________________________________
//__________________________________________________________________________________


//COPY MARKER FILE_________________________________________________________________
//
COPY ~might_and_guile/lib/markers/d5_archy.d5~ ~override~
//__________________________________________________________________________________

/*

should do: 
- crippling hit = -STR + slow (use ARSLO?)  
- fumble = 0 APR (use ARDIS?)
- trip = fall + slow (ARTRP)
- pin - 0 move (ARMOV)
...
- stun = stun (slinger) (ARSTN)
- blind = blind (sniper) (ARBLI)
- hammer = knockback (marksman) (ARHAM)

*/

//ARCHER ABILITIES___________________________________________________________________
//
COPY ~might_and_guile/fighter/d5_artrp.eff~ ~override~
COPY ~might_and_guile/fighter/d5_artrp.spl~ ~override~ 	//	called shot: trip
	SAY NAME1 @23113
	SAY UNIDENTIFIED_DESC @23114
	WRITE_ASCII 0x3a ~d5_artrp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_artrp~ END
COPY ~might_and_guile/fighter/d5_artrp.bam~ ~override~

COPY ~might_and_guile/fighter/d5_armv1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_armv2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_armov.spl~ ~override~	//	called shot: pin
	SAY NAME1 @23111
	SAY UNIDENTIFIED_DESC @23112
	WRITE_ASCII 0x3a ~d5_armov~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_armov~ END
COPY ~might_and_guile/fighter/d5_armov.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arsl1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arsl2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arsl3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arslo.spl~ ~override~	//	called shot: cripple
	SAY NAME1 @23119
	SAY UNIDENTIFIED_DESC @23120
	WRITE_ASCII 0x3a ~d5_arslo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslo~ END
COPY ~might_and_guile/fighter/d5_arslo.bam~ ~override~

COPY ~might_and_guile/fighter/d5_ards1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ards2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ards3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ardis.spl~ ~override~	//	called shot: disarm
	SAY NAME1 @23115
	SAY UNIDENTIFIED_DESC @23116
	WRITE_ASCII 0x3a ~d5_ardis~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_ardis~ END
COPY ~might_and_guile/fighter/d5_ardis.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arbli.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arbli.spl~ ~override~	//	called shot: blind
	SAY NAME1 @23121
	SAY UNIDENTIFIED_DESC @23122
	WRITE_ASCII 0x3a ~d5_arbli~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arbli~ END
COPY ~might_and_guile/fighter/d5_arbli.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arhm1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arhm2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arhm3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arham.spl~ ~override~	//	called shot: hammer
	SAY NAME1 @23117
	SAY UNIDENTIFIED_DESC @23118
	WRITE_ASCII 0x3a ~d5_arham~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arham~ END
COPY ~might_and_guile/fighter/d5_arham.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arstn.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arstn.spl~ ~override~	//	called shot: stun
	SAY NAME1 @23123
	SAY UNIDENTIFIED_DESC @23124
	WRITE_ASCII 0x3a ~d5_arstn~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arstn~ END
COPY ~might_and_guile/fighter/d5_arstn.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arnt1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arnt2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arent.spl~ ~override~	//	called shot: entangle
	SAY NAME1 @23131
	SAY UNIDENTIFIED_DESC @23132
	WRITE_ASCII 0x3a ~d5_arent~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arent~ END
COPY ~might_and_guile/fighter/d5_arent.bam~ ~override~

COPY ~might_and_guile/fighter/d5_arslp.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arslp.spl~ ~override~	//	called shot: sleep
	SAY NAME1 @23133
	SAY UNIDENTIFIED_DESC @23134
	WRITE_ASCII 0x3a ~d5_arslp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslp~ END
COPY ~might_and_guile/fighter/d5_arslp.bam~ ~override~

COPY ~might_and_guile/fighter/d5_ffire.vvc~ ~override~
COPY ~might_and_guile/fighter/d5_arff1.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff2.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff3.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff4.eff~ ~override~
COPY ~might_and_guile/fighter/d5_arff5.eff~ ~override~
COPY ~might_and_guile/fighter/d5_ffire.vvc~ ~override~
COPY ~might_and_guile/fighter/d5_arffi.spl~ ~override~	//	called shot: faerie fire
	SAY NAME1 @23135
	SAY UNIDENTIFIED_DESC @23136
	WRITE_ASCII 0x3a ~d5_arffi~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arffi~ END
COPY ~might_and_guile/fighter/d5_arffi.bam~ ~override~


COPY ~might_and_guile/fighter/d5_csa.spl~ ~override~		//	give trip
	SAY NAME1 @23113
	SAY UNIDENTIFIED_DESC @23114
	WRITE_ASCII 0x3a ~d5_artrp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_artrp~ END
COPY ~might_and_guile/fighter/d5_csb.spl~ ~override~		//	give pin
	SAY NAME1 @23111
	SAY UNIDENTIFIED_DESC @23112
	WRITE_ASCII 0x3a ~d5_armov~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_armov~ END
COPY ~might_and_guile/fighter/d5_csc.spl~ ~override~		//	give cripple
	SAY NAME1 @23119
	SAY UNIDENTIFIED_DESC @23120
	WRITE_ASCII 0x3a ~d5_arslo~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslo~ END
COPY ~might_and_guile/fighter/d5_csd.spl~ ~override~		//	give disarm
	SAY NAME1 @23115
	SAY UNIDENTIFIED_DESC @23116
	WRITE_ASCII 0x3a ~d5_ardis~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_ardis~ END
COPY ~might_and_guile/fighter/d5_cse.spl~ ~override~		//	give blind
	SAY NAME1 @23121
	SAY UNIDENTIFIED_DESC @23122
	WRITE_ASCII 0x3a ~d5_arbli~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arbli~ END
COPY ~might_and_guile/fighter/d5_csf.spl~ ~override~		//	give hammer
	SAY NAME1 @23117
	SAY UNIDENTIFIED_DESC @23118
	WRITE_ASCII 0x3a ~d5_arham~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arham~ END
COPY ~might_and_guile/fighter/d5_csg.spl~ ~override~		//	give stun
	SAY NAME1 @23123
	SAY UNIDENTIFIED_DESC @23124
	WRITE_ASCII 0x3a ~d5_arstn~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arstn~ END
COPY ~might_and_guile/fighter/d5_csh.spl~ ~override~		//	give entangle
	SAY NAME1 @23131
	SAY UNIDENTIFIED_DESC @23132
	WRITE_ASCII 0x3a ~d5_arent~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arent~ END
COPY ~might_and_guile/fighter/d5_csi.spl~ ~override~		//	give sleep
	SAY NAME1 @23133
	SAY UNIDENTIFIED_DESC @23134
	WRITE_ASCII 0x3a ~d5_arslp~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arslp~ END
COPY ~might_and_guile/fighter/d5_csj.spl~ ~override~		//	give faerie fire
	SAY NAME1 @23135
	SAY UNIDENTIFIED_DESC @23136
	WRITE_ASCII 0x3a ~d5_arffi~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_arffi~ END

/*
COPY ~might_and_guile/fighter/d5_rafx.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/fighter/d5_rafy.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/fighter/d5_rafz.spl~ ~override~
	SAY NAME1 @7
COPY ~might_and_guile/fighter/d5_raf1.spl~ ~override~
	SAY NAME1 @3210
	SAY UNIDENTIFIED_DESC @3210
COPY ~might_and_guile/fighter/d5_rafa.spl~ ~override~
	SAY NAME1 @7

COPY ~might_and_guile/fighter/d5_raf.bam~ ~override~
ACTION_FOR_EACH shotclab IN ~d5_rafa~ ~d5_rafb~ ~d5_rafc~ ~d5_rafd~ ~d5_rafe~ ~d5_raff~ ~d5_rafg~ ~d5_refh~ ~d5_refa~ ~d5_refb~ ~d5_refc~ ~d5_refd~ ~d5_refe~ ~d5_reff~ ~d5_refg~ ~d5_refh~ BEGIN
  COPY ~might_and_guile/fighter/%shotclab%.spl~ ~override~
	SAY NAME1 @7
	SAY UNIDENTIFIED_DESC @7
	WRITE_ASCII 0x3a ~d5_raf~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_raf~ END
END
ACTION_FOR_EACH shoteff IN ~d5_raf1~ ~d5_raf2~ ~d5_raf3~ ~d5_raf4~ ~d5_raf5~ ~d5_raf6~ ~d5_raf7~ ~d5_ref1~ ~d5_ref2~ ~d5_ref3~ ~d5_ref4~ ~d5_ref5~ ~d5_ref6~ ~d5_ref7~ ~d5_ref8~ BEGIN
  COPY ~might_and_guile/fighter/%shoteff%.eff~ ~override~
END
ACTION_FOR_EACH shotspell IN ~d5_raf1~ ~d5_raf2~ ~d5_raf3~ ~d5_raf4~ ~d5_raf5~ ~d5_raf6~ ~d5_raf7~ ~d5_ref1~ ~d5_ref2~ ~d5_ref3~ ~d5_ref4~ ~d5_ref5~ ~d5_ref6~ ~d5_ref7~ ~d5_ref8~ BEGIN
  COPY ~might_and_guile/fighter/%shotspell%.spl~ ~override~
	SAY NAME1 @3210
	SAY UNIDENTIFIED_DESC @3210
	WRITE_ASCII 0x3a ~d5_raf~
	LPF ALTER_SPELL_HEADER STR_VAR icon = ~d5_raf~ END
END
*/
//___________________________________________________________________________________

