
// v3

DEFINE_ACTION_FUNCTION semi_spontaneous_arcane BEGIN

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_semi_spont.d5~) BEGIN

//semi spont spellstate_______________________________________________________________
//
ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_ARCANE~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_ARCANE~) BEGIN
		SET semi_spont_arcane = %state_ind%
	  END
	END
  BUT_ONLY
END
/*
ACTION_IF !(FILE FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_ARCANE~)) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_ARCANE~ RET new_state_ind END
  OUTER_SET semi_spont_arcane = %new_state_ind%
END
*/
ACTION_IF !(VARIABLE_IS_SET %semi_spont_arcane%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_ARCANE~ RET new_state_ind END
  OUTER_SET semi_spont_arcane = %new_state_ind%
END

//prepared spells spellstate__________________________________________________________
//
ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SPL_PREP~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SPL_PREP~) BEGIN
		SET prepared_spells_state = %state_ind%
	  END
	END
  BUT_ONLY
END
/*
ACTION_IF !(FILE FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SPL_PREP~)) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SPL_PREP~ RET new_state_ind END
  OUTER_SET prepared_spells_state = %new_state_ind%
END
*/
ACTION_IF !(VARIABLE_IS_SET %prepared_spells_state%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SPL_PREP~ RET new_state_ind END
  OUTER_SET prepared_spells_state = %new_state_ind%
END


//add spell slot stat checks to SPLPROT______________________________________________
//
APPEND ~splprot.2da~ ~D5_SLOTS_1_7%TAB%108%TAB%-1%TAB%7~ UNLESS ~D5_SLOTS_1_7~
APPEND ~splprot.2da~ ~D5_SLOTS=1_7%TAB%108%TAB%-1%TAB%8~ UNLESS ~D5_SLOTS=1_7~
APPEND ~splprot.2da~ ~D5_SLOTS_8_9%TAB%109%TAB%-1%TAB%7~ UNLESS ~D5_SLOTS_8_9~
APPEND ~splprot.2da~ ~D5_SLOTS=8_9%TAB%109%TAB%-1%TAB%8~ UNLESS ~D5_SLOTS=8_9~
APPEND ~splprot.2da~ ~D5_FATIGUE_0%TAB%30%TAB%0%TAB%1~ UNLESS ~D5_FATIGUE_0~
APPEND ~splprot.2da~ ~D5_PREP_SPLZ%TAB%0x112%TAB%%prepared_spells_state%%TAB%1~ UNLESS ~D5_PREP_SPLZ~
APPEND ~splprot.2da~ ~D5_NOT_PREP%TAB%0x112%TAB%%prepared_spells_state%%TAB%5~ UNLESS ~D5_NOT_PREP~

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS_1_7~) BEGIN
	  SET fake_sorc_slots_1_7 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS=1_7~) BEGIN
	  SET fake_slots_equal_1_7 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS_8_9~) BEGIN
	  SET fake_sorc_slots_8_9 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS=8_9~) BEGIN
	  SET fake_slots_equal_8_9 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_0~) BEGIN
	  SET fatigue_zero = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_PREP_SPLZ~) BEGIN
	  SET prep_spells_row = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_NOT_PREP~) BEGIN
	  SET not_prep_row = %row%
	END
  END
BUT_ONLY


//remove all mage spell slots_________________________________________________________
//
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d517slt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d589slt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 384 timing = 9 END
BUT_ONLY

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d500slt.spl~
  PATCH_IF (MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~62~) BEGIN	//	level 1 cantrips
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 126 timing = 9 END
  END
  PATCH_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~62~) BEGIN	//	level 1 cantrips
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 target = 1 parameter1 = (0 - 1) parameter2 = 127 timing = 9 END
  END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d502slt.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 2 target = 1 timing = 9 END


//create advance copies of some spells________________________________________________
//
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b206.spl~

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d50aspl.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI908~ END
  PATCH_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~16~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = ~SPWI110~ END
  END
  PATCH_IF !(MOD_IS_INSTALLED ~TomeAndBlood.tp2~ ~55~) BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI420~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI710~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI809~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~SPWI617~ END
  END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot1a.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot1b.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot1c.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot1d.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot2a.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot2b.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot2c.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot2d.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot3a.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot3b.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot3c.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot3d.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot4a.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot4b.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot4c.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot4d.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot5a.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot5b.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot5c.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot5d.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot6a.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot6b.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot6c.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot6d.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot7a.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot7b.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot7c.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot7d.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot8a.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot8b.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot8c.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot8d.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot9a.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot9b.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot9c.spl~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blot9d.spl~

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5bsplz.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 4) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot1a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 4) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot1b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 4) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot1c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 4) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot1d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 8) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot2a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 8) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot2b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 8) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot2c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 8) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot2d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 12) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot3a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 12) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot3b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 12) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot3c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 12) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot3d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 16) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot4a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 16) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot4b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 16) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot4c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 16) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot4d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 20) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot5a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 20) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot5b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 20) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot5c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 20) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot5d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot6a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot6b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot6c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot6d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 28) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot7a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 28) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot7b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 28) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot7c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 28) parameter2 = %fake_sorc_slots_1_7% timing = 1 STR_VAR resource = ~d5blot7d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 24) parameter2 = %fake_sorc_slots_8_9% timing = 1 STR_VAR resource = ~d5blot8a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 24) parameter2 = %fake_sorc_slots_8_9% timing = 1 STR_VAR resource = ~d5blot8b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 24) parameter2 = %fake_sorc_slots_8_9% timing = 1 STR_VAR resource = ~d5blot8c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 24) parameter2 = %fake_sorc_slots_8_9% timing = 1 STR_VAR resource = ~d5blot8d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (1 << 28) parameter2 = %fake_sorc_slots_8_9% timing = 1 STR_VAR resource = ~d5blot9a~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (2 << 28) parameter2 = %fake_sorc_slots_8_9% timing = 1 STR_VAR resource = ~d5blot9b~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (4 << 28) parameter2 = %fake_sorc_slots_8_9% timing = 1 STR_VAR resource = ~d5blot9c~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (8 << 28) parameter2 = %fake_sorc_slots_8_9% timing = 1 STR_VAR resource = ~d5blot9d~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 0 duration = 1 STR_VAR resource = ~d5bsplz~ END

//assign stats for spell slots to each spell level____________________________________
//
// level 1 = 	108 << 4
// level 2 = 	108 << 8
// level 3 = 	108 << 12
// level 4 = 	108 << 16
// level 5 = 	108 << 20
// level 6 =	108 << 24
// level 7 = 	108 << 28
// level 8 =    109 << 24
// level 9 =    109 << 28
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src1a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src1%let%.spl~
	  SAY NAME1 @21991
	  SAY UNIDENTIFIED_DESC @21991
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 4) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src1%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src2a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src2%let%.spl~
	  SAY NAME1 @21992
	  SAY UNIDENTIFIED_DESC @21992
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src2%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src3a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src3%let%.spl~
	  SAY NAME1 @21993
	  SAY UNIDENTIFIED_DESC @21993
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src3%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src4a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src4%let%.spl~
	  SAY NAME1 @21994
	  SAY UNIDENTIFIED_DESC @21994
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src4%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src5a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src5%let%.spl~
	  SAY NAME1 @21995
	  SAY UNIDENTIFIED_DESC @21995
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src5%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src6a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src6%let%.spl~
	  SAY NAME1 @21996
	  SAY UNIDENTIFIED_DESC @21996
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src6%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src7a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src7%let%.spl~
	  SAY NAME1 @21997
	  SAY UNIDENTIFIED_DESC @21997
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (108 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src7%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src8a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src8%let%.spl~
	  SAY NAME1 @21989
	  SAY UNIDENTIFIED_DESC @21989
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (109 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src8%let%~ END
  END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src9a.spl~ BEGIN
  ACTION_FOR_EACH let IN ~a~ ~b~ ~c~ ~d~ ~e~ ~f~ ~g~ ~h~ ~i~ ~j~ ~k~ ~l~ ~m~ ~n~ ~o~ ~p~ ~q~ ~r~ ~s~ ~t~ BEGIN
	COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src9%let%.spl~
	  SAY NAME1 @21990
	  SAY UNIDENTIFIED_DESC @21990
	  LPF ALTER_SPELL_HEADER INT_VAR target = 5 STR_VAR icon = ~spcl919b~ END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (109 + (0x10000 * 1)) timing = 9 END
	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~d5src9%let%~ END
  END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-1.spl~ BEGIN
 COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src-1.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 4) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-2.spl~ BEGIN
 COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src-2.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-3.spl~ BEGIN
 COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src-3.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 12) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-4.spl~ BEGIN
 COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src-4.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 16) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-5.spl~ BEGIN
 COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src-5.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 20) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-6.spl~ BEGIN
 COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src-6.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-7.spl~ BEGIN
 COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src-7.spl~
   LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 28) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-8.spl~ BEGIN
 COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src-8.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 24) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5src-9.spl~ BEGIN
 COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5src-9.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 28) parameter2 = (109 + (0x10000 * 1)) timing = 1 END
END


// generate master 2da list of learnable spells_______________________________________
//
OUTER_SET scroll_spell_ind = 0
OUTER_SPRINT $scroll_spells(~spell~) ~0~ // ~%scroll_spell_ind%~
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
  READ_BYTE     0x2f current ELSE 0
  READ_BYTE     0x2b current2 ELSE 0
  READ_LONG 0x64 headoffset  ELSE 0
  READ_SHORT 0x68 headcount  ELSE 0
  READ_LONG 0x6a effectsoffset  ELSE 0
  haslearn = 0
  hascast = 0
//  PATCH_IF (headcount = 2) BEGIN
    FOR (headcyc = 0; headcyc < headcount ; headcyc = headcyc + 1) BEGIN
      thishead = 0
      READ_SHORT (headoffset + (headcyc * 0x38) + 0x1e) effcount  ELSE 0
      READ_SHORT (headoffset + (headcyc * 0x38) + 0x20) effectsindex  ELSE 0
      FOR (effcyc = 0; effcyc < effcount; effcyc = effcyc + 1) BEGIN
        READ_SHORT (effectsoffset + (effectsindex + effcyc)* 0x30) opcode ELSE 0
        PATCH_IF (opcode = 0x93) AND (thishead = 0) BEGIN
          READ_ASCII (effectsoffset + 0x14 + (effectsindex + effcyc)* 0x30) resref_learn  ELSE 0
          INNER_PATCH_FILE ~%resref_learn%.spl~ BEGIN
            READ_SHORT 0x1c type
          END
          PATCH_IF (type = 1) BEGIN // arcane spell scroll
            thishead = 1
            haslearn = 1
          END
        END 
        PATCH_IF ((opcode = 0x92) OR (opcode = 0x94)) AND (thishead = 0) BEGIN
          READ_ASCII (effectsoffset + 0x14 + (effectsindex + effcyc)* 0x30) resref_cast  ELSE 0
          INNER_PATCH_FILE ~%resref_cast%.spl~ BEGIN
            READ_SHORT 0x1c type
          END
          PATCH_IF (type = 1) BEGIN // arcane spell scroll
            thishead = 1
            hascast = 1
          END
        END 
      END 
    END 
//  END // end has 2 headers
  PATCH_IF (haslearn = 1) AND (hascast = 1) AND (~%resref_cast%~ STRING_EQUAL_CASE ~%resref_learn%~) BEGIN
	SPRINT $scroll_spells(~%resref_learn%~) ~1~ // ~%scroll_spell_ind%~
	SET ++scroll_spell_ind
  END
BUT_ONLY

ACTION_FOR_EACH hla IN
	~spwi920~
	~spwi921~
	~spwi922~
	~spwi923~
	~spwi924~
	~spwi925~
	~TG#DRGB~
	~TG#CLEA~
	~TG#BONU~
	~TG#DTHF~
	~TG#AEGI~
	~TG#FORS~
	~LI#SCRB~		BEGIN
  COPY_EXISTING ~%hla%.spl~ ~override~
	READ_SHORT 0x1c spell_type
	PATCH_IF (spell_type = 1) BEGIN
	  SPRINT $scroll_spells(~%hla%~) ~1~
	END
  IF_EXISTS BUT_ONLY
END


// generate sclons.2da________________________________________________________________
//
<<<<<<<< d5/d5sclons.2da
2DA V1.0 
SPLRES
		206		LEARN	EFF		INNATE	DISPLAY
>>>>>>>> 

COPY ~d5/d5sclons.2da~ ~override/d5sclons.2da~ 
//COPY ~d5/d5sclons.2da~ ~override/d5bclons.2da~ 

ACTION_PHP_EACH scroll_spells AS arcane_spell => ind BEGIN
  ACTION_IF (%ind% > 0) BEGIN
	ACTION_IF FILE_EXISTS_IN_GAME ~%arcane_spell%.spl~ BEGIN
	  COPY_EXISTING ~%arcane_spell%.spl~ ~override~
		PATCH_IF (~%arcane_spell%~ STRING_MATCHES_REGEXP ~[Ss][Pp][Ww][Ii][1-9][0-9][0-9]~ = 0) BEGIN
		  INNER_PATCH_SAVE 206_spell ~%arcane_spell%~ BEGIN
			REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5b6~
		  END
		  INNER_PATCH_SAVE learn_spell ~%arcane_spell%~ BEGIN
			REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5bx~
		  END
		  INNER_PATCH_SAVE spell_eff ~%arcane_spell%~ BEGIN
			REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~D5BV~
		  END
		  INNER_PATCH_SAVE innate_spell ~%arcane_spell%~ BEGIN
			REPLACE_TEXTUALLY ~[Ss][Pp][Ww][Ii]~ ~d5b4~
		  END
		  TEXT_SPRINT real_spell ~%arcane_spell%~
		  PATCH_IF NOT (FILE_CONTAINS_EVALUATED (~d5sclons.2da~ ~%arcane_spell%~)) BEGIN
			INNER_ACTION BEGIN
			  APPEND ~d5sclons.2da~ ~%arcane_spell%	%206_spell%	%learn_spell%	%spell_eff%	%innate_spell%	%real_spell% ~
			END
		  END
		END
	  BUT_ONLY
	END
  END
END


// 'prepare spells' spell_____________________________________________________________
//
OUTER_SET prep_message = RESOLVE_STR_REF(@21984)
COPY ~%MOD_FOLDER%/data/semi_spont/d5swtch.bam~ ~override~
COPY ~%MOD_FOLDER%/data/semi_spont/d5prepb.bam~ ~override/d5prepb.bam~
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5prepb.spl~
  SAY NAME1 @21982 											// ~daily spell preparation~
  SAY UNIDENTIFIED_DESC @21983								// ~daily spell preparation~
  WRITE_ASCII 0x3a ~d5swtch~ #8
  LPF ALTER_SPELL_HEADER INT_VAR target = 7 STR_VAR icon = ~d5swtch~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d517slt~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d589slt~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5b206~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = ~d5prepb1~ END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 139 target = 1 parameter1 = %prep_message% timing = 1 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END

COPY_EXISTING ~d5prepb.spl~ ~override/d5perpb.spl~
  LPF DELETE_EFFECT INT_VAR match_opcode = 139 END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5prepb1.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 2 timing = 9 END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 101 target = 1 parameter2 = 145 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 328 target = 1 special = 1 parameter2 = %prepared_spells_state% timing = 9 END


//daily spell slot refresh____________________________________________________________
//
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blotz.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = ~d5blots~ END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5blots.eff~ BEGIN
  CREATE EFF ~d5blots~
	WRITE_LONG 0x10 232
	WRITE_LONG 0x14 1
	WRITE_LONG 0x1c 0
	WRITE_LONG 0x20 20
	WRITE_LONG 0x24 9
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5blots~ #8
	WRITE_LONG 0x48 102
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5blots.spl~ BEGIN
  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blots.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %fatigue_zero% timing = 1 STR_VAR resource = ~d5blotf~ END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5blotf.spl~ BEGIN
  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blotf.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %prep_spells_row% timing = 1 STR_VAR resource = ~d5blotr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = 0 parameter2 = %not_prep_row% timing = 1 STR_VAR resource = ~d5brfrsh~ END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5blotr.spl~ BEGIN
  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5blotr.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter1 = 0 parameter2 = 2 timing = 0 duration = 12 STR_VAR resource = ~d5blotr~ END
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5blotr.eff~ BEGIN
  CREATE EFF ~d5blotr~
	WRITE_LONG 0x10 67
	WRITE_LONG 0x14 1
	WRITE_LONG 0x28 12
	WRITE_SHORT 0x2c 100
	WRITE_ASCII 0x30 ~d5blotr~ #8
	WRITE_ASCII 0x70 ~shskull~ #8
END

ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5blotr.cre~ BEGIN
  COPY ~%MOD_FOLDER%/data/semi_spont/d5blotr.cre~ ~override~
END


// script to check memorized spells________________________________________________
//
<<<<<<<<d5/inline_script.baf
>>>>>>>>

COPY ~d5/inline_script.baf~ ~weidu_external/d5_bard_cast/d5blotr.baf~

COPY_EXISTING ~d5sclons.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_sclons~ cols
  FOR (row = 0; row < r2en_sclons; ++row) BEGIN
	READ_2DA_ENTRY_FORMER ~r2en_sclons~ row 0 original_spell
	READ_2DA_ENTRY_FORMER ~r2en_sclons~ row 2 learn_spell
	INNER_ACTION BEGIN
	  APPEND_OUTER ~weidu_external/d5_bard_cast/d5blotr.baf~ ~
IF
    TriggerOverride(LastSummonerOf(Myself),HaveSpellRES("%original_spell%"))
THEN
    RESPONSE #100
    ActionOverride(LastSummonerOf(Myself),ApplySpellRes("%learn_spell%",Myself))
    Continue()
END
~
	END
  END
BUT_ONLY

APPEND_OUTER ~weidu_external/d5_bard_cast/d5blotr.baf~ ~
IF
	True()
THEN
	RESPONSE #100
	ActionOverride(LastSummonerOf(Myself),ApplySpellRes("D5PREPD",Myself))
	DestroySelf() 
END
~

COMPILE ~weidu_external/d5_bard_cast/d5blotr.baf~


// spell to simply refresh spell slots________________________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5brfrsh.spl~ BEGIN
  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5brfrsh.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-4~ END
  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
END


// spell to set prepped spells and refresh slots______________________________________
//
ACTION_IF NOT FILE_EXISTS_IN_GAME ~d5prepd.spl~ BEGIN
  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5prepd.spl~
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 93 target = 1 parameter1 = 1 parameter2 = 1 timing = 1 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d517slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d589slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d589slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d589slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d589slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d589slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d589slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d589slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d589slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d589slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = ~d589slt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5prepb1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-2~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-3~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-4~ END
  	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-5~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-6~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-7~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-8~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5src-9~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 279 target = 1 parameter2 = 2 timing = 9 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
END


//clone spells________________________________________________________________________
//
COPY_EXISTING ~d5sclons.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW ~r2en_sclons~ cols
  FOR (row = 0; row < r2en_sclons; ++row) BEGIN
	READ_2DA_ENTRY_FORMER ~r2en_sclons~ row 0 real_spell
	READ_2DA_ENTRY_FORMER ~r2en_sclons~ row 1 206_spell
	READ_2DA_ENTRY_FORMER ~r2en_sclons~ row 2 learn_spell
	READ_2DA_ENTRY_FORMER ~r2en_sclons~ row 3 spell_eff
	READ_2DA_ENTRY_FORMER ~r2en_sclons~ row 4 innate_spell
	READ_2DA_ENTRY_FORMER ~r2en_sclons~ row 5 book_spell
	INNER_ACTION BEGIN
	  COPY_EXISTING ~%real_spell%.spl~ ~override~
		READ_LONG 0x34 spell_level
	  BUT_ONLY
// make innates that cast the original
//	  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%innate_spell%.spl~ BEGIN
		COPY_EXISTING ~%real_spell%.spl~ ~override/%innate_spell%.spl~
		  WRITE_SHORT 0x1c 4
		  LPF ALTER_SPELL_HEADER INT_VAR location = 2 END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5bwiz~ END
// 			don't need that ^ if casting original spell
		  READ_LONG 0x64 abil_offset
		  READ_SHORT 0x68 abil_number
		  READ_BYTE (%abil_offset% + 0x0c) abil_target					
		  READ_SHORT (%abil_offset% + 0x0e) abil_range
		  READ_LONG 0x6a eff_offset
		  WHILE (%abil_number% > 0) BEGIN
			SET abil_number = (%abil_number% - 1)
			WRITE_SHORT (%abil_offset% + 0x26 + (0x28 * %abil_number%)) 1
		  END
		  READ_BYTE (%eff_offset% + 0x02) eff_target
		  LPF DELETE_EFFECT INT_VAR match_probability2 = 0 END
		  PATCH_IF (%abil_target% = 4) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 148 target = 1 power = 0 parameter1 = 0 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~%real_spell%~ END
			PATCH_IF (%abil_range% < 35) BEGIN
			  PATCH_IF (%abil_range% > 4) BEGIN
				LPF ALTER_SPELL_HEADER INT_VAR range = (%abil_range% - 3) END
			  END
			  PATCH_IF (%abil_range% < 5) BEGIN
			 	LPF ALTER_SPELL_HEADER INT_VAR target = 5 END	// might need to carve out exceptions, e.g. burning hands
			  END
			END
		  END
		  ELSE BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 2 power = 0 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%real_spell%~ END
		  END
// exempt lvl 1 if lv1 1 cantrips
		  PATCH_IF MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~ BEGIN
//		   PATCH_IF NOT (%spell_level%) = 1 BEGIN
		   PATCH_IF (%spell_level% > 1) BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5src-%spell_level%~ END
		   END
		  END
		  PATCH_IF NOT MOD_IS_INSTALLED ~tomeandblood.tp2~ ~62~ BEGIN
			LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5src-%spell_level%~ END
		  END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
//	  END
// make .EFFs adding the innate spell
//	  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%spell_eff%.eff~ BEGIN
	  OUTER_SET string_length = (STRING_LENGTH ~%spell_eff%~)
	  ACTION_IF (%string_length% < 8) BEGIN
		CREATE EFF ~%spell_eff%~
		 WRITE_LONG 0x10 171
		 WRITE_LONG 0x14 1
		 WRITE_LONG 0x24 0
		 WRITE_LONG 0x28 1
		 WRITE_SHORT 0x2c 100
		 WRITE_EVALUATED_ASCII 0x30 ~%innate_spell%~ #8
		 WRITE_LONG 0x90 1
		 WRITE_EVALUATED_ASCII 0x94 ~%spell_eff%~ #8
	  END
//	  END
// make 206 spells preventing the .EFF
//	  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%206_spell%.spl~ BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/%206_spell%.spl~
		 WRITE_SHORT 0x1c 4
	  	 LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
	  	 LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
//	  END
// add 206 spells to CLAB spell
	  COPY_EXISTING ~d5b206.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
// make learn spells canceling the 206
//	  ACTION_IF NOT FILE_EXISTS_IN_GAME ~%learn_spell%.spl~ BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/%learn_spell%.spl~
	  	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = EVAL ~%206_spell%~ END
//	  END
// add 172 to d5bsplz
	  COPY_EXISTING ~d5bsplz.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
// add 172 to d5prepb - edit: maybe don't need to, because already in bsplz and prepb casts bsplz
//	  COPY_EXISTING ~d5prepb.spl~ ~override~
//		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 172 target = 1 timing = 9 STR_VAR resource = EVAL ~%innate_spell%~ END
// generate slot#x spells
//	  ACTION_IF (spell_level < 8) BEGIN
	  ACTION_IF FILE_EXISTS_IN_GAME ~d5blot%spell_level%a.spl~ BEGIN
		COPY_EXISTING ~d5blot%spell_level%a.spl~ ~override~
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		COPY_EXISTING ~d5blot%spell_level%b.spl~ ~override~
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		COPY_EXISTING ~d5blot%spell_level%c.spl~ ~override~
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		COPY_EXISTING ~d5blot%spell_level%d.spl~ ~override~
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 177 target = 1 parameter2 = 2 timing = 9 STR_VAR resource = EVAL ~%spell_eff%~ END
	  END
	END
  END
BUT_ONLY


//disable quickspell buttons__________________________________________________________
//
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5brdnq.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 3 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 4 timing = 9 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 144 target = 1 parameter2 = 5 timing = 9 END

COPY ~%MOD_FOLDER%/lib/d5_marker.d5~ ~override/d5_semi_spont.d5~

END

// ***** ^^ the above only needs to be done once ^^___________________________________

END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_MACRO semi_int_slots BEGIN

ACTION_DEFINE_ASSOCIATIVE_ARRAY int_nums_lets BEGIN
	13	=> 1a
	14	=> 1b
	15	=> 2a
	16	=> 2b
	17	=> 3a
	18	=> 3b
	19	=> 4a
	20	=> 4b
	21	=> 5a
	22	=> 5b
	23	=> 6a
	24	=> 6b
	25	=> 7a
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_semi_int.d5~) BEGIN

// stat-based bonus spells____________________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5nabsw.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5nabsw.spl~
	LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5absp1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5abspw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5abspw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intws~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intww~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwy~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrso~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrss~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrst~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsy~ END
END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intbz.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 127 target = 1 timing = 9 END

//OUTER_SET string = RESOLVE_STR_REF(~something is happening...~)

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb1a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 4) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 139 target = 1 parameter1 = %string% timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb1b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 4) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb2a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb2b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb3a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb3b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb4a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb4b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb5a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb5b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb6a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb6b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5intb7a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (108 + (0x10000 * 1)) timing = 1 END

COPY_EXISTING ~d5blotf.spl~ ~override~
  PHP_EACH int_nums_lets AS int => slot BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %int% parameter2 = 128 timing = 1 STR_VAR resource = EVAL ~d5intb%slot%~ END
  END
  PHP_EACH int_nums_lets AS int => slot BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = EVAL ~d5intb%slot%~ END
  END
IF_EXISTS BUT_ONLY


COPY ~%MOD_FOLDER%/lib/d5_marker.d5~ ~override/d5_semi_int.d5~

END

// ***** ^^ the above only needs to be done once ^^___________________________________

END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_MACRO semi_cha_slots BEGIN

/*
APPEND ~splprot.2da~ ~D5_CHR_SLOTS%TAB%42%TAB%-1%TAB%1~ UNLESS ~D5_CHR_SLOTS~

COPY_EXISTING ~splprot.2da~ ~override~
	COUNT_2DA_COLS cols 
	READ_2DA_ENTRIES_NOW rows cols   
	FOR (row = 1; row < rows; ++row) BEGIN 
	  READ_2DA_ENTRY_FORMER rows row 0 ~stat~ 
	  PATCH_IF ~%stat%~ STRING_EQUAL_CASE ~D5_CHR_SLOTS~ BEGIN
	    SET chr_slots = %row%
	  END
	END
BUT_ONLY
*/

ACTION_DEFINE_ASSOCIATIVE_ARRAY cha_nums_lets BEGIN
	13	=> 1a
	14	=> 1b
	15	=> 2a
	16	=> 2c
	17	=> 2b
	18	=> 3a
	19	=> 3c
	20	=> 3b
	21	=> 4a
	22	=> 4c
	23	=> 4b
	24	=> 5a
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_semi_cha.d5~) BEGIN

// stat-based bonus spells____________________________________________________________
//
ACTION_IF !(FILE_EXISTS_IN_GAME ~d5nabsw.spl~) BEGIN
  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5nabsw.spl~
	LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5absp1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5absp1~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5abspw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5abspw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwo~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intws~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwt~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intww~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5intwy~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsl~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsm~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsn~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrso~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsp~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsq~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsr~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrss~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrst~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsu~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsv~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsw~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsx~ END
	LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 9 STR_VAR resource = ~d5chrsy~ END
END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chasz.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 42 parameter1 = (0 - 1) parameter2 = 31 target = 1 timing = 9 END

//OUTER_SET string = RESOLVE_STR_REF(~something is happening...~)

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas1a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 4) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 139 target = 1 parameter1 = %string% timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas1b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 4) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas2a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas2c.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 target = 1 parameter1 = 1 parameter2 = 0 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas2b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas3a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas3c.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 target = 1 parameter1 = 2 parameter2 = 0 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas3b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas4a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas4c.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 target = 1 parameter1 = 3 parameter2 = 0 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas4b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5chas5a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 1 END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham1a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 1 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham1b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 2 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham2a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 3 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham2c.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 target = 1 parameter1 = 1 parameter2 = 0 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham2b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 4 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham3a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 5 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham3c.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 target = 1 parameter1 = 2 parameter2 = 0 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham3b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 6 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham4a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 7 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham4c.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 191 target = 1 parameter1 = 3 parameter2 = 0 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham4b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 8 timing = 0 duration = 126144000 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5cham5a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 95 target = 1 parameter1 = 9 timing = 0 duration = 126144000 END

COPY ~%MOD_FOLDER%/lib/d5_marker.d5~ ~override/d5_semi_cha.d5~

END

// ***** ^^ the above only needs to be done once ^^___________________________________

END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


DEFINE_ACTION_MACRO semi_wis_slots BEGIN

ACTION_DEFINE_ASSOCIATIVE_ARRAY wis_nums_lets BEGIN
	13	=> 1a
	14	=> 1b
	15	=> 2a
	16	=> 2b
	17	=> 3a
	18	=> 3b
	19	=> 4a
	20	=> 4b
	21	=> 5a
	22	=> 5b
	23	=> 6a
	24	=> 6b
	25	=> 7a
END

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_semi_wis.d5~) BEGIN

// stat-based bonus spells____________________________________________________________
//

//OUTER_SET string = RESOLVE_STR_REF(~something is happening...~)

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb1a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 4) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 139 target = 1 parameter1 = %string% timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb1b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 4) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb2a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb2b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb3a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb3b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb4a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb4b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb5a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb5b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb6a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb6b.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (134 + (0x10000 * 1)) timing = 1 END
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5wisb7a.spl~
  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (134 + (0x10000 * 1)) timing = 1 END

COPY_EXISTING ~d5shfrsh.spl~ ~override~
  PHP_EACH wis_nums_lets AS wis => slot BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %wis% parameter2 = 128 timing = 1 STR_VAR resource = EVAL ~d5wisb%slot%~ END
  END
  PHP_EACH wis_nums_lets AS wis => slot BEGIN
	LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 1 STR_VAR resource = EVAL ~d5wisb%slot%~ END
  END
IF_EXISTS BUT_ONLY

COPY ~%MOD_FOLDER%/lib/d5_marker.d5~ ~override/d5_semi_wis.d5~

END

// ***** ^^ the above only needs to be done once ^^___________________________________

END		//	end define function


//__________________________________________________________________________________
//__________________________________________________________________________________


//MAKE +SPELL SLOT ITEMS WORK________________________________________________________
//
DEFINE_ACTION_FUNCTION arcane_spont_items BEGIN

ACTION_IF !(FILE_EXISTS_IN_GAME ~d5_arcane_slot_items.d5~) BEGIN

COPY_EXISTING ~splprot.2da~ ~override~
  COUNT_2DA_COLS cols
  READ_2DA_ENTRIES_NOW rows cols
  FOR (row = 1; row < rows; ++row) BEGIN
	READ_2DA_ENTRY_FORMER rows row 0 ~stat~
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS_1_7~) BEGIN
	  SET fake_sorc_slots_1_7 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS=1_7~) BEGIN
	  SET fake_slots_equal_1_7 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS_8_9~) BEGIN
	  SET fake_sorc_slots_8_9 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_SLOTS=8_9~) BEGIN
	  SET fake_slots_equal_8_9 = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_FATIGUE_0~) BEGIN
	  SET fatigue_zero = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_PREP_SPLZ~) BEGIN
	  SET prep_spells_row = %row%
	END
	PATCH_IF (~%stat%~ STRING_EQUAL_CASE ~D5_NOT_PREP~) BEGIN
	  SET not_prep_row = %row%
	END
  END
BUT_ONLY

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_MULTI_SORC~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_MULTI_SORC~) BEGIN
		SET multi_sorc_state = %state_ind%
	  END
	END
  BUT_ONLY
END
ACTION_IF !(VARIABLE_IS_SET %multi_sorc_state%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_MULTI_SORC~ RET new_state_ind END
  OUTER_SET multi_sorc_state = %new_state_ind%
END

ACTION_IF (FILE_CONTAINS_EVALUATED (~splstate.ids~ ~D5_SEMI_ARCANE~)) BEGIN
  COPY_EXISTING ~splstate.ids~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~state_name~
	  READ_2DA_ENTRY_FORMER rows row 0 ~state_ind~
	  PATCH_IF (~%state_name%~ STRING_EQUAL_CASE ~D5_SEMI_ARCANE~) BEGIN
		SET semi_spont_arcane = %state_ind%
	  END
	END
  BUT_ONLY
END
ACTION_IF !(VARIABLE_IS_SET %semi_spont_arcane%) BEGIN
  LAF d5_resolve_state STR_VAR new_state_id = ~D5_SEMI_ARCANE~ RET new_state_ind END
  OUTER_SET semi_spont_arcane = %new_state_ind%
END

OUTER_SET generic_ind = 1
OUTER_SET mageslot_item_ind = 1
OUTER_TEXT_SPRINT $mage_slot_items(~0~ ~0~ ~0~ ~0~) ~item~
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ override
  SET slot_item = 0
  PATCH_IF SOURCE_SIZE > 0x72 BEGIN
    GET_OFFSET_ARRAY glob_fx ITM_V10_GEN_EFFECTS
    PHP_EACH glob_fx AS idx => off BEGIN
      PATCH_IF SHORT_AT off == 42 BEGIN
        SET slot_item = 1
        READ_LONG off + 0x04 param1 ELSE 0
        READ_LONG off + 0x08 param2 ELSE 0
        FOR (spell_level = 1; spell_level < 10; ++spell_level) BEGIN
          PATCH_IF param2 & (2 ** (spell_level - 1)) BEGIN
            TEXT_SPRINT $mage_slot_items(~%generic_ind%~ ~%mageslot_item_ind%~ ~%spell_level%~ ~%param1%~) ~%SOURCE_RES%~
            SET ++generic_ind
          END
        END
        PATCH_IF param2 == 0 BEGIN
          TEXT_SPRINT $mage_slot_items(~%generic_ind%~ ~%mageslot_item_ind%~ ~%param1%~ ~99~) ~%SOURCE_RES%~
          SET ++generic_ind
        END
      END // ELSE
      PATCH_IF SHORT_AT off == 177 /* || SHORT_AT off == 326 */ BEGIN
        READ_ASCII off + 0x14 eff_res (8) NULL
        INNER_PATCH_FILE ~%eff_res%.EFF~ BEGIN
          PATCH_IF LONG_AT 0x010 == 42 BEGIN
            SET slot_item = 1
            READ_LONG 0x1c param1 ELSE 0
            READ_LONG 0x20 param2 ELSE 0
            FOR (spell_level = 1; spell_level < 10; ++spell_level) BEGIN
              PATCH_IF param2 & (2 ** (spell_level - 1)) BEGIN
                TEXT_SPRINT $mage_slot_items(~%generic_ind%~ ~%mageslot_item_ind%~ ~%spell_level%~ ~%param1%~) ~%SOURCE_RES%~
                SET ++generic_ind
              END
            END
            PATCH_IF param2 == 0 BEGIN
              TEXT_SPRINT $mage_slot_items(~%generic_ind%~ ~%mageslot_item_ind%~ ~%param1%~ ~99~) ~%SOURCE_RES%~
              SET ++generic_ind
            END
          END
        END
      END
    END
  END
  PATCH_IF slot_item = 1 BEGIN
    SET ++mageslot_item_ind
  END
BUT_ONLY
	  
/*
ACTION_PHP_EACH mage_slot_items AS ind => slot_item BEGIN
  PRINT ~%ind% %ind_1% %ind_2% %ind_3% %slot_item%~
END
*/

ACTION_PHP_EACH mage_slot_items AS ind => slot_item BEGIN
 ACTION_IF (%ind% > 0) BEGIN
  PRINT ~%ind% %ind_1% %ind_2% %ind_3% %slot_item%~
  ACTION_IF (%ind_3% < 99) BEGIN
	ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b#%ind_1%%ind_2%.spl~) BEGIN
	  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b#%ind_1%%ind_2%.spl~
		LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
		PATCH_IF (%ind_2% = 1) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 4) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		END
		PATCH_IF (%ind_2% = 2) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		END
		PATCH_IF (%ind_2% = 3) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		END
		PATCH_IF (%ind_2% = 4) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		END
		PATCH_IF (%ind_2% = 5) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		END
		PATCH_IF (%ind_2% = 6) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		END
		PATCH_IF (%ind_2% = 7) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		END
		PATCH_IF (%ind_2% = 8) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (109 + (0x10000 * 1)) timing = 1 duration = 0 END
		END
		PATCH_IF (%ind_2% = 9) BEGIN
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (109 + (0x10000 * 1)) timing = 1 duration = 0 END
		END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%%ind_2%~ END
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	END
	ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b_%ind_1%%ind_2%.spl~) BEGIN
	  COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b_%ind_1%%ind_2%.spl~
		LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%%ind_2%~ END
//		LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	END
//	COPY_EXISTING ~d5b_000.spl~ ~override~
//	  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
//	IF_EXISTS BUT_ONLY
	COPY_EXISTING ~d5blots.spl~ ~override~
				~d5sslot.spl~ ~override~
	  PATCH_IF (%ind_2% = 1) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 4) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	  END
	  PATCH_IF (%ind_2% = 2) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 8) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	  END
	  PATCH_IF (%ind_2% = 3) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 12) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	  END
	  PATCH_IF (%ind_2% = 4) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 16) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	  END
	  PATCH_IF (%ind_2% = 5) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 20) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	  END
	  PATCH_IF (%ind_2% = 6) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 24) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	  END
	  PATCH_IF (%ind_2% = 7) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 28) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	  END
	  PATCH_IF (%ind_2% = 8) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 24) parameter2 = %fake_slots_equal_8_9% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	  END
	  PATCH_IF (%ind_2% = 9) BEGIN
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 28) parameter2 = %fake_slots_equal_8_9% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	  END
	IF_EXISTS BUT_ONLY
	COPY_EXISTING ~%slot_item%.itm~ ~override~
//	  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%%ind_2%~ END
	  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%%ind_2%~ END
	  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%%ind_2%~ END
//	  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%%ind_2%~ END
	  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = EVAL ~d5b_%ind_1%%ind_2%~ END
	IF_EXISTS BUT_ONLY
  END	//	end if not spell-doubling
  ACTION_IF (%ind_3% = 99) BEGIN
	ACTION_IF (%ind_2% > 0) BEGIN
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b#%ind_1%1.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b#%ind_1%1.spl~
		  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 4) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%1~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%1~ END
	  END
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b_%ind_1%1.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b_%ind_1%1.spl~
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%1~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%1~ END
	  END
	  COPY_EXISTING ~d5blots.spl~ ~override~
	  				~d5sslot.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 4) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%1~ END
	  IF_EXISTS BUT_ONLY
	  COPY_EXISTING ~%slot_item%.itm~ ~override~
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%1~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%1~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%1~ END
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%1~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = EVAL ~d5b_%ind_1%1~ END
	  IF_EXISTS BUT_ONLY
	END
	ACTION_IF (%ind_2% > 1) BEGIN
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b#%ind_1%2.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b#%ind_1%2.spl~
		  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%2~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%2~ END
	  END
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b_%ind_1%2.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b_%ind_1%2.spl~
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%2~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%2~ END
	  END
	  COPY_EXISTING ~d5blots.spl~ ~override~
	  				~d5sslot.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 8) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%2~ END
	  IF_EXISTS BUT_ONLY
	  COPY_EXISTING ~%slot_item%.itm~ ~override~
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%2~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%2~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%2~ END
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%2~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = EVAL ~d5b_%ind_1%2~ END
	  IF_EXISTS BUT_ONLY
	END
	ACTION_IF (%ind_2% > 2) BEGIN
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b#%ind_1%3.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b#%ind_1%3.spl~
		  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 12) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%3~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%3~ END
	  END
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b_%ind_1%3.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b_%ind_1%3.spl~
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%3~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%3~ END
	  END
	  COPY_EXISTING ~d5blots.spl~ ~override~
	  				~d5sslot.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 12) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%3~ END
	  IF_EXISTS BUT_ONLY
	  COPY_EXISTING ~%slot_item%.itm~ ~override~
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%3~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%3~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%3~ END
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%3~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = EVAL ~d5b_%ind_1%3~ END
	  IF_EXISTS BUT_ONLY
	END
	ACTION_IF (%ind_2% > 3) BEGIN
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b#%ind_1%4.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b#%ind_1%4.spl~
		  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 16) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%4~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%4~ END
	  END
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b_%ind_1%4.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b_%ind_1%4.spl~
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%4~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%4~ END
	  END
	  COPY_EXISTING ~d5blots.spl~ ~override~
	  				~d5sslot.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 16) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%4~ END
	  IF_EXISTS BUT_ONLY
	  COPY_EXISTING ~%slot_item%.itm~ ~override~
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%4~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%4~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%4~ END
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%4~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = EVAL ~d5b_%ind_1%4~ END
	  IF_EXISTS BUT_ONLY
	END
	ACTION_IF (%ind_2% > 4) BEGIN
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b#%ind_1%5.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b#%ind_1%5.spl~
		  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 20) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%5~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%5~ END
	  END
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b_%ind_1%5.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b_%ind_1%5.spl~
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%5~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%5~ END
	  END
	  COPY_EXISTING ~d5blots.spl~ ~override~
	  				~d5sslot.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 20) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%5~ END
	  IF_EXISTS BUT_ONLY
	  COPY_EXISTING ~%slot_item%.itm~ ~override~
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%5~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%5~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%5~ END
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%5~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = EVAL ~d5b_%ind_1%5~ END
	  IF_EXISTS BUT_ONLY
	END
	ACTION_IF (%ind_2% > 5) BEGIN
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b#%ind_1%6.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b#%ind_1%6.spl~
		  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%6~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%6~ END
	  END
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b_%ind_1%6.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b_%ind_1%6.spl~
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%6~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%6~ END
	  END
	  COPY_EXISTING ~d5blots.spl~ ~override~
	  				~d5sslot.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 24) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%6~ END
	  IF_EXISTS BUT_ONLY
	  COPY_EXISTING ~%slot_item%.itm~ ~override~
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%6~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%6~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%6~ END
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%6~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = EVAL ~d5b_%ind_1%6~ END
	  IF_EXISTS BUT_ONLY
	END
	ACTION_IF (%ind_2% > 6) BEGIN
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b#%ind_1%7.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b#%ind_1%7.spl~
		  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%7~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%7~ END
	  END
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b_%ind_1%7.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b_%ind_1%7.spl~
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%7~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%7~ END
	  END
	  COPY_EXISTING ~d5blots.spl~ ~override~
	  				~d5sslot.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 28) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%7~ END
	  IF_EXISTS BUT_ONLY
	  COPY_EXISTING ~%slot_item%.itm~ ~override~
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%7~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%7~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%7~ END
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%7~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = EVAL ~d5b_%ind_1%7~ END
	  IF_EXISTS BUT_ONLY
	END
	ACTION_IF (%ind_2% > 7) BEGIN
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b#%ind_1%8.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b#%ind_1%8.spl~
		  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 24) parameter2 = (109 + (0x10000 * 1)) timing = 1 duration = 0 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%8~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%8~ END
	  END
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b_%ind_1%8.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b_%ind_1%8.spl~
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%8~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%8~ END
	  END
	  COPY_EXISTING ~d5blots.spl~ ~override~
	  				~d5sslot.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 24) parameter2 = %fake_slots_equal_8_9% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%8~ END
	  IF_EXISTS BUT_ONLY
	  COPY_EXISTING ~%slot_item%.itm~ ~override~
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%8~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%8~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%8~ END
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%8~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = EVAL ~d5b_%ind_1%8~ END
	  IF_EXISTS BUT_ONLY
	END
	ACTION_IF (%ind_2% > 8) BEGIN
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b#%ind_1%9.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b#%ind_1%9.spl~
		  LPF ALTER_SPELL_HEADER INT_VAR target = 5 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 28) parameter2 = (109 + (0x10000 * 1)) timing = 1 duration = 0 END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%9~ END
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%9~ END
	  END
	  ACTION_IF !(FILE_EXISTS_IN_GAME ~d5b_%ind_1%9.spl~) BEGIN
		COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5b_%ind_1%9.spl~
		  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b#%ind_1%9~ END
//		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
		  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%9~ END
	  END
	  COPY_EXISTING ~d5blots.spl~ ~override~
	  				~d5sslot.spl~ ~override~
		LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 28) parameter2 = %fake_slots_equal_8_9% timing = 1 STR_VAR resource = EVAL ~d5b_%ind_1%9~ END
	  IF_EXISTS BUT_ONLY
	  COPY_EXISTING ~%slot_item%.itm~ ~override~
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%9~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%9~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 1 STR_VAR resource = EVAL ~d5b#%ind_1%9~ END
//		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = EVAL ~d5b_%ind_1%9~ END
		LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = EVAL ~d5b_%ind_1%9~ END
	  IF_EXISTS BUT_ONLY
	END
  END	//	end if not spell-doubling
  COPY_EXISTING ~%slot_item%.itm~ ~override~
//	LPF DELETE_EFFECT INT_VAR match_opcode = 321 STR_VAR resource = ~d5b_000~ END
//	LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5b_000~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 326 STR_VAR match_resource = ~d5bsplz~ END
	LPF DELETE_EFFECT INT_VAR match_opcode = 326 STR_VAR match_resource = ~d5ssplz~ END
//	LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = (0 - 1) opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
	LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = (0 - 1) opcode = 326 target = 1 parameter1 = %semi_spont_arcane% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
	LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = (0 - 1) opcode = 326 target = 1 parameter1 = %multi_sorc_state% parameter2 = 110 timing = 4 duration = 1 STR_VAR resource = ~d5ssplz~ END
  IF_EXISTS BUT_ONLY
 END
END

/* test method
COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5-2slt.spl~
//  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = ((0 - 1) << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
  LPF ADD_SPELL_EFFECT INT_VAR insert_point = 0 opcode = 321 target = 1 timing = 9 STR_VAR resource = ~d5+2slt~ END

COPY_EXISTING ~d5blots.spl~ ~override~
			~d5sslot.spl~ ~override~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 326 target = 1 parameter1 = (15 << 8) parameter2 = %fake_slots_equal_1_7% timing = 1 STR_VAR resource = ~d5-2slt~ END

COPY ~%MOD_FOLDER%/lib/d5_base.spl~ ~override/d5+2slt.spl~
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 233 target = 1 parameter1 = (1 << 8) parameter2 = (108 + (0x10000 * 1)) timing = 1 duration = 0 END
  LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 1 parameter1 = (0 - 1) timing = 1 STR_VAR resource = ~d5+2slt~ END

COPY_EXISTING ~ring08.itm~ ~override~
  LPF ADD_ITEM_EQEFFECT INT_VAR opcode = 146 target = 1 parameter2 = 1 timing = 4 duration = 1 STR_VAR resource = ~d5bsplz~ END
  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 146 target = 1 parameter2 = 1 timing = 1 STR_VAR resource = ~d5+2slt~ END
  LPF ADD_ITEM_EQEFFECT INT_VAR insert_point = 0 opcode = 206 target = 1 parameter1 = (0 - 1) timing = 2 STR_VAR resource = ~d5-2slt~ END
*/


COPY ~%MOD_FOLDER%/lib/d5_marker.d5~ ~override/d5_arcane_slot_items.d5~

END

// ***** ^^ the above only needs to be done once ^^___________________________________

END		//	end define function


